import { createAdminClient } from '@/lib/supabase/admin';
import { getCurrentWebshopInstance } from '@/lib/instances/access';

export type ContentKind='blog'|'landing'|'page';
export type ContentStatus='draft'|'published';
export type ContentPage={id:string;kind:ContentKind;slug:string;title:string;excerpt:string|null;body:string;heroTitle:string|null;heroSubtitle:string|null;ctaLabel:string|null;ctaHref:string|null;seoTitle:string|null;seoDescription:string|null;status:ContentStatus;publishedAt:string|null;createdAt:string;updatedAt:string};
type Row={id:string;kind:ContentKind;slug:string;title:string;excerpt:string|null;body:string;hero_title:string|null;hero_subtitle:string|null;cta_label:string|null;cta_href:string|null;seo_title:string|null;seo_description:string|null;status:ContentStatus;published_at:string|null;created_at:string;updated_at:string};
const map=(r:Row):ContentPage=>({id:r.id,kind:r.kind,slug:r.slug,title:r.title,excerpt:r.excerpt,body:r.body,heroTitle:r.hero_title,heroSubtitle:r.hero_subtitle,ctaLabel:r.cta_label,ctaHref:r.cta_href,seoTitle:r.seo_title,seoDescription:r.seo_description,status:r.status,publishedAt:r.published_at,createdAt:r.created_at,updatedAt:r.updated_at});
const fields='id,kind,slug,title,excerpt,body,hero_title,hero_subtitle,cta_label,cta_href,seo_title,seo_description,status,published_at,created_at,updated_at';
async function getScoped(){const instance=await getCurrentWebshopInstance();return instance?{instance,admin:createAdminClient()}:null}
export async function getAdminContent(options:{throwOnError?:boolean}={}){const scoped=await getScoped();if(!scoped){if(options.throwOnError)throw new Error('CONTENT_INSTANCE_REQUIRED');return[];}const{data,error}=await scoped.admin.from('content_pages').select(fields).eq('instance_id',scoped.instance.id).order('updated_at',{ascending:false});if(error){if(options.throwOnError)throw error;return[];}return((data??[])as Row[]).map(map)}
export async function getPublicContent(kind:ContentKind){const scoped=await getScoped();if(!scoped)return[];const{data,error}=await scoped.admin.from('content_pages').select(fields).eq('instance_id',scoped.instance.id).eq('kind',kind).eq('status','published').or(`published_at.is.null,published_at.lte.${new Date().toISOString()}`).order('published_at',{ascending:false});if(error)return[];return((data??[])as Row[]).map(map)}
export async function getPublicContentBySlug(kind:ContentKind,slug:string){const scoped=await getScoped();if(!scoped)return null;const{data,error}=await scoped.admin.from('content_pages').select(fields).eq('instance_id',scoped.instance.id).eq('kind',kind).eq('slug',slug).eq('status','published').maybeSingle();if(error||!data)return null;const page=map(data as Row);if(page.publishedAt&&new Date(page.publishedAt).getTime()>Date.now())return null;return page}
export async function getPublicPageBySlug(slug:string){return await getPublicContentBySlug('page',slug)??await getPublicContentBySlug('landing',slug)}
