import type {CSSProperties,ReactNode} from 'react';
import {StorefrontRendererRegistry,type StorefrontComponentRenderProps} from '@/components/builder/storefront-runtime-renderer';
import {storefrontInteractiveStateProps} from '@/components/builder/storefront-interactive-state';
import {StorefrontStickyHeaderState} from '@/components/builder/storefront-sticky-header-state';
import type {StorefrontResolvedComponentNode} from '@/lib/builder/storefront-runtime';
import {resolveStorefrontVisualStyle} from '@/lib/builder/storefront-visual-style';
import {resolveStorefrontStyleSlot} from '@/lib/builder/storefront-fidelity-engine';
import {resolveStorefrontTypography} from '@/lib/builder/storefront-fidelity-typography';
import {sanitizeStorefrontHeaderScrolledStyle,sanitizeStorefrontStickyHeaderBehavior} from '@/lib/builder/storefront-fidelity-behavior';

export const STOREFRONT_PRIMITIVE_RENDERERS_VERSION='shoporation.storefront-primitive-renderers.v4' as const;
const text=(value:unknown,fallback='')=>typeof value==='string'?value:fallback;
const bool=(value:unknown,fallback=false)=>typeof value==='boolean'?value:fallback;
const number=(value:unknown,fallback:number)=>typeof value==='number'&&Number.isFinite(value)?value:fallback;
const oneOf=<T extends string>(value:unknown,allowed:readonly T[],fallback:T):T=>typeof value==='string'&&allowed.includes(value as T)?value as T:fallback;
const visualStyle=(value:unknown,viewport:StorefrontComponentRenderProps['viewport'])=>resolveStorefrontVisualStyle(value,viewport) as CSSProperties;
const slotStyle=(value:unknown,slot:string,viewport:StorefrontComponentRenderProps['viewport'])=>resolveStorefrontStyleSlot(value,slot,viewport) as CSSProperties;
const typographyStyle=(value:unknown,viewport:StorefrontComponentRenderProps['viewport'])=>resolveStorefrontTypography(value,viewport) as CSSProperties;
const SPACING=['none','xs','s','m','l','xl','2xl'] as const;type Spacing=typeof SPACING[number];
const spacingValue=(value:unknown,fallback:Spacing='m')=>{const token=oneOf(value,SPACING,fallback);const values:Record<Spacing,string>={none:'0',xs:'0.5rem',s:'1rem',m:'1.5rem',l:'2.5rem',xl:'4rem','2xl':'6rem'};return `var(--shoporation-space-${token}, ${values[token]})`;};
const toneStyle=(value:unknown):CSSProperties=>{const tone=oneOf(value,['background','surface','muted','primary','text'] as const,'background');const styles:Record<typeof tone,CSSProperties>={background:{background:'var(--shoporation-color-background, #fff)',color:'var(--shoporation-color-text, #111827)'},surface:{background:'var(--shoporation-color-surface, #f8fafc)',color:'var(--shoporation-color-text, #111827)'},muted:{color:'var(--shoporation-color-muted-text, #64748b)'},primary:{background:'var(--shoporation-color-primary, #111827)',color:'var(--shoporation-color-primary-contrast, #fff)'},text:{color:'var(--shoporation-color-text, #111827)'}};return styles[tone];};
const gridSpanStyle=(node:StorefrontResolvedComponentNode):CSSProperties=>({gridColumn:`span ${node.resolved.gridSpan} / span ${node.resolved.gridSpan}`});
const widthStyle=(value:unknown,presentation=''):CSSProperties=>{if(presentation==='edge')return{width:'100%',maxWidth:'none',marginInline:'auto'};const width=oneOf(value,['full','wide','content','narrow'] as const,'content');if(width==='full')return{width:'100%'};if(width==='wide')return{width:'100%',maxWidth:'var(--shoporation-wide-commerce-max, 1440px)',marginInline:'auto'};if(width==='narrow')return{width:'100%',maxWidth:'var(--shoporation-readable-max, 760px)',marginInline:'auto'};return{width:'100%',maxWidth:'var(--shoporation-content-max, 1200px)',marginInline:'auto'};};
const safeHref=(value:unknown,fallback='#')=>{if(typeof value!=='string'||!value.trim())return fallback;const href=value.trim();return href.startsWith('/')||href.startsWith('#')||href.startsWith('https://')||href.startsWith('mailto:')||href.startsWith('tel:')?href:fallback;};
const safeImageSrc=(value:unknown)=>{if(typeof value!=='string'||!value.trim())return null;const src=value.trim();return src.startsWith('/')||src.startsWith('https://')?src:null;};
const intrinsicSize=(value:unknown)=>{if(typeof value!=='string')return'auto 720px';const match=/^auto\s+(\d{2,4})px$/i.exec(value.trim());if(!match)return'auto 720px';const px=Math.max(100,Math.min(2400,Number(match[1])));return`auto ${px}px`;};

function SectionRenderer({config,children,node,viewport}:StorefrontComponentRenderProps){const presentation=text(config.presentation);const deferOffscreen=bool(config.deferOffscreen,false);const performanceStyle=deferOffscreen?({contentVisibility:'auto',containIntrinsicSize:intrinsicSize(config.intrinsicSize)} as CSSProperties):{};const style:CSSProperties={...toneStyle(config.tone),...gridSpanStyle(node),width:'100%',maxWidth:'100%',minWidth:0,boxSizing:'border-box',paddingBlock:presentation==='flush'?'0':spacingValue(config.spacing,'l'),...performanceStyle,...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)};return <section data-storefront-component="layout.section" data-presentation={presentation||undefined} data-storefront-defer-offscreen={deferOffscreen?'true':undefined} style={style}><div style={{...widthStyle(config.width,presentation),...visualStyle(config.innerStyle,viewport),...slotStyle(config.styleSlots,'inner',viewport)}}>{children}</div></section>;}
function ContainerRenderer({config,children,node,viewport}:StorefrontComponentRenderProps){const presentation=text(config.presentation);return <div data-storefront-component="layout.container" data-presentation={presentation||undefined} style={{...widthStyle(config.width,presentation),...gridSpanStyle(node),boxSizing:'border-box',minWidth:0,paddingInline:presentation==='edge'?'0':spacingValue(config.spacing,'m'),...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)}}>{children}</div>;}
function GridRenderer({config,children,node,viewport}:StorefrontComponentRenderProps){const columns=Math.max(1,Math.min(12,Math.round(number(config.columns,12))));const align=oneOf(config.align,['start','center','end','stretch'] as const,'stretch');const presentation=text(config.presentation);const responsiveCards=presentation==='responsive-cards'||presentation==='trust-strip';const resolvedColumns=responsiveCards?(presentation==='trust-strip'?(viewport==='mobile'?2:columns):(viewport==='mobile'?1:viewport==='tablet'?Math.min(2,columns):columns)):columns;return <div data-storefront-component="layout.grid" data-presentation={presentation||undefined} style={{...gridSpanStyle(node),width:'100%',maxWidth:'100%',minWidth:0,boxSizing:'border-box',display:'grid',gridTemplateColumns:`repeat(${resolvedColumns}, minmax(0, 1fr))`,gap:spacingValue(config.gap,'m'),alignItems:align,...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)}}>{children}</div>;}
function StackRenderer({config,children,node,viewport}:StorefrontComponentRenderProps){const direction=oneOf(config.direction,['vertical','horizontal'] as const,'vertical');const align=oneOf(config.align,['start','center','end','stretch'] as const,'stretch');const justify=oneOf(config.justify,['start','center','end','between'] as const,'start');const alignItems:CSSProperties['alignItems']=align==='start'?'flex-start':align==='end'?'flex-end':align;const justifyContent:CSSProperties['justifyContent']=justify==='start'?'flex-start':justify==='end'?'flex-end':justify==='between'?'space-between':'center';const presentation=text(config.presentation);const sticky=presentation==='sticky-buybox'&&viewport!=='mobile'&&node.resolved.gridSpan<12;return <div data-storefront-component="layout.stack" data-presentation={presentation||undefined} style={{...gridSpanStyle(node),maxWidth:'100%',minWidth:0,boxSizing:'border-box',display:'flex',flexDirection:direction==='horizontal'?'row':'column',gap:spacingValue(config.gap,'m'),alignItems,justifyContent,...(sticky?{position:'sticky',top:'6.25rem',alignSelf:'start'}:{}),...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)}}>{children}</div>;}

const accentContent=(content:string,accent:string,style:CSSProperties)=>{if(!accent)return content;const at=content.toLocaleLowerCase().indexOf(accent.toLocaleLowerCase());if(at<0)return content;return <>{content.slice(0,at)}<span style={{color:'var(--shoporation-color-accent, #caa2d6)',...style}}>{content.slice(at,at+accent.length)}</span>{content.slice(at+accent.length)}</>;};
function HeadingRenderer({config,node,viewport}:StorefrontComponentRenderProps){const level=Math.max(1,Math.min(6,Math.round(number(config.level,2))));const align=oneOf(config.align,['left','center','right'] as const,'left');const presentation=text(config.presentation);const editorial=presentation==='display-editorial';const section=presentation==='section-editorial';const style:CSSProperties={...toneStyle(config.tone),...gridSpanStyle(node),textAlign:align,margin:0,whiteSpace:'pre-line',fontFamily:editorial?'var(--shoporation-display-font,var(--shoporation-heading-font, Georgia, serif))':section?'var(--shoporation-body-font, Arial, sans-serif)':undefined,fontWeight:editorial?500:section?720:undefined,fontSize:editorial?'clamp(3rem,7.2vw,7.2rem)':section?'clamp(1.8rem,3vw,2.65rem)':undefined,lineHeight:editorial?.86:section?1.02:undefined,letterSpacing:editorial?'-.055em':section?'-.035em':undefined,textTransform:editorial?'uppercase':undefined,...typographyStyle(config.typography,viewport),...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)};const content=accentContent(text(config.text),text(config.accentText),{...visualStyle(config.accentStyle,viewport),...slotStyle(config.styleSlots,'accent',viewport)});const props={'data-storefront-component':'content.heading','data-presentation':presentation||undefined,style};if(level===1)return <h1 {...props}>{content}</h1>;if(level===2)return <h2 {...props}>{content}</h2>;if(level===3)return <h3 {...props}>{content}</h3>;if(level===4)return <h4 {...props}>{content}</h4>;if(level===5)return <h5 {...props}>{content}</h5>;return <h6 {...props}>{content}</h6>;}
function TextRenderer({config,node,viewport}:StorefrontComponentRenderProps){const as=oneOf(config.as,['p','span','small','strong'] as const,'p');const align=oneOf(config.align,['left','center','right'] as const,'left');const presentation=text(config.presentation);const style:CSSProperties={...toneStyle(config.tone),...gridSpanStyle(node),textAlign:align,margin:as==='p'?0:undefined,lineHeight:presentation==='body-editorial'?1.55:undefined,fontSize:presentation==='body-editorial'?'clamp(.95rem,1.5vw,1.12rem)':presentation==='eyebrow-editorial'?'.7rem':undefined,textTransform:presentation==='eyebrow-editorial'?'uppercase':undefined,letterSpacing:presentation==='eyebrow-editorial'?'.17em':undefined,fontWeight:presentation==='eyebrow-editorial'?650:undefined,...typographyStyle(config.typography,viewport),...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)};const content=text(config.text);const common={'data-storefront-component':'content.text','data-presentation':presentation||undefined,style};if(as==='span')return <span {...common}>{content}</span>;if(as==='small')return <small {...common}>{content}</small>;if(as==='strong')return <strong {...common}>{content}</strong>;return <p {...common}>{content}</p>;}
function ImageRenderer({config,node,viewport}:StorefrontComponentRenderProps){const src=safeImageSrc(config.src);if(!src)return null;const fit=oneOf(config.fit,['cover','contain'] as const,'cover');const loading=oneOf(config.loading,['lazy','eager'] as const,'lazy');const radius=oneOf(config.radius,['none','s','m','l','pill'] as const,'none');const radiusValue={none:'0',s:'0.375rem',m:'0.75rem',l:'1.25rem',pill:'9999px'}[radius];const width=Math.max(1,Math.round(number(config.width,1200)));const height=Math.max(1,Math.round(number(config.height,800)));const presentation=text(config.presentation);return <img data-storefront-component="content.image" data-presentation={presentation||undefined} src={src} alt={text(config.alt)} width={width} height={height} loading={loading} style={{...gridSpanStyle(node),display:'block',width:'100%',height:presentation==='fill'?'100%':'auto',minHeight:presentation==='fill'?'100%':undefined,objectFit:fit,objectPosition:text(config.objectPosition,'center'),borderRadius:radiusValue,...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)}}/>;}
function ButtonRenderer({config,node,viewport}:StorefrontComponentRenderProps){const href=safeHref(config.href);const variant=oneOf(config.variant,['primary','secondary','ghost'] as const,'primary');const size=oneOf(config.size,['s','m','l'] as const,'m');const padding=size==='s'?'0.5rem 0.875rem':size==='l'?'0.875rem 1.375rem':'0.7rem 1.1rem';const variantStyle:Record<typeof variant,CSSProperties>={primary:{background:'var(--shoporation-color-primary, #111827)',color:'var(--shoporation-color-primary-contrast, #fff)',border:'1px solid var(--shoporation-color-primary, #111827)'},secondary:{background:'transparent',color:'var(--shoporation-color-text, #111827)',border:'1px solid var(--shoporation-color-border, #cbd5e1)'},ghost:{background:'transparent',color:'var(--shoporation-color-text, #111827)',border:'1px solid transparent'}};const presentation=text(config.presentation);const interaction=storefrontInteractiveStateProps(config.styleSlots,viewport,'root');return <a data-storefront-component="content.button" data-presentation={presentation||undefined} href={href} aria-label={text(config.ariaLabel)||undefined} className={interaction.className} style={{...gridSpanStyle(node),...variantStyle[variant],display:'inline-flex',width:'fit-content',alignItems:'center',justifyContent:'center',padding,borderRadius:presentation==='editorial-square'?'2px':'var(--shoporation-radius-m, 0.75rem)',textDecoration:'none',fontWeight:650,fontSize:presentation==='editorial-square'?'.79rem':undefined,letterSpacing:presentation==='editorial-square'?'.035em':undefined,textTransform:presentation==='editorial-square'?'uppercase':undefined,...typographyStyle(config.typography,viewport),...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport),...interaction.style,...(viewport==='mobile'?{minHeight:'32px'}:{})}}>{text(config.label,'Tovább')}</a>;}

type NavigationItem={label:string;href:string;symbol?:string;ariaLabel?:string};const navigationItems=(value:unknown):NavigationItem[]=>Array.isArray(value)?value.flatMap(item=>{if(!item||typeof item!=='object'||Array.isArray(item))return[];const row=item as Record<string,unknown>;const label=text(row.label);const href=safeHref(row.href,'');const symbol=text(row.symbol);const ariaLabel=text(row.ariaLabel);return label&&href?[{label,href,...(symbol?{symbol}:{}),...(ariaLabel?{ariaLabel}:{})}]:[]}):[];
type UtilityItem={label:string;href:string;symbol:string};const utilityItems=(value:unknown):UtilityItem[]=>Array.isArray(value)?value.flatMap((item,index)=>{if(!item||typeof item!=='object'||Array.isArray(item))return[];const row=item as Record<string,unknown>;const label=text(row.label,`Művelet ${index+1}`);const href=safeHref(row.href,'#');const symbol=text(row.symbol,label.slice(0,1));return[{label,href,symbol}];}):[];
function NavigationRenderer({config,node,viewport}:StorefrontComponentRenderProps){const items=navigationItems(config.items);const layout=oneOf(config.layout,['horizontal','vertical'] as const,'horizontal');const presentation=text(config.presentation);const interaction=storefrontInteractiveStateProps(config.styleSlots,viewport,'item');return <nav data-storefront-component="system.navigation" data-storefront-protected-system="navigation" data-presentation={presentation||undefined} aria-label={text(config.ariaLabel,'Fő navigáció')} style={{...gridSpanStyle(node),display:'flex',flexDirection:layout==='vertical'?'column':'row',gap:presentation==='editorial-lab'?'clamp(.8rem,2vw,1.75rem)':'var(--shoporation-space-m, 1.5rem)',alignItems:layout==='vertical'?'stretch':'center',fontSize:presentation==='editorial-lab'?'.74rem':undefined,letterSpacing:presentation==='editorial-lab'?'.035em':undefined,textTransform:presentation==='editorial-lab'?'uppercase':undefined,whiteSpace:'nowrap',...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)}}>{items.map(item=><a key={`${item.href}:${item.label}`} href={item.href} aria-label={item.ariaLabel||(item.symbol?item.label:undefined)} title={item.symbol?item.label:undefined} className={interaction.className} style={{color:'inherit',textDecoration:'none',...slotStyle(config.styleSlots,'item',viewport),...interaction.style}}>{item.symbol?<span aria-hidden="true">{item.symbol}</span>:item.label}</a>)}</nav>;}
function SocialPlatformIcon({label}:{label:string}){
  const key=label.trim().toLowerCase();
  const common={width:18,height:18,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const,'aria-hidden':true};
  if(key.includes('youtube'))return <svg {...common}><rect x="3" y="6" width="18" height="12" rx="3"/><path d="m10 9 5 3-5 3Z" fill="currentColor" stroke="none"/></svg>;
  if(key.includes('instagram'))return <svg {...common}><rect x="4" y="4" width="16" height="16" rx="5"/><circle cx="12" cy="12" r="3.5"/><circle cx="17.2" cy="6.8" r=".9" fill="currentColor" stroke="none"/></svg>;
  if(key.includes('tiktok'))return <svg {...common}><path d="M14 4v10.2a4.2 4.2 0 1 1-3.4-4.1"/><path d="M14 4c1.1 2.3 2.8 3.6 5 3.8"/></svg>;
  if(key==='x'||key.includes('twitter'))return <svg {...common}><path d="M5 4 19 20M19 4 5 20"/></svg>;
  if(key.includes('twitch'))return <svg {...common}><path d="M5 4h15v10l-5 5h-4l-3 2v-2H5Z"/><path d="M10 8v5M15 8v5"/></svg>;
  if(key.includes('facebook'))return <svg {...common}><path d="M14.5 5H13a3 3 0 0 0-3 3v11M7 11h8"/></svg>;
  if(key.includes('linkedin'))return <svg {...common}><rect x="4" y="9" width="3" height="10" rx=".5"/><circle cx="5.5" cy="5.5" r="1.5" fill="currentColor" stroke="none"/><path d="M11 19V9h3v1.6c.8-1.2 1.8-1.9 3.4-1.9 2.3 0 3.6 1.5 3.6 4.4V19"/></svg>;
  if(key.includes('pinterest'))return <svg {...common}><circle cx="12" cy="12" r="8"/><path d="M10.2 17.8 12 10.2c.4-1.7 2.9-1.2 2.5.7-.5 2.3-1.8 3.7-3.4 3.1-1.8-.7-2.6-2.3-2.1-4.3.6-2.6 3.5-4.3 6.1-3.5"/></svg>;
  return <span aria-hidden="true">{label.slice(0,1)}</span>;
}

function SocialLinksRenderer({config,node,viewport}:StorefrontComponentRenderProps){
  const items=navigationItems(config.items);if(!items.length)return null;
  const presentation=text(config.presentation),interaction=storefrontInteractiveStateProps(config.styleSlots,viewport,'item');
  return <aside data-storefront-component="system.social-links" data-storefront-protected-system="social-links" data-presentation={presentation||undefined} style={{...gridSpanStyle(node),minWidth:0,display:'grid',gap:'var(--shoporation-space-s,1rem)',...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)}}>
    {text(config.title)?<strong style={{...visualStyle(config.titleStyle,viewport),...slotStyle(config.styleSlots,'title',viewport)}}>{text(config.title)}</strong>:null}
    <nav aria-label={text(config.ariaLabel,'Közösségi média')} style={{display:'flex',flexWrap:'wrap',gap:'.55rem',alignItems:'center',...visualStyle(config.navigationStyle,viewport),...slotStyle(config.styleSlots,'navigation',viewport)}}>{items.map(item=><a key={`${item.href}:${item.label}`} href={item.href} target="_blank" rel="noopener noreferrer" aria-label={item.ariaLabel||item.label} title={item.label} className={interaction.className} style={{display:'inline-flex',alignItems:'center',justifyContent:'center',minWidth:'2.25rem',minHeight:'2.25rem',color:'inherit',textDecoration:'none',border:'1px solid var(--shoporation-color-border,#cbd5e1)',borderRadius:'var(--shoporation-radius-m,.75rem)',...visualStyle(config.itemStyle,viewport),...slotStyle(config.styleSlots,'item',viewport),...interaction.style}}><SocialPlatformIcon label={item.label}/></a>)}</nav>
    {text(config.copy)?<strong style={{whiteSpace:'pre-line',...visualStyle(config.copyStyle,viewport),...slotStyle(config.styleSlots,'copy',viewport)}}>{text(config.copy)}</strong>:null}
  </aside>;
}

function HeaderRenderer({config,children,node,viewport}:StorefrontComponentRenderProps){
  const sticky=bool(config.sticky,false);const tone=oneOf(config.tone,['background','surface','primary'] as const,'background');const presentation=text(config.presentation);const editorial=presentation==='editorial-lab';const utility=utilityItems(config.utilityItems);const compact=editorial&&viewport==='mobile';const brandInteraction=storefrontInteractiveStateProps(config.styleSlots,viewport,'brand');const utilityInteraction=storefrontInteractiveStateProps(config.styleSlots,viewport,'utilityItem');const scrollBehavior=sanitizeStorefrontStickyHeaderBehavior(config.behavior);
  const rootStyle:CSSProperties={...toneStyle(tone),...gridSpanStyle(node),position:sticky?'sticky':'relative',top:sticky?0:undefined,zIndex:sticky?20:undefined,borderBottom:'1px solid var(--shoporation-color-border, #e2e8f0)',...visualStyle(config.style,viewport),...slotStyle(config.styleSlots,'root',viewport)};
  const innerStyle:CSSProperties={maxWidth:editorial?'none':'var(--shoporation-content-max, 1200px)',marginInline:'auto',padding:editorial?'.7rem clamp(1rem,3vw,2.4rem)':'1rem clamp(1rem,3vw,2rem)',display:'flex',alignItems:'center',justifyContent:'space-between',gap:editorial?'clamp(.75rem,2vw,2rem)':'1.5rem',minHeight:editorial?'4rem':undefined,...visualStyle(config.innerStyle,viewport),...slotStyle(config.styleSlots,'inner',viewport)};
  const content=<><a href={safeHref(config.brandHref,'/')} className={brandInteraction.className} style={{display:'grid',gap:editorial?'.08rem':'0',fontWeight:editorial?850:700,fontSize:editorial?'1.02rem':undefined,letterSpacing:editorial?'.09em':undefined,textTransform:editorial?'uppercase':undefined,color:'inherit',textDecoration:'none',lineHeight:1,...visualStyle(config.brandStyle,viewport),...slotStyle(config.styleSlots,'brand',viewport),...brandInteraction.style}}><span>{text(config.brandLabel,'Shoporation')}</span>{text(config.tagline)?<small style={{fontSize:editorial?'.43rem':'.7rem',letterSpacing:editorial?'.2em':'.08em',fontWeight:550,...visualStyle(config.taglineStyle,viewport),...slotStyle(config.styleSlots,'tagline',viewport)}}>{text(config.tagline)}</small>:null}</a>{compact?<span aria-label="Mobil navigáció" style={{marginLeft:'auto',fontSize:'1.2rem',...visualStyle(config.mobileToggleStyle,viewport),...slotStyle(config.styleSlots,'mobileToggle',viewport)}}>☰</span>:<div style={{display:'flex',alignItems:'center',justifyContent:'center',flex:editorial?'1 1 auto':undefined,overflow:'hidden',...slotStyle(config.styleSlots,'navigationFrame',viewport)}}>{children}</div>}{editorial?<nav aria-label="Gyorsműveletek" style={{display:'flex',gap:compact?'.55rem':'.8rem',alignItems:'center',...visualStyle(config.utilityStyle,viewport),...slotStyle(config.styleSlots,'utility',viewport)}}>{utility.map(item=><a key={`${item.label}:${item.href}`} href={item.href} aria-label={item.label} title={item.label} className={utilityInteraction.className} style={{color:'inherit',textDecoration:'none',fontSize:'1rem',lineHeight:1,...slotStyle(config.styleSlots,'utilityItem',viewport),...utilityInteraction.style}}>{item.symbol}</a>)}</nav>:null}</>;
  if(sticky&&scrollBehavior.enabled)return <StorefrontStickyHeaderState threshold={scrollBehavior.threshold} presentation={presentation||undefined} rootStyle={rootStyle} rootScrolledStyle={sanitizeStorefrontHeaderScrolledStyle(slotStyle(config.styleSlots,'rootScrolled',viewport))} innerStyle={innerStyle} innerScrolledStyle={sanitizeStorefrontHeaderScrolledStyle(slotStyle(config.styleSlots,'innerScrolled',viewport))}>{content}</StorefrontStickyHeaderState>;
  return <header data-storefront-component="system.header" data-storefront-protected-system="header" data-presentation={presentation||undefined} style={rootStyle}><div style={innerStyle}>{content}</div></header>;
}

const RENDERERS:readonly [string,number,(props:StorefrontComponentRenderProps)=>ReactNode][]=[['layout.section',1,SectionRenderer],['layout.container',1,ContainerRenderer],['layout.grid',1,GridRenderer],['layout.stack',1,StackRenderer],['content.heading',1,HeadingRenderer],['content.text',1,TextRenderer],['content.image',1,ImageRenderer],['content.button',1,ButtonRenderer],['system.header',1,HeaderRenderer],['system.navigation',1,NavigationRenderer],['system.social-links',1,SocialLinksRenderer]] as const;
export function createStorefrontPrimitiveRendererRegistry(){const registry=new StorefrontRendererRegistry();for(const[componentKey,componentVersion,renderer]of RENDERERS)registry.register(componentKey,componentVersion,renderer);return registry;}
