import type {CSSProperties,ReactNode} from 'react';
import type {StorefrontComponentRenderProps} from '@/components/builder/storefront-runtime-renderer';
import {createStorefrontStructuredProductRendererRegistry} from '@/components/builder/storefront-structured-product';
import {resolveStorefrontVisualStyle} from '@/lib/builder/storefront-visual-style';

export const STOREFRONT_VISUAL_LAYER_RENDERERS_VERSION='shoporation.storefront-visual-layer-renderers.v1' as const;
const text=(value:unknown,fallback='')=>typeof value==='string'?value:fallback;
const number=(value:unknown,fallback=0)=>typeof value==='number'&&Number.isFinite(value)?value:fallback;
const HEIGHT:Record<string,string>={compact:'24rem',editorial:'36rem',hero:'clamp(38rem,72vw,58rem)','beauty-hero':'clamp(35rem,53vw,49rem)'};
const RADIUS:Record<string,string>={none:'0',m:'1rem',l:'1.75rem'};
const OFFSET:Record<string,string>={none:'0',xs:'.5rem',s:'clamp(.75rem,1.5vw,1rem)',m:'clamp(1rem,2vw,1.5rem)',l:'clamp(1.25rem,3vw,3rem)',xl:'clamp(1.25rem,5vw,5rem)',xxl:'clamp(2rem,8vw,10rem)'};
const WIDTH:Record<string,string>={auto:'auto',narrow:'18rem',medium:'28rem',wide:'42rem',half:'50%',major:'63%',minor:'37%',full:'100%'};
const LAYER_HEIGHT:Record<string,string>={auto:'auto',half:'50%',full:'100%'};
const PADDING:Record<string,string>={none:'0',s:'.65rem',m:'1rem',l:'1.5rem',xl:'clamp(1.5rem,4vw,4.5rem)'};
function toneBackground(value:unknown){const tone=text(value,'transparent');if(tone==='scrim-soft')return'rgba(0,0,0,.18)';if(tone==='scrim-strong')return'rgba(0,0,0,.36)';if(tone==='surface')return'var(--shoporation-color-background,#fff)';if(tone==='accent')return'var(--shoporation-color-accent,#b99a5d)';if(tone==='primary')return'var(--shoporation-color-primary,#111)';return'transparent';}
function Canvas({config,node,children,viewport}:StorefrontComponentRenderProps){const presentation=text(config.presentation);const configured=HEIGHT[text(config.height,presentation==='editorial-lab'?'beauty-hero':'hero')]??HEIGHT.hero;const height=presentation==='editorial-lab'?(viewport==='mobile'?'46rem':viewport==='tablet'?'43rem':'49rem'):configured;const tone=text(config.tone,'background');const background=tone==='primary'?'var(--shoporation-color-primary,#111)':tone==='surface'?'var(--shoporation-color-surface,#eee)':'var(--shoporation-color-background,#fff)';const radius=RADIUS[text(config.radius,'none')]??'0';return <section data-storefront-visual="layered-canvas" data-presentation={presentation||undefined} style={{gridColumn:`span ${node.resolved.gridSpan} / span ${node.resolved.gridSpan}`,position:'relative',isolation:'isolate',minHeight:height,overflow:'hidden',background,borderRadius:radius,...resolveStorefrontVisualStyle(config.style,viewport) as CSSProperties}}>{children}</section>;}
function Layer({config,children,viewport}:StorefrontComponentRenderProps){const position=text(config.position,'full');const x=OFFSET[text(config.offsetX,'none')]??'0';const y=OFFSET[text(config.offsetY,'none')]??'0';const presentation=text(config.presentation);const style:CSSProperties={position:'absolute',zIndex:Math.max(0,Math.min(20,Math.round(number(config.zIndex,1)))),width:WIDTH[text(config.width,'auto')]??'auto',maxWidth:text(config.width,'auto')==='full'?undefined:'calc(100% - 2rem)',height:LAYER_HEIGHT[text(config.height,'auto')]??'auto',padding:PADDING[text(config.padding,'none')]??'0',background:toneBackground(config.tone),opacity:Math.max(0,Math.min(1,number(config.opacity,1))),pointerEvents:text(config.pointerEvents,'auto')==='none'?'none':'auto',boxSizing:'border-box'};
  if(position==='full')Object.assign(style,{inset:0,width:'100%',height:'100%',maxWidth:'none'});else if(position==='top-left')Object.assign(style,{top:y,left:x});else if(position==='top-right')Object.assign(style,{top:y,right:x});else if(position==='bottom-left')Object.assign(style,{bottom:y,left:x});else if(position==='bottom-right')Object.assign(style,{bottom:y,right:x});else if(position==='center-left')Object.assign(style,{top:'50%',left:x,transform:'translateY(-50%)'});else if(position==='center-right')Object.assign(style,{top:'50%',right:x,transform:'translateY(-50%)'});else Object.assign(style,{top:'50%',left:'50%',transform:'translate(-50%,-50%)'});
  if(presentation==='editorial-photo')Object.assign(style,viewport==='mobile'?{top:0,left:0,right:0,bottom:'auto',transform:'none',width:'100%',maxWidth:'none',height:'54%',padding:0}:{top:0,right:0,left:'auto',bottom:0,transform:'none',width:viewport==='tablet'?'58%':'63%',maxWidth:'none',height:'100%',padding:0});
  if(presentation==='editorial-copy-panel')Object.assign(style,viewport==='mobile'?{top:'auto',right:0,bottom:0,left:0,transform:'none',width:'100%',maxWidth:'none',height:'50%',padding:'1.4rem 1.2rem',background:'var(--shoporation-color-background,#fffaf5)'}:{top:0,right:'auto',bottom:0,left:0,transform:'none',width:viewport==='tablet'?'48%':'43%',maxWidth:'none',height:'100%',padding:'clamp(2.5rem,5vw,5.5rem)',background:'var(--shoporation-color-background,#fffaf5)'});
  if(presentation==='editorial-product-inset')Object.assign(style,viewport==='mobile'?{display:'none'}:{top:'auto',left:'auto',right:viewport==='tablet'?'1rem':'2rem',bottom:viewport==='tablet'?'1rem':'2rem',transform:'none',width:viewport==='tablet'?'15rem':'20rem',maxWidth:'30%',height:viewport==='tablet'?'10.5rem':'14rem',padding:'.45rem',background:'rgba(255,250,245,.92)'});
  if(presentation==='editorial-badge')Object.assign(style,{top:viewport==='mobile'?'.75rem':'1.4rem',right:viewport==='mobile'?'.75rem':'1.5rem',bottom:'auto',left:'auto',transform:'none',width:'auto',height:'auto',padding:viewport==='mobile'?'.55rem':'.75rem'});
  Object.assign(style,resolveStorefrontVisualStyle(config.style,viewport));
  return <div data-storefront-visual="layer" data-layer-position={position} data-presentation={presentation||undefined} style={style}>{children}</div>;}
export const STOREFRONT_VISUAL_LAYER_RENDERERS:readonly [string,number,(props:StorefrontComponentRenderProps)=>ReactNode][]=[['visual.layered-canvas',1,Canvas],['visual.layer',1,Layer]] as const;
export function createStorefrontVisualLayerRendererRegistry(){const registry=createStorefrontStructuredProductRendererRegistry();for(const[key,version,renderer]of STOREFRONT_VISUAL_LAYER_RENDERERS)registry.register(key,version,renderer);return registry;}
