'use client';

import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';
import {useCart} from '@/components/cart/cart-provider';
import {runGuidedFinder,type FinderRunResult,type FinderSelections} from '@/lib/commerce/guided-finder';
import {buildComposerAddIntent,buildComposerReadModel,type ComposerCatalogItem,type ComposerSelection,type MultiProductComposerConfig} from '@/lib/commerce/multi-product-composer';
import {buildConfiguratorAddIntent,buildConfiguratorReadModel,type ConfiguratorCatalogPart,type ConfiguratorReadModel,type ConfiguratorSelection,type ProductConfiguratorConfig} from '@/lib/commerce/product-configurator';
import type {CompatibilityRule} from '@/lib/commerce/compatibility-engine';
import type {StorefrontExistingEngineRecord,StorefrontConfiguratorDocument,StorefrontGuidedFinderDocument,StorefrontComposerDocument} from '@/lib/builder/storefront-existing-engine-config';

type CatalogRow={productId:string;variantId:string;label:string;href:string;slug:string;eligible:boolean;channelVisible:boolean;price:{amountMinor:number;currency:string;display:string;source:'shared-pricing-authority'};stock:{available:boolean;statusLabel:string};attributes:Record<string,string>;compatibility:ConfiguratorCatalogPart['compatibility']};
type RuntimeState={finder:Record<string,FinderRunResult|undefined>;configurator:Record<string,ConfiguratorReadModel|undefined>;configSelections:Record<string,readonly ConfiguratorSelection[]|undefined>};
type RuntimeContextValue=RuntimeState&{setFinder:(key:string,value:FinderRunResult|undefined)=>void;setConfigurator:(key:string,value:ConfiguratorReadModel|undefined,selections:readonly ConfiguratorSelection[])=>void};
const RuntimeContext=createContext<RuntimeContextValue|null>(null);
const rec=(value:unknown):Record<string,unknown>|null=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:null;
const records=(value:unknown)=>Array.isArray(value)?value.filter(item=>{const row=rec(item);return row&&typeof row.configKey==='string'&&typeof row.engineKind==='string';}) as StorefrontExistingEngineRecord[]:[];
const catalogRows=(value:unknown)=>Array.isArray(value)?value.filter(item=>{const row=rec(item);return row&&typeof row.productId==='string'&&typeof row.variantId==='string';}) as CatalogRow[]:[];
const text=(value:unknown,f='')=>typeof value==='string'?value:f;
const newKey=(prefix:string)=>`${prefix}-${typeof crypto!=='undefined'&&'randomUUID'in crypto?crypto.randomUUID():`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`}`;
const pick=(rows:StorefrontExistingEngineRecord[],key:string)=>rows.find(row=>row.configKey===key)??(key?null:rows.length===1?rows[0]:null);
const cardStyle={border:'1px solid var(--shoporation-color-border,#ddd)',borderRadius:'.8rem',padding:'.8rem',background:'var(--shoporation-color-background,#fff)'} as const;

export function StorefrontExistingCommerceRuntimeProvider({children}:{children:ReactNode}){
  const[finder,setFinderState]=useState<RuntimeState['finder']>({}),[configurator,setConfiguratorState]=useState<RuntimeState['configurator']>({}),[configSelections,setConfigSelections]=useState<RuntimeState['configSelections']>({});
  const setFinder=useCallback((key:string,value:FinderRunResult|undefined)=>setFinderState(current=>current[key]===value?current:{...current,[key]:value}),[]);
  const setConfigurator=useCallback((key:string,value:ConfiguratorReadModel|undefined,selections:readonly ConfiguratorSelection[])=>{setConfiguratorState(current=>current[key]===value?current:{...current,[key]:value});setConfigSelections(current=>current[key]===selections?current:{...current,[key]:selections});},[]);
  const value=useMemo(()=>({finder,configurator,configSelections,setFinder,setConfigurator}),[finder,configurator,configSelections,setFinder,setConfigurator]);
  return <RuntimeContext.Provider value={value}>{children}</RuntimeContext.Provider>;
}
function runtime(){return useContext(RuntimeContext)}

export function GuidedFinderRuntime({config,fallback}:{config:Record<string,unknown>;fallback:ReactNode}){
  const ctx=runtime(),setFinder=ctx?.setFinder,engineRows=records(config.engineConfigs).filter(row=>row.engineKind==='guided_finder'),record=pick(engineRows,text(config.finderKey)),catalog=catalogRows(config.catalog);
  const finderConfig=record?(record.document as StorefrontGuidedFinderDocument).config:null;
  const[selections,setSelections]=useState<FinderSelections>({});
  useEffect(()=>setSelections({}),[record?.configKey]);
  const candidates=useMemo(()=>catalog.map(item=>({id:`${item.productId}:${item.variantId}`,label:item.label,href:item.href,eligible:item.eligible&&item.channelVisible&&item.stock.available,attributes:item.attributes})),[catalog]);
  const result=useMemo(()=>finderConfig?runGuidedFinder({config:finderConfig,selections,candidates}):null,[finderConfig,selections,candidates]);
  useEffect(()=>{if(setFinder&&record)setFinder(record.configKey,result??undefined)},[setFinder,record?.configKey,result]);
  if(!finderConfig||!record)return <>{fallback}</>;
  const update=(questionId:string,optionId:string,mode:'single'|'multi')=>setSelections(current=>{const selected=current[questionId]??[];const next=mode==='single'?[optionId]:selected.includes(optionId)?selected.filter(value=>value!==optionId):[...selected,optionId];return{...current,[questionId]:next};});
  return <section data-existing-commerce-runtime="guided-finder" style={{display:'grid',gap:'1rem',padding:'clamp(1.25rem,3vw,2.5rem)',background:'var(--shoporation-color-surface,#f5f1f3)',borderRadius:'1rem'}}>
    {text(config.eyebrow)?<small style={{textTransform:'uppercase',letterSpacing:'.12em'}}>{text(config.eyebrow)}</small>:null}<h2 style={{margin:0}}>{text(config.title,finderConfig.label)}</h2>{text(config.copy)?<p style={{margin:0}}>{text(config.copy)}</p>:null}
    {finderConfig.steps.map((step,stepIndex)=><div key={step.id} style={{display:'grid',gap:'.8rem'}}><strong>{stepIndex+1}. {step.title}</strong>{step.copy?<small>{step.copy}</small>:null}{step.questions.map(question=><fieldset key={question.id} style={{...cardStyle,display:'grid',gap:'.55rem'}}><legend><strong>{question.label}</strong>{question.required?' *':''}</legend><div style={{display:'flex',gap:'.55rem',flexWrap:'wrap'}}>{question.options.map(option=>{const selected=(selections[question.id]??[]).includes(option.id);return <button type="button" key={option.id} aria-pressed={selected} onClick={()=>update(question.id,option.id,question.mode)} style={{padding:'.65rem .85rem',border:'1px solid var(--shoporation-color-border,#bbb)',borderRadius:'999px',background:selected?'var(--shoporation-color-primary,#222)':'var(--shoporation-color-background,#fff)',color:selected?'var(--shoporation-color-primary-contrast,#fff)':'inherit'}}>{option.label}</button>})}</div></fieldset>)}</div>)}
    {result?<div role="status" style={{display:'grid',gap:'.65rem'}}><strong>{result.explanation}</strong>{result.results.map(item=><a key={item.id} href={item.href} style={{...cardStyle,color:'inherit',textDecoration:'none'}}><strong>{item.label}</strong><small style={{display:'block'}}>Egyező preferenciák: {item.preferredMatched} · kötelező eltérés: {item.requiredMismatched}</small></a>)}</div>:<small>Töltsd ki a kötelező kérdéseket az ajánláshoz.</small>}
  </section>;
}

export function GuidedResultsRuntime({config,fallback}:{config:Record<string,unknown>;fallback:ReactNode}){const ctx=runtime(),rows=records(config.engineConfigs).filter(row=>row.engineKind==='guided_finder'),record=pick(rows,text(config.finderKey)),result=record&&ctx?.finder[record.configKey];if(!record||!result)return <>{fallback}</>;return <section data-existing-commerce-runtime="guided-results" style={{display:'grid',gap:'.8rem'}}><h2 style={{margin:0}}>{text(config.title,'Ajánlott találatok')}</h2><p>{result.explanation}</p>{result.results.map(item=><a key={item.id} href={item.href} style={{...cardStyle,color:'inherit',textDecoration:'none'}}>{item.label}</a>)}</section>}
export function GuidedExplanationRuntime({config,fallback}:{config:Record<string,unknown>;fallback:ReactNode}){const ctx=runtime(),rows=records(config.engineConfigs).filter(row=>row.engineKind==='guided_finder'),record=pick(rows,text(config.finderKey)),result=record&&ctx?.finder[record.configKey];if(!record||!result)return <>{fallback}</>;const evidence=result.results[0]?.evidence??[];return <section data-existing-commerce-runtime="guided-explanation" style={{display:'grid',gap:'.6rem'}}><h2 style={{margin:0}}>{text(config.title,'Miért ezt ajánljuk?')}</h2>{evidence.map(item=><div key={item.ruleId} style={cardStyle}><strong>{item.matched?'✓':'—'} {item.reason}</strong></div>)}</section>}

function composerCatalog(config:MultiProductComposerConfig,catalog:CatalogRow[]):ComposerCatalogItem[]{return catalog.map(item=>({...item,slotIds:config.mode==='slots'?(config.slots??[]).filter(slot=>!slot.eligibleProductIds||slot.eligibleProductIds.includes(item.productId)).map(slot=>slot.id):undefined}));}
export function ComposerRuntime({config,fallback}:{config:Record<string,unknown>;fallback:ReactNode}){
  const{replaceCommerceGroup}=useCart(),rows=records(config.engineConfigs).filter(row=>row.engineKind==='multi_product_composer'),record=pick(rows,text(config.composerKey)),source=record?(record.document as StorefrontComposerDocument).config:null,catalog=catalogRows(config.catalog),[selections,setSelections]=useState<ComposerSelection[]>([]),[notice,setNotice]=useState('');
  useEffect(()=>{setSelections([]);setNotice('')},[record?.configKey]);
  const commerceCatalog=useMemo(()=>source?composerCatalog(source,catalog):[],[source,catalog]);
  const model=useMemo(()=>source?buildComposerReadModel({config:source,selections,catalog:commerceCatalog}):null,[source,selections,commerceCatalog]);
  if(!source||!record)return <>{fallback}</>;
  const change=(item:CatalogRow,slotId:string|undefined,delta:number)=>setSelections(current=>{const index=current.findIndex(row=>row.variantId===item.variantId&&(row.slotId??'')===(slotId??'')),existing=index>=0?current[index]:undefined,nextQty=(existing?.quantity??0)+delta;if(nextQty<=0)return current.filter((_,i)=>i!==index);const next={productId:item.productId,variantId:item.variantId,quantity:nextQty,...(slotId?{slotId}:{})};return index>=0?current.map((row,i)=>i===index?next:row):[...current,next];});
  const add=()=>{const compositionId=newKey('composition'),intent=buildComposerAddIntent(compositionId,{config:source,selections,catalog:commerceCatalog});if(!intent)return;const items=intent.lines.flatMap((line,index)=>{const item=catalog.find(candidate=>candidate.productId===line.productId&&candidate.variantId===line.variantId);if(!item)return[];const itemKey=`item-${index}-${line.variantId}`;return[{productId:item.productId,variantId:item.variantId,slug:item.slug,name:item.label,unitPrice:item.price.amountMinor,quantity:line.quantity,minimumQuantity:1,orderMultiple:1,lineId:`${compositionId}:${itemKey}`,commerceGroup:{type:'composition' as const,id:compositionId,engineVersion:intent.engineVersion,definitionKey:intent.composerKey,definitionVersion:intent.composerVersion,itemKey,slotId:line.slotId??null}}]});replaceCommerceGroup('composition',compositionId,items);setNotice('Az összeállítás bekerült a kosárba.')};
  const renderItems=(slotId?:string)=>catalog.filter(item=>{if(!item.eligible||!item.channelVisible||!item.stock.available)return false;if(!slotId)return true;const eligibleIds=source.slots?.find(slot=>slot.id===slotId)?.eligibleProductIds;return!eligibleIds?.length||eligibleIds.includes(item.productId)}).map(item=>{const qty=selections.find(row=>row.variantId===item.variantId&&(row.slotId??'')===(slotId??''))?.quantity??0;return <div key={`${slotId??'pool'}:${item.variantId}`} style={cardStyle}><strong>{item.label}</strong><small style={{display:'block'}}>{item.price.display} · {item.stock.statusLabel}</small><div style={{display:'flex',gap:'.5rem',alignItems:'center',marginTop:'.5rem'}}><button type="button" aria-label={`${item.label} mennyiségének csökkentése`} disabled={qty<=0} onClick={()=>change(item,slotId,-1)}>−</button><span aria-live="polite" aria-atomic="true">{qty}</span><button type="button" aria-label={`${item.label} mennyiségének növelése`} onClick={()=>change(item,slotId,1)}>+</button></div></div>});
  return <section data-existing-commerce-runtime="composer" style={{display:'grid',gap:'1rem',padding:'clamp(1.25rem,3vw,2.5rem)',background:'var(--shoporation-color-surface,#f5efe4)',borderRadius:'1rem'}}><h2 style={{margin:0}}>{text(config.title,source.label)}</h2>{text(config.copy)?<p>{text(config.copy)}</p>:null}{source.mode==='slots'?(source.slots??[]).map(slot=><div key={slot.id} style={{display:'grid',gap:'.6rem'}}><strong>{slot.label} · {slot.minItems}–{slot.maxItems} db</strong><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(12rem,1fr))',gap:'.6rem'}}>{renderItems(slot.id)}</div></div>):<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(12rem,1fr))',gap:'.6rem'}}>{renderItems()}</div>}<div><strong>{model?.totalItems??0} / {source.minItems}–{source.maxItems} db</strong>{model?.currentSubtotalMinor!==null&&model?.currentSubtotalMinor!==undefined?<span> · {new Intl.NumberFormat('hu-HU').format(model.currentSubtotalMinor)} {model.currency}</span>:null}</div>{model?.violations.length?<small>{model.violations[0]?.message}</small>:null}<button type="button" disabled={model?.status!=='ready'} onClick={add}>{text(config.actionLabel,'Összeállítás kosárba')}</button>{notice?<small role="status">{notice}</small>:null}</section>;
}

function configuratorCatalog(config:ProductConfiguratorConfig,catalog:CatalogRow[]):ConfiguratorCatalogPart[]{return catalog.map(item=>({...item,slotIds:config.slots.filter(slot=>!slot.eligibleProductIds||slot.eligibleProductIds.includes(item.productId)).map(slot=>slot.id)}));}
export function ConfiguratorRuntime({config,fallback}:{config:Record<string,unknown>;fallback:ReactNode}){
  const ctx=runtime(),setConfigurator=ctx?.setConfigurator,{replaceCommerceGroup}=useCart(),rows=records(config.engineConfigs).filter(row=>row.engineKind==='product_configurator'),record=pick(rows,text(config.configuratorKey)),document=record?record.document as StorefrontConfiguratorDocument:null,source=document?.config??null,rules=(document?.compatibilityRules??[]) as readonly CompatibilityRule[],catalog=catalogRows(config.catalog),[selections,setSelections]=useState<ConfiguratorSelection[]>([]),[notice,setNotice]=useState('');
  useEffect(()=>{setSelections([]);setNotice('')},[record?.configKey]);
  const parts=useMemo(()=>source?configuratorCatalog(source,catalog):[],[source,catalog]);
  const model=useMemo(()=>source?buildConfiguratorReadModel({config:source,selections,catalog:parts,compatibilityRules:rules}):null,[source,selections,parts,rules]);
  useEffect(()=>{if(setConfigurator&&record)setConfigurator(record.configKey,model??undefined,selections)},[setConfigurator,record?.configKey,model,selections]);
  if(!source||!record)return <>{fallback}</>;
  const choose=(slotId:string,value:string)=>setSelections(current=>{const without=current.filter(item=>item.slotId!==slotId);if(!value)return without;const [productId,variantId]=value.split('|');return productId&&variantId?[...without,{slotId,productId,variantId}]:without;});
  const add=()=>{const configurationId=newKey('configuration'),intent=buildConfiguratorAddIntent(configurationId,{config:source,selections,catalog:parts,compatibilityRules:rules});if(!intent)return;const items=intent.lines.flatMap((line,index)=>{const item=catalog.find(candidate=>candidate.productId===line.productId&&candidate.variantId===line.variantId);if(!item)return[];const itemKey=`item-${index}-${line.variantId}`;return[{productId:item.productId,variantId:item.variantId,slug:item.slug,name:item.label,unitPrice:item.price.amountMinor,quantity:1,minimumQuantity:1,orderMultiple:1,lineId:`${configurationId}:${itemKey}`,commerceGroup:{type:'configuration' as const,id:configurationId,engineVersion:intent.engineVersion,definitionKey:intent.configuratorKey,definitionVersion:intent.configuratorVersion,itemKey,slotId:line.slotId}}]});replaceCommerceGroup('configuration',configurationId,items);setNotice('A konfiguráció bekerült a kosárba.')};
  return <section data-existing-commerce-runtime="configurator" style={{display:'grid',gap:'1rem',padding:'clamp(1.25rem,3vw,2.5rem)',background:'var(--shoporation-color-surface,#171a20)',border:'1px solid var(--shoporation-color-border,#333)',borderRadius:'1rem'}}><h2 style={{margin:0}}>{text(config.title,source.label)}</h2>{source.slots.map(slot=>{const selected=selections.find(item=>item.slotId===slot.id);const eligible=parts.filter(part=>part.slotIds.includes(slot.id)&&part.eligible&&part.channelVisible&&part.stock.available);return <label key={slot.id} style={{display:'grid',gap:'.35rem'}}><strong>{slot.label}{slot.required?' *':''}</strong><select value={selected?`${selected.productId}|${selected.variantId}`:''} onChange={event=>choose(slot.id,event.target.value)}><option value="">Nincs kiválasztva</option>{eligible.map(part=><option key={part.variantId} value={`${part.productId}|${part.variantId}`}>{part.label} · {part.price.display}</option>)}</select></label>})}<strong role="status">{model?.status==='ready'?'Kompatibilis és kosárba tehető':model?.status==='incompatible'?'Nem kompatibilis':model?.status==='unknown'?'A kompatibilitás nem igazolható':'Hiányos konfiguráció'}</strong>{model?.violations.length?<small>{model.violations[0]?.message}</small>:null}<button type="button" disabled={model?.status!=='ready'} onClick={add}>{text(config.actionLabel,'Konfiguráció kosárba')}</button>{notice?<small role="status">{notice}</small>:null}</section>;
}

function selectedConfigurator(config:Record<string,unknown>,ctx:RuntimeContextValue|null){const rows=records(config.engineConfigs).filter(row=>row.engineKind==='product_configurator'),record=pick(rows,text(config.configuratorKey));return{record,model:record?ctx?.configurator[record.configKey]:undefined,selections:record?ctx?.configSelections[record.configKey]??[]:[]};}
export function ConfiguratorSlotListRuntime({config,fallback}:{config:Record<string,unknown>;fallback:ReactNode}){const ctx=runtime(),{record,model,selections}=selectedConfigurator(config,ctx);if(!record||!model)return <>{fallback}</>;const document=record.document as StorefrontConfiguratorDocument;return <section data-existing-commerce-runtime="configurator-slots" style={{display:'grid',gap:'.7rem'}}><h2>{text(config.title,'Komponensek')}</h2>{document.config.slots.map(slot=>{const selected=selections.find(item=>item.slotId===slot.id),row=model.selections.find(item=>item.selection.slotId===slot.id);return <div key={slot.id} style={cardStyle}><strong>{slot.label}</strong><span style={{display:'block'}}>{row?.part.label??(selected?'Nem elérhető':'Nincs kiválasztva')}</span></div>})}</section>}
export function CompatibilityStatusRuntime({config,fallback}:{config:Record<string,unknown>;fallback:ReactNode}){const ctx=runtime(),{record,model}=selectedConfigurator(config,ctx),hideUnknown=config.hideWhenUnknown===true;if(!record||!model)return hideUnknown?null:<>{fallback}</>;const status=model.compatibility?.status??'unknown';if(hideUnknown&&status==='unknown')return null;const label=status==='compatible'?text(config.compatibleLabel,'Kompatibilis'):status==='incompatible'?text(config.incompatibleLabel,'Nem kompatibilis'):text(config.unknownLabel,'Ismeretlen');return <section data-existing-commerce-runtime="compatibility-status" data-status={status} style={cardStyle}><small>{text(config.title,'Compatibility')}</small><strong style={{display:'block',fontSize:'1.2rem'}}>{label}</strong><p>{status==='unknown'?'A rendelkezésre álló strukturált adatokból nem igazolható a kompatibilitás. Az ismeretlen állapot nem kompatibilis.':model.compatibility?.results.map(item=>item.explanation).join(' ')}</p></section>}
export function CompatibilityEvidenceRuntime({config,fallback}:{config:Record<string,unknown>;fallback:ReactNode}){const ctx=runtime(),{record,model}=selectedConfigurator(config,ctx);if(!record||!model?.compatibility)return <>{fallback}</>;return <section data-existing-commerce-runtime="compatibility-evidence" style={{display:'grid',gap:'.7rem'}}><h2>{text(config.title,'Kompatibilitási bizonyíték')}</h2>{model.compatibility.results.length?model.compatibility.results.map(item=><div key={item.ruleId} style={cardStyle}><strong>{item.label} · {item.status}</strong><p>{item.explanation}</p><small>{item.leftDisplay} ↔ {item.rightDisplay}</small></div>):<p>{text(config.emptyLabel,'Nincs elég strukturált bizonyíték; az állapot ismeretlen.')}</p>}</section>}
