import { getCurrentAddons, getCurrentPlan } from '@/lib/plans/access';
import { ADDONS } from '@/lib/plans/addons';
import { PLANS, type FeatureCode } from '@/lib/plans/catalog';

const FEATURE_LABELS: Record<FeatureCode,string>={catalog:'Termék-, kategória- és katalóguskezelés',inventory:'Készletkezelés és napi készletműveletek',orders:'Teljes rendeléskezelés',returns:'Visszáru és elállás kezelése',customers:'Ügyféladatbázis és vásárlói adatok',coupons:'Kuponok, kedvezmények és akciók',basicAnalytics:'Értékesítési statisztikák és dashboard',marketingBasics:'Alap marketingeszközök',contentMarketing:'Tartalomkezelés, blog és SEO',importExport:'Termék import és export',bulkOperations:'Tömeges termék- és készletműveletek',wishlists:'Kívánságlista',stockNotifications:'Készlet-visszaérkezési értesítések',productRecommendations:'Cross-sell, upsell és termékajánlások',reviews:'Vásárlói vélemények és moderáció',searchFiltering:'Termékkeresés és szűrés',commerceIntegrations:'Fizetés, szállítás és számlázási integrációk',support:'Ügyfélszolgálati eszközök',advancedAnalytics:'Részletes üzleti elemzések',crm:'Fejlett CRM, ügyfélérték és utánkövetés',advancedCampaigns:'Kampányközpont, attribúció és megtérülés',officeCommunication:'Digitális iroda és kommunikáció',automation:'Automatizálások és üzemi vezérlés',procurement:'Készlet- és beszerzéstervezés',cashflow:'Cash-flow és pénzügyi előrejelzés',executiveAnalytics:'Vezetői analitika és döntéstámogatás',advancedIntegrations:'Haladó rendszerintegrációk',apiAccess:'Külső API-hozzáférés'};
type Props={searchParams?:Promise<{reason?:string;feature?:string;addon?:string}>};

export default async function PackagePage({searchParams}:Props){
  const[current,enabledAddons,params]=await Promise.all([getCurrentPlan(),getCurrentAddons(),searchParams??Promise.resolve({})]);
  const alap=new Set<FeatureCode>(PLANS.alap.features),pro=new Set<FeatureCode>(PLANS.pro.features);
  const rows=[...new Set<FeatureCode>([...PLANS.alap.features,...PLANS.pro.features])];
  const requested=params.feature as FeatureCode|undefined;
  return <section className="adminMain">
    <span className="eyebrow">Shoperation csomagok</span><h1 className="sectionTitle">Csomagkezelés</h1><p className="lead">Átlátható összehasonlítás arról, mit tartalmaz az Alap, mit ad hozzá a Pro, és mely kiegészítők kapcsolhatók külön havidíjjal.</p>
    <div className="cards adminMetricCards"><article className="card"><span className="badge">Aktív csomag</span><div className="price">Shoperation {PLANS[current].name}</div><p className="muted">{PLANS[current].description}</p></article><article className="card"><span className="badge">Külön aktiválható extrák</span><div className="price">{enabledAddons.length}</div><p className="muted">A csomagtól külön kezelhető szolgáltatások.</p></article></div>
    {params.reason==='pro-required'&&<div className="adminAuditNotice"><strong>Ez a funkció Pro képesség.</strong><p>{requested&&FEATURE_LABELS[requested]?FEATURE_LABELS[requested]:'A megnyitott funkció'} a Pro csomag része.</p></div>}
    {params.reason==='addon-required'&&<div className="adminAuditNotice"><strong>Külön kiegészítő szükséges.</strong><p>Az extra nem új csomagszint: Alap vagy Pro mellé külön kapcsolható be, ha kompatibilis.</p></div>}
    <section className="card"><div className="adminToolbar"><div><span className="eyebrow">Funkciómátrix</span><h2>Alap vagy Pro?</h2></div></div><div className="packageLegend"><span className="badge">✓ tartalmazza</span><span className="badge">— nem része</span></div><div className="adminTableScroll"><table className="adminTable packageMatrix"><thead><tr><th>Funkció</th><th>Shoperation Alap</th><th>Shoperation Pro</th></tr></thead><tbody>{rows.map(feature=><tr key={feature}><td><strong>{FEATURE_LABELS[feature]}</strong></td><td className={alap.has(feature)?'yes':'no'}>{alap.has(feature)?'✓':'—'}</td><td className={pro.has(feature)?'yes':'no'}>{pro.has(feature)?'✓':'—'}</td></tr>)}</tbody></table></div></section>
    <section className="card"><span className="eyebrow">Külön aktiválható kiegészítők</span><h2>Extrák Alap és Pro mellé</h2><p className="muted">Az AI és más feláras szolgáltatások nem feltétlenül Pro-exkluzívak. A kompatibilis csomag mellé külön havidíjjal kapcsolhatók.</p><div className="cards">{Object.values(ADDONS).map(addon=><article className="card" key={addon.code}><span className="badge">{enabledAddons.includes(addon.code)?'Aktív':'Külön extra'}</span><h3>{addon.name}</h3><p>{addon.description}</p><p className="muted">Elérhető: {addon.compatiblePlans.map(plan=>plan==='alap'?'Alap':'Pro').join(' + ')}</p></article>)}</div></section>
  </section>;
}
