import { createAdminClient } from '@/lib/supabase/admin';
import { communicationTemplates } from '@/lib/communication/templates';

export const dynamic='force-dynamic';
type Job={id:string;recipient_email:string;purpose:string;template_key:string;status:string;attempts:number;scheduled_at:string;sent_at:string|null;last_error:string|null;provider_message_id:string|null;created_at:string};
const statusLabel:Record<string,string>={pending:'Várakozik',processing:'Feldolgozás',sent:'Elküldve',failed:'Hibás',blocked:'Blokkolva',cancelled:'Törölve'};
export default async function CommunicationAdmin(){const admin=createAdminClient();const {data,error}=await admin.from('communication_jobs').select('id,recipient_email,purpose,template_key,status,attempts,scheduled_at,sent_at,last_error,provider_message_id,created_at').order('created_at',{ascending:false}).limit(500);const jobs=(data??[]) as Job[];const count=(s:string)=>jobs.filter(j=>j.status===s).length;const marketing=jobs.filter(j=>j.purpose==='marketing').length;const transactional=jobs.filter(j=>j.purpose==='transactional').length;
return <section className="adminMain"><span className="eyebrow">Admin · Kommunikáció</span><h1 className="sectionTitle">Kommunikációs műveleti központ</h1><p className="lead">Küldési sor, sablonok, hibák és auditállapot egy helyen. A szolgáltatói e-mail adapter bekötéséig ez a réteg nem küld külső levelet.</p>{error&&<div className="errorNotice"><strong>A kommunikációs sor most nem olvasható.</strong></div>}
<div className="cards adminMetricCards"><div className="card"><span className="badge">Várakozik</span><div className="price">{count('pending')}</div><p className="muted">ütemezett küldési feladat</p></div><div className="card"><span className="badge">Hibás / blokkolt</span><div className="price">{count('failed')+count('blocked')}</div><p className="muted">beavatkozást igényel</p></div><div className="card"><span className="badge">Elküldve</span><div className="price">{count('sent')}</div><p className="muted">auditált sikeres küldés</p></div><div className="card"><span className="badge">Cél</span><div className="price">{transactional}/{marketing}</div><p className="muted">tranzakciós / marketing feladat</p></div></div>
<section className="card"><span className="eyebrow">Sablonregiszter</span><h2>Engedélyezett kommunikációs típusok</h2><div className="integrationList">{communicationTemplates.map(t=><div key={t.key}><span><strong>{t.subject}</strong><br/><span className="muted">{t.description}</span></span><strong>{t.purpose==='marketing'?'Marketing':'Tranzakciós'}</strong></div>)}</div></section>
<section className="tableCard"><div className="adminTableScroll"><table className="adminTable"><thead><tr><th>Címzett</th><th>Típus / sablon</th><th>Állapot</th><th>Ütemezés</th><th>Próbálkozás</th><th>Szolgáltató / hiba</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><strong>{j.recipient_email}</strong></td><td>{j.purpose==='marketing'?'Marketing':'Tranzakciós'}<br/><span className="muted">{j.template_key}</span></td><td><span className="badge">{statusLabel[j.status]??j.status}</span>{j.sent_at&&<><br/><span className="muted">{new Intl.DateTimeFormat('hu-HU',{dateStyle:'short',timeStyle:'short'}).format(new Date(j.sent_at))}</span></>}</td><td>{new Intl.DateTimeFormat('hu-HU',{dateStyle:'short',timeStyle:'short'}).format(new Date(j.scheduled_at))}</td><td>{j.attempts}</td><td>{j.provider_message_id?<span className="muted">{j.provider_message_id}</span>:j.last_error?<span className="muted">{j.last_error}</span>:<span className="muted">—</span>}</td></tr>)}</tbody></table></div>{jobs.length===0&&<p className="muted">Még nincs kommunikációs feladat a sorban.</p>}</section>
<p className="muted">Marketingfeladat csak aktív hozzájárulással kerülhet a sorba. Az idempotencia-kulcs ugyanazon kommunikáció többszöri sorba állítását akadályozza meg.</p></section>;
}
