import Link from 'next/link';
import { AuthForm } from '@/components/auth/auth-form';
import { LogoutButton } from '@/components/auth/logout-button';
import { ProfileForm } from '@/components/account/profile-form';
import { MarketingConsentForm } from '@/components/account/marketing-consent-form';
import { ResellerRequestButton } from '@/components/account/reseller-request-button';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { getCurrentWebshopInstance } from '@/lib/instances/access';
import { formatHuf } from '@/lib/catalog';
import { orderStatusDescription,orderStatusLabel,paymentMethodLabel,shippingMethodLabel,trackingProviderUrl } from '@/lib/order-display';

export default async function AccountPage(){
 const instance=await getCurrentWebshopInstance(),brandName=instance?.brand.name??'Webáruház',configured=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY));
 if(!configured)return <main className="section accountPage"><div className="shell"><span className="eyebrow">{brandName} fiók</span><h1 className="sectionTitle">A saját vásárlói központod.</h1><div className="card"><h2>A hitelesítés még nincs konfigurálva.</h2><p className="muted">A publikus webshop ettől függetlenül használható.</p><Link className="btn btnPrimary" href="/webaruhaz">Vásárlás</Link></div></div></main>;
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();
 if(!user)return <main className="section accountPage"><div className="shell"><span className="eyebrow">{brandName} fiók</span><h1 className="sectionTitle">Belépés vagy regisztráció</h1><p className="muted">Belépés után egy helyen követheted a rendeléseidet, számláidat és szállításaidat.</p><AuthForm instanceId={instance?.id??null}/></div></main>;
 if(!instance)return <main className="section accountPage"><div className="shell"><div className="card"><h1>Nincs aktív webshop.</h1><LogoutButton/></div></div></main>;

 const[profileResult,partnerResult,ordersResult,wishlistResult]=await Promise.all([
  supabase.from('profiles').select('full_name,company_name,tax_number').eq('id',user.id).maybeSingle(),
  supabase.from('customer_instance_roles').select('role,reseller_approved,reseller_requested_at,approved_at').eq('instance_id',instance.id).eq('user_id',user.id).maybeSingle(),
  supabase.from('orders').select('id,order_number,status,total_gross_huf,created_at,shipping_method,payment_method,tracking_number,invoice_number,invoice_url').eq('instance_id',instance.id).eq('customer_id',user.id).order('created_at',{ascending:false}).limit(50),
  supabase.from('wishlists').select('id',{count:'exact',head:true}).eq('instance_id',instance.id).eq('user_id',user.id),
 ]);
 const profile=profileResult.data,partner=partnerResult.data,orders=ordersResult.data,wishlistCount=wishlistResult.count,accountLoadError=Boolean(profileResult.error||partnerResult.error||ordersResult.error||wishlistResult.error);
 let marketingConsent=false,marketingLoadError=false;
 try{const admin=createAdminClient();const{data,error}=await admin.from('marketing_consents').select('status').eq('instance_id',instance.id).eq('user_id',user.id).eq('channel','email').order('occurred_at',{ascending:false}).limit(1).maybeSingle();marketingConsent=data?.status==='granted';marketingLoadError=Boolean(error)}catch{marketingLoadError=true}
 const roleLabel=partner?.role==='reseller'?(partner.reseller_approved?'Jóváhagyott viszonteladó':'Viszonteladói partner – jóváhagyás alatt'):'Vásárló',orderList=orders??[],activeOrders=orderList.filter(order=>!['completed','cancelled','refunded'].includes(order.status)),completedOrders=orderList.filter(order=>order.status==='completed'),totalSpent=completedOrders.reduce((sum,order)=>sum+Number(order.total_gross_huf||0),0),latestActive=activeOrders[0],latestTrackingUrl=latestActive?trackingProviderUrl(latestActive.shipping_method):null;

 return <main className="section accountPage"><div className="shell">
  <div className="sectionIntro"><div><span className="eyebrow">{brandName} fiók</span><h1 className="sectionTitle">Szia, {profile?.full_name?.split(' ')[0]||'üdv újra'}!</h1><p className="lead">Rendelések, szállítás, számlák és mentett termékek egyetlen áttekinthető helyen.</p></div><div className="actions"><Link className="btn btnPrimary" href="/webaruhaz">Új rendelés</Link><Link className="btn btnGhost" href="/fiokom/kivansaglista">Kívánságlista ({wishlistCount??0})</Link><LogoutButton/></div></div>
  {accountLoadError&&<div className="errorNotice" role="alert"><strong>A fiókadatok egy része most nem tölthető be.</strong><p>Ne tekintsd üresnek a rendelési vagy kívánságlista-adatokat, amíg ez az üzenet látható.</p></div>}
  {latestActive&&<section className="featurePanel accountHero"><div className="sectionIntro"><div><span className="eyebrow">Legutóbbi aktív rendelés</span><h2>{latestActive.order_number} · {orderStatusLabel(latestActive.status)}</h2><p className="muted">{orderStatusDescription(latestActive.status,latestActive.payment_method,latestActive.shipping_method)}</p></div><div className="actions"><Link className="btn btnPrimary" href={`/fiokom/rendeles/${latestActive.id}`}>Rendelés követése</Link>{latestActive.tracking_number&&latestTrackingUrl?<a className="btn btnGhost" href={latestTrackingUrl} target="_blank" rel="noreferrer">Futár oldala</a>:null}</div></div></section>}
  <div className="cards accountFeatureGrid"><article className="card"><span className="badge">Folyamatban</span><div className="price">{activeOrders.length}</div><p className="muted">Aktív rendelés.</p></article><article className="card"><span className="badge">Teljesített</span><div className="price">{completedOrders.length}</div><p className="muted">Lezárt rendelések.</p></article><article className="card"><span className="badge">Kívánságlista</span><div className="price">{wishlistCount??0}</div><p className="muted">Elmentett termék.</p><Link className="textLink" href="/fiokom/kivansaglista">Megnyitás</Link></article><article className="card"><span className="badge">Teljesített érték</span><div className="price">{formatHuf(totalSpent)}</div><p className="muted">A teljesített rendelések összege.</p></article></div>
  <div className="splitFeature accountProfileGrid"><section className="featurePanel"><span className="eyebrow">Profil és számlázási alapadatok</span><h2>{profile?.full_name||user.email}</h2><ProfileForm fullName={profile?.full_name??''} companyName={profile?.company_name??''} taxNumber={profile?.tax_number??''}/></section><section className="featurePanel"><span className="eyebrow">Kommunikáció</span><h2>Marketing beállítások</h2>{marketingLoadError&&<p className="errorNotice" role="alert">A marketing-hozzájárulás aktuális állapota most nem tölthető be.</p>}<MarketingConsentForm initialConsent={marketingConsent}/><hr/><span className="eyebrow">Partnerstátusz · {brandName}</span><h3>{roleLabel}</h3>{partner?.role==='reseller'&&!partner.reseller_approved?<p className="muted">A partnerigény kizárólag ehhez a webshophoz tartozik. Jóváhagyásig lakossági árak és hozzáférési szabályok érvényesek.</p>:partner?.role==='reseller'&&partner.reseller_approved?<p className="muted">A partnerár és a B2B kínálat ebben a webshopban aktív.</p>:<ResellerRequestButton/>}</section></div>
  <div className="sectionIntro"><div><span className="eyebrow">Rendeléseim</span><h2>Rendelési előzmények</h2></div></div>
  <section className="tableCard"><div className="adminTableScroll"><table className="adminTable"><thead><tr><th>Rendelés</th><th>Állapot</th><th>Összeg</th><th>Szállítás / fizetés</th><th>Dokumentum</th><th>Dátum</th></tr></thead><tbody>{orderList.map(order=><tr key={order.id}><td><Link className="textLink" href={`/fiokom/rendeles/${order.id}`}><strong>{order.order_number}</strong></Link></td><td><span className="badge">{orderStatusLabel(order.status)}</span></td><td><strong>{formatHuf(order.total_gross_huf)}</strong></td><td>{shippingMethodLabel(order.shipping_method)} / {paymentMethodLabel(order.payment_method)}</td><td>{order.invoice_url?<a className="textLink" href={order.invoice_url} target="_blank" rel="noreferrer">{order.invoice_number??'Számla'}</a>:<span className="muted">Folyamatban</span>}</td><td>{new Intl.DateTimeFormat('hu-HU',{dateStyle:'short'}).format(new Date(order.created_at))}</td></tr>)}</tbody></table></div>{!accountLoadError&&!orderList.length&&<div className="accountEmptyState"><h3>Még nincs rendelésed ebben a webshopban.</h3><Link className="btn btnPrimary" href="/webaruhaz">Irány a webáruház</Link></div>}</section>
 </div></main>;
}
