'use client';

import { useMemo } from 'react';
import { useCart } from '@/components/cart/cart-provider';
import { useAnalytics } from '@/components/analytics/analytics-provider';
import { formatHuf,type Product } from '@/lib/catalog';
import type { RecommendationRule } from '@/lib/recommendations/server';

type Props={products:Product[];rules?:RecommendationRule[];context?:'cart'|'confirmation'};

export function ProductRecommendations({products,rules=[],context='cart'}:Props){const{items,add}=useCart(),{track}=useAnalytics();const recommendations=useMemo(()=>{const inCart=new Set(items.map(item=>item.variantId??item.productId)),byId=new Map(products.map(product=>[product.id,product])),sourceIds=context==='cart'?inCart:new Set<string>();const configured=rules.filter(rule=>rule.active&&(!rule.sourceVariantId||sourceIds.has(rule.sourceVariantId))).sort((a,b)=>a.priority-b.priority).map(rule=>byId.get(rule.recommendedVariantId)).filter((product):product is Product=>Boolean(product&&product.stock>=product.minimumQuantity&&!inCart.has(product.id)));const unique=[...new Map(configured.map(product=>[product.id,product])).values()];if(unique.length>=3)return unique.slice(0,3);const fallback=products.filter(product=>product.stock>=product.minimumQuantity&&!inCart.has(product.id)&&!unique.some(item=>item.id===product.id));return[...unique,...fallback].slice(0,3)},[products,rules,items,context]);if(!recommendations.length)return null;
 return <section className="featurePanel recommendationPanel"><div className="sectionIntro"><div><span className="eyebrow">{context==='confirmation'?'Még hasznos lehet':'Gyakran együtt választják'}</span><h2>{context==='confirmation'?'Egészítsd ki a következő rendelésed.':'Egészítsd ki a kosarad.'}</h2><p className="muted">Az ajánlatok a webshopban beállított sorrendet követik, és csak elérhető terméket mutatnak.</p></div></div><div className="cards recommendationGrid">{recommendations.map(product=><article className="card" key={product.id}><span className="badge">{product.size}</span><h3>{product.name}</h3><p className="muted">{product.short}</p><strong className="price">{formatHuf(product.grossPrice)}</strong>{product.minimumQuantity>1&&<small className="muted">Minimum {product.minimumQuantity} db</small>}<button className="btn btnGhost" type="button" onClick={()=>{add({productId:product.id,variantId:product.id,slug:product.slug,name:product.name,unitPrice:product.grossPrice,quantity:product.minimumQuantity,minimumQuantity:product.minimumQuantity,orderMultiple:product.orderMultiple});track('select_item',{item_id:product.id,item_name:product.name,item_list_name:context==='cart'?'cart_cross_sell':'post_purchase_offer',value:product.grossPrice*product.minimumQuantity,currency:'HUF'});track('add_to_cart',{item_id:product.id,item_name:product.name,value:product.grossPrice*product.minimumQuantity,currency:'HUF',quantity:product.minimumQuantity})}}>{context==='confirmation'?'Kosárba a következő vásárláshoz':'Kosárhoz adom'}</button></article>)}</div></section>
}
