'use client';

import { useMemo } from 'react';
import { useCart } from '@/components/cart/cart-provider';
import { useAnalytics } from '@/components/analytics/analytics-provider';
import { formatHuf,type Product } from '@/lib/catalog';
import type { RecommendationRule } from '@/lib/recommendations/server';

type Props={products:Product[];rules?:RecommendationRule[]};

export function ProductRecommendations({products,rules=[]}:Props){const{items,add}=useCart(),{track}=useAnalytics();const recommendations=useMemo(()=>{const inCart=new Set(items.map(item=>item.variantId??item.productId)),byId=new Map(products.map(product=>[product.id,product])),sourceIds=inCart;const configured=rules.filter(rule=>rule.active&&(!rule.sourceVariantId||sourceIds.has(rule.sourceVariantId))).sort((a,b)=>a.priority-b.priority).map(rule=>byId.get(rule.recommendedVariantId)).filter((product):product is Product=>Boolean(product&&product.stock>=product.minimumQuantity&&!inCart.has(product.id)));const unique=[...new Map(configured.map(product=>[product.id,product])).values()];if(unique.length>=3)return unique.slice(0,3);const fallback=products.filter(product=>product.stock>=product.minimumQuantity&&!inCart.has(product.id)&&!unique.some(item=>item.id===product.id));return[...unique,...fallback].slice(0,3)},[products,rules,items]);if(!recommendations.length)return null;
 return <section className="featurePanel recommendationPanel" data-cart-cross-sell="shared" data-cart-cross-sell-presentation="template-native" style={{background:'var(--card,var(--shoporation-color-surface))',color:'var(--ink,var(--shoporation-color-text))',borderColor:'var(--line,var(--shoporation-color-border))',boxShadow:'none'}}><div className="sectionIntro"><div><span className="eyebrow">Gyakran együtt választják</span><h2 style={{color:'var(--ink,var(--shoporation-color-text))'}}>Egészítsd ki a kosarad.</h2><p style={{color:'var(--muted,var(--shoporation-color-muted-text))'}}>Az ajánlatok a webshopban beállított sorrendet követik, és csak elérhető terméket mutatnak.</p></div></div><div className="cards recommendationGrid">{recommendations.map(product=><article className="card" key={product.id} style={{background:'var(--card,var(--shoporation-color-surface))',color:'var(--ink,var(--shoporation-color-text))',borderColor:'var(--line,var(--shoporation-color-border))'}}><span className="badge">{product.size}</span><h3>{product.name}</h3><p style={{color:'var(--muted,var(--shoporation-color-muted-text))'}}>{product.short}</p><strong className="price">{formatHuf(product.grossPrice)}</strong>{product.minimumQuantity>1&&<small style={{color:'var(--muted,var(--shoporation-color-muted-text))'}}>Minimum {product.minimumQuantity} db</small>}<button className="btn btnPrimary" type="button" style={{minHeight:44}} onClick={()=>{add({productId:product.id,variantId:product.id,slug:product.slug,name:product.name,unitPrice:product.grossPrice,quantity:product.minimumQuantity,minimumQuantity:product.minimumQuantity,orderMultiple:product.orderMultiple});track('select_item',{item_id:product.id,item_name:product.name,item_list_name:'cart_cross_sell',value:product.grossPrice*product.minimumQuantity,currency:'HUF'});track('add_to_cart',{item_id:product.id,item_name:product.name,value:product.grossPrice*product.minimumQuantity,currency:'HUF',quantity:product.minimumQuantity})}}>Kosárhoz adom</button></article>)}</div></section>
}
