import{redirect}from'next/navigation';import{createClient}from'@/lib/supabase/server';import{createAdminClient}from'@/lib/supabase/admin';import{getCurrentWebshopInstance}from'@/lib/instances/access';import{B2BQuoteRequestManager}from'@/components/account/b2b-quote-request-manager';
export const dynamic='force-dynamic';
export default async function B2BQuotesPage({searchParams}:{searchParams:Promise<{variantId?:string}>}){const q=await searchParams,[supabase,instance]=await Promise.all([createClient(),getCurrentWebshopInstance()]),{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/fiokom?next=/fiokom/ajanlatkeresek');if(!instance)redirect('/fiokom');const a=createAdminClient(),{data:relation}=await a.from('customer_instance_roles').select('role,reseller_approved,b2b_account_id').eq('instance_id',instance.id).eq('user_id',user.id).maybeSingle();if(relation?.role!=='reseller'||relation.reseller_approved!==true||!relation.b2b_account_id)redirect('/fiokom');
 const[{data:variantRows},{data:channelRows},{data:reqRows}]=await Promise.all([
  a.from('product_variants').select('id,sku,label,minimum_order_quantity,order_multiple,products!inner(id,name,active)').eq('instance_id',instance.id).eq('active',true),
  a.from('product_channel_settings').select('product_id').eq('instance_id',instance.id).eq('channel_code','b2b').eq('visible',true),
  a.from('b2b_quote_requests').select('id,status,note,created_at,submitted_at,opportunity_id').eq('instance_id',instance.id).eq('account_id',relation.b2b_account_id).order('created_at',{ascending:false}).limit(100)
 ]);
 const visible=new Set((channelRows??[]).map((x:any)=>x.product_id)),variants=(variantRows??[]).filter((x:any)=>x.products?.active&&visible.has(x.products.id)).map((x:any)=>({id:x.id,sku:x.sku,label:x.label,name:x.products.name,minimumQuantity:Math.max(1,Number(x.minimum_order_quantity||1)),orderMultiple:Math.max(1,Number(x.order_multiple||1))}));
 const requests=reqRows??[],ids=requests.map((x:any)=>x.id),oppIds=requests.flatMap((x:any)=>x.opportunity_id?[x.opportunity_id]:[]);
 const[{data:itemRows},{data:offerRows}]=await Promise.all([
  ids.length?a.from('b2b_quote_request_items').select('request_id,variant_id,quantity,product_variants!inner(sku,label,products!inner(name))').eq('instance_id',instance.id).in('request_id',ids):Promise.resolve({data:[]}),
  oppIds.length?a.from('commercial_offers').select('id,opportunity_id,status,quantity,total_net_huf,net_price_after_huf,expires_at,product_variants!inner(label,products!inner(name))').eq('instance_id',instance.id).in('opportunity_id',oppIds).in('status',['approved','sent','accepted','expired']).order('created_at',{ascending:false}):Promise.resolve({data:[]})
 ]);
 const view=requests.map((r:any)=>({id:r.id,status:r.status,note:r.note,createdAt:r.created_at,submittedAt:r.submitted_at,items:(itemRows??[]).filter((x:any)=>x.request_id===r.id).map((x:any)=>({variantId:x.variant_id,name:x.product_variants?.products?.name??'Termék',sku:x.product_variants?.sku??'',label:x.product_variants?.label??'',quantity:x.quantity})),offers:(offerRows??[]).filter((x:any)=>x.opportunity_id===r.opportunity_id).map((x:any)=>({id:x.id,status:x.status,quantity:x.quantity,totalNetHuf:x.total_net_huf==null?null:Number(x.total_net_huf),netPriceAfterHuf:x.net_price_after_huf==null?null:Number(x.net_price_after_huf),expiresAt:x.expires_at,name:x.product_variants?.products?.name??'Termék',label:x.product_variants?.label??''}))}));
 return <main className="section accountPage"><div className="shell"><div className="sectionIntro"><div><span className="eyebrow">B2B partnerfiók</span><h1 className="sectionTitle">Ajánlatkéréseim</h1><p className="lead">Piszkozat, beküldött kérés és kereskedői ajánlat ugyanabban a folyamatban.</p></div></div><B2BQuoteRequestManager variants={variants} requests={view} initialVariantId={q.variantId}/></div></main>}
