import Link from'next/link';
import{redirect}from'next/navigation';
import{getAdminRequestUser}from'@/lib/auth/admin-api';
import{requireCurrentStoreContext}from'@/lib/instances/scope';
import{requirePlanFeature}from'@/lib/plans/access';
import{createAdminClient}from'@/lib/supabase/admin';
import{updateMailboxResponsibilityAction,updateThreadRelationshipsAction}from'../communication-hub-actions';

export const dynamic='force-dynamic';
type Mailbox={mailbox_key:string;label:string;is_active:boolean;responsible_user_id:string|null};
type Thread={id:string;subject:string;customer_email:string|null;customer_user_id:string|null;customer_ref:string|null;sales_owner_user_id:string|null;mailbox_key:string|null;updated_at:string};
type Binding={user_id:string;valid_until:string|null};
type OrderCustomer={customer_id:string|null;customer_email:string};
type CustomerRef={customer_id:string};
type Profile={id:string;email:string|null;full_name:string|null};
const active=(until:string|null)=>!until||Date.parse(until)>Date.now();

export default async function CommunicationHubPage(){
  await requirePlanFeature('officeCommunicationAdvanced');const actor=await getAdminRequestUser('support.manage');if(!actor)redirect('/admin/hozzaferes-megtagadva');const scope=await requireCurrentStoreContext('support.manage');const db=createAdminClient();const now=new Date().toISOString();
  const[mailboxResult,threadResult,bindingResult,orderResult,valueResult,journeyResult]=await Promise.all([
    db.from('office_mailboxes').select('mailbox_key,label,is_active,responsible_user_id').eq('instance_id',scope.instanceId).order('label',{ascending:true}),
    db.from('office_threads').select('id,subject,customer_email,customer_user_id,customer_ref,sales_owner_user_id,mailbox_key,updated_at').eq('instance_id',scope.instanceId).eq('conversation_type','customer').order('updated_at',{ascending:false}).limit(300),
    scope.organizationId?db.from('role_bindings').select('user_id,valid_until').eq('organization_id',scope.organizationId).is('revoked_at',null).lte('valid_from',now).or(`instance_id.eq.${scope.instanceId},instance_id.is.null`):Promise.resolve({data:[]as Binding[],error:null}),
    db.from('orders').select('customer_id,customer_email').eq('instance_id',scope.instanceId).not('customer_id','is',null).order('created_at',{ascending:false}).limit(500),
    db.from('customer_value_profiles').select('customer_id').eq('instance_id',scope.instanceId).limit(500),
    db.from('customer_journeys').select('customer_id').eq('instance_id',scope.instanceId).limit(500),
  ]);
  const mailboxes=(mailboxResult.data??[])as Mailbox[],threads=(threadResult.data??[])as Thread[];const staffIds=[...new Set(((bindingResult.data??[])as Binding[]).filter(row=>active(row.valid_until)).map(row=>row.user_id))];const orderCustomers=(orderResult.data??[])as OrderCustomer[];const customerUserIds=[...new Set(orderCustomers.map(row=>row.customer_id).filter((value):value is string=>Boolean(value)))];const profileIds=[...new Set([...staffIds,...customerUserIds])];const profileResult=profileIds.length?await db.from('profiles').select('id,email,full_name').in('id',profileIds):{data:[]as Profile[],error:null};const profiles=(profileResult.data??[])as Profile[];const profileMap=new Map(profiles.map(profile=>[profile.id,profile]));const labelFor=(id:string)=>profileMap.get(id)?.full_name||profileMap.get(id)?.email||`${id.slice(0,8)}…`;const staff=staffIds.map(id=>({id,label:labelFor(id)})).sort((a,b)=>a.label.localeCompare(b.label,'hu'));const customerUsers=customerUserIds.map(id=>({id,label:profileMap.get(id)?.email||orderCustomers.find(row=>row.customer_id===id)?.customer_email||labelFor(id)})).sort((a,b)=>a.label.localeCompare(b.label,'hu'));const refs=[...new Set([...(valueResult.data??[]as CustomerRef[]).map(row=>row.customer_id),...(journeyResult.data??[]as CustomerRef[]).map(row=>row.customer_id)].filter(Boolean))].sort();const loadError=Boolean(mailboxResult.error||threadResult.error||bindingResult.error||orderResult.error||valueResult.error||journeyResult.error||profileResult.error);
  return <section className="adminMain"><div className="sectionIntro"><div><span className="eyebrow">Pro · Communication Hub 2.0</span><h1 className="sectionTitle">Felelősség és ügyfélkapcsolatok</h1><p className="lead">A postafiók-felelős, regisztrált vásárló, CRM-kulcs és sales owner külön kapcsolat. Egyik sem aktivál új mailboxot, DNS-t vagy MX-et.</p></div><Link className="btn btnGhost" href="/admin/kommunikacio/iroda">Vissza az ügyféllevelezéshez</Link></div>
  {loadError&&<div className="errorNotice"><strong>Az adatok egy része nem tölthető be.</strong><p>Hiányos állapotban a módosítások nem tekinthetők biztonságosan ellenőrzöttnek.</p></div>}
  <section className="featurePanel"><span className="eyebrow">Postafiókok</span><h2>Felelős munkatárs</h2><p className="muted">A felelős csak az új vagy gazdátlan ügyek alapértelmezett kiosztását adja. Meglévő kézi felelőst nem ír felül.</p><div className="cards">{mailboxes.map(mailbox=><article className="card" key={mailbox.mailbox_key}><div className="adminToolbar"><strong>{mailbox.label}</strong><span className="badge">{mailbox.is_active?'Aktív':'Inaktív'}</span></div><p className="muted">{mailbox.mailbox_key}</p>{!loadError&&<form action={updateMailboxResponsibilityAction} className="adminToolbar"><input type="hidden" name="mailboxKey" value={mailbox.mailbox_key}/><select name="responsibleUserId" defaultValue={mailbox.responsible_user_id??''}><option value="">Nincs alapértelmezett felelős</option>{staff.map(member=><option key={member.id} value={member.id}>{member.label}</option>)}</select><button className="btn btnGhost">Mentés</button></form>}</article>)}</div>{!mailboxes.length&&!mailboxResult.error&&<p className="muted">Nincs konfigurált Office postafiók. Ez az oldal nem hoz létre és nem aktivál egyet sem.</p>}</section>
  <section className="featurePanel"><span className="eyebrow">Ügyfélthreadek</span><h2>Customer / CRM / sales kapcsolatok</h2><div className="cards">{threads.map(thread=><article className="card" key={thread.id}><div className="adminToolbar"><strong>{thread.subject}</strong><span className="muted">{thread.customer_email??'Nincs e-mail'}</span></div><p className="muted">Mailbox: {thread.mailbox_key??'—'}</p>{!loadError&&<form action={updateThreadRelationshipsAction} className="stackForm"><input type="hidden" name="threadId" value={thread.id}/><label><span>Regisztrált vásárló</span><select name="customerUserId" defaultValue={thread.customer_user_id??''}><option value="">Nincs összekapcsolva</option>{customerUsers.map(customer=><option key={customer.id} value={customer.id}>{customer.label}</option>)}</select></label><label><span>CRM / kereskedelmi customer ref</span><input name="customerRef" list={`customer-refs-${thread.id}`} defaultValue={thread.customer_ref??''} maxLength={200} placeholder="Nincs összekapcsolva"/><datalist id={`customer-refs-${thread.id}`}>{refs.map(ref=><option key={ref} value={ref}/>)}</datalist></label><label><span>Sales owner</span><select name="salesOwnerUserId" defaultValue={thread.sales_owner_user_id??''}><option value="">Nincs sales owner</option>{staff.map(member=><option key={member.id} value={member.id}>{member.label}</option>)}</select></label><button className="btn btnGhost">Kapcsolatok mentése</button></form>}</article>)}</div></section></section>;
}
