import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { getCurrentWebshopInstance } from '@/lib/instances/access';
import { getCommerceSettings } from '@/lib/commerce/settings';
import { formatHuf } from '@/lib/catalog';
import { orderEventLabel, orderNextAction, orderProgress, orderStatusDescription, orderStatusLabel, paymentMethodLabel, shippingMethodLabel, trackingProviderUrl } from '@/lib/order-display';
import { PaymentRetryButton } from '@/components/account/payment-retry-button';

function commercialPaymentRetryReady(options:{code:string;flow:string}[],method:string){return options.some(option=>option.code===method&&option.flow==='online_redirect')}

export default async function CustomerOrderPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/fiokom'); const instance=await getCurrentWebshopInstance();if(!instance)notFound();
  const [{data:order,error:orderError},{data:items,error:itemsError},{data:events,error:eventsError}]=await Promise.all([
    supabase.from('orders').select('id,order_number,status,customer_email,customer_phone,billing_name,billing_company,billing_tax_number,billing_postcode,billing_city,billing_address,shipping_name,shipping_postcode,shipping_city,shipping_address,subtotal_gross_huf,discount_gross_huf,shipping_gross_huf,total_gross_huf,shipping_method,parcel_point_id,payment_method,tracking_number,invoice_number,invoice_url,note,created_at').eq('id',id).eq('instance_id',instance.id).eq('customer_id',user.id).maybeSingle(),
    supabase.from('order_items').select('id,product_name,variant_label,sku,quantity,unit_gross_huf,line_total_gross_huf').eq('order_id',id).eq('instance_id',instance.id),
    supabase.from('order_events').select('id,event_type,from_status,to_status,metadata,created_at').eq('order_id',id).eq('instance_id',instance.id).order('created_at',{ascending:true}),
  ]);
  if(orderError)return <main className="section"><div className="shell"><span className="eyebrow">Rendelés betöltése</span><h1 className="sectionTitle">A rendelés részletei most nem tölthetők be.</h1><p className="lead">A rendelést ne add le újra emiatt. Próbáld meg később, vagy térj vissza a rendeléslistához.</p><Link className="btn btnPrimary" href="/fiokom">Vissza a fiókhoz</Link></div></main>;
  if(!order)notFound();
  let retryablePayment=false;if(order.status==='pending_payment'){try{const commerce=await getCommerceSettings();retryablePayment=commercialPaymentRetryReady(commerce.paymentOptions,order.payment_method)}catch{}}
  const reorderQuery=new URLSearchParams(); (items??[]).forEach(item=>reorderQuery.append('sku',`${item.sku}:${item.quantity}`));
  const progress=orderProgress(order.status); const nextAction=orderNextAction(order.status,order.payment_method,order.shipping_method); const trackingUrl=trackingProviderUrl(order.shipping_method);
  const createdAt=new Intl.DateTimeFormat('hu-HU',{dateStyle:'long',timeStyle:'short'}).format(new Date(order.created_at));
  const detailLoadError=Boolean(itemsError||eventsError);
  return <main className="section accountOrderPage"><div className="shell"><div className="sectionIntro"><div><span className="eyebrow">Rendelés részletei</span><h1 className="sectionTitle">{order.order_number}</h1><p className="lead">{orderStatusDescription(order.status,order.payment_method,order.shipping_method)}</p></div><div className="actions"><Link className="btn btnGhost" href="/fiokom">Vissza a fiókhoz</Link><Link className="btn btnPrimary" href={`/webaruhaz?${reorderQuery.toString()}`}>Újrarendelés</Link></div></div>
    {detailLoadError&&<div className="errorNotice" role="alert"><strong>A rendelés tételei vagy eseménytörténete közül valamelyik most nem tölthető be.</strong> A rendelés alapadatai ettől még érvényesek.</div>}
    {retryablePayment&&<section className="featurePanel paymentRetryPanel" style={{marginBottom:28}}><div><span className="eyebrow">Fizetésre vár</span><h2>A rendelést nem kell újra leadnod.</h2><p className="muted">A korábbi fizetési próbálkozás nem zárta le a rendelést. Új, biztonságos fizetési folyamatot indíthatsz ugyanahhoz a rendeléshez.</p></div><PaymentRetryButton orderId={order.id}/></section>}
    <section className="featurePanel" style={{marginBottom:28}}><div className="sectionIntro"><div><span className="eyebrow">Rendeléskövetés</span><h2>{progress.terminal?orderStatusLabel(order.status):'Hol tart a rendelésed?'}</h2></div><span className="badge">{orderStatusLabel(order.status)}</span></div>{progress.terminal?<p className="muted">Ez a rendelés lezárt állapotban van. A részletes eseményeket lejjebb továbbra is visszanézheted.</p>:<div className="timeline">{progress.steps.map((step,index)=><div key={step} className="timelineItem"><strong>{index<=progress.active?'✓ ':''}{step}</strong><span className="muted">{index<progress.active?'Kész':index===progress.active?'Jelenlegi lépés':'Következik'}</span></div>)}</div>}</section>
    <div className="cards"><article className="card"><span className="badge">Aktuális állapot</span><h3>{orderStatusLabel(order.status)}</h3><p className="muted">Rendelés leadva: {createdAt}</p></article><article className="card"><span className="badge">{nextAction.title}</span><h3>Mi történik most?</h3><p className="muted">{nextAction.text}</p></article><article className="card"><span className="badge">Fizetendő</span><div className="price">{formatHuf(order.total_gross_huf)}</div><p className="muted">Termékek: {formatHuf(order.subtotal_gross_huf)} · Kedvezmény: {formatHuf(order.discount_gross_huf??0)} · Szállítás: {formatHuf(order.shipping_gross_huf)}</p></article><article className="card"><span className="badge">Dokumentumok</span><h3>{order.invoice_number??'Számla készül'}</h3>{order.invoice_url?<a className="btn btnGhost" href={order.invoice_url} target="_blank" rel="noreferrer">Számla megnyitása</a>:<p className="muted">A számla elkészülte után itt lesz elérhető.</p>}</article></div>
    {(order.tracking_number||order.parcel_point_id)&&<section className="card" style={{marginTop:28}}><div className="sectionIntro"><div><span className="eyebrow">Szállítási információ</span><h2>{order.tracking_number?'A csomagod követhető':'Csomagpont kiválasztva'}</h2><p className="muted">{order.tracking_number?`${shippingMethodLabel(order.shipping_method)} nyomkövetési azonosító: ${order.tracking_number}`:`Csomagpont azonosító: ${order.parcel_point_id}`}</p></div>{order.tracking_number&&trackingUrl?<a className="btn btnPrimary" href={trackingUrl} target="_blank" rel="noreferrer">Futár nyomkövetése</a>:null}</div></section>}
    <section className="tableCard" style={{marginTop:28}}><div style={{padding:'20px 20px 0'}}><span className="eyebrow">Tételek</span><h2>Mit rendeltél?</h2></div><div className="adminTableScroll"><table className="adminTable"><thead><tr><th>Termék</th><th>Mennyiség</th><th>Egységár</th><th>Összesen</th></tr></thead><tbody>{(items??[]).map(item=><tr key={item.id}><td><strong>{item.product_name}</strong><br/><span className="muted">{item.variant_label} · {item.sku}</span></td><td>{item.quantity}</td><td>{formatHuf(item.unit_gross_huf)}</td><td><strong>{formatHuf(item.line_total_gross_huf)}</strong></td></tr>)}</tbody></table></div></section>
    <div className="splitFeature" style={{marginTop:28}}><section className="featurePanel"><span className="eyebrow">Számlázás</span><h2>{order.billing_name}</h2><p className="muted">{order.billing_company&&<>{order.billing_company}<br/></>}{order.billing_tax_number&&<>Adószám: {order.billing_tax_number}<br/></>}{order.billing_postcode} {order.billing_city}, {order.billing_address}<br/>{order.customer_email}{order.customer_phone?<><br/>{order.customer_phone}</>:null}</p></section><section className="featurePanel"><span className="eyebrow">Szállítás és fizetés</span><h2>{order.shipping_name||order.billing_name}</h2><p className="muted">{order.shipping_postcode} {order.shipping_city}, {order.shipping_address}<br/>Szállítás: {shippingMethodLabel(order.shipping_method)}<br/>Fizetés: {paymentMethodLabel(order.payment_method)}<br/>{order.tracking_number?`Nyomkövetés: ${order.tracking_number}`:order.parcel_point_id?`Csomagpont: ${order.parcel_point_id}`:'Nyomkövetés még nincs'}</p></section></div>
    {order.note&&<section className="card" style={{marginTop:28}}><span className="eyebrow">Megjegyzésed</span><p>{order.note}</p></section>}
    <section className="card" style={{marginTop:28}}><span className="eyebrow">Eseménytörténet</span><h2>Rendelési idővonal</h2><div className="timeline">{(events??[]).map(event=><div key={event.id} className="timelineItem"><strong>{orderEventLabel(event.event_type,event.from_status,event.to_status,event.metadata as Record<string,unknown>|null)}</strong><span className="muted">{new Intl.DateTimeFormat('hu-HU',{dateStyle:'short',timeStyle:'short'}).format(new Date(event.created_at))}</span></div>)}</div>{!eventsError&&!events?.length&&<p className="muted">A rendelési események hamarosan itt jelennek meg.</p>}</section>
  </div></main>;
}
