import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { formatHuf } from '@/lib/catalog';
import { orderProgress, orderStatusLabel, paymentMethodLabel, shippingMethodLabel } from '@/lib/order-display';

export default async function CustomerOrderPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/fiokom');
  const [{data:order},{data:items},{data:events}]=await Promise.all([
    supabase.from('orders').select('id,order_number,status,customer_email,customer_phone,billing_name,billing_company,billing_tax_number,billing_postcode,billing_city,billing_address,shipping_name,shipping_postcode,shipping_city,shipping_address,subtotal_gross_huf,discount_gross_huf,shipping_gross_huf,total_gross_huf,shipping_method,parcel_point_id,payment_method,tracking_number,invoice_number,invoice_url,note,created_at').eq('id',id).maybeSingle(),
    supabase.from('order_items').select('id,product_name,variant_label,sku,quantity,unit_gross_huf,line_total_gross_huf').eq('order_id',id),
    supabase.from('order_events').select('id,event_type,from_status,to_status,metadata,created_at').eq('order_id',id).order('created_at',{ascending:true}),
  ]);
  if(!order)notFound();
  const reorderQuery=new URLSearchParams(); (items??[]).forEach(item=>reorderQuery.append('sku',`${item.sku}:${item.quantity}`)); const progress=orderProgress(order.status);
  return <main className="section"><div className="shell"><div className="sectionIntro"><div><span className="eyebrow">Rendelés részletei</span><h1 className="sectionTitle">{order.order_number}</h1><p className="muted">{orderStatusLabel(order.status)}</p></div><div className="actions"><Link className="btn btnGhost" href="/fiokom">Vissza a fiókhoz</Link><Link className="btn btnPrimary" href={`/webaruhaz?${reorderQuery.toString()}`}>Újrarendelés</Link></div></div>
    <section className="card" style={{marginBottom:28}}><span className="eyebrow">Rendeléskövetés</span><h2>{progress.terminal?orderStatusLabel(order.status):'Hol tart a rendelésed?'}</h2>{progress.terminal?<p className="muted">Ez a rendelés lezárt állapotban van. Ha kérdésed van vele kapcsolatban, keresd ügyfélszolgálatunkat a rendelési számmal.</p>:<div className="timeline">{progress.steps.map((step,index)=><div key={step} className="timelineItem"><strong>{index<=progress.active?'✓ ':''}{step}</strong><span className="muted">{index<progress.active?'Kész':index===progress.active?'Jelenlegi lépés':'Következik'}</span></div>)}</div>}</section>
    <div className="cards"><article className="card"><h3>Állapot</h3><div className="price">{orderStatusLabel(order.status)}</div><p className="muted">Létrehozva: {new Intl.DateTimeFormat('hu-HU',{dateStyle:'long',timeStyle:'short'}).format(new Date(order.created_at))}</p></article><article className="card"><h3>Fizetendő</h3><div className="price">{formatHuf(order.total_gross_huf)}</div><p className="muted">Termékek: {formatHuf(order.subtotal_gross_huf)} · kedvezmény: {formatHuf(order.discount_gross_huf??0)} · szállítás: {formatHuf(order.shipping_gross_huf)}</p></article><article className="card"><h3>Dokumentumok</h3><div className="price">{order.invoice_number??'Számla készül'}</div>{order.invoice_url?<a className="btn btnGhost" href={order.invoice_url} target="_blank" rel="noreferrer">Számla megnyitása</a>:<p className="muted">A számla elkészülte után itt lesz elérhető.</p>}</article></div>
    <section className="tableCard"><table className="adminTable"><thead><tr><th>Termék</th><th>Mennyiség</th><th>Egységár</th><th>Összesen</th></tr></thead><tbody>{(items??[]).map(item=><tr key={item.id}><td><strong>{item.product_name}</strong><br/><span className="muted">{item.variant_label} · {item.sku}</span></td><td>{item.quantity}</td><td>{formatHuf(item.unit_gross_huf)}</td><td>{formatHuf(item.line_total_gross_huf)}</td></tr>)}</tbody></table></section>
    <div className="splitFeature" style={{marginTop:28}}><section className="featurePanel"><span className="eyebrow">Számlázás</span><h2>{order.billing_name}</h2><p className="muted">{order.billing_company&&<>{order.billing_company}<br/></>}{order.billing_tax_number&&<>Adószám: {order.billing_tax_number}<br/></>}{order.billing_postcode} {order.billing_city}, {order.billing_address}</p></section><section className="featurePanel"><span className="eyebrow">Szállítás</span><h2>{order.shipping_name||order.billing_name}</h2><p className="muted">{order.shipping_postcode} {order.shipping_city}, {order.shipping_address}<br/>Szállítás: {shippingMethodLabel(order.shipping_method)}<br/>Fizetés: {paymentMethodLabel(order.payment_method)}<br/>{order.tracking_number?`Nyomkövetés: ${order.tracking_number}`:order.parcel_point_id?`Csomagpont: ${order.parcel_point_id}`:'Nyomkövetés még nincs'}</p></section></div>
    <section className="card" style={{marginTop:28}}><span className="eyebrow">Eseménytörténet</span><h2>Rendelési idővonal</h2><div className="timeline">{(events??[]).map(event=><div key={event.id} className="timelineItem"><strong>{event.event_type==='order_created'?'Rendelés létrehozva':event.event_type==='status_changed'?`${orderStatusLabel(event.from_status)} → ${orderStatusLabel(event.to_status)}`:event.event_type==='invoice_created'?'Számla elkészült':event.event_type==='shipment_created'?'Csomagfeladás létrehozva':'Rendelés frissítve'}</strong><span className="muted">{new Intl.DateTimeFormat('hu-HU',{dateStyle:'short',timeStyle:'short'}).format(new Date(event.created_at))}</span></div>)}</div></section>
  </div></main>;
}
