import{readFileSync}from'node:fs';import{resolve}from'node:path';import{describe,expect,it}from'vitest';const read=(p:string)=>readFileSync(resolve(process.cwd(),p),'utf8');
describe('Shoperation admin launch readiness',()=>{
 it('keeps the launch center visible in merchant navigation',()=>{const ia=read('src/lib/navigation/admin-ia.ts');expect(ia).toContain("href:'/admin/indulas'");expect(ia).toContain("label:'Indítási központ'")});
 it('uses standard Alap commerce settings for payment and shipping setup',()=>{const p=read('src/app/admin/indulas/page.tsx');expect(p).toContain("href:'/admin/beallitasok/fizetes-szallitas?tab=szallitas'");expect(p).toContain("href:'/admin/beallitasok/fizetes-szallitas?tab=fizetes'");expect(p).not.toContain("href:'/admin/integraciok'")});
 it('keeps the Alap dashboard commerce shortcut out of Pro integration operations',()=>{const d=read('src/app/admin/page.tsx'),c=d.match(/<Link className="card textLink" href="([^"]+)"><strong>Fizetés és szállítás<\/strong>/);expect(c?.[1]).toBe('/admin/beallitasok/fizetes-szallitas')});
 it('degrades safely while a fresh database is not fully bootstrapped',()=>{const p=read('src/app/admin/indulas/page.tsx');expect(p).toContain('safeProducts');expect(p).toContain('safeCommerce');expect(p).toContain('Promise.all')});
 it('keeps mobile admin navigation accessible',()=>{const css=read('src/app/admin/admin-shell.css');expect(css).toMatch(/@media\(max-width:850px\)[\s\S]*\.adminSide\{display:block/);expect(css).not.toMatch(/@media\(max-width:850px\)[\s\S]*\.adminSide\{display:none/)});
 it('recognizes platform-level roles as admin access',()=>{const g=read('src/lib/auth/require-admin.ts'),p=read('src/lib/auth/platform-operator.ts');expect(g).toContain("from('platform_operators')");expect(g).toContain("['owner','admin','operator']");expect(p).toContain("export type PlatformRole = 'owner' | 'admin' | 'operator'");expect(p).toContain('requirePlatformOwner')});
 it('keeps platform-owner claims private and role-based',()=>{const m=read('supabase/migrations/20260901102358_platform_owner_access.sql');expect(m).toContain('private.platform_owner_claims');expect(m).toContain("check (role in ('owner','admin','operator'))");expect(m).toContain('revoke all on private.platform_owner_claims from public, anon, authenticated')});
});
