import { readFileSync,readdirSync } from 'node:fs';import { resolve } from 'node:path';import { describe,expect,it } from 'vitest';
const migrationsDir=resolve(process.cwd(),'supabase/migrations');const historicalLegacy=new Set(['002_seed_products.sql','002_store_runtime.sql','004_orders.sql','004_commerce_audit.sql','006_email_outbox.sql','006_reseller_pricing.sql','009_checkout_rpc.sql','009_coupon_discount_engine.sql','014_marketing.sql','015_checkout_shipping_threshold.sql','016_analytics_events.sql','017_order_item_cost_snapshot.sql','037_content_pages.sql','037_order_item_cost_snapshot.sql']);const forbidden=[/water-k/i,/waterk/i,/okospolymer/i,/info@water-k\.hu/i,/waterk\.hu/i,/40\s*g/i,/750\s*g/i,/25\s*kg/i,/\b990\b/,/14990/,/215900/];
describe('Shoperation database bootstrap neutrality',()=>{
 it('pins every remaining customer-era SQL occurrence to the documented historical migration set',()=>{for(const file of readdirSync(migrationsDir).filter(f=>f.endsWith('.sql'))){const text=readFileSync(resolve(migrationsDir,file),'utf8');if(forbidden.some(r=>r.test(text)))expect(historicalLegacy.has(file),`${file} contains customer-era assumptions outside the historical allowlist`).toBe(true)}});
 for(const rel of ['supabase/customer-baseline/migrations/0001_shoperation_v1_schema.sql','supabase/customer-baseline/seed.sql','supabase/customer-baseline/source-preflight.sql','supabase/customer-baseline/target-postflight.sql','supabase/customer-baseline/target-preflight.sql','supabase/seed.sql'])it(`${rel} contains no customer-specific identity or SKU assumptions`,()=>{const text=readFileSync(resolve(process.cwd(),rel),'utf8');for(const r of forbidden)expect(text,`${rel} matches ${r}`).not.toMatch(r)});
 it('keeps the default seed customer-neutral and data-empty',()=>{const seed=readFileSync(resolve(process.cwd(),'supabase/seed.sql'),'utf8').toLowerCase();expect(seed).toContain('intentionally customer-neutral');expect(seed).toContain('no customer-specific data loaded')});
 it('fails closed to Alap at the database default layer',()=>{expect(readFileSync(resolve(process.cwd(),'supabase/migrations/20260831122000_fail_closed_plan_defaults.sql'),'utf8')).toContain("set default 'alap'")});
 it('removes obsolete checkout RPC overloads while keeping the tenant provider-neutral runtime entrypoint',()=>{const migration=readFileSync(resolve(process.cwd(),'supabase/migrations/20260831124500_drop_legacy_place_order_overloads.sql'),'utf8').replace(/\s+/g,' ');const route=readFileSync(resolve(process.cwd(),'src/app/api/orders/route.ts'),'utf8');const wrapper=readFileSync(resolve(process.cwd(),'src/lib/orders/tenant-checkout.ts'),'utf8');expect(migration).toContain('drop function if exists public.place_order( text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, text, uuid, jsonb );');expect(route).toContain('placeTenantOrder');expect(wrapper).toMatch(/place_order_provider_v4_idempotent/);expect(route).not.toMatch(/\.rpc\(['"]place_order['"]/)});
});
