import {describe,expect,it} from 'vitest';
import {GUIDED_FINDER_ENGINE_VERSION,GUIDED_FINDER_TEMPLATE_SWITCH_MUTATION_BOUNDARY,runGuidedFinder,validateFinderSelections,validateGuidedFinderConfig,type FinderCandidate,type GuidedFinderConfig} from '@/lib/commerce/guided-finder';
const config:GuidedFinderConfig={version:1,tenantId:'tenant-demo',finderKey:'beauty-formula',label:'Formula Finder',safetyPolicy:'non-diagnostic',partialPolicy:'show-nearest',maxResults:4,steps:[{id:'preferences',title:'Preferenciák',questions:[{id:'texture',label:'Milyen textúrát kedvelsz?',mode:'single',required:true,options:[{id:'gel',label:'Gél',rules:[{id:'rule-texture-gel',attributeKey:'texture',operator:'eq',value:'gel',kind:'required',reason:'Gél textúrát választottál.'}]},{id:'cream',label:'Krém',rules:[{id:'rule-texture-cream',attributeKey:'texture',operator:'eq',value:'cream',kind:'required',reason:'Krém textúrát választottál.'}]}]},{id:'finish',label:'Milyen érzetet keresel?',mode:'multi',options:[{id:'light',label:'Könnyed',rules:[{id:'rule-light',attributeKey:'finish',operator:'includes',value:'light',kind:'preferred',weight:3,reason:'Könnyed érzetet részesítesz előnyben.'}]},{id:'fragrance-free',label:'Illatanyag nélkül',rules:[{id:'rule-fragrance',attributeKey:'fragrance-free',operator:'eq',value:true,kind:'preferred',weight:5,reason:'Illatanyag-mentes formulát preferálsz.'}]}]}]}]};
const candidates:FinderCandidate[]=[{id:'a',label:'Cloud Gel',href:'/termek/cloud-gel',eligible:true,attributes:{texture:'gel',finish:['light','fresh'],'fragrance-free':true}},{id:'b',label:'Rich Gel',href:'/termek/rich-gel',eligible:true,attributes:{texture:'gel',finish:['rich'],'fragrance-free':false}},{id:'c',label:'Soft Cream',href:'/termek/soft-cream',eligible:true,attributes:{texture:'cream',finish:['light'],'fragrance-free':true}},{id:'hidden',label:'Hidden Gel',href:'/termek/hidden',eligible:false,attributes:{texture:'gel',finish:['light'],'fragrance-free':true}}];
describe('E3 Guided Finder v1',()=>{
 it('validates tenant-scoped versioned deterministic configuration',()=>{expect(GUIDED_FINDER_ENGINE_VERSION).toBe('shoporation.guided-finder.v1');expect(validateGuidedFinderConfig(config)).toEqual([]);});
 it('maps selected answers to required/preferred rules and ranks exact eligible products deterministically',()=>{const result=runGuidedFinder({config,selections:{texture:['gel'],finish:['light','fragrance-free']},candidates})!;expect(result.status).toBe('exact');expect(result.results.map(x=>x.id)).toEqual(['a','b']);expect(result.results[0]).toMatchObject({score:8,requiredMismatched:0,preferredMatched:2});expect(result.results.some(x=>x.id==='hidden')).toBe(false);});
 it('explains matched and mismatched criteria instead of returning a black-box score',()=>{const result=runGuidedFinder({config,selections:{texture:['gel'],finish:['fragrance-free']},candidates})!;const rich=result.results.find(x=>x.id==='b')!;expect(rich.evidence).toEqual(expect.arrayContaining([expect.objectContaining({ruleId:'rule-texture-gel',matched:true}),expect.objectContaining({ruleId:'rule-fragrance',matched:false})]));});
 it('supports explicit partial results when no candidate satisfies all required rules',()=>{const result=runGuidedFinder({config,selections:{texture:['cream']},candidates:[{...candidates[0],attributes:{texture:'gel'}}]})!;expect(result.status).toBe('partial');expect(result.exactMatchCount).toBe(0);expect(result.results[0].requiredMismatched).toBe(1);});
 it('supports zero-result policy without inventing recommendations',()=>{const zero={...config,partialPolicy:'zero' as const};const result=runGuidedFinder({config:zero,selections:{texture:['cream']},candidates:[{...candidates[0],attributes:{texture:'gel'}}]})!;expect(result).toMatchObject({status:'zero',results:[]});});
 it('fails closed on missing/invalid answers and non-diagnostic policy violations',()=>{expect(validateFinderSelections(config,{texture:[]}).some(x=>x.code==='FINDER_REQUIRED_ANSWER_MISSING')).toBe(true);expect(validateFinderSelections(config,{texture:['gel','cream']}).some(x=>x.code==='FINDER_SINGLE_ANSWER_MULTIPLE')).toBe(true);const unsafe={...config,label:'Diagnózis és kezelés finder'};expect(validateGuidedFinderConfig(unsafe).some(x=>x.code==='FINDER_NON_DIAGNOSTIC_POLICY_VIOLATION')).toBe(true);});
 it('keeps finder configuration and commerce authorities outside template switching',()=>{expect(GUIDED_FINDER_TEMPLATE_SWITCH_MUTATION_BOUNDARY).toMatchObject({storefrontPageDrafts:true,finderConfiguration:false,products:false,variants:false,pricing:false,inventory:false,customers:false,orders:false});});
});
