import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest';
const read=(path:string)=>readFileSync(path,'utf8');
describe('Incident Intelligence merchant reporting UI',()=>{
 it('keeps merchant reporter staged until its isolated admin activation release',()=>{const layout=read('src/app/admin/layout.tsx'),ui=read('src/components/admin/merchant-incident-reporter.tsx');expect(ui).toContain('MerchantIncidentReporter');expect(layout).not.toContain('<MerchantIncidentReporter/>');});
 it('reuses ShoperationDialog rather than creating a parallel admin modal authority',()=>{const ui=read('src/components/admin/merchant-incident-reporter.tsx'),dialog=read('src/components/admin/shoperation-dialog.tsx');expect(ui).toContain("from'@/components/admin/shoperation-dialog'");expect(ui).toContain('<ShoperationDialog');expect(dialog).toContain('children?:ReactNode');expect(dialog).toContain('{children}');expect(dialog).toContain("querySelector<HTMLElement>('input:not([disabled]),select:not([disabled]),textarea:not([disabled])')")});
 it('posts merchant evidence to the shared Incident Intelligence API and shows deterministic routing',()=>{const ui=read('src/components/admin/merchant-incident-reporter.tsx');expect(ui).toContain("fetch('/api/incidents/merchant'");expect(ui).toContain("routePath:pathname");expect(ui).toContain("surfaceKey:'admin.merchant-incident-reporter'");expect(ui).toContain("actionKey:'merchant.incident.submit'");expect(ui).toContain('ownerLabel');expect(ui).toContain('result.routing.ownership');expect(ui).toContain('triagePending');expect(ui).not.toMatch(/from\(['\"]platform_incidents['\"]\)/)});
 it('uses the shared read-only incident evidence helper instead of a UI width authority',()=>{const ui=read('src/components/admin/merchant-incident-reporter.tsx'),evidence=read('src/lib/incidents/browser-evidence.ts');expect(ui).toContain('captureIncidentViewportEvidence');expect(ui).not.toContain('window.innerWidth');expect(evidence).toContain('window.innerWidth');expect(evidence).toContain('window.innerHeight')});
 it('keeps the trigger and form responsive',()=>{const css=read('src/components/admin/merchant-incident-reporter.module.css');expect(css).toContain('position:fixed');expect(css).toContain('min-height:44px');expect(css).toContain('@media(max-width:680px)');expect(css).toContain('grid-template-columns:1fr')});
});
