import{describe,expect,it}from'vitest';import{readFileSync}from'node:fs';import{join}from'node:path';const read=(p:string)=>readFileSync(join(process.cwd(),p),'utf8');
describe('merchant admin server page tenant contracts',()=>{
 it('scopes analytics and cashflow reads to the active store',()=>{for(const p of['src/app/admin/elemzes/page.tsx','src/app/admin/cashflow/page.tsx']){const s=read(p);expect(s).toContain("requireCurrentStoreContext('analytics.read')");expect(s).toContain(".eq('instance_id',scope.instanceId)")}});
 it('requires procurement permission and tenant filters',()=>{const s=read('src/app/admin/beszerzes/page.tsx');expect(s).toContain("requireCurrentStoreContext('procurement.manage')");expect(s).toContain(".eq('instance_id',scope.instanceId)")});
 it('requires sales permission and scopes all CRM reads',()=>{const s=read('src/app/admin/ertekesites/page.tsx');expect(s).toContain("requireCurrentStoreContext('sales.manage')");expect(s).toContain("commercial_pipeline_summary");expect(s).toContain(".eq('instance_id',scope.instanceId)")});
 it('tenantizes commercial actions and planners',()=>{const s=read('src/app/api/admin/commercial/actions/route.ts');expect(s).toContain("getAdminRequestUser('sales.manage')");expect(s).toContain('plan_commercial_opportunities_v2');expect(s).toContain('create_commercial_offer_v2');expect(s).toContain(".eq('instance_id',store.instanceId)")});
 it('scopes product recommendation reads and writes to the active store',()=>{const page=read('src/app/admin/termekajanlasok/page.tsx'),list=read('src/lib/recommendations/server.ts'),create=read('src/app/api/admin/recommendations/route.ts'),item=read('src/app/api/admin/recommendations/[id]/route.ts'),migration=read('supabase/migrations/20260903145000_admin_engagement_evidence_atomic_v2.sql');expect(page).toContain("requireCurrentStoreContext('catalog.manage')");expect(list).toContain("eq('instance_id',instance.id)");expect(create).toContain("getAdminRequestUser('catalog.manage')");expect(create).toContain('p_instance_id:scope.instanceId');expect(item).toContain('p_instance_id:scope.instanceId');expect(create).toContain('admin_mutate_product_recommendation_v2');expect(item).toContain('admin_mutate_product_recommendation_v2');expect(migration).toContain('RECOMMENDATION_TARGET_TENANT_MISMATCH');expect(migration).toContain('public.can_manage_catalog(p_instance_id,p_actor)')});
 it('adds tenant keys and preserves existing view contracts',()=>{const tables=read('supabase/migrations/20260901157000_commercial_tenant_scope.sql').toLowerCase(),views=read('supabase/migrations/20260901157100_commercial_tenant_views.sql').toLowerCase();expect(tables).toContain('commercial_opportunities add column if not exists instance_id');expect(tables).toContain('can_manage_sales');expect(views).toContain('customer_commercial_metrics with(security_invoker=true)');expect(views).toContain('commercial_pipeline_summary with(security_invoker=true)');expect(views).toMatch(/cogs_to_revenue_pct,instance_id from g/);expect(views).toMatch(/lost_count,instance_id from public\.commercial_opportunities/)});
});
