import fs from'node:fs';import path from'node:path';import{describe,expect,test}from'vitest';const root=process.cwd(),read=(f:string)=>fs.readFileSync(path.join(root,f),'utf8'),page=read('src/app/admin/beszerzes/page.tsx'),controls=read('src/components/admin/procurement-controls.tsx'),createApi=read('src/app/api/admin/procurement/route.ts'),updateApi=read('src/app/api/admin/procurement/[id]/route.ts');
describe('procurement and stock receipt workflows',()=>{
 test('procurement remains Pro-only on page and write APIs',()=>{expect(page).toMatch(/requirePlanFeature\('procurement'\)/);for(const api of[createApi,updateApi]){expect(api).toMatch(/getAdminRequestUser\('procurement\.manage'\)/);expect(api).toMatch(/requireCurrentStoreContext\('procurement\.manage'\)/);expect(api).toMatch(/hasCurrentPlanFeature\('procurement'\)/);expect(api).toMatch(/status:403/)}});
 test('reorder proposal accounts for demand, incoming stock, lead time, safety stock, MOQ and multiples',()=>{expect(page).toMatch(/daily=q\/30/);expect(page).toMatch(/supplier_lead_time_days/);expect(page).toMatch(/safety_stock_days/);expect(page).toMatch(/minimum_order_quantity/);expect(page).toMatch(/order_multiple/);expect(page).toMatch(/position=p\.stock\+incoming/)});
 test('creating a purchase order is draft-first and validates duplicate variants and quantities',()=>{expect(createApi).toMatch(/Ugyanaz a termék csak egyszer szerepelhet/);expect(createApi).toMatch(/create_purchase_order_v2/);expect(createApi).toMatch(/p_instance_id:scope\.instanceId/)});
 test('UI exposes the controlled draft to approved to ordered to received lifecycle',()=>{for(const s of['draft','approved','ordered','received'])expect(page).toContain(s);expect(controls).toMatch(/approve|order|receive/)});
 test('receipt mutations delegate stock changes to transactional database RPCs',()=>{expect(updateApi).toMatch(/receive_purchase_order/);expect(updateApi).not.toMatch(/from\('product_variants'\)\.update/)});
 test('partial receipts reject duplicate item identifiers and the UI caps receipt quantity at remaining stock',()=>{expect(updateApi).toMatch(/Set/);expect(controls).toMatch(/remaining|Math\.max/)});
 test('purchase order writes remain audit logged',()=>{expect(createApi).toMatch(/recordAdminAudit/);expect(updateApi).toMatch(/recordAdminAudit/)});
});
