import{readFileSync}from'node:fs';
import{describe,expect,test}from'vitest';
const read=(path:string)=>readFileSync(path,'utf8');
describe('Product Intake Center canonical UI and hardening',()=>{
 test('keeps Product Intake capabilities behind the current central Products landing',()=>{const hub=read('src/app/admin/termekek/feltoltes/page.tsx'),center=read('src/app/admin/termekek/page.tsx'),nav=read('src/components/navigation/admin-navigation.tsx');for(const marker of['Termékfeltöltő Központ','Új termék létrehozása','Tömeges feltöltés','Webshop-migráció','Meglévő termék másolása','Folyamatban lévő piszkozatok','Legutóbbi importok','Katalógus áttekintés'])expect(hub).toContain(marker);expect(center).toContain('Termékkezelés');expect(center).toContain('Termékek feltöltése / import');expect(center).toContain('/admin/termekek/import-export');expect(nav).toContain("'products':'/admin/termekek'");expect(nav).not.toContain("'products':'/admin/termekek/feltoltes'");expect(nav).toContain("'digital-office':'/admin/kommunikacio'")});
 test('supports resumable draft editing and autosave conflict protection',()=>{const editor=read('src/components/admin/product-intake-editor.tsx'),route=read('src/app/api/admin/catalog/products/[id]/draft/route.ts'),page=read('src/app/admin/termekek/feltoltes/[id]/page.tsx');expect(page).toContain("eq('product_id',id)");expect(editor).toContain('1100');expect(editor).toContain('expectedUpdatedAt');expect(route).toContain("rpc('update_catalog_draft_v1'");expect(route).toContain("code:'stale'");expect(route).toContain('CATALOG_DRAFT_STALE')});
 test('variant image assignment reuses product media and is tenant constrained',()=>{const editor=read('src/components/admin/product-intake-editor.tsx'),sql=read('supabase/migrations/20260910221500_product_intake_center_hardening_v1.sql');expect(editor).toContain('Kép hozzárendelése');expect(editor).toContain("fetch('/api/admin/catalog/media'");expect(editor).toContain('mediaId');expect(sql).toContain('primary_media_id');expect(sql).toContain('product_media_id_product_instance_uidx');expect(sql).toContain('CATALOG_MEDIA_FOREIGN')});
 test('product SEO is real storefront metadata with safe fallback',()=>{const editor=read('src/components/admin/product-intake-editor.tsx'),catalog=read('src/lib/catalog-server.ts'),productPage=read('src/app/termek/[slug]/page.tsx');expect(editor).toContain('SEO és keresési megjelenés');expect(editor).toContain('Meta description');expect(catalog).toContain('seo_title');expect(catalog).toContain('seoDescription');expect(productPage).toContain('product.seoTitle||product.name');expect(productPage).toContain('product.seoDescription||product.short')});
 test('per-product channel switches reuse existing channel settings authority',()=>{const editor=read('src/components/admin/product-intake-editor.tsx'),sql=read('supabase/migrations/20260910221500_product_intake_center_hardening_v1.sql');expect(editor).toContain('setB2cVisible');expect(editor).toContain('setB2bVisible');expect(editor).toContain('A webshop B2B csatornája jelenleg ki van kapcsolva');expect(sql).toContain('public.product_channel_settings');expect(sql).toContain("'b2c'");expect(sql).toContain("'b2b'");expect(sql).not.toContain('create table public.product_channel_settings')});
 test('draft authority stays atomic, service-role mediated and publish explicit',()=>{for(const path of['supabase/migrations/20260910221500_product_intake_center_hardening_v1.sql','supabase/customer-baseline/migrations/0010_product_intake_center_hardening_v1.sql']){const sql=read(path);expect(sql).toContain('public.create_catalog_draft_v2');expect(sql).toContain('public.update_catalog_draft_v1');expect(sql).toContain('public.publish_catalog_product_v1');expect(sql).toContain('public.can_manage_catalog(p_instance_id,p_actor)');expect(sql).toContain('to service_role');expect(sql).toContain('CATALOG_PUBLISH_NOT_DRAFT')}});
 test('v1 authority remains intact while later Product Intake slices extend it',()=>{const sql=read('supabase/migrations/20260910221500_product_intake_center_hardening_v1.sql'),onboarding=read('src/app/api/admin/catalog/onboarding/route.ts');expect(sql).toContain('create_catalog_draft_v2');expect(onboarding).toContain("rpc('create_catalog_draft_v1'");expect(onboarding).toContain("rpc('create_catalog_draft_v2'")});
});
