import {describe,expect,it} from 'vitest';
import {PROFESSIONAL_B2B_ENGINE_VERSION,PROFESSIONAL_B2B_SERVER_AUTHORITIES,PROFESSIONAL_TEMPLATE_SWITCH_MUTATION_BOUNDARY,buildProfessionalExperience,buildProfessionalOfferReadModel,buildProfessionalProductReadModel,buildProfessionalQuantityHint,buildProfessionalReorderLines,normalizeQuickOrderSku,validateProfessionalProductAuthority,type ProfessionalProductAuthoritySnapshot} from '@/lib/commerce/professional-b2b';
const product:ProfessionalProductAuthoritySnapshot={authority:'server',productId:'p-1',variantId:'v-1',sku:'TD-001',name:'Pro Drill 18V',href:'/termek/pro-drill',channelVisible:true,stockQuantity:14,stockLabel:'14 db raktáron',displayNetPrice:'99 900 Ft + ÁFA',displayGrossPrice:'126 873 Ft',priceAuthority:'partner',minimumQuantity:2,orderMultiple:2,canRequestQuote:true};
describe('E11 Professional / B2B Experience v1',()=>{
 it('locks the engine identity and server-authoritative boundaries',()=>{expect(PROFESSIONAL_B2B_ENGINE_VERSION).toBe('shoporation.professional-b2b-experience.v1');expect(PROFESSIONAL_B2B_SERVER_AUTHORITIES).toEqual(expect.arrayContaining(['pricing-tax','stock','moq-order-multiple','offer-acceptance','reorder-revalidation']));});
 it('builds a professional product read model without recomputing price, tax or stock',()=>{const model=buildProfessionalProductReadModel(product)!;expect(model.displayNetPrice).toBe(product.displayNetPrice);expect(model.displayGrossPrice).toBe(product.displayGrossPrice);expect(model.stockQuantity).toBe(14);expect(model.requiresServerRevalidation).toBe(true);expect(model.quantityHint).toContain('Minimum 2 db');});
 it('fails closed for unsafe or incomplete server snapshots and hidden channel products',()=>{expect(validateProfessionalProductAuthority({...product,minimumQuantity:0}).some(x=>x.code==='PROFESSIONAL_MOQ_INVALID')).toBe(true);expect(buildProfessionalProductReadModel({...product,href:'javascript:alert(1)'})).toBeNull();expect(buildProfessionalProductReadModel({...product,channelVisible:false})).toBeNull();});
 it('shows partner surfaces only from an approved server-authoritative B2B context',()=>{expect(buildProfessionalExperience({authority:'server',channel:'b2b',accountStatus:'approved',approvedReseller:true,canRequestQuote:true,canViewOffers:true,canReorder:true})?.showPartnerExperience).toBe(true);expect(buildProfessionalExperience({authority:'server',channel:'b2b',accountStatus:'pending',approvedReseller:false,canRequestQuote:true,canViewOffers:true,canReorder:true})?.showPartnerExperience).toBe(false);});
 it('keeps quantity normalization a client hint and requires authoritative checkout revalidation',()=>{expect(buildProfessionalQuantityHint({requestedQuantity:5,minimumQuantity:2,orderMultiple:2})).toMatchObject({suggestedQuantity:6,clientHintOnly:true,requiresServerRevalidation:true});});
 it('allows offer acceptance UI only when the server says a sent offer is acceptable and href is safe',()=>{const ok=buildProfessionalOfferReadModel({authority:'server',id:'o-1',number:'AJ-001',status:'sent',totalLabel:'250 000 Ft',canAccept:true,acceptanceHref:'/ajanlat/o-1/elfogadas'})!;expect(ok.acceptanceEnabled).toBe(true);expect(buildProfessionalOfferReadModel({...ok,status:'expired'})?.acceptanceEnabled).toBe(false);expect(buildProfessionalOfferReadModel({...ok,acceptanceHref:'javascript:alert(1)'})?.acceptanceEnabled).toBe(false);});
 it('marks reorder lines for server revalidation, normalizes SKU input, and keeps template switching presentation-only',()=>{expect(buildProfessionalReorderLines([{authority:'server',productId:'p',variantId:'v',sku:'ab-12',name:'Bit set',previousQuantity:4,href:'/termek/bit'}])[0].requiresServerRevalidation).toBe(true);expect(normalizeQuickOrderSku(' ab 12<script> ')).toBe('AB12SCRIPT');expect(PROFESSIONAL_TEMPLATE_SWITCH_MUTATION_BOUNDARY).toMatchObject({storefrontPageDrafts:true,products:false,variants:false,orders:false,b2bAccounts:false,pricing:false,inventory:false,offers:false});});
});
