import fs from 'node:fs';import path from 'node:path';import{describe,expect,test}from'vitest';const root=process.cwd();const read=(file:string)=>fs.readFileSync(path.join(root,file),'utf8');const plans=read('src/lib/plans/catalog.ts'),planAccess=read('src/lib/plans/access.ts'),instances=read('src/lib/instances/access.ts'),manifest=JSON.parse(read('supabase/customer-baseline/manifest.json')) as Record<string,unknown>;
describe('release cross-cutting contracts',()=>{
 test('package catalog remains exactly Alap and Pro with unreleased capabilities planned only',()=>{expect(plans).toMatch(/export type PlanCode = 'alap' \| 'pro'/);expect(plans).toContain("'teamChatSecureAttachments'");expect(plans).toContain("'apiAccess'");const p=plans.slice(plans.indexOf('const PRO_FEATURES'),plans.indexOf('export const PLANNED_PRO_FEATURES'));expect(p).not.toContain("'teamChatSecureAttachments'");expect(p).not.toContain("'apiAccess'")});
 test('plan resolution fails closed to Alap and prefers the current webshop instance when resolved',()=>{expect(planAccess).toMatch(/fallback: PlanCode = isPlanCode\(configuredDefault\) \? configuredDefault : 'alap'/);expect(planAccess).toMatch(/const instance = await getCurrentWebshopInstance\(\)/);expect(planAccess).toMatch(/if \(instance\) return instance\.subscriptionPlan/)});
 test('configured instance lookup only accepts pilot or active stores',()=>{expect(instances).toMatch(/WEBSHOP_INSTANCE_SLUG/);expect(instances).toMatch(/in\('status',\['pilot','active'\]\)/);expect(instances).toMatch(/isPlanCode\(row\.subscription_plan\)/)});
 test('RBAC and legacy membership resolution refuse ambiguous multi-instance assignment',()=>{expect(instances).toMatch(/role_bindings/);expect(instances).toMatch(/webshop_instance_members/);expect(instances).toMatch(/candidates\.size!==1/);expect(instances).toMatch(/return null/)});
 test('new customer baseline remains neutral, Alap by default and never replays historical migrations',()=>{expect(['ready','snapshot-reviewed']).toContain(manifest.status);expect(manifest.legacyMigrationReplay).toBe(false);expect(manifest.sourcePolicy).toBe('schema-snapshot-only');expect(manifest.defaultPlan).toBe('alap');expect(String(manifest.snapshotFile)).toContain('0001_shoperation_v1_schema.sql')});
 test('schema-changing forward migrations fail closed until their Fresh Install proof is repeated',()=>{if(manifest.status==='snapshot-reviewed'){expect(manifest.freshInstallProofRequired).toBe(true);expect(manifest.proofContractSha256).toBeNull()}else{expect(manifest.freshInstallProofRequired).toBe(false);expect(String(manifest.notes)).toMatch(/Fresh Install/i)}});
});
