import {readFileSync} from 'node:fs';
import {describe,expect,it} from 'vitest';
import {SHOPERATION_GLOBAL_BASELINE_FAILURE_IDS,SHOPERATION_KNOWN_FAILURES,SHOPERATION_NEGATIVE_KNOWLEDGE,evaluateShoperationKnowledgeIntegrity} from '@/lib/quality-system/shoperation-knowledge';
import {resolveShoperationKnowledgeScope} from '@/lib/quality-system/scope-resolver';
import {classifyShoperationFailureSignal,isUnresolvedFailureIntake} from '@/lib/quality-system/failure-intake';
import {TEMPLATE_FACTORY_KNOWN_FAILURES} from '@/lib/builder/template-factory/knowledge-registry';

describe('Shoperation global quality knowledge',()=>{
  it('unifies global and Template Factory Known Failures under one integrity gate',()=>{const integrity=evaluateShoperationKnowledgeIntegrity();expect(integrity.ok,JSON.stringify(integrity.issues)).toBe(true);expect(SHOPERATION_KNOWN_FAILURES.length).toBeGreaterThan(TEMPLATE_FACTORY_KNOWN_FAILURES.length);for(const failure of TEMPLATE_FACTORY_KNOWN_FAILURES)expect(SHOPERATION_KNOWN_FAILURES.some(item=>item.id===failure.id&&item.provider==='template-factory')).toBe(true);expect(new Set(SHOPERATION_KNOWN_FAILURES.map(item=>item.id)).size).toBe(SHOPERATION_KNOWN_FAILURES.length);});
  it('keeps learned failures complete: invariant, regression, applicability and shared recurring repair',()=>{for(const failure of SHOPERATION_KNOWN_FAILURES){expect(failure.invariantIds.length,failure.id).toBeGreaterThan(0);expect(failure.regressionTests.length,failure.id).toBeGreaterThan(0);if(failure.applicability.mode==='subsystem')expect(failure.applicability.subsystems.length,failure.id).toBeGreaterThan(0);if(failure.occurrences>=2)expect(failure.remediationPolicy,failure.id).toBe('shared-root-cause-required');}expect(SHOPERATION_NEGATIVE_KNOWLEDGE.length).toBeGreaterThanOrEqual(5);expect(SHOPERATION_NEGATIVE_KNOWLEDGE.every(item=>item.sourceRecords.length>0)).toBe(true);});
  it('runs shipping/fulfillment knowledge without dragging Template Factory-only guards into the active set',()=>{const scope=resolveShoperationKnowledgeScope({changedFiles:['src/lib/shipping/dpd-provider.ts']});expect(scope.directSubsystems).toContain('inventory-fulfillment-authority');expect(scope.impactedSubsystems).toContain('payment-checkout-order-authority');expect(scope.activeFailureIds).toEqual(expect.arrayContaining([...SHOPERATION_GLOBAL_BASELINE_FAILURE_IDS,'SQ-KF-010']));expect(scope.activeFailureIds).not.toContain('TF-KF-003');expect(scope.activeFailureIds).not.toContain('TF-KF-016');const skipped=scope.selection.find(item=>item.failureId==='TF-KF-003');expect(skipped?.selected).toBe(false);expect(skipped?.reasons).toContain('not-applicable-to-current-scope');});
  it('expands to the full knowledge set when the knowledge authority itself changes',()=>{const scope=resolveShoperationKnowledgeScope({changedFiles:['src/lib/quality-system/scope-resolver.ts']});expect(scope.fullReplay).toBe(true);expect(scope.knowledgeInfrastructureChanged).toBe(true);expect(scope.activeFailureIds.length).toBe(SHOPERATION_KNOWN_FAILURES.length);expect(scope.selection.every(item=>item.selected)).toBe(true);});
  it('makes scope decisions explainable and exposes unresolved unclassified production code',()=>{const scope=resolveShoperationKnowledgeScope({changedFiles:['src/unknown-authority/new-runtime.ts']});expect(scope.unresolvedFiles).toEqual(['src/unknown-authority/new-runtime.ts']);expect(scope.activeFailureIds).toEqual(expect.arrayContaining([...SHOPERATION_GLOBAL_BASELINE_FAILURE_IDS]));for(const selected of scope.selection.filter(item=>item.selected))expect(selected.reasons.length).toBeGreaterThan(0);});
  it('matches known signatures before opening a new candidate and keeps generic failures review-only',()=>{const base={sourceCommit:'abc',failureSource:'browser-matrix',symptom:'failure',evidence:['manifest']};const known=classifyShoperationFailureSignal({...base,rawErrorCode:'SHOWROOM_ENGINE_DEMO_MISSING'});expect(known.classificationStatus).toBe('matched-known-failure');expect(known.knownFailureId).toBe('TF-KF-021');expect(known.evidence).toEqual(['manifest']);const unknown=classifyShoperationFailureSignal({...base,rawErrorCode:'DPD_PROVIDER_CONTRACT_SIGNATURE_DRIFT'});expect(unknown.classificationStatus).toBe('candidate-new-failure');expect(isUnresolvedFailureIntake(unknown)).toBe(true);const generic=classifyShoperationFailureSignal({...base,rawErrorCode:'BUILD_FAILED'});expect(generic.classificationStatus).toBe('needs-review');expect(generic.knownFailureId).toBeNull();});
  it('requires a periodic full-system replay and durable intake persistence wiring',()=>{const weekly=readFileSync('.github/workflows/shoperation-knowledge-full-replay.yml','utf8'),ci=readFileSync('.github/workflows/ci.yml','utf8'),factory=readFileSync('.github/workflows/template-factory-quality-gate.yml','utf8');expect(weekly).toContain('schedule:');expect(weekly).toContain("SHOPERATION_KNOWLEDGE_FORCE_FULL: '1'");expect(weekly).toContain('npm test');for(const workflow of [ci,factory]){expect(workflow).toContain('Knowledge Before Build');expect(workflow).toContain('shoperation-failure-intake.mjs');expect(workflow).toContain('Persist unresolved failure intake');expect(workflow).toContain('[Quality intake]');}});
});
