import {readFileSync} from 'node:fs';
import {describe,expect,it} from 'vitest';
import {SHOPERATION_KNOWN_FAILURES,evaluateShoperationKnowledgeIntegrity} from '@/lib/quality-system/shoperation-knowledge';
import {resolveShoperationKnowledgeScope} from '@/lib/quality-system/scope-resolver';
const policy=JSON.parse(readFileSync('quality/knowledge/development-guard-policy.v1.json','utf8')) as {intentMatchers:{pattern:string;subsystems:string[]}[];directives:Record<string,{preventiveDirective:string;forbiddenApproaches:string[];requiredBeforeEdit:string[]}>;editRules:{id:string;severity:string;failureIds:string[]}[];negativeKnowledgeApplicability:Record<string,string[]>;};
const scopePolicy=JSON.parse(readFileSync('quality/knowledge/knowledge-scope-policy.v1.json','utf8')) as {dependencies:Record<string,string[]>;knowledgeInfrastructurePrefixes:string[]};
describe('Shoperation Development-Time Known Failure Guard',()=>{
  it('requires a preventive directive for every global and Template Factory Known Failure',()=>{const integrity=evaluateShoperationKnowledgeIntegrity();expect(integrity.ok,JSON.stringify(integrity.issues)).toBe(true);const ids=SHOPERATION_KNOWN_FAILURES.map(item=>item.id);expect(Object.keys(policy.directives).sort()).toEqual([...ids].sort());for(const id of ids){const directive=policy.directives[id];expect(directive.preventiveDirective.length,id).toBeGreaterThan(20);expect(directive.forbiddenApproaches.length,id).toBeGreaterThan(0);expect(directive.requiredBeforeEdit.length,id).toBeGreaterThan(0);}});
  it('keeps the preventive-development failure in the always-on global baseline',()=>{const k=JSON.parse(readFileSync('quality/knowledge/shoperation-quality-knowledge.v1.json','utf8')) as {globalBaselineFailureIds:string[]};expect(k.globalBaselineFailureIds).toContain('SQ-KF-022');const shipping=resolveShoperationKnowledgeScope({changedFiles:['src/lib/shipping/dpd-provider.ts']});expect(shipping.activeFailureIds).toContain('SQ-KF-022');expect(shipping.activeFailureIds).not.toContain('TF-KF-003');});
  it('bounds short provider tokens so unrelated words cannot expand development scope',()=>{const shipping=policy.intentMatchers.find(item=>item.subsystems.includes('inventory-fulfillment-authority'));expect(shipping).toBeTruthy();const matcher=new RegExp(shipping!.pattern,'i');expect(matcher.test('implementation details')).toBe(false);expect(matcher.test('MPL carrier integration')).toBe(true);});
  it('does not treat bug-report wording as login intent',()=>{const auth=policy.intentMatchers.find(item=>item.subsystems.includes('auth-access-authority'));expect(auth).toBeTruthy();const matcher=new RegExp(auth!.pattern,'i');expect(matcher.test('hibabejelentő felület')).toBe(false);expect(matcher.test('vásárlói bejelentkezés')).toBe(true);expect(matcher.test('login flow')).toBe(true);});
  it('does not let auth match authority',()=>{const auth=policy.intentMatchers.find(item=>item.subsystems.includes('auth-access-authority'));expect(auth).toBeTruthy();const matcher=new RegExp(auth!.pattern,'i');expect(matcher.test('shared Incident Intelligence authority')).toBe(false);expect(matcher.test('auth flow')).toBe(true);expect(matcher.test('authentication flow')).toBe(true);expect(matcher.test('authorization rule')).toBe(true);});
  it('uses one canonical dependency graph for TypeScript and Node development tooling',()=>{expect(scopePolicy.dependencies['inventory-fulfillment-authority']).toContain('payment-checkout-order-authority');expect(scopePolicy.dependencies['payment-checkout-order-authority']).toContain('customer-account');expect(scopePolicy.knowledgeInfrastructurePrefixes).toContain('quality/knowledge/');});
  it('has edit-time prevention for the strongest known unsafe implementation patterns',()=>{const blockIds=policy.editRules.filter(rule=>rule.severity==='block').map(rule=>rule.id);expect(blockIds).toEqual(expect.arrayContaining(['DEV-BLOCK-001','DEV-BLOCK-002','DEV-BLOCK-003']));expect(policy.editRules.some(rule=>rule.failureIds.includes('SQ-KF-016'))).toBe(true);expect(policy.editRules.some(rule=>rule.failureIds.includes('SQ-KF-017'))).toBe(true);});
  it('wires plan, edit-time and incremental guards into both general CI and Template Factory CI',()=>{for(const file of ['.github/workflows/ci.yml','.github/workflows/template-factory-quality-gate.yml']){const workflow=readFileSync(file,'utf8');expect(workflow).toContain('Plan Before Code Gate');expect(workflow).toContain('Edit-Time Known Failure Guard');expect(workflow).toContain('Incremental Known Failure Replay');expect(workflow).toContain('shoperation-plan-before-code.mjs --check');expect(workflow).toContain('shoperation-edit-time-guard.mjs --check');expect(workflow).toContain('shoperation-incremental-replay.mjs --check');expect(workflow).toContain('INCREMENTAL_OUTCOME');expect(workflow).toContain('INCREMENTAL_REPLAY_FAILED');expect(workflow).toContain('Upload Development Guard evidence');}});
  it('makes the preventive protocol repository-level instructions for coding agents',()=>{const agents=readFileSync('AGENTS.md','utf8');expect(agents).toContain('BEFORE THE FIRST IMPLEMENTATION EDIT');expect(agents).toContain('development-guard.md');expect(agents).toContain('Plan Before Code');expect(agents).toContain('shoperation-incremental-replay.mjs --check');});
});
