import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {describe,expect,it} from 'vitest';
import {SHOPERATION_KNOWN_FAILURES,evaluateShoperationKnowledgeIntegrity} from '@/lib/quality-system/shoperation-knowledge';
import {resolveShoperationKnowledgeScope} from '@/lib/quality-system/scope-resolver';
const policy=JSON.parse(readFileSync('quality/knowledge/development-guard-policy.v1.json','utf8')) as {generalRules:string[];intentMatchers:{pattern:string;subsystems:string[]}[];directives:Record<string,{preventiveDirective:string;forbiddenApproaches:string[];requiredBeforeEdit:string[]}>;editRules:{id:string;severity:string;failureIds:string[]}[];negativeKnowledgeApplicability:Record<string,string[]>;};
const scopePolicy=JSON.parse(readFileSync('quality/knowledge/knowledge-scope-policy.v1.json','utf8')) as {dependencies:Record<string,string[]>;knowledgeInfrastructurePrefixes:string[]};
describe('Shoperation Development-Time Known Failure Guard',()=>{
  it('classifies source-controlled storefront demo media as Template Factory scope',()=>{
    const scope=resolveShoperationKnowledgeScope({changedFiles:['public/storefront-demo/example/hero.webp']});
    expect(scope.directSubsystems).toContain('builder-template-system');
    expect(scope.impactedSubsystems).toContain('shared-storefront');
    expect(scope.unresolvedFiles).toEqual([]);
  });
  it('requires a preventive directive for every global and Template Factory Known Failure',()=>{const integrity=evaluateShoperationKnowledgeIntegrity();expect(integrity.ok,JSON.stringify(integrity.issues)).toBe(true);const ids=SHOPERATION_KNOWN_FAILURES.map(item=>item.id);expect(Object.keys(policy.directives).sort()).toEqual([...ids].sort());for(const id of ids){const directive=policy.directives[id];expect(directive.preventiveDirective.length,id).toBeGreaterThan(20);expect(directive.forbiddenApproaches.length,id).toBeGreaterThan(0);expect(directive.requiredBeforeEdit.length,id).toBeGreaterThan(0);}});
  it('keeps the preventive-development failure in the always-on global baseline',()=>{const k=JSON.parse(readFileSync('quality/knowledge/shoperation-quality-knowledge.v1.json','utf8')) as {globalBaselineFailureIds:string[]};expect(k.globalBaselineFailureIds).toContain('SQ-KF-022');const shipping=resolveShoperationKnowledgeScope({changedFiles:['src/lib/shipping/dpd-provider.ts']});expect(shipping.activeFailureIds).toContain('SQ-KF-022');expect(shipping.activeFailureIds).not.toContain('TF-KF-003');});
  it('does not let product intent match production terminology',()=>{const storefront=policy.intentMatchers.find(item=>item.subsystems.includes('storefront-ui'));expect(storefront).toBeTruthy();const matcher=new RegExp(storefront!.pattern,'i');expect(matcher.test('production evidence closure')).toBe(false);expect(matcher.test('product page')).toBe(true);expect(matcher.test('termék oldal')).toBe(true);});
  it('bounds short provider tokens so unrelated words cannot expand development scope',()=>{const shipping=policy.intentMatchers.find(item=>item.subsystems.includes('inventory-fulfillment-authority'));expect(shipping).toBeTruthy();const matcher=new RegExp(shipping!.pattern,'i');expect(matcher.test('implementation details')).toBe(false);expect(matcher.test('MPL carrier integration')).toBe(true);});
  it('does not treat bug-report wording as login intent',()=>{const auth=policy.intentMatchers.find(item=>item.subsystems.includes('auth-access-authority'));expect(auth).toBeTruthy();const matcher=new RegExp(auth!.pattern,'i');expect(matcher.test('hibabejelentő felület')).toBe(false);expect(matcher.test('vásárlói bejelentkezés')).toBe(true);expect(matcher.test('login flow')).toBe(true);});
  it('does not let auth match authority',()=>{const auth=policy.intentMatchers.find(item=>item.subsystems.includes('auth-access-authority'));expect(auth).toBeTruthy();const matcher=new RegExp(auth!.pattern,'i');expect(matcher.test('shared Incident Intelligence authority')).toBe(false);expect(matcher.test('auth flow')).toBe(true);expect(matcher.test('authentication flow')).toBe(true);expect(matcher.test('authorization rule')).toBe(true);});
  it('uses one canonical dependency graph for TypeScript and Node development tooling',()=>{expect(scopePolicy.dependencies['inventory-fulfillment-authority']).toContain('payment-checkout-order-authority');expect(scopePolicy.dependencies['payment-checkout-order-authority']).toContain('customer-account');expect(scopePolicy.dependencies['commerce-read-model-authority']).toContain('shared-storefront');expect(scopePolicy.dependencies['content-authority']).toContain('shared-storefront');expect(scopePolicy.knowledgeInfrastructurePrefixes).toContain('quality/knowledge/');expect(scopePolicy.knowledgeInfrastructurePrefixes).toContain('scripts/shoperation-codebase-atlas.mjs');expect(scopePolicy.knowledgeInfrastructurePrefixes).toContain('scripts/shoperation-support-history-backfill.mjs');expect(scopePolicy.knowledgeInfrastructurePrefixes).toContain('scripts/template-factory-product-owner-handoff.mjs');const runtime=readFileSync('scripts/lib/shoperation-development-runtime.mjs','utf8');expect(runtime).toContain('{knowledgeInfrastructureChanged=true;continue;}');});
  it('has edit-time prevention for the strongest known unsafe implementation patterns',()=>{const blockIds=policy.editRules.filter(rule=>rule.severity==='block').map(rule=>rule.id);expect(blockIds).toEqual(expect.arrayContaining(['DEV-BLOCK-001','DEV-BLOCK-002','DEV-BLOCK-003']));expect(policy.editRules.some(rule=>rule.failureIds.includes('SQ-KF-016'))).toBe(true);expect(policy.editRules.some(rule=>rule.failureIds.includes('SQ-KF-017'))).toBe(true);});
  it('pins plan, knowledge preflight and edit-time guard to one change transaction authority',()=>{
    const runtime=readFileSync('scripts/lib/shoperation-development-runtime.mjs','utf8'),plan=readFileSync('scripts/shoperation-plan-before-code.mjs','utf8'),preflight=readFileSync('scripts/shoperation-knowledge-preflight.mjs','utf8'),edit=readFileSync('scripts/shoperation-edit-time-guard.mjs','utf8');
    expect(runtime).toContain('export function resolveDevelopmentBase');
    expect(plan).toContain('getChangedFiles({baseSha:plan.changeBaseSha})');
    expect(edit).toContain('getChangedFiles({baseSha:plan.changeBaseSha})');
    expect(preflight).toContain("import {getChangedFiles} from './lib/shoperation-development-runtime.mjs'");
    expect(preflight).toContain('getChangedFiles({baseSha:developmentPlan.changeBaseSha})');
    expect(preflight).toContain('transaction.materialFiles??[]');
    expect(preflight).not.toContain("developmentPlan.changeBaseSha?.trim()||process.env.QUALITY_BASE_SHA");
  });
  it('keeps Git-proven deletions in the shared development transaction instead of dropping D status',()=>{
    const output=execFileSync(process.execPath,['scripts/lib/shoperation-development-runtime.mjs','--change-status-self-test'],{encoding:'utf8'});
    expect(output).toContain('Development change-status self-test: PASS');
    const runtime=readFileSync('scripts/lib/shoperation-development-runtime.mjs','utf8');
    const edit=readFileSync('scripts/shoperation-edit-time-guard.mjs','utf8');
    expect(runtime).toContain("'--name-status','--diff-filter=ACMRD'");
    expect(runtime).toContain('deletedFiles');
    expect(edit).toContain('deletedVerifiedChangeSet');
    expect(edit).toContain('{tombstones:diff.materialDeletedFiles??[]}');
    const knowledge=readFileSync('scripts/shoperation-knowledge-preflight.mjs','utf8');
    const risk=readFileSync('scripts/release-risk-budget.mjs','utf8');
    const truth=readFileSync('scripts/shoperation-truth-gate.mjs','utf8');
    expect(knowledge).toContain('transaction.materialDeletedFiles??[]');
    expect(risk).toContain("'--diff-filter=ACMRD'");
    expect(truth).toContain("'--diff-filter=ACMRD'");
    expect(risk).toContain('RELEASE_RISK_EXPLICIT_BASE_UNRESOLVED');
    expect(risk).toContain('RELEASE_RISK_EXPLICIT_HEAD_UNRESOLVED');
    expect(risk).toContain('RELEASE_RISK_MERGE_BASE_UNRESOLVED');
  });
  it('resolves pull-request head identity before generic GITHUB_SHA fallback',()=>{
    const runtime=readFileSync('scripts/lib/shoperation-development-runtime.mjs','utf8');
    expect(runtime).toContain('event?.pull_request?.head?.sha');
    expect(runtime).toContain("resolution:'PULL_REQUEST_HEAD'");
    expect(runtime).toContain("resolution:'UNRESOLVED_EXPLICIT'");
    expect(runtime).toContain('const headIdentity=resolveDevelopmentHead()');
    expect(runtime.indexOf('process.env.SHOPERATION_REPLAY_HEAD')).toBeLessThan(runtime.indexOf('process.env.GITHUB_SHA'));
  });
  it('prevents plan-only or metadata commits from shrinking the active development transaction',()=>{
    const runtime=readFileSync('scripts/lib/shoperation-development-runtime.mjs','utf8'),plan=readFileSync('scripts/shoperation-plan-before-code.mjs','utf8');
    expect(runtime).toContain("git(['diff','--name-status','--diff-filter=ACMRD',base,head])");
    expect(runtime).toContain('const base=resolveDevelopmentBase({changeBaseSha:requestedBase||null})');
    expect(plan).toContain('diff.materialFiles??[]');
    expect(plan).not.toContain("getChangedFiles()");
  });
  it('binds stacked branch CI to the canonical Development Transaction instead of reinterpreting event refs',()=>{
    const output=execFileSync(process.execPath,['scripts/lib/shoperation-development-runtime.mjs','--ci-transaction-self-test'],{encoding:'utf8'});
    expect(output).toContain('Development CI transaction self-test: PASS');
    const workflow=readFileSync('.github/workflows/ci.yml','utf8');
    const runtime=readFileSync('scripts/lib/shoperation-development-runtime.mjs','utf8');
    const exactHead="ref: ${{ github.event.pull_request.head.sha || github.sha }}";
    expect(workflow.split(exactHead).length-1).toBeGreaterThanOrEqual(2);
    expect(workflow).toContain("- 'fix/**'");
    expect(workflow).toContain('Bind canonical Development Transaction identity');
    expect(workflow).toContain('--ci-transaction-env >> "$GITHUB_ENV"');
    expect(workflow).not.toContain('QUALITY_BASE_SHA: ${{ github.event.pull_request.base.sha || github.event.before }}');
    expect(workflow).not.toContain('DEVELOPMENT_BASE_SHA: ${{ github.event.pull_request.base.sha || github.event.before }}');
    expect(workflow).not.toContain('RELEASE_BASE_SHA: ${{ github.event.pull_request.base.sha || github.event.before }}');
    expect(runtime).toContain('CI_TRANSACTION_BASE_MISMATCH');
    expect(runtime).toContain('CI_TRANSACTION_ANCESTRY_INVALID');
    expect(runtime).toContain("authority:'quality/development/active-plan.json#changeBaseSha'");
  });
  it('wires development-time guards into development proof CI while preserving post-merge replay and evidence',()=>{for(const file of ['.github/workflows/ci.yml','.github/workflows/template-factory-quality-gate.yml']){const workflow=readFileSync(file,'utf8');expect(workflow).toContain('Plan Before Code Gate');expect(workflow).toContain('Edit-Time Known Failure Guard');expect(workflow).toContain('Incremental Known Failure Replay');expect(workflow).toContain('shoperation-plan-before-code.mjs --check');expect(workflow).toContain('shoperation-edit-time-guard.mjs --check');expect(workflow).toContain('shoperation-incremental-replay.mjs --check');expect(workflow).toContain('INCREMENTAL_OUTCOME');expect(workflow).toContain('INCREMENTAL_REPLAY_FAILED');expect(workflow).toContain('Upload Development Guard evidence');}});
  it('runs A/B Reference Sync before replay and catches stale source assertions plus deleted asset paths',()=>{const output=execFileSync(process.execPath,['scripts/lib/shoperation-reference-sync-runtime.mjs','--self-test'],{encoding:'utf8'});expect(output).toContain('Reference Sync self-test: PASS');expect(output).toContain('bare-object-key=IGNORED');expect(output).toContain('coverage-overflow=BLOCK');const refSource=readFileSync('scripts/lib/shoperation-reference-sync-runtime.mjs','utf8');expect(refSource).toContain('diffData(base,head)');expect(refSource).toContain('grep(patterns,head)');expect(refSource).toContain('REFERENCE_SYNC_CHECKOUT_HEAD_MISMATCH');const edit=readFileSync('scripts/shoperation-edit-time-guard.mjs','utf8');expect(edit).toContain('evaluateReferenceSynchronization');expect(edit).toContain('DEV-BLOCK-REFERENCE-SYNC');expect(edit).toContain('DEV-REVIEW-REFERENCE-SYNC');expect(edit).toContain('reference-sync.json');expect(policy.generalRules.some(rule=>rule.includes('repository-wide Reference Sync closure'))).toBe(true);});
  it('enforces durable PO instruction required edits in both plan and edit-time directions',()=>{
    const plan=readFileSync('scripts/shoperation-plan-before-code.mjs','utf8');
    const edit=readFileSync('scripts/shoperation-edit-time-guard.mjs','utf8');
    expect(plan).toContain('INSTRUCTION_REQUIRED');
    expect(plan).toContain('DEV_PLAN_PO_INSTRUCTION_REQUIRED_CHANGE_UNDECLARED');
    expect(edit).toContain('buildExecutionRoute');
    expect(edit).toContain('instructionRequired');
    expect(edit).toContain('requiredChangeSet=[...new Set([...declaredSemanticRequired,...instructionRequired,...referenceRequired])]');
  });
  it('binds review exceptions to one exact finding fingerprint instead of a whole rule',()=>{
    const output=execFileSync(process.execPath,['scripts/lib/shoperation-development-runtime.mjs','--exception-self-test'],{encoding:'utf8'});
    expect(output).toContain('Development exception self-test: PASS');
    const edit=readFileSync('scripts/shoperation-edit-time-guard.mjs','utf8');
    const plan=readFileSync('scripts/shoperation-plan-before-code.mjs','utf8');
    expect(edit).toContain('matchGuardException(finding,exceptionList)');
    expect(edit).not.toContain('exceptions.get(rule.id)');
    expect(plan).toContain("required:['ruleId','file','findingFingerprint','reason']");
  });
  it('keeps composite Edit-Time decisions monotonic and excludes plan metadata from material implementation scope',()=>{
    const output=execFileSync(process.execPath,['scripts/lib/shoperation-development-runtime.mjs','--decision-self-test'],{encoding:'utf8'});
    expect(output).toContain('Development decision self-test: PASS');
    const edit=readFileSync('scripts/shoperation-edit-time-guard.mjs','utf8');
    expect(edit).toContain('diff.materialFiles??[]');
    expect(edit).toContain('DEV-BLOCK-IMPLEMENTATION-SYNC-OUTSIDE-PLAN');
    expect(edit).toContain('childDecisions={referenceSync:referenceSync.decision,implementationSync:implementationSync.decision,poInstructionState:poInstructionState.decision}');
    expect(edit).toContain('aggregateGateDecision({localBlocking:blocking.length>0,childDecisions:Object.values(childDecisions)})');
  });
  it('makes the preventive protocol repository-level instructions for coding agents',()=>{const agents=readFileSync('AGENTS.md','utf8');expect(agents).toContain('BEFORE THE FIRST IMPLEMENTATION EDIT');expect(agents).toContain('development-guard.md');expect(agents).toContain('Plan Before Code');expect(agents).toContain('shoperation-incremental-replay.mjs --check');});
});
