import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {describe,expect,it} from 'vitest';
import {buildCartCommerceGroups,type Cart} from '@/lib/cart/types';
import {mergeCartItem} from '@/lib/commerce/cart-engine';
import {evaluateCompatibility} from '@/lib/commerce/compatibility-engine';
import {validateStorefrontExistingEngineDocument,withStorefrontEngineTenant,type StorefrontGuidedFinderDocument} from '@/lib/builder/storefront-existing-engine-config';
const read=(path:string)=>readFileSync(resolve(process.cwd(),path),'utf8');
const migration='supabase/migrations/20260913062000_special_commerce_existing_engine_closure.sql';
const baseline='supabase/customer-baseline/migrations/0023_special_commerce_existing_engine_closure.sql';

describe('Special Commerce Wave 5 existing engine closure',()=>{
 it('keeps production and customer forward migration byte-identical with server-only engine config authority',()=>{const sql=read(migration);expect(read(baseline)).toBe(sql);expect(sql).toContain('create table if not exists public.storefront_commerce_engine_configs');expect(sql).toContain('alter table public.storefront_commerce_engine_configs enable row level security');expect(sql).toContain('revoke all on public.storefront_commerce_engine_configs from public,anon,authenticated');expect(sql).toContain('grant select on public.storefront_commerce_engine_configs to service_role');expect(sql).toContain("set search_path=''");expect(sql).toContain('save_storefront_commerce_engine_config_v1');expect(sql).toContain('delete_storefront_commerce_engine_config_v1');});
 it('wraps authoritative v5 checkout instead of cloning pricing/stock/order logic',()=>{const sql=read(migration);expect(sql).toContain('place_order_provider_v6_idempotent');expect(sql).toContain('v_result:=public.place_order_provider_v5_idempotent');expect(sql).toContain('COMMERCE_GROUP_ALLOCATION_EXCEEDS_CART');expect(sql).toContain('COMMERCE_GROUP_IDEMPOTENCY_MISMATCH');expect(sql).toContain('COMMERCE_GROUP_REPLAY_METADATA_MISSING');expect(sql).toContain('foreign key(group_id,order_id,instance_id)');expect(sql).toContain('foreign key(order_item_id,order_id,instance_id)');expect(sql).toContain('from public,anon,authenticated');expect(sql).toContain('to service_role');});
 it('application order path carries grouped metadata only at authoritative order commit',()=>{const wrapper=read('src/lib/orders/tenant-checkout.ts'),route=read('src/app/api/orders/route.ts'),form=read('src/components/checkout/checkout-form.tsx'),quote=read('src/app/api/checkout/quote/route.ts');expect(wrapper).toContain("admin.rpc('place_order_provider_v6_idempotent'");expect(wrapper).toContain('p_commerce_groups:input.commerceGroups');expect(route).toContain('commerceGroups:z.array');expect(route).toContain('commerceGroups}) as PlaceOrderResult');expect(form).toContain('buildCartCommerceGroups');expect(form).toContain('JSON.stringify({checkout,items,commerceGroups})');expect(quote).not.toContain('commerceGroups');});
 it('preserves grouped cart line identity and reconstructs deterministic order group requests',()=>{const grouped={productId:'p1',variantId:'v1',slug:'one',name:'One',unitPrice:100,quantity:2,lineId:'line-a',commerceGroup:{type:'composition' as const,id:'composition-1',engineVersion:'shoporation.multi-product-composer.v1',definitionKey:'box',definitionVersion:1,itemKey:'a',slotId:'main'}};const ordinary={productId:'p1',variantId:'v1',slug:'one',name:'One',unitPrice:100,quantity:1};expect(mergeCartItem([ordinary],grouped)).toHaveLength(2);const cart:Cart={items:[grouped,{...grouped,quantity:1,lineId:'line-b',commerceGroup:{...grouped.commerceGroup,itemKey:'b',slotId:'extra'}}]};const groups=buildCartCommerceGroups(cart);expect(groups).toHaveLength(1);expect(groups[0]?.id).toBe('composition-1');expect(groups[0]?.items.map(item=>item.quantity)).toEqual([2,1]);expect(read('src/lib/commerce/cart-engine.ts')).toContain("item.lineId?`line:${item.lineId}`");});
 it('does not treat missing compatibility evidence as compatible',()=>{expect(evaluateCompatibility({rules:[],parts:[]})).toEqual({status:'unknown',results:[],required:{compatible:0,incompatible:0,unknown:0},advisory:{compatible:0,incompatible:0,unknown:0}});expect(read('src/lib/commerce/compatibility-engine.ts')).toContain("if(!input.rules.length)return{status:'unknown'");});
 it('validates canonical E3 documents after server-side tenant injection',()=>{const doc:StorefrontGuidedFinderDocument={config:{version:1,tenantId:'placeholder',finderKey:'finder-1',label:'Finder',safetyPolicy:'standard',partialPolicy:'show-nearest',maxResults:12,steps:[{id:'step-1',title:'Step',questions:[{id:'q-1',label:'Question',mode:'single',required:true,options:[{id:'one',label:'One',rules:[{id:'r-1',attributeKey:'attr.use-case.x',operator:'eq',value:'home',kind:'required',reason:'Explicit attribute'}]}]}]}]}};const scoped=withStorefrontEngineTenant('guided_finder',doc,'11111111-1111-4111-8111-111111111111');expect(validateStorefrontExistingEngineDocument('guided_finder',scoped)).toEqual([]);});
 it('uses authoritative catalog evidence and explicit product attributes without a parallel price engine',()=>{const server=read('src/lib/builder/storefront-existing-commerce-server.ts');expect(server).toContain('getStorefrontInteractiveSceneCatalogForInstance');expect(server).toContain("from('product_attributes')");expect(server).toContain('runProductDiscovery');expect(server).toContain("source:'compare-spec-engine.v1'");expect(server).not.toContain('gross_price_huf');});
 it('keeps Page Schema binding shared across Builder, preview and published renderer',()=>{const renderer=read('src/components/builder/storefront-runtime-renderer.tsx'),bindings=read('src/lib/builder/storefront-existing-commerce-bindings.ts'),runtime=read('src/components/builder/storefront-existing-commerce-runtime.tsx');expect(renderer).toContain('const authorityPage=ensureStorefrontResponsiveAuthority(normalizedPage)');expect(renderer).toContain('bindStorefrontExistingCommerceRuntime(authorityPage)');expect(renderer).toContain('StorefrontExistingCommerceRuntimeProvider');expect(bindings).toContain('catalog.existingCommerceProducts');expect(bindings).toContain('commerce.existingEngines.finders');expect(runtime).toContain('runGuidedFinder');expect(runtime).toContain('buildComposerAddIntent');expect(runtime).toContain('buildConfiguratorAddIntent');});
 it('versions Builder registries and managed configuration for the Wave 5 contract',()=>{expect(read('src/lib/builder/storefront-builder-registry.ts')).toContain('storefront-builder-registry.special-commerce-v5');expect(read('src/components/builder/storefront-builder-renderer-registry.tsx')).toContain('storefront-builder-renderers.special-commerce-v5');expect(read('src/lib/builder/storefront-managed-config.ts')).toContain('storefront-managed-config.v5');});
 it('exposes merchant controls while hiding engine keys from generic structured editing',()=>{const managed=read('src/lib/builder/storefront-managed-config.ts'),finder=read('src/lib/builder/storefront-guided-finder.ts'),composer=read('src/lib/builder/storefront-multi-product-composer.ts'),configurator=read('src/lib/builder/storefront-configurator.ts'),controls=read('src/components/admin/storefront-existing-commerce-controls.tsx'),library=read('src/components/admin/existing-commerce-engine-library.tsx');expect(managed).toContain("'guided.finder':new Set(['finderKey'])");expect(managed).toContain("'composer.builder':new Set(['composerKey'])");expect(managed).toContain("'configurator.builder':new Set(['configuratorKey'])");expect(finder).not.toContain("configurable:['finderKey'");expect(composer).not.toContain("configurable:['composerKey'");expect(configurator).not.toContain("configurable:['configuratorKey'");expect(controls).toContain('data-existing-commerce-controls-v1');expect(controls).toContain('Commerce motorok kezelése');expect(library).toContain('data-existing-commerce-engine-library-v1');expect(library).not.toContain('JSON.stringify');});
 it('preserves historical composition/configuration groups on actual order-line ids without replacing refund authority',()=>{const helper=read('src/lib/orders/order-commerce-groups.ts'),account=read('src/app/fiokom/rendeles/[id]/page.tsx');expect(helper).toContain('refundableLineIds');expect(helper).toContain("from('order_commerce_groups')");expect(helper).toContain("from('order_commerce_group_items')");expect(account).toContain('getOrderCommerceGroups(instance.id,order.id)');expect(account).toContain('data-order-commerce-groups-v1');expect(account).toContain('/fiokom/visszakuldes');expect(account).toContain('groupItem.orderItemId');});
 it('preserves commerce group metadata in authenticated checkout recovery',()=>{expect(read('src/components/checkout/checkout-recovery-saver.tsx')).toContain('commerceGroup:i.commerceGroup');expect(read('src/app/api/account/checkout-recovery/route.ts')).toContain('commerceGroup:group.optional()');const restore=read('src/app/kosar/visszaallitas/page.tsx');expect(restore).toContain("eq('instance_id',instance.id)");expect(restore).toContain('commerceGroup:savedItem.commerceGroup');expect(restore).toContain('variantId:row.id');});
 it('keeps Fresh Install proof state honest after later baseline extensions',()=>{const manifest=JSON.parse(read('supabase/customer-baseline/manifest.json')) as{status:string;freshInstallProofRequired:boolean;proofContractSha256:null|string;notes:string};expect(['ready','snapshot-reviewed']).toContain(manifest.status);if(manifest.status==='ready'){expect(manifest.freshInstallProofRequired).toBe(false);expect(manifest.proofContractSha256).toMatch(/^[a-f0-9]{64}$/)}else{expect(manifest.freshInstallProofRequired).toBe(true);expect(manifest.proofContractSha256).toBeNull()}expect(manifest.notes).toContain('0035_order_operational_authenticated_privilege_contract.sql');expect(manifest.notes).toContain('0036_product_documents_post_purchase_account_authority.sql');expect(manifest.notes).toContain('0001-0018');});
});
