import {describe,expect,it} from 'vitest';
import {DEFAULT_STORY_TYPE_REGISTRY,STORY_TEMPLATE_SWITCH_MUTATION_BOUNDARY,buildStoryReadModel,canRenderStory,preserveStoryDocumentsAcrossTemplateSwitch,validateStoryDocument,type StoryDocument} from '@/lib/content/story-engine';
const published:StoryDocument={version:1,id:'story-origin-001',slug:'gold-origin',storyType:'origin',status:'published',title:'Az arany útja',excerpt:'Dokumentált anyag- és eredettörténet.',author:{id:'author-atelier',name:'Heritage Atelier'},taxonomy:{categories:['Materials','Materials'],tags:['gold',' craft ','gold']},publishedAt:'2026-09-08T08:00:00Z',relations:[{id:'origin-certified',type:'origin',entityId:'origin-record-1',label:'Ellenőrzött beszállítói eredet',href:'/eredet/1',verified:true},{id:'product-ring',type:'product',entityId:'product-1',label:'Signet Ring',href:'/termek/signet-ring'}],blocks:[{id:'intro',type:'prose',text:'A történet kizárólag ellenőrzött eredetadatokra hivatkozik.'},{id:'claim',type:'provenance',title:'Eredet',claims:[{label:'Anyag',value:'18K arany',originRelationId:'origin-certified'}]},{id:'related',type:'relation-grid',title:'Kapcsolódó darab',relationIds:['product-ring']} ]};
describe('E10 Editorial / Story Engine v1',()=>{
 it('registers the agreed structured story types',()=>{expect(DEFAULT_STORY_TYPE_REGISTRY.list().map(item=>item.key)).toEqual(['lookbook','maker','journal','origin','process','before-after']);});
 it('validates published stories, normalizes taxonomy and builds a read model',()=>{const validation=validateStoryDocument(published);expect(validation.ok).toBe(true);const read=buildStoryReadModel(published,{now:new Date('2026-09-08T10:00:00Z')});expect(read?.taxonomy.categories).toEqual(['Materials']);expect(read?.taxonomy.tags).toEqual(['gold','craft']);});
 it('keeps draft/published/preview lifecycle explicit',()=>{const draft={...published,id:'story-draft',slug:'draft-story',status:'draft' as const,publishedAt:undefined};expect(canRenderStory(draft)).toBe(false);expect(canRenderStory(draft,{preview:true})).toBe(true);expect(buildStoryReadModel(draft)).toBeNull();expect(buildStoryReadModel(draft,{preview:true})?.title).toBe('Az arany útja');});
 it('fails closed on unverifiable provenance claims instead of inventing heritage/origin evidence',()=>{const invalid={...published,relations:published.relations.map(item=>item.type==='origin'?{...item,verified:false}:item)};const result=validateStoryDocument(invalid);expect(result.ok).toBe(false);expect(result.violations.some(item=>item.code==='STORY_PROVENANCE_UNVERIFIED')).toBe(true);});
 it('rejects duplicated product authority and unsafe arbitrary markup/URLs',()=>{const unsafe={...published,relations:[...published.relations,{id:'product-bad',type:'product' as const,entityId:'product-2',label:'Bad',href:'javascript:alert(1)',price:'1 Ft'} as never],blocks:[...published.blocks,{id:'unsafe-prose',type:'prose' as const,text:'<script>alert(1)</script>'}]};const result=validateStoryDocument(unsafe);expect(result.violations.some(item=>item.code==='STORY_PRODUCT_AUTHORITY_DUPLICATED')).toBe(true);expect(result.violations.some(item=>item.code==='STORY_RELATION_URL_UNSAFE')).toBe(true);expect(result.violations.some(item=>item.code==='STORY_UNSAFE_MARKUP')).toBe(true);});
 it('preserves story documents across template switch and declares draft-only template mutation authority',()=>{const preserved=preserveStoryDocumentsAcrossTemplateSwitch([published]);expect(preserved[0]).toBe(published);expect(STORY_TEMPLATE_SWITCH_MUTATION_BOUNDARY).toMatchObject({storyDocuments:false,products:false,collections:false,makers:false,storefrontPageDrafts:true});});
});
