import {readFileSync} from 'node:fs';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe,expect,it} from 'vitest';
import {StorefrontRuntimeRenderer} from '@/components/builder/storefront-runtime-renderer';
import {createStorefrontVisualBuilderComponentRegistry,STOREFRONT_BUILDER_REGISTRY_VERSION} from '@/lib/builder/storefront-builder-registry';
import {createStorefrontVisualBuilderRendererRegistry,STOREFRONT_BUILDER_RENDERER_REGISTRY_VERSION} from '@/components/builder/storefront-builder-renderer-registry';
import {PLANS} from '@/lib/plans/catalog';
import {buildRoomSceneAddIntent,buildRoomSceneComposerReadModel,ROOM_SCENE_COMPOSER_AUTHORITY,ROOM_SCENE_COMPOSER_VERSION} from '@/lib/commerce/room-scene-composer';
import type {InteractiveSceneConfig,InteractiveSceneProductProjection} from '@/lib/commerce/interactive-scene';
import type {StorefrontPageDocument} from '@/lib/builder/storefront-runtime';

const scene:InteractiveSceneConfig={sceneKey:'living-room-01',kind:'room',hotspots:[{id:'sofa',productId:'p-sofa',label:'Kanapé',position:{desktop:{x:35,y:60}},setRequired:true},{id:'lamp',productId:'p-lamp',label:'Állólámpa',position:{desktop:{x:74,y:32}},setRequired:false}]};
const price=(amount:number)=>({amountMinor:amount,currency:'HUF',display:`${amount} Ft`,source:'shared-pricing-authority' as const});
const products:InteractiveSceneProductProjection[]=[{productId:'p-sofa',label:'Kanapé',href:'/termek/kanape',eligible:true,priceDisplay:'320000 Ft-tól',stockLabel:'Készleten',variants:[{variantId:'sofa-grey',label:'Szürke',eligible:true,channelVisible:true,price:price(320000),stock:{available:true,statusLabel:'Készleten'}},{variantId:'sofa-beige',label:'Bézs',eligible:true,channelVisible:true,price:price(335000),stock:{available:true,statusLabel:'Készleten'}}]},{productId:'p-lamp',label:'Állólámpa',href:'/termek/allolampa',eligible:true,priceDisplay:'79000 Ft',stockLabel:'Készleten',variants:[{variantId:'lamp-black',label:'Fekete',eligible:true,channelVisible:true,price:price(79000),stock:{available:true,statusLabel:'Készleten'}},{variantId:'lamp-brass',label:'Sárgaréz',eligible:true,channelVisible:true,price:price(83000),stock:{available:true,statusLabel:'Készleten'}}]}];

describe('Special Commerce Wave 4 — Room / Scene Composer',()=>{
 it('specializes the existing scene engine instead of creating commerce authority',()=>{expect(ROOM_SCENE_COMPOSER_VERSION).toBe('shoporation.room-scene-composer.v1');expect(Object.values(ROOM_SCENE_COMPOSER_AUTHORITY).every(value=>value===false)).toBe(true);expect(()=>buildRoomSceneComposerReadModel({tenantId:'tenant-1',scene:{...scene,kind:'look'},products})).toThrow('ROOM_SCENE_KIND_REQUIRED');});
 it('maps room hotspots to E4 slots and never guesses among multiple variants',()=>{const model=buildRoomSceneComposerReadModel({tenantId:'tenant-1',scene,products});expect(model.composerConfig.mode).toBe('slots');expect(model.composerConfig.slots?.map(slot=>({id:slot.id,min:slot.minItems,max:slot.maxItems}))).toEqual([{id:'sofa',min:1,max:1},{id:'lamp',min:0,max:1}]);expect(model.slots.find(slot=>slot.hotspotId==='sofa')?.selectedVariantId).toBeNull();expect(model.ready).toBe(false);expect(buildRoomSceneAddIntent('room-cart-1',{tenantId:'tenant-1',scene,products})).toBeNull();});
 it('requires an explicit variant for an included optional multi-variant room item',()=>{const model=buildRoomSceneComposerReadModel({tenantId:'tenant-1',scene,products,selectedVariants:{sofa:'sofa-grey'},includedOptionalHotspotIds:['lamp']});expect(model.ready).toBe(false);expect(model.violations.some(item=>item.code==='ROOM_SCENE_VARIANT_REQUIRED'&&item.path==='hotspot:lamp')).toBe(true);});
 it('produces the existing E4 atomic intent for a valid complete room',()=>{const input={tenantId:'tenant-1',scene,products,selectedVariants:{sofa:'sofa-beige',lamp:'lamp-brass'},includedOptionalHotspotIds:['lamp']} as const;const model=buildRoomSceneComposerReadModel(input);expect(model.ready).toBe(true);expect(model.pricingAuthoritative).toBe(false);expect(model.requiresCartRevalidation).toBe(true);expect(model.subtotalDisplay).toBeTruthy();const intent=buildRoomSceneAddIntent('living-room-cart-1',input);expect(intent?.atomic).toBe(true);expect(intent?.engineVersion).toBe('shoporation.multi-product-composer.v1');expect(intent?.lines.map(line=>[line.productId,line.variantId,line.slotId])).toEqual([['p-sofa','sofa-beige','sofa'],['p-lamp','lamp-brass','lamp']]);expect(intent?.requiredRevalidation).toEqual(['composer-eligibility','channel','price','stock']);expect(intent?.silentReplacementAllowed).toBe(false);});
 it('fails closed when authoritative stock evidence becomes unavailable',()=>{const unavailable=products.map(product=>product.productId!=='p-sofa'?product:{...product,variants:product.variants?.map(variant=>variant.variantId==='sofa-grey'?{...variant,stock:{available:false,statusLabel:'Jelenleg nem készleten'}}:variant)});const model=buildRoomSceneComposerReadModel({tenantId:'tenant-1',scene,products:unavailable,selectedVariants:{sofa:'sofa-grey'}});expect(model.ready).toBe(false);expect(model.violations.some(item=>item.code==='COMPOSER_ITEM_OUT_OF_STOCK')).toBe(true);});
 it('keeps Shop the Room on the existing Pro Interactive Scene entitlement and shared bindings',()=>{const definition=createStorefrontVisualBuilderComponentRegistry().get('commerce.interactive-scene',1)!;expect(definition.manifest.capability).toEqual({minPlan:'pro',features:['catalog','interactiveSceneCommerce']});expect(definition.bindingSlots).toEqual(['tenantId','backgroundImage','products']);expect(STOREFRONT_BUILDER_REGISTRY_VERSION).toBe('shoporation.storefront-builder-registry.special-commerce-v4');expect(STOREFRONT_BUILDER_RENDERER_REGISTRY_VERSION).toBe('shoporation.storefront-builder-renderers.special-commerce-v4');const controls=readFileSync('src/components/admin/storefront-interactive-scene-controls.tsx','utf8');expect(controls).toContain('Kötelező elem a teljes szettben');expect(controls).toContain('Alapértelmezett változat');expect(controls).not.toContain('JSON.stringify');});
 it('binds context identity, channel-visible variants, shared price and stock evidence server-side',()=>{const server=readFileSync('src/lib/builder/storefront-interactive-scene-server.ts','utf8'),runtime=readFileSync('src/lib/builder/storefront-runtime-source.ts','utf8'),builder=readFileSync('src/lib/builder/storefront-builder-server.ts','utf8'),operations=readFileSync('src/lib/builder/storefront-interactive-scene-operations.ts','utf8');expect(server).toContain('product_channel_settings');expect(server).toContain("source:'shared-pricing-authority'");expect(server).toContain('stock:{available:stock>0');expect(runtime).toContain('context:{instanceId}');expect(builder).toContain('context:{instanceId:instance.id}');expect(operations).toContain("tenantId:{path:'context.instanceId'}");});
 it('renders the room specialization from the same Interactive Scene component',()=>{const page:StorefrontPageDocument={schemaVersion:1,pageKey:'room',pageType:'home',templateKey:'test.room',templateVersion:1,sections:[{id:'room-scene',componentKey:'commerce.interactive-scene',componentVersion:1,config:{sceneKey:'living-room-01',sceneKind:'room',title:'Shop the Room',backgroundImage:'/room.jpg',backgroundAlt:'Nappali',hotspots:scene.hotspots,showSetSummary:true,setTitle:'A teljes enteriőr'},bindings:{tenantId:{path:'context.instanceId'},products:{path:'catalog.interactiveSceneProducts'}}}]};const html=renderToStaticMarkup(<StorefrontRuntimeRenderer page={page} viewport="desktop" bindingContext={{context:{instanceId:'tenant-1'},catalog:{interactiveSceneProducts:products}}} componentRegistry={createStorefrontVisualBuilderComponentRegistry()} rendererRegistry={createStorefrontVisualBuilderRendererRegistry()} capability={{plan:'pro',features:PLANS.pro.features}}/>);expect(html).toContain('data-storefront-interactive-scene-v1');expect(html).toContain('data-scene-kind="room"');expect(html).toContain('data-room-scene-composer-v1');expect(html).toContain('Válassz változatot');});
 it('keeps AR/3D and cart persistence outside Wave 4',()=>{const doc=readFileSync('docs/SPECIAL_COMMERCE_WAVE4_ROOM_SCENE.md','utf8');expect(doc).toContain('AR / room placement remains a separate post-launch premium capability');expect(doc).toContain('actual cart consumer/persistence');expect(doc).toContain('Wave 5 — Existing engine closure');});
});
