import {renderToStaticMarkup} from 'react-dom/server';
import {describe,expect,it} from 'vitest';
import {StorefrontRuntimeRenderer} from '@/components/builder/storefront-runtime-renderer';
import {createStorefrontStoryRendererRegistry} from '@/components/builder/storefront-story';
import {createStorefrontStoryComponentRegistry} from '@/lib/builder/storefront-story';
import {PLANS} from '@/lib/plans/catalog';
import {LOOT_VAULT_ENGINE_CONTRACT,LOOT_VAULT_HOME_PAGE,LOOT_VAULT_HOME_SECTION_ORDER,LOOT_VAULT_PRODUCT_PAGE,LOOT_VAULT_RARITY_LEVELS,LOOT_VAULT_TEMPLATE_KEY,LOOT_VAULT_TEMPLATE_PACKAGE,LOOT_VAULT_TEMPLATE_VERSION,LOOT_VAULT_VISUAL_DNA} from '@/lib/builder/templates/loot-vault';
import {evaluateStorefrontTemplateCapabilityGate,planStorefrontTemplateInstallation} from '@/lib/builder/storefront-template-installation';
import {validateStorefrontPageDocument} from '@/lib/builder/storefront-runtime';
const capability={plan:'alap' as const,features:PLANS.alap.features};

describe('Scale-out Wave 20 Loot Vault',()=>{
 it('locks the collector-vault identity and avoids gambling/RGB/scarcity clichés',()=>{expect(LOOT_VAULT_TEMPLATE_KEY).toBe('gaming.loot-vault');expect(LOOT_VAULT_TEMPLATE_VERSION).toBe(1);expect(LOOT_VAULT_VISUAL_DNA.character).toBe('dark-theatrical-collector-vault-commerce');expect(LOOT_VAULT_VISUAL_DNA.exclusions).toEqual(expect.arrayContaining(['rgb-gamer-chaos','loot-box-gambling-ui','fake-scarcity','fake-countdown','collection-tracker-v1']));expect(LOOT_VAULT_RARITY_LEVELS).toEqual(['Common','Rare','Epic','Legendary','Mythic']);});
 it('corrects the historical engine mapping: E9 reorder and E8 context are not Loot Vault v1 dependencies',()=>{expect(LOOT_VAULT_ENGINE_CONTRACT.requiredForFullExperience).toEqual(['E1','E2','E7','E10','E13']);expect(LOOT_VAULT_ENGINE_CONTRACT.explicitlyNotRequired).toEqual(['E8','E9']);expect(LOOT_VAULT_ENGINE_CONTRACT.collectionTracker).toMatch(/deferred/);expect(LOOT_VAULT_ENGINE_CONTRACT.preorderRule).toMatch(/catalog-product-commerce-and-inventory/);});
 it('ships 14 Alap-compatible presets through the shared E7+E10 story registry',()=>{const registry=createStorefrontStoryComponentRegistry();const gate=evaluateStorefrontTemplateCapabilityGate({template:LOOT_VAULT_TEMPLATE_PACKAGE,componentRegistry:registry,capability});expect(gate.violations.filter(x=>x.severity==='error')).toEqual([]);expect(gate.ok).toBe(true);expect(LOOT_VAULT_TEMPLATE_PACKAGE.pages).toHaveLength(14);expect(new Set(LOOT_VAULT_TEMPLATE_PACKAGE.pages.map(x=>x.pageType)).size).toBe(14);for(const page of LOOT_VAULT_TEMPLATE_PACKAGE.pages){const result=validateStorefrontPageDocument(page,registry,capability);expect(result.ok,`${page.pageType}: ${JSON.stringify(result.violations)}`).toBe(true);}});
 it('locks the recovered v1 Home order with Collector Selection as the main commerce area and no Collection Tracker',()=>{expect(LOOT_VAULT_HOME_PAGE.metadata?.sectionOrder).toEqual(LOOT_VAULT_HOME_SECTION_ORDER);expect(LOOT_VAULT_HOME_SECTION_ORDER).toEqual(['Vault Hero','Universe Selector','Limited / Exclusive / Preorder','Collector Selection','Vault Feature','Drop Alert','Join the Hunt','Footer']);expect(LOOT_VAULT_HOME_PAGE.metadata?.largestCommerceSection).toBe('Collector Selection');expect(JSON.stringify(LOOT_VAULT_HOME_PAGE)).not.toMatch(/collection\.tracker|context\.profile-selector|retention\./i);});
 it('renders collector commerce and story surfaces without fabricated scarcity state',()=>{const html=renderToStaticMarkup(<StorefrontRuntimeRenderer page={LOOT_VAULT_HOME_PAGE} viewport="desktop" bindingContext={{brand:{name:'Vault Archive',homeHref:'/',copyright:'© Vault Archive'},navigation:{primary:[],footer:[]},collection:{navigation:[{id:'figures',label:'Figures',href:'/webaruhaz?u=figures'}]},content:{lootHero:{title:'Enter the archive.'},lootDrops:{title:'Limited / Exclusive / Preorder'},lootCollectorSelection:{title:'Collector Selection'},vaultFeature:{title:'Edition Stories'},dropAlert:{title:'Drop Alert'},joinHunt:{title:'Join the Hunt'}},catalog:{featured:[{id:'preorder',name:'Archive Statue',href:'/termek/archive-statue',price:'49 900 Ft',badges:['Preorder']}],products:[{id:'book',name:'Concept Archive',href:'/termek/concept-archive',price:'19 900 Ft'}]}} componentRegistry={createStorefrontStoryComponentRegistry()} rendererRegistry={createStorefrontStoryRendererRegistry()} capability={capability}/>);expect(html).toContain('Enter the archive.');expect(html).toContain('Archive Statue');expect(html).toContain('Preorder');expect(html).toContain('Concept Archive');expect(html).toContain('Edition Stories');expect(html).toContain('Drop Alert');expect(html).toContain('Join the Hunt');});
 it('renders PDP 7/12 + 5/12 with only supplied rarity/edition facts',()=>{const ctx={brand:{name:'Vault Archive',homeHref:'/'},navigation:{primary:[],footer:[]},product:{name:'Archive Statue',description:'Collector object.',gallery:[{src:'https://example.com/statue.jpg',alt:'Archive Statue'}],badges:['Preorder'],keySpecs:[{specKey:'rarity',label:'Rarity',displayValue:'Legendary'},{specKey:'edition',label:'Edition',displayValue:'Numbered'}],specGroups:[{groupKey:'edition',label:'Edition',rows:[{specKey:'numbering',label:'Numbering',displayValue:'12 / 500'},{specKey:'format',label:'Format',displayValue:'Statue'}]}]},variant:{optionLabel:'Változat',optionOptions:[]},pricing:{displayPrice:'49 900 Ft',compareAtPrice:''},inventory:{stockLabel:'Előrendelhető'},commerce:{purchaseLabel:'Előrendelés',purchaseHref:'#preorder'},content:{productStory:{title:'The object behind the edition.'}},recommendations:{products:[]}};const desktop=renderToStaticMarkup(<StorefrontRuntimeRenderer page={LOOT_VAULT_PRODUCT_PAGE} viewport="desktop" bindingContext={ctx} componentRegistry={createStorefrontStoryComponentRegistry()} rendererRegistry={createStorefrontStoryRendererRegistry()} capability={capability}/>);const mobile=renderToStaticMarkup(<StorefrontRuntimeRenderer page={LOOT_VAULT_PRODUCT_PAGE} viewport="mobile" bindingContext={ctx} componentRegistry={createStorefrontStoryComponentRegistry()} rendererRegistry={createStorefrontStoryRendererRegistry()} capability={capability}/>);expect(desktop).toContain('span 7 / span 7');expect(desktop).toContain('span 5 / span 5');expect(mobile).toContain('span 12 / span 12');expect(desktop).toContain('Legendary');expect(desktop).toContain('12 / 500');expect(desktop).toContain('Előrendelhető');expect(desktop).toContain('Előrendelés');});
 it('keeps demo/install safety free from fake scarcity, rarity, preorder and tracker authority',()=>{const demo=JSON.stringify(LOOT_VAULT_TEMPLATE_PACKAGE.demoFixtures??[]);expect(demo).not.toMatch(/rarity|legendary|exclusive|limited|numbered|preorderDate|releaseDate|stockCount|countdown|collectionTracker|odds|lootBox/i);const plan=planStorefrontTemplateInstallation({template:LOOT_VAULT_TEMPLATE_PACKAGE,componentRegistry:createStorefrontStoryComponentRegistry(),capability});expect(plan.mode).toBe('install');expect(plan.pages).toHaveLength(14);expect(plan.mutationBoundary).toMatchObject({storefrontPageDrafts:true,products:false,variants:false,customers:false,orders:false,b2b:false});expect(plan.demoLifecycle.install.every(x=>x.namespace==='gaming-loot-vault')).toBe(true);});
 it('keeps E13 checkout provider-neutral',()=>{const checkout=LOOT_VAULT_TEMPLATE_PACKAGE.pages.find(x=>x.pageType==='checkout')!;expect(checkout.metadata?.engineBinding).toBe('E13');expect(JSON.stringify(checkout)).not.toMatch(/K&H|khpos|vpos|payment_secret|merchantId/i);});
});
