import type { Cart,CartItem } from '@/lib/cart/types';

export type CommerceQuote={productId:string;variantId?:string|null;slug:string;name:string;unitPrice:number;availableQuantity:number;purchasable:boolean;image?:string;minimumQuantity?:number;orderMultiple?:number};
export type CartValidationIssue={productId:string;code:'unavailable'|'price_changed'|'quantity_reduced'|'missing';message:string};
export type CartValidationResult={cart:Cart;issues:CartValidationIssue[];changed:boolean};

export const cartLineKey=(item:Pick<CartItem,'productId'|'variantId'>)=>`${item.productId}:${item.variantId??'default'}`;
export const normalizeOrderMultiple=(value=1)=>Number.isFinite(value)&&value>0?Math.max(1,Math.floor(value)):1;
export const normalizeMinimumQuantity=(minimum=1,multiple=1)=>{const step=normalizeOrderMultiple(multiple),min=Number.isFinite(minimum)&&minimum>0?Math.max(1,Math.floor(minimum)):1;return Math.ceil(min/step)*step};
export function normalizeQuantity(value:number,max?:number,minimum=1,multiple=1){const step=normalizeOrderMultiple(multiple),min=normalizeMinimumQuantity(minimum,step),raw=Math.max(min,Math.floor(Number.isFinite(value)?value:min));let quantity=Math.ceil(raw/step)*step;if(typeof max==='number'){const cap=Math.floor(Math.max(0,max)/step)*step;if(cap<min)return 0;quantity=Math.min(quantity,cap)}return quantity}
export function normalizeCartItem(item:CartItem):CartItem{const minimum=normalizeMinimumQuantity(item.minimumQuantity??1,item.orderMultiple??1);return{...item,unitPrice:Math.max(0,Number.isFinite(item.unitPrice)?item.unitPrice:0),minimumQuantity:minimum,orderMultiple:normalizeOrderMultiple(item.orderMultiple??1),quantity:normalizeQuantity(item.quantity,undefined,minimum,item.orderMultiple??1)}}
export function mergeCartItem(items:CartItem[],incoming:CartItem):CartItem[]{const normalized=normalizeCartItem(incoming),key=cartLineKey(normalized),existing=items.find(item=>cartLineKey(item)===key);if(!existing)return[...items,normalized];return items.map(item=>cartLineKey(item)===key?{...item,minimumQuantity:normalized.minimumQuantity,orderMultiple:normalized.orderMultiple,quantity:normalizeQuantity(item.quantity+normalized.quantity,undefined,normalized.minimumQuantity,normalized.orderMultiple)}:item)}
export function validateCartAgainstQuotes(cart:Cart,quotes:CommerceQuote[]):CartValidationResult{const quoteMap=new Map(quotes.map(quote=>[`${quote.productId}:${quote.variantId??'default'}`,quote])),issues:CartValidationIssue[]=[],items:CartItem[]=[];for(const item of cart.items){const quote=quoteMap.get(cartLineKey(item));if(!quote){issues.push({productId:item.productId,code:'missing',message:`${item.name} már nem található a katalógusban.`});continue}const minimum=normalizeMinimumQuantity(quote.minimumQuantity??item.minimumQuantity??1,quote.orderMultiple??item.orderMultiple??1),multiple=normalizeOrderMultiple(quote.orderMultiple??item.orderMultiple??1);if(!quote.purchasable||quote.availableQuantity<minimum){issues.push({productId:item.productId,code:'unavailable',message:`${quote.name} jelenleg nem rendelhető a szükséges minimum mennyiségben.`});continue}const quantity=normalizeQuantity(item.quantity,quote.availableQuantity,minimum,multiple);if(quantity!==item.quantity)issues.push({productId:item.productId,code:'quantity_reduced',message:`${quote.name} mennyiségét a rendelési szabályokhoz és az elérhető készlethez igazítottuk.`});if(quote.unitPrice!==item.unitPrice)issues.push({productId:item.productId,code:'price_changed',message:`${quote.name} ára megváltozott; a kosarat az aktuális árra frissítettük.`});if(quantity>0)items.push({...item,slug:quote.slug,name:quote.name,unitPrice:quote.unitPrice,quantity,image:quote.image??item.image,minimumQuantity:minimum,orderMultiple:multiple})}return{cart:{items},issues,changed:issues.length>0}}
