import 'server-only';
export type ProviderRequirement={key:string;label:string;secret:boolean};export type ProviderGuide={contract:string;requirements:ProviderRequirement[];verification:string;notes?:string};
const guides:Record<string,ProviderGuide>={
 external_logistics:{contract:'Nincs szükség közvetlen futárcéges API-szerződésre. A webshop a külső logisztikai partnerrel áll szerződésben vagy operatív kapcsolatban.',requirements:[],verification:'Érvényes partner e-mail cím szükséges. A Shoperation naplózott rendelési értesítést küld a partnernek, a futárfoglalást a partner végzi.'},
 kh_card:{contract:'Aktív K&H vPOS/eAPI elfogadói szerződés és aktivált vPOS szükséges.',requirements:[{key:'KH_VPOS_ID',label:'vPOS ID / merchantId',secret:false},{key:'KH_PRIVATE_KEY',label:'Kereskedői RSA privát aláíró kulcs',secret:true},{key:'KH_GATEWAY_PUBLIC_KEY',label:'K&H gateway RSA publikus kulcs',secret:false},{key:'KH_ENVIRONMENT',label:'Környezet (sandbox vagy live)',secret:false}],verification:'A Shoperation SHA256withRSA aláírással ECHO kapcsolatpróbát végez. A fizetés csak sikeres banki aláírás-ellenőrzés és státuszlekérdezés mellett aktiválható.',notes:'A K&H eAPI merchantId mezőjéhez a vPOS ID tartozik. A privát kulcs kizárólag szerveroldali titok; a MID-et ne írd a KH_VPOS_ID mezőbe.'},
 stripe:{contract:'Aktív Stripe kereskedői fiók. Külön Shoperation-szerződés nem szükséges.',requirements:[{key:'STRIPE_SECRET_KEY',label:'Secret key',secret:true},{key:'STRIPE_WEBHOOK_SECRET',label:'Webhook signing secret',secret:true}],verification:'Szerveroldali Stripe API-kapcsolat és webhook aláírás ellenőrzése.'},
 simplepay:{contract:'OTP SimplePay kereskedői szerződés és éles merchant hozzáférés.',requirements:[{key:'SIMPLEPAY_MERCHANT',label:'Merchant azonosító',secret:false},{key:'SIMPLEPAY_SECRET_KEY',label:'Titkos kulcs',secret:true}],verification:'Merchant konfiguráció és SimplePay API-kapcsolat ellenőrzése.'},
 barion:{contract:'Aktív Barion shop szükséges. A webshop közvetlenül a Barionnal szerződik.',requirements:[{key:'BARION_POS_KEY',label:'Titkos POSKey',secret:true},{key:'BARION_PAYEE_EMAIL',label:'Barion shop / kedvezményezett e-mail',secret:false}],verification:'A Shoperation ellenőrzi a Barion API elérését. A callback után a fizetési státuszt a Barion PaymentState API-ból kérjük vissza.'},
 foxpost:{contract:'Aktív FOXPOST üzleti szerződés/API-hozzáférés az automatizált feladáshoz.',requirements:[{key:'FOXPOST_API_KEY',label:'API kulcs',secret:true}],verification:'A szolgáltatói adapter csak hiteles partneri API-kapcsolat után aktiválható.'},
 gls:{contract:'Aktív GLS üzleti szerződés és API-hozzáférés.',requirements:[{key:'GLS_USERNAME',label:'API felhasználó',secret:false},{key:'GLS_PASSWORD',label:'API jelszó',secret:true},{key:'GLS_CLIENT_NUMBER',label:'Ügyfélszám',secret:false}],verification:'GLS hitelesítés és szállítási API-kapcsolat ellenőrzése.'},
 mpl:{contract:'Aktív MPL üzleti szerződés/API-hozzáférés az automatizált feladáshoz.',requirements:[{key:'MPL_API_KEY',label:'API hozzáférés',secret:true}],verification:'MPL API-hozzáférés ellenőrzése.'},
 dpd:{contract:'Aktív DPD üzleti szerződés és partneri API/webservice hozzáférés.',requirements:[{key:'DPD_USERNAME',label:'API felhasználó',secret:false},{key:'DPD_PASSWORD',label:'API jelszó',secret:true}],verification:'Csak partneri specifikáció szerinti sikeres teszt után aktiválható.',notes:'Partneri specifikáció nélkül a kapcsolat fail-closed marad.'},
 packeta:{contract:'Aktív Packeta ügyfélfiók szükséges.',requirements:[{key:'PACKETA_API_PASSWORD',label:'API password · csomagfeladáshoz',secret:true},{key:'PACKETA_WIDGET_API_KEY',label:'Widget/API key · csomagpontlistához',secret:true},{key:'PACKETA_SENDER',label:'Feladó / e-shop azonosító',secret:false}],verification:'A Shoperation a Packeta v5 pickup feedet, v6 kiválasztás-validációt és REST/XML createPacket folyamatot használja.',notes:'A Packeta külön kezeli az API Passwordöt és a Widget/API Keyt. A böngésző egyik értéket sem kapja meg: a csomagpontlista a Shoperation szerveroldali végpontján keresztül érkezik.'},
 expressone:{contract:'Aktív Express One üzleti szerződés és webservice hozzáférés szükséges.',requirements:[{key:'EXPRESSONE_API_KEY',label:'Partneri API/webservice hozzáférés',secret:true}],verification:'Partneri specifikáció szerinti sikeres teszt után aktiválható.'},
 szamlazz:{contract:'Aktív Számlázz.hu fiók és Számla Agent hozzáférés szükséges.',requirements:[{key:'SZAMLAZZ_AGENT_KEY',label:'Számla Agent kulcs',secret:true},{key:'SZAMLAZZ_CONNECTION_VERIFIED',label:'Szerveroldali kapcsolat engedélyezve',secret:false}],verification:'A Shoperation szerveroldalon ellenőrzi az Agent kulcsot egy nem létező külső számlaazonosító lekérdezésével. A teszt nem hoz létre számlát.',notes:'Az Agent kulcs kizárólag szerveroldali titok. A kapcsolat csak sikeres API-ellenőrzés után aktiválható.'}
};
export function getProviderGuide(code:string,connectionMode:string):ProviderGuide{if(guides[code])return guides[code];if(code.startsWith('external_'))return guides.external_logistics;if(connectionMode==='manual')return{contract:'Ehhez a módhoz nincs kötelező API-szerződés a Shoperationben.',requirements:[],verification:'A mód adminisztratív aktiválása elegendő.'};return{contract:'A választott szolgáltatóval közvetlenül kell szerződni vagy API-hozzáférést kérni.',requirements:[],verification:'Az adapterhez szükséges hitelesítő adatok és egy sikeres kapcsolatpróba szükséges.'}}
export function configuredEnvironmentFields(requirements:ProviderRequirement[]){return requirements.filter(item=>Boolean(process.env[item.key])).map(item=>item.key)}
