import {COMPATIBILITY_ENGINE_VERSION,evaluateCompatibility,type CompatibilityEvaluation,type CompatibilityPart,type CompatibilityRule} from '@/lib/commerce/compatibility-engine';

export const PRODUCT_CONFIGURATOR_ENGINE_VERSION='shoporation.product-configurator.v1' as const;
export type ConfiguratorPriceEvidence={amountMinor:number;currency:string;display:string;source:'shared-pricing-authority'};
export type ConfiguratorStockEvidence={available:boolean;label:string};
export type ConfiguratorSlot={id:string;label:string;required:boolean;eligibleProductIds?:readonly string[]};
export type ProductConfiguratorConfig={version:1;tenantId:string;configuratorKey:string;label:string;slots:readonly ConfiguratorSlot[]};
export type ConfiguratorCatalogPart={productId:string;variantId:string;label:string;href:string;slotIds:readonly string[];eligible:boolean;channelVisible:boolean;price:ConfiguratorPriceEvidence;stock:ConfiguratorStockEvidence;compatibility:CompatibilityPart['specs']};
export type ConfiguratorSelection={slotId:string;productId:string;variantId:string};
export type ConfiguratorViolation={code:string;path:string;message:string};
export type ConfiguratorReadModel={status:'incomplete'|'ready'|'incompatible'|'unknown'|'invalid';selections:Array<{selection:ConfiguratorSelection;part:ConfiguratorCatalogPart}>;missingRequiredSlots:string[];compatibility:CompatibilityEvaluation|null;currentSubtotalMinor:number|null;currency:string|null;pricingAuthoritative:false;compatibilityAuthoritative:false;requiresServerRevalidation:true;violations:ConfiguratorViolation[]};
export type ConfiguratorCartIntent={engineVersion:typeof PRODUCT_CONFIGURATOR_ENGINE_VERSION;compatibilityEngineVersion:typeof COMPATIBILITY_ENGINE_VERSION;operation:'add'|'replace';atomic:true;configurationId:string;configuratorKey:string;configuratorVersion:1;lines:Array<{slotId:string;productId:string;variantId:string;quantity:1;configurationId:string}>;requiredRevalidation:readonly ['configurator-eligibility','compatibility','channel','price','stock'];pricingAuthority:'shared-pricing-authority';compatibilityAuthority:'server-authoritative-final-validation';silentReplacementAllowed:false};

const KEY=/^[a-z0-9]+(?:[._-][a-z0-9]+)*$/;const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;const safeHref=(value:string)=>value.startsWith('/')||value.startsWith('#')||value.startsWith('https://');const issue=(out:ConfiguratorViolation[],code:string,path:string,message:string)=>out.push({code,path,message});
export function validateProductConfiguratorConfig(config:ProductConfiguratorConfig):ConfiguratorViolation[]{const out:ConfiguratorViolation[]=[];if(config.version!==1)issue(out,'CONFIGURATOR_VERSION_UNSUPPORTED','version','Only Product Configurator v1 is supported.');if(!KEY.test(config.tenantId)||!KEY.test(config.configuratorKey))issue(out,'CONFIGURATOR_IDENTITY_INVALID','identity','Tenant and configurator keys must be lowercase and key-safe.');if(!config.label.trim())issue(out,'CONFIGURATOR_LABEL_REQUIRED','label','Configurator label is required.');if(!config.slots.length)issue(out,'CONFIGURATOR_SLOTS_REQUIRED','slots','At least one slot is required.');const seen=new Set<string>();config.slots.forEach((slot,index)=>{const path=`slots.${index}`;if(!KEY.test(slot.id)||seen.has(slot.id))issue(out,'CONFIGURATOR_SLOT_ID_INVALID',`${path}.id`,'Slot id must be unique and key-safe.');seen.add(slot.id);if(!slot.label.trim())issue(out,'CONFIGURATOR_SLOT_LABEL_REQUIRED',`${path}.label`,'Slot label is required.');if(slot.eligibleProductIds&&new Set(slot.eligibleProductIds).size!==slot.eligibleProductIds.length)issue(out,'CONFIGURATOR_SLOT_ELIGIBILITY_DUPLICATE',`${path}.eligibleProductIds`,'Eligible product ids must be unique.');});return out;}
function findPart(catalog:readonly ConfiguratorCatalogPart[],selection:ConfiguratorSelection){return catalog.find(part=>part.productId===selection.productId&&part.variantId===selection.variantId);}
export function validateConfiguratorSelections(input:{config:ProductConfiguratorConfig;selections:readonly ConfiguratorSelection[];catalog:readonly ConfiguratorCatalogPart[]}):ConfiguratorViolation[]{const out=validateProductConfiguratorConfig(input.config);if(out.length)return out;const slotsSeen=new Set<string>();input.selections.forEach((selection,index)=>{const path=`selections.${index}`;if(!KEY.test(selection.slotId)||!ID.test(selection.productId)||!ID.test(selection.variantId))issue(out,'CONFIGURATOR_SELECTION_ID_INVALID',path,'Selection identifiers are invalid.');if(slotsSeen.has(selection.slotId))issue(out,'CONFIGURATOR_SLOT_DUPLICATE_SELECTION',path,'A slot can contain only one selected part in v1.');slotsSeen.add(selection.slotId);const slot=input.config.slots.find(candidate=>candidate.id===selection.slotId);if(!slot){issue(out,'CONFIGURATOR_SLOT_UNKNOWN',`${path}.slotId`,'Selected slot does not exist.');return;}const part=findPart(input.catalog,selection);if(!part){issue(out,'CONFIGURATOR_PART_NOT_FOUND',path,'Selected part is unavailable.');return;}if(!safeHref(part.href))issue(out,'CONFIGURATOR_PART_HREF_UNSAFE',path,'Selected part href is unsafe.');if(!part.slotIds.includes(slot.id))issue(out,'CONFIGURATOR_PART_SLOT_INELIGIBLE',path,'Selected part is not eligible for this slot.');if(slot.eligibleProductIds&&!slot.eligibleProductIds.includes(part.productId))issue(out,'CONFIGURATOR_SLOT_PRODUCT_INELIGIBLE',path,'Selected product is not allowed in this slot.');if(!part.eligible)issue(out,'CONFIGURATOR_PART_INELIGIBLE',path,'Selected part is not currently eligible.');if(!part.channelVisible)issue(out,'CONFIGURATOR_PART_CHANNEL_HIDDEN',path,'Selected part is hidden in the active commerce channel.');if(!part.stock.available)issue(out,'CONFIGURATOR_PART_OUT_OF_STOCK',path,'Selected part is currently unavailable.');if(!Number.isInteger(part.price.amountMinor)||part.price.amountMinor<0||!part.price.currency.trim()||part.price.source!=='shared-pricing-authority')issue(out,'CONFIGURATOR_PRICE_EVIDENCE_INVALID',path,'Price evidence must come from the shared pricing authority.');});return out;}
export function buildConfiguratorReadModel(input:{config:ProductConfiguratorConfig;selections:readonly ConfiguratorSelection[];catalog:readonly ConfiguratorCatalogPart[];compatibilityRules:readonly CompatibilityRule[]}):ConfiguratorReadModel{const violations=validateConfiguratorSelections(input);const rows=input.selections.flatMap(selection=>{const part=findPart(input.catalog,selection);return part?[{selection:{...selection},part}]:[];});const selectedSlots=new Set(input.selections.map(selection=>selection.slotId));const missingRequiredSlots=input.config.slots.filter(slot=>slot.required&&!selectedSlots.has(slot.id)).map(slot=>slot.id);const parts:CompatibilityPart[]=rows.map(({selection,part})=>({slotId:selection.slotId,productId:part.productId,variantId:part.variantId,label:part.label,specs:part.compatibility}));const compatibility=evaluateCompatibility({rules:input.compatibilityRules,parts});if(!compatibility)issue(violations,'CONFIGURATOR_COMPATIBILITY_RULES_INVALID','compatibility','Compatibility rules are invalid.');const currencies=new Set(rows.map(row=>row.part.price.currency));if(currencies.size>1)issue(violations,'CONFIGURATOR_CURRENCY_MISMATCH','pricing','Selected parts must use one currency.');let status:ConfiguratorReadModel['status']='invalid';if(!violations.length){if(missingRequiredSlots.length)status='incomplete';else if(compatibility?.status==='incompatible')status='incompatible';else if(compatibility?.status==='unknown'||!compatibility)status='unknown';else status='ready';}return{status,selections:rows,missingRequiredSlots,compatibility,currentSubtotalMinor:currencies.size===1?rows.reduce((sum,row)=>sum+row.part.price.amountMinor,0):null,currency:currencies.size===1?[...currencies][0]??null:null,pricingAuthoritative:false,compatibilityAuthoritative:false,requiresServerRevalidation:true,violations};}
function intent(operation:'add'|'replace',configurationId:string,input:{config:ProductConfiguratorConfig;selections:readonly ConfiguratorSelection[];catalog:readonly ConfiguratorCatalogPart[];compatibilityRules:readonly CompatibilityRule[]}):ConfiguratorCartIntent|null{if(!KEY.test(configurationId))return null;const model=buildConfiguratorReadModel(input);if(model.status!=='ready')return null;return{engineVersion:PRODUCT_CONFIGURATOR_ENGINE_VERSION,compatibilityEngineVersion:COMPATIBILITY_ENGINE_VERSION,operation,atomic:true,configurationId,configuratorKey:input.config.configuratorKey,configuratorVersion:input.config.version,lines:input.selections.map(selection=>({...selection,quantity:1 as const,configurationId})),requiredRevalidation:['configurator-eligibility','compatibility','channel','price','stock'],pricingAuthority:'shared-pricing-authority',compatibilityAuthority:'server-authoritative-final-validation',silentReplacementAllowed:false};}
export function buildConfiguratorAddIntent(configurationId:string,input:{config:ProductConfiguratorConfig;selections:readonly ConfiguratorSelection[];catalog:readonly ConfiguratorCatalogPart[];compatibilityRules:readonly CompatibilityRule[]}){return intent('add',configurationId,input);}export function buildConfiguratorEditIntent(configurationId:string,input:{config:ProductConfiguratorConfig;selections:readonly ConfiguratorSelection[];catalog:readonly ConfiguratorCatalogPart[];compatibilityRules:readonly CompatibilityRule[]}){return intent('replace',configurationId,input);}
export const PRODUCT_CONFIGURATOR_TEMPLATE_SWITCH_MUTATION_BOUNDARY=Object.freeze({storefrontPageDrafts:true,configuratorConfiguration:false,compatibilityRules:false,products:false,variants:false,pricing:false,inventory:false,carts:false,customers:false,orders:false} as const);
