'use client';
import{useState}from'react';
import{useRouter}from'next/navigation';

async function act(body:unknown){const r=await fetch('/api/admin/commercial/actions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error??'A művelet sikertelen.');return p}
export function CommercialRefresh(){const[b,setB]=useState(false),[m,setM]=useState('');const r=useRouter();return <div><button className="btn btnPrimary" disabled={b} onClick={async()=>{setB(true);setM('');try{await act({action:'refresh'});setM('Lehetőségek és feladatok frissítve.');r.refresh()}catch(e){setM(e instanceof Error?e.message:'Hiba.')}finally{setB(false)}}}>{b?'Frissítés…':'Értékesítési lehetőségek frissítése'}</button>{m&&<span className="helperText" role="status"> {m}</span>}</div>}
export function OpportunityActions({id}:{id:string}){const[b,setB]=useState(false),[m,setM]=useState('');const r=useRouter();async function go(status:string){setB(true);setM('');try{await act({action:'opportunity',id,status});r.refresh()}catch(e){setM(e instanceof Error?e.message:'A módosítás nem sikerült.')}finally{setB(false)}}return <div><div className="adminInlineActions"><button className="btn" disabled={b} onClick={()=>go('in_progress')}>Kezelés megkezdése</button><button className="btn" disabled={b} onClick={()=>go('won')}>Megnyert</button><button className="btn" disabled={b} onClick={()=>go('lost')}>Elvesztett</button></div>{m&&<span className="helperText" role="status">{m}</span>}</div>}
export function OfferCreate({opportunityId,variants}:{opportunityId:string;variants:{id:string;sku:string;label:string}[]}){const[b,setB]=useState(false),[m,setM]=useState('');const r=useRouter();async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setB(true);setM('');try{await act({action:'create_offer',opportunityId,variantId:String(f.get('variantId')),quantity:Number(f.get('quantity')),discountPercent:Number(f.get('discountPercent')),minimumMarginPercent:Number(f.get('minimumMarginPercent'))});setM('Ajánlattervezet létrehozva.');r.refresh()}catch(e){setM(e instanceof Error?e.message:'Hiba.')}finally{setB(false)}}return <details><summary className="btn">Ajánlat készítése</summary><form onSubmit={submit}><label>Termékváltozat<select name="variantId" required defaultValue=""><option value="" disabled>Válassz terméket</option>{variants.map(v=><option key={v.id} value={v.id}>{v.sku} · {v.label}</option>)}</select></label><label>Mennyiség<input name="quantity" type="number" min="1" defaultValue="1" required/></label><label>Kedvezmény (%)<input name="discountPercent" type="number" min="0" max="100" step="0.1" defaultValue="0" required/></label><label>Elvárt minimum árrés (%)<input name="minimumMarginPercent" type="number" min="0" max="100" step="0.1" defaultValue="20" required/></label><button className="btn btnPrimary" disabled={b}>{b?'Mentés…':'Ajánlattervezet létrehozása'}</button>{m&&<span className="helperText" role="status">{m}</span>}</form></details>}
export function TaskActions({id}:{id:string}){const[b,setB]=useState(false),[m,setM]=useState('');const r=useRouter();return <span><button className="btn" disabled={b} onClick={async()=>{setB(true);setM('');try{await act({action:'task',id,status:'completed',outcome:'Admin felületen lezárva'});r.refresh()}catch(e){setM(e instanceof Error?e.message:'A feladat lezárása nem sikerült.')}finally{setB(false)}}}>Feladat lezárása</button>{m&&<small className="helperText" role="status"> {m}</small>}</span>}
export function OfferActions({id,status}:{id:string;status:string}){const[b,setB]=useState(false),[m,setM]=useState('');const r=useRouter();async function run(body:unknown){setB(true);setM('');try{await act(body);r.refresh()}catch(e){setM(e instanceof Error?e.message:'Műveleti hiba.')}finally{setB(false)}}return <div><div className="adminInlineActions">{status==='draft'&&<button className="btn" disabled={b} onClick={()=>run({action:'approve_offer',id})}>Árrés ellenőrzése és jóváhagyás</button>}{status==='approved'&&<button className="btn" disabled={b} onClick={()=>run({action:'offer_status',id,status:'sent'})}>Kiküldöttnek jelölés</button>}{['approved','sent'].includes(status)&&<button className="btn" disabled={b} onClick={()=>run({action:'offer_status',id,status:'accepted'})}>Elfogadottnak jelölés</button>}{['draft','approved','sent'].includes(status)&&<button className="btn" disabled={b} onClick={()=>run({action:'offer_status',id,status:'cancelled'})}>Ajánlat törlése</button>}</div>{m&&<span className="helperText" role="status">{m}</span>}</div>}
