'use client';
import{useState}from'react';import{useRouter}from'next/navigation';

async function jsonPost(url:string,body?:unknown){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error??'A művelet nem sikerült.');return j}

export function ControlCycleButton(){const[busy,setBusy]=useState(false);const router=useRouter();return <button className="btn" disabled={busy} onClick={async()=>{setBusy(true);try{await jsonPost('/api/admin/control-tower/run');router.refresh()}catch(e){alert(e instanceof Error?e.message:'A kontrollciklus nem sikerült.')}finally{setBusy(false)}}}>{busy?'Elemzés…':'Kontrollciklus futtatása'}</button>}

export function AlertActions({alertId,status}:{alertId:string;status:string}){const[busy,setBusy]=useState(false);const router=useRouter();async function go(targetStatus:string,snoozeHours?:number){setBusy(true);try{await jsonPost('/api/admin/control-tower/alert',{alertId,targetStatus,snoozeHours});router.refresh()}catch(e){alert(e instanceof Error?e.message:'A riasztás módosítása nem sikerült.')}finally{setBusy(false)}}return <div className="actions">{status==='open'&&<button className="btn btnGhost" disabled={busy} onClick={()=>go('acknowledged')}>Átvettem</button>}{['open','acknowledged'].includes(status)&&<button className="btn btnGhost" disabled={busy} onClick={()=>go('snoozed',4)}>4 órára halasztás</button>}{['open','acknowledged','snoozed'].includes(status)&&<button className="btn btnGhost" disabled={busy} onClick={()=>go('resolved')}>Megoldottnak jelölés</button>}{['open','acknowledged','snoozed'].includes(status)&&<button className="btn btnGhost" disabled={busy} onClick={()=>go('dismissed')}>Elvetés</button>}</div>}

export function TaskActions({taskId,status}:{taskId:string|null;status:string|null}){const[busy,setBusy]=useState(false);const router=useRouter();if(!taskId||!status)return null;async function go(targetStatus:string){let outcome:string|undefined;if(targetStatus==='completed'){outcome=window.prompt('Röviden írd le a döntést / eredményt:')?.trim();if(!outcome)return}setBusy(true);try{await jsonPost('/api/admin/control-tower/task',{taskId,targetStatus,outcome});router.refresh()}catch(e){alert(e instanceof Error?e.message:'A feladat módosítása nem sikerült.')}finally{setBusy(false)}}return <div className="actions">{status==='open'&&<button className="btn btnGhost" disabled={busy} onClick={()=>go('in_progress')}>Kezdem</button>}{['open','in_progress'].includes(status)&&<button className="btn btnGhost" disabled={busy} onClick={()=>go('completed')}>Lezárás</button>}</div>}
