'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

export type CouponRow={id:string;code:string;description:string|null;discount_type:'percent'|'fixed';discount_value:number;min_subtotal_huf:number;max_discount_huf:number|null;usage_limit:number|null;usage_count:number;starts_at:string|null;ends_at:string|null;active:boolean};

export function CouponCreateForm(){
  const router=useRouter(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const fd=new FormData(event.currentTarget);const body={code:String(fd.get('code')??''),description:String(fd.get('description')??''),discountType:String(fd.get('discountType')??'percent'),discountValue:Number(fd.get('discountValue')),minSubtotalHuf:Number(fd.get('minSubtotalHuf')||0),maxDiscountHuf:fd.get('maxDiscountHuf')?Number(fd.get('maxDiscountHuf')):null,usageLimit:fd.get('usageLimit')?Number(fd.get('usageLimit')):null,startsAt:fd.get('startsAt')?new Date(String(fd.get('startsAt'))).toISOString():null,endsAt:fd.get('endsAt')?new Date(String(fd.get('endsAt'))).toISOString():null};try{const r=await fetch('/api/admin/coupons',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const p=await r.json();if(!r.ok){setMessage(p.error??'Nem sikerült létrehozni a kupont.');return;}event.currentTarget.reset();setMessage('Kupon létrehozva.');router.refresh();}catch{setMessage('Hálózati hiba.');}finally{setBusy(false)}}
  return <form className="card" onSubmit={submit}><div className="adminToolbar"><h2>Új kupon</h2><span className="badge">Szerveroldali validáció</span></div><div className="form-grid"><input name="code" required minLength={3} maxLength={32} placeholder="Kód, pl. KEDVEZMENY10"/><input name="description" placeholder="Belső leírás"/><select name="discountType" defaultValue="percent"><option value="percent">Százalékos (%)</option><option value="fixed">Fix összeg (Ft)</option></select><input name="discountValue" type="number" min="1" required placeholder="Kedvezmény értéke"/><input name="minSubtotalHuf" type="number" min="0" defaultValue="0" placeholder="Minimum kosárérték"/><input name="maxDiscountHuf" type="number" min="1" placeholder="Max. kedvezmény (opcionális)"/><input name="usageLimit" type="number" min="1" placeholder="Felhasználási limit"/><label>Kezdés<input name="startsAt" type="datetime-local"/></label><label>Lejárat<input name="endsAt" type="datetime-local"/></label></div><button className="btn btnPrimary" disabled={busy}>{busy?'Mentés…':'Kupon létrehozása'}</button>{message&&<p className="helperText">{message}</p>}</form>;
}

export function CouponToggle({coupon}:{coupon:CouponRow}){const router=useRouter();const[busy,setBusy]=useState(false),[message,setMessage]=useState('');async function toggle(){if(busy)return;if(coupon.active&&!window.confirm(`Biztosan kikapcsolod a(z) ${coupon.code} kupont?`))return;setBusy(true);setMessage('');try{const response=await fetch('/api/admin/coupons',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:coupon.id,active:!coupon.active})});const payload=await response.json().catch(()=>({}))as{error?:string};if(!response.ok){setMessage(payload.error??'A kupon módosítása nem sikerült.');return}router.refresh()}catch{setMessage('Hálózati hiba. A kupon állapotát nem tekintjük módosítottnak.')}finally{setBusy(false)}}return <span><button className="btn btnGhost" type="button" onClick={toggle} disabled={busy}>{busy?'…':coupon.active?'Kikapcsolás':'Aktiválás'}</button>{message&&<small className="helperText" role="status"> {message}</small>}</span>}
