'use client';

import {useMemo,useState,useTransition} from 'react';
import {deleteExistingCommerceEngineAction,saveComposerAction,saveConfiguratorAction,saveGuidedFinderAction} from '@/app/admin/tartalom/commerce-engines/actions';

type RecordRow={id:string;engineKind:'guided_finder'|'multi_product_composer'|'product_configurator';configKey:string;label:string};
type Attribute={key:string;label:string};
const lines=(value:string)=>value.split('\n').map(line=>line.trim()).filter(Boolean);
const split=(value:string)=>value.split('|').map(part=>part.trim());
const kindLabel=(kind:RecordRow['engineKind'])=>kind==='guided_finder'?'Guided Finder':kind==='multi_product_composer'?'Multi-Product Composer':'Product Configurator + Compatibility';
export function ExistingCommerceEngineLibrary({initialRecords,attributes}:{initialRecords:readonly RecordRow[];attributes:readonly Attribute[]}){
  const[pending,startTransition]=useTransition(),[message,setMessage]=useState(''),[error,setError]=useState('');
  const[finder,setFinder]=useState({key:'product-finder',label:'Termékkereső',question:'Mi a legfontosabb szempont?',attribute:attributes[0]?.key??'',options:'Otthon = otthon\nMunka = munka'});
  const[composer,setComposer]=useState({key:'build-a-box',label:'Saját csomag',mode:'pool' as'pool'|'slots',min:2,max:6,duplicate:3,slots:'alap | Alap | 1 | 3\nkiegeszito | Kiegészítő | 1 | 3'});
  const[configurator,setConfigurator]=useState({key:'product-configurator',label:'Termék konfigurátor',slots:'fo | Fő komponens | igen\nkiegeszito | Kiegészítő | igen',ruleLabel:'Kompatibilitás',left:'fo',right:'kiegeszito',attribute:attributes[0]?.key??''});
  const byKind=useMemo(()=>({guided_finder:initialRecords.filter(row=>row.engineKind==='guided_finder'),multi_product_composer:initialRecords.filter(row=>row.engineKind==='multi_product_composer'),product_configurator:initialRecords.filter(row=>row.engineKind==='product_configurator')}),[initialRecords]);
  const run=(action:()=>Promise<unknown>,success:string)=>{setError('');setMessage('');startTransition(()=>{void action().then(()=>{setMessage(success);window.location.reload();}).catch(reason=>setError(reason instanceof Error?reason.message:'A művelet nem sikerült.'));});};
  return <div style={{display:'grid',gap:24,marginTop:24}} data-existing-commerce-engine-library-v1>
    {(message||error)?<div className={error?'errorNotice':'card'} role="status">{error||message}</div>:null}
    <section className="card"><span className="eyebrow">Aktív konfigurációk</span><h2>Meglévő motorok</h2><p className="muted">A kulcsot a Visual Builder választja ki. A konfiguráció nem tartalmaz ár-, készlet- vagy rendelési authorityt.</p>{initialRecords.length?<div className="adminTableScroll"><table className="adminTable"><thead><tr><th>Típus</th><th>Név</th><th>Kulcs</th><th></th></tr></thead><tbody>{initialRecords.map(row=><tr key={row.id}><td>{kindLabel(row.engineKind)}</td><td><strong>{row.label}</strong></td><td><code>{row.configKey}</code></td><td><button className="btn btnGhost" type="button" disabled={pending} onClick={()=>run(()=>deleteExistingCommerceEngineAction(row.id),'Konfiguráció törölve.')}>Törlés</button></td></tr>)}</tbody></table></div>:<p className="muted">Még nincs mentett Guided Finder, Composer vagy Configurator.</p>}</section>

    <section className="featurePanel"><span className="eyebrow">E3 · Guided Finder</span><h2>Vezetett termékkereső</h2><p className="muted">Egy explicit termékattribútumhoz rendelsz válaszokat. A rendszer nem talál ki terméktulajdonságot; kizárólag a Termékkezelésben megadott attribútumot használja.</p><div className="form-grid"><label className="checkoutField"><span>Kulcs</span><input value={finder.key} onChange={e=>setFinder({...finder,key:e.target.value})}/></label><label className="checkoutField"><span>Név</span><input value={finder.label} onChange={e=>setFinder({...finder,label:e.target.value})}/></label><label className="checkoutField"><span>Kérdés</span><input value={finder.question} onChange={e=>setFinder({...finder,question:e.target.value})}/></label><label className="checkoutField"><span>Katalógusattribútum</span><select value={finder.attribute} onChange={e=>setFinder({...finder,attribute:e.target.value})}><option value="">Válassz attribútumot</option>{attributes.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label className="checkoutField" style={{gridColumn:'1 / -1'}}><span>Válaszok — soronként „Címke = pontos attribútumérték”</span><textarea rows={5} value={finder.options} onChange={e=>setFinder({...finder,options:e.target.value})}/></label></div><button className="btn btnPrimary" type="button" disabled={pending||!finder.attribute} onClick={()=>run(()=>saveGuidedFinderAction({configKey:finder.key,label:finder.label,questionLabel:finder.question,attributeKey:finder.attribute,options:lines(finder.options).flatMap(line=>{const pos=line.indexOf('=');return pos>0?[{label:line.slice(0,pos).trim(),value:line.slice(pos+1).trim()}]:[]})}),'Guided Finder mentve.')}>Finder mentése</button><small className="muted">Mentett: {byKind.guided_finder.length}</small></section>

    <section className="featurePanel"><span className="eyebrow">E4 · Multi-Product Composer</span><h2>Build-a-Box / csomagösszeállító</h2><div className="form-grid"><label className="checkoutField"><span>Kulcs</span><input value={composer.key} onChange={e=>setComposer({...composer,key:e.target.value})}/></label><label className="checkoutField"><span>Név</span><input value={composer.label} onChange={e=>setComposer({...composer,label:e.target.value})}/></label><label className="checkoutField"><span>Mód</span><select value={composer.mode} onChange={e=>setComposer({...composer,mode:e.target.value as'pool'|'slots'})}><option value="pool">Szabad válogatás</option><option value="slots">Pozíciók / csoportok</option></select></label><label className="checkoutField"><span>Minimum tétel</span><input type="number" min="1" value={composer.min} onChange={e=>setComposer({...composer,min:Number(e.target.value)})}/></label><label className="checkoutField"><span>Maximum tétel</span><input type="number" min="1" value={composer.max} onChange={e=>setComposer({...composer,max:Number(e.target.value)})}/></label><label className="checkoutField"><span>Azonos termék maximuma</span><input type="number" min="1" value={composer.duplicate} onChange={e=>setComposer({...composer,duplicate:Number(e.target.value)})}/></label>{composer.mode==='slots'?<label className="checkoutField" style={{gridColumn:'1 / -1'}}><span>Pozíciók — „kulcs | név | minimum | maximum”</span><textarea rows={5} value={composer.slots} onChange={e=>setComposer({...composer,slots:e.target.value})}/></label>:null}</div><button className="btn btnPrimary" type="button" disabled={pending} onClick={()=>run(()=>saveComposerAction({configKey:composer.key,label:composer.label,mode:composer.mode,minItems:composer.min,maxItems:composer.max,duplicateLimit:composer.duplicate,slots:composer.mode==='slots'?lines(composer.slots).map(line=>{const[id,label,min,max]=split(line);return{id:id??'',label:label??'',minItems:Number(min??0),maxItems:Number(max??1)}}):undefined}),'Composer mentve.')}>Composer mentése</button><small className="muted">Mentett: {byKind.multi_product_composer.length}</small></section>

    <section className="featurePanel"><span className="eyebrow">E5 + E6 · Configurator</span><h2>Konfigurátor és szerveroldali kompatibilitási szabály</h2><p className="muted">Az „Ismeretlen” nem számít kompatibilisnek. Legalább egy explicit összehasonlítás kell két komponenshely között ugyanazon strukturált attribútum alapján.</p><div className="form-grid"><label className="checkoutField"><span>Kulcs</span><input value={configurator.key} onChange={e=>setConfigurator({...configurator,key:e.target.value})}/></label><label className="checkoutField"><span>Név</span><input value={configurator.label} onChange={e=>setConfigurator({...configurator,label:e.target.value})}/></label><label className="checkoutField" style={{gridColumn:'1 / -1'}}><span>Komponenshelyek — „kulcs | név | igen/nem”</span><textarea rows={5} value={configurator.slots} onChange={e=>setConfigurator({...configurator,slots:e.target.value})}/></label><label className="checkoutField"><span>Szabály neve</span><input value={configurator.ruleLabel} onChange={e=>setConfigurator({...configurator,ruleLabel:e.target.value})}/></label><label className="checkoutField"><span>Bal slot kulcsa</span><input value={configurator.left} onChange={e=>setConfigurator({...configurator,left:e.target.value})}/></label><label className="checkoutField"><span>Jobb slot kulcsa</span><input value={configurator.right} onChange={e=>setConfigurator({...configurator,right:e.target.value})}/></label><label className="checkoutField"><span>Összehasonlított attribútum</span><select value={configurator.attribute} onChange={e=>setConfigurator({...configurator,attribute:e.target.value})}><option value="">Válassz attribútumot</option>{attributes.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label></div><button className="btn btnPrimary" type="button" disabled={pending||!configurator.attribute} onClick={()=>run(()=>saveConfiguratorAction({configKey:configurator.key,label:configurator.label,slots:lines(configurator.slots).map(line=>{const[id,label,required]=split(line);return{id:id??'',label:label??'',required:['igen','yes','true','1'].includes((required??'').toLowerCase())}}),rules:[{label:configurator.ruleLabel,leftSlotId:configurator.left,rightSlotId:configurator.right,attributeKey:configurator.attribute}]}),'Configurator mentve.')}>Configurator mentése</button><small className="muted">Mentett: {byKind.product_configurator.length}</small></section>
  </div>;
}
