'use client';

import{useEffect,useRef,useState,useTransition}from'react';
import{autosaveReplyDraftAction,officeComposerInitialState,saveReplyDraftAction,sendCustomerEmailV4Action,type OfficeComposerActionState}from'@/app/admin/kommunikacio/iroda/composer-actions';
import{useOfficeDraftAutosave}from'@/components/admin/use-office-draft-autosave';
import{getOfficeEmailAttachmentAvailability,officeEmailAttachmentProblem,uploadAndScanOfficeEmailAttachments,type OfficeEmailAttachmentAvailability}from'@/lib/office/email-attachment-client';
import{OFFICE_PRIVATE_ATTACHMENT_MIME_TYPES}from'@/lib/office/private-attachments';

function PendingSpinner(){return <svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" focusable="false"><g><path fill="currentColor" d="M12 2a10 10 0 0 1 9.4 6.58l-1.88.68A8 8 0 0 0 12 4V2Z"/><animateTransform attributeName="transform" type="rotate" from="0 12 12" to="360 12 12" dur="0.8s" repeatCount="indefinite"/></g></svg>}
type ReplySnapshot={ccEmails:string;bccEmails:string;body:string};
type ReplyDraft={id:string;revision:number;ccEmails:string[];bccEmails:string[];body:string};
type DelegationOption={userId:string;label:string};
function replyFormData(threadId:string,snapshot:ReplySnapshot,draftId:string,revision:number|null,attachmentIds:string[]=[],actingForUserId?:string){const form=new FormData();form.set('threadId',threadId);form.set('ccEmails',snapshot.ccEmails);form.set('bccEmails',snapshot.bccEmails);form.set('body',snapshot.body);if(draftId)form.set('draftId',draftId);if(revision)form.set('revision',String(revision));for(const id of attachmentIds)form.append('attachmentId',id);if(actingForUserId)form.set('actingForUserId',actingForUserId);return form}
function attachmentHelp(checked:boolean,availability:OfficeEmailAttachmentAvailability){if(!checked)return'A csatolmány-biztonsági rendszer állapotát ellenőrizzük…';if(availability.enabled)return'Legfeljebb 5 fájl, fájlonként 10 MB. A fájl privát karanténba kerül, és csak tartalom- + vírusellenőrzés után küldhető.';if(availability.reason==='scanner_unavailable')return'A vírusellenőrző jelenleg nem elérhető, ezért fájl nem küldhető. Szöveges e-mail továbbra is használható.';return'A csatolmányküldés jelenleg nem érhető el.'}

export function OfficeCustomerEmailForm({threadId,sendingConfigured=false,advancedEmail=false,initialDraft,delegationOptions=[]}:{threadId:string;sendingConfigured?:boolean;advancedEmail?:boolean;initialDraft?:ReplyDraft;delegationOptions?:DelegationOption[]}){
  const[ccEmails,setCcEmails]=useState(advancedEmail?initialDraft?.ccEmails.join(', ')??'':'');const[bccEmails,setBccEmails]=useState(advancedEmail?initialDraft?.bccEmails.join(', ')??'':'');const[body,setBody]=useState(initialDraft?.body??'');const[actingForUserId,setActingForUserId]=useState('');const[files,setFiles]=useState<File[]>([]);const[attachmentAvailability,setAttachmentAvailability]=useState<OfficeEmailAttachmentAvailability>({enabled:false,reason:'unknown'});const[attachmentChecked,setAttachmentChecked]=useState(false);const fileInput=useRef<HTMLInputElement>(null);const[operationState,setOperationState]=useState<OfficeComposerActionState>(officeComposerInitialState);const[actionPending,startTransition]=useTransition();const snapshot:ReplySnapshot={ccEmails:advancedEmail?ccEmails:'',bccEmails:advancedEmail?bccEmails:'',body};const snapshotKey=JSON.stringify(snapshot);const meaningful=(advancedEmail?[ccEmails,bccEmails,body]:[body]).some(value=>value.trim().length>0);const sendReady=body.trim().length>0&&!officeEmailAttachmentProblem(files);
  useEffect(()=>{let active=true;getOfficeEmailAttachmentAvailability().then(value=>{if(active){setAttachmentAvailability(value);setAttachmentChecked(true)}});return()=>{active=false}},[]);
  const draft=useOfficeDraftAutosave({snapshot,snapshotKey,meaningful,initialDraftId:initialDraft?.id,initialRevision:initialDraft?.revision??null,autosave:({snapshot:next,draftId,revision})=>autosaveReplyDraftAction(officeComposerInitialState,replyFormData(threadId,next,draftId,revision)),manualSave:({snapshot:next,draftId,revision})=>saveReplyDraftAction(officeComposerInitialState,replyFormData(threadId,next,draftId,revision))});
  function save(){setOperationState(officeComposerInitialState);void draft.saveNow()}
  function send(){if(!sendReady||!sendingConfigured||draft.status==='conflict')return;startTransition(async()=>{setOperationState(officeComposerInitialState);const problem=officeEmailAttachmentProblem(files);if(problem){setOperationState({status:'error',message:problem});return}const saveResult=await draft.saveNow();if(saveResult&&(saveResult.status==='conflict'||saveResult.status==='error'||saveResult.status==='blocked')){setOperationState(saveResult);return}const safeDraftId=saveResult?.draftId??draft.draftId;const safeRevision=saveResult?.revision??draft.revision;if(!safeDraftId||!safeRevision){setOperationState({status:'error',message:'A csatolmányos küldéshez előbb igazolt piszkozatmentés szükséges.'});return}let attachmentIds:string[]=[];try{if(files.length){if(!attachmentAvailability.enabled)throw new Error('A fájlok biztonsági ellenőrzése jelenleg nem érhető el.');attachmentIds=await uploadAndScanOfficeEmailAttachments(safeDraftId,files)}}catch(error){setOperationState({status:'blocked',message:error instanceof Error?error.message:'A csatolmány ellenőrzése nem sikerült.'});return}const result=await sendCustomerEmailV4Action(officeComposerInitialState,replyFormData(threadId,snapshot,safeDraftId,safeRevision,attachmentIds,advancedEmail?actingForUserId:undefined));setOperationState(result);if(result.status==='success'){setCcEmails('');setBccEmails('');setBody('');setActingForUserId('');setFiles([]);if(fileInput.current)fileInput.current.value='';draft.reset()}})}
  return <div className="stackForm" aria-busy={actionPending||draft.status==='saving'}>
    {advancedEmail?<div className="splitFeature"><label className="stackForm"><span>Másolat (CC)</span><input value={ccEmails} onChange={event=>setCcEmails(event.target.value)} maxLength={3300} placeholder="pelda@ceg.hu" disabled={actionPending}/></label><label className="stackForm"><span>Titkos másolat (BCC)</span><input value={bccEmails} onChange={event=>setBccEmails(event.target.value)} maxLength={3300} placeholder="belso@ceg.hu" disabled={actionPending}/></label></div>:<p className="muted">CC/BCC címzettek a Pro ügyféllevelezési csomagban érhetők el.</p>}
    <textarea name="body" required rows={3} maxLength={10000} placeholder="Ügyfélnek" value={body} onChange={event=>setBody(event.target.value)} disabled={actionPending}/>
    <label className="stackForm"><span>Csatolmányok</span><input ref={fileInput} type="file" multiple accept={OFFICE_PRIVATE_ATTACHMENT_MIME_TYPES.join(',')} disabled={!attachmentAvailability.enabled||actionPending} onChange={event=>setFiles(Array.from(event.target.files??[]))}/><span className="muted">{attachmentHelp(attachmentChecked,attachmentAvailability)}</span></label>
    {files.length>0&&<p className="muted">{files.length} fájl kiválasztva{officeEmailAttachmentProblem(files)?` · ${officeEmailAttachmentProblem(files)}`:''}</p>}
    {advancedEmail&&delegationOptions.length>0&&<label><span>Válasz más nevében</span><select value={actingForUserId} onChange={event=>setActingForUserId(event.target.value)} disabled={actionPending}><option value="">Saját nevemben</option>{delegationOptions.map(option=><option key={option.userId} value={option.userId}>{option.label}</option>)}</select></label>}
    {!sendingConfigured&&<div className="adminAuditNotice"><strong>Küldés még nincs aktiválva.</strong><p>A válasz automatikusan piszkozatként menthető. Küldéshez külön jóváhagyott Digitális Iroda postafiók szükséges.</p></div>}
    <div className="adminToolbar"><button type="button" className="btn btnGhost" onClick={save} disabled={actionPending||draft.status==='saving'||draft.status==='conflict'||!meaningful}>Piszkozat mentése</button><button type="button" className="btn btnPrimary" onClick={send} disabled={actionPending||draft.status==='conflict'||!sendReady||!sendingConfigured}>{actionPending?<><PendingSpinner/> Feldolgozás…</>:'E-mail válasz'}</button>{draft.status!=='conflict'&&draft.status!=='error'&&<span className="muted" role="status" aria-live="polite">{draft.message||'Még nincs mentett válaszpiszkozat.'}</span>}</div>
    {draft.status==='conflict'&&<div className="errorNotice" role="alert"><strong>Válaszpiszkozat-ütközés.</strong><p>{draft.message}</p></div>}{draft.status==='error'&&<div className="errorNotice" role="alert"><strong>Az automatikus mentés nem sikerült.</strong><p>{draft.message} A kézi mentéssel újra próbálhatod.</p></div>}{operationState.message&&(operationState.status==='blocked'||operationState.status==='error'||operationState.status==='conflict'?<div className="errorNotice" role="alert">{operationState.message}</div>:<p className="muted" role="status">{operationState.message}</p>)}
  </div>;
}
