'use client';
import{useState}from'react';
import styles from'@/app/admin/termekek/feltoltes/product-intake.module.css';
import v2 from'@/app/admin/termekek/feltoltes/product-intake-v2.module.css';

export type ProductCopilotSuggestion={shortDescription?:string;description?:string;seoTitle?:string;seoDescription?:string;category?:string;reason?:string};
type ProductContext={name:string;shortDescription:string;description:string;seoTitle:string;seoDescription:string;category:string;colors:string[];sizes:string[]};
type Mode='description'|'seo'|'category'|'complete';
type Response={error?:string;suggestion?:ProductCopilotSuggestion;requiresApproval?:boolean;model?:string};
const actions:Array<{mode:Mode;label:string;icon:string}>=[{mode:'description',label:'Leírás javaslata',icon:'✦'},{mode:'seo',label:'SEO javítása',icon:'⌕'},{mode:'category',label:'Kategória javaslata',icon:'◇'},{mode:'complete',label:'Adatok kiegészítése',icon:'＋'}];
const fields:Array<{key:keyof ProductCopilotSuggestion;label:string}>=[{key:'shortDescription',label:'Rövid leírás'},{key:'description',label:'Leírás'},{key:'seoTitle',label:'SEO cím'},{key:'seoDescription',label:'Meta description'},{key:'category',label:'Kategória'}];

export function ProductCopilot({product,onApply}:{product:ProductContext;onApply:(value:ProductCopilotSuggestion)=>void}){
 const[busy,setBusy]=useState<Mode|null>(null),[result,setResult]=useState<ProductCopilotSuggestion|null>(null),[message,setMessage]=useState(''),[model,setModel]=useState('');
 async function run(mode:Mode){if(busy)return;setBusy(mode);setMessage('');setResult(null);try{const response=await fetch('/api/admin/catalog/copilot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,product})}),payload=await response.json().catch(()=>({}))as Response;if(!response.ok||!payload.suggestion){setMessage(payload.error??'A Product Copilot most nem tudott javaslatot készíteni.');return}setResult(payload.suggestion);setModel(payload.model??'')}catch{setMessage('Hálózati hiba a Product Copilot használata közben.')}finally{setBusy(null)}}
 const applicable=result?Object.fromEntries(Object.entries(result).filter(([key])=>key!=='reason'))as ProductCopilotSuggestion:null;
 return <section id="copilot" className={`${styles.railCard} ${v2.copilotCard}`}><div className={styles.railTitle}><h2>✦ Product Copilot</h2><span>Javaslat · jóváhagyással</span></div><p className={v2.copilotIntro}>Segít a termékszöveg, SEO és kategória finomításában. Semmit nem ment és nem publikál helyetted.</p><div className={v2.copilotActions}>{actions.map(action=><button type="button" key={action.mode} disabled={Boolean(busy)||!product.name.trim()} onClick={()=>void run(action.mode)}><span>{action.icon}</span>{busy===action.mode?'Gondolkodik…':action.label}</button>)}</div>{message&&<div className={`${v2.copilotMessage} ${styles.saveError}`} role="alert">{message}</div>}{result&&<div className={v2.copilotResult}><div className={v2.copilotResultHeader}><strong>Javasolt módosítások</strong>{model&&<small>{model}</small>}</div>{fields.flatMap(field=>{const value=result[field.key];if(typeof value!=='string'||!value.trim())return[];const patch={[field.key]:value}as ProductCopilotSuggestion;return <article key={field.key}><div><strong>{field.label}</strong><button type="button" onClick={()=>onApply(patch)}>Alkalmaz</button></div><p>{value}</p></article>})}{result.reason&&<small className={v2.copilotReason}>{result.reason}</small>}{applicable&&Object.keys(applicable).length>0&&<button className={v2.copilotApplyAll} type="button" onClick={()=>onApply(applicable)}>Mind alkalmaz</button>}<small className={v2.copilotDisclaimer}>AI-javaslat. Mentés előtt ellenőrizd a termék tényleges adatait.</small></div>}</section>;
}
