'use client';

import{FormEvent,useEffect,useState}from'react';
import{createClient}from'@/lib/supabase/browser';

type Kind='manual'|'datasheet'|'size_guide'|'warranty_info'|'compatibility'|'installation_guide'|'other';
type Visibility='public'|'account';
type Variant={id:string;label:string};
type DocumentRow={documentId:string;variantId:string|null;variantLabel:string|null;kind:Kind;title:string;description:string|null;sortOrder:number;visibility:Visibility;fileName:string;mediaType:string;sizeBytes:number;status:'pending'|'active'|'revoked';createdAt:string};
type ListResponse={documents?:DocumentRow[];error?:string};
type PrepareResponse={documentId?:string;bucket?:string;path?:string;token?:string;error?:string};
const BUCKET='product-documents-private';
const labels:Record<Kind,string>={manual:'Használati útmutató',datasheet:'Adatlap',size_guide:'Mérettáblázat',warranty_info:'Garanciális információ',compatibility:'Kompatibilitási lap',installation_guide:'Telepítési útmutató',other:'Egyéb dokumentum'};
const accept='.pdf,.jpg,.jpeg,.png,.txt,.csv,.doc,.docx,.xls,.xlsx';
const allowedTypes=new Set(['application/pdf','image/jpeg','image/png','text/plain','text/csv','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);
const fmtSize=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1024*1024?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/(1024*1024)).toFixed(1)} MB`;

export function ProductDocumentManager({productId,variants}:{productId:string;variants:Variant[]}){
  const[documents,setDocuments]=useState<DocumentRow[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false);
  const[kind,setKind]=useState<Kind>('manual'),[visibility,setVisibility]=useState<Visibility>('account'),[variantId,setVariantId]=useState(''),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[sortOrder,setSortOrder]=useState(0),[file,setFile]=useState<File|null>(null);
  async function reload(){setLoading(true);try{const r=await fetch(`/api/admin/catalog/product-documents?productId=${encodeURIComponent(productId)}`,{cache:'no-store'}),p=await r.json().catch(()=>({}))as ListResponse;if(!r.ok)throw new Error(p.error??'A dokumentumok nem tölthetők be.');setDocuments(p.documents??[])}catch(e){setMessage(e instanceof Error?e.message:'A dokumentumok nem tölthetők be.');setError(true)}finally{setLoading(false)}}
  useEffect(()=>{void reload()},[productId]);
  async function revoke(documentId:string){if(busy)return;setBusy(true);setMessage('');setError(false);try{const r=await fetch(`/api/admin/catalog/product-documents?documentId=${encodeURIComponent(documentId)}`,{method:'DELETE'}),p=await r.json().catch(()=>({}))as{error?:string};if(!r.ok)throw new Error(p.error??'A dokumentum nem távolítható el.');setMessage('A termékdokumentum storefront hozzáférése visszavonva.');await reload()}catch(e){setMessage(e instanceof Error?e.message:'A dokumentum nem távolítható el.');setError(true)}finally{setBusy(false)}}
  async function submit(event:FormEvent){event.preventDefault();if(busy||!file)return;setMessage('');setError(false);if(!allowedTypes.has(file.type)){setMessage('Nem támogatott fájltípus. PDF, kép, TXT/CSV, Word vagy Excel dokumentum tölthető fel.');setError(true);return}if(file.size<1||file.size>25*1024*1024){setMessage('A termékdokumentum legfeljebb 25 MB lehet.');setError(true);return}setBusy(true);let preparedId:string|undefined;try{
    const r=await fetch('/api/admin/catalog/product-documents',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId,variantId:variantId||null,kind,title:title.trim()||file.name,description:description.trim()||undefined,sortOrder,visibility,fileName:file.name,mediaType:file.type,sizeBytes:file.size})}),p=await r.json().catch(()=>({}))as PrepareResponse;
    if(!r.ok||!p.documentId||p.bucket!==BUCKET||!p.path||!p.token)throw new Error(p.error??'A dokumentum feltöltése nem készíthető elő.');preparedId=p.documentId;
    const supabase=createClient(),upload=await supabase.storage.from(BUCKET).uploadToSignedUrl(p.path,p.token,file,{contentType:file.type});if(upload.error)throw new Error('A dokumentum feltöltése nem sikerült.');
    const activate=await fetch('/api/admin/catalog/product-documents',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({documentId:p.documentId})}),activated=await activate.json().catch(()=>({}))as{error?:string};if(!activate.ok)throw new Error(activated.error??'A dokumentum feltöltődött, de nem aktiválható.');
    setKind('manual');setVisibility('account');setVariantId('');setTitle('');setDescription('');setSortOrder(0);setFile(null);setMessage('A termékdokumentum aktiválva.');await reload();
  }catch(e){if(preparedId)await fetch(`/api/admin/catalog/product-documents?documentId=${encodeURIComponent(preparedId)}`,{method:'DELETE'}).catch(()=>undefined);setMessage(e instanceof Error?e.message:'A dokumentum feltöltése nem sikerült.');setError(true)}finally{setBusy(false)}}
  return <div className="stack" data-product-document-manager style={{gap:14,marginTop:14}}><form onSubmit={submit} className="stack" style={{gap:10}}><div className="formGrid"><label>Típus<select value={kind} onChange={e=>setKind(e.target.value as Kind)}>{(Object.keys(labels)as Kind[]).map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label><label>Láthatóság<select value={visibility} onChange={e=>setVisibility(e.target.value as Visibility)}><option value="account">Bejelentkezett fiók</option><option value="public">Nyilvános termékoldal</option></select></label><label>Változat<select value={variantId} onChange={e=>setVariantId(e.target.value)}><option value="">Minden változat</option>{variants.map(variant=><option key={variant.id} value={variant.id}>{variant.label}</option>)}</select></label><label>Sorrend<input type="number" min={0} max={10000} value={sortOrder} onChange={e=>setSortOrder(Number(e.target.value)||0)}/></label></div><label>Megjelenő cím<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} placeholder="pl. Használati útmutató"/></label><label>Leírás<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000} rows={2} placeholder="Opcionális rövid leírás"/></label><label>Fájl<input type="file" accept={accept} onChange={e=>setFile(e.target.files?.[0]??null)} required/></label><button className="btn btnPrimary" type="submit" disabled={busy||!file}>{busy?'Feldolgozás…':'Termékdokumentum feltöltése'}</button></form>{message&&<div className={error?'errorNotice':'adminAuditNotice'} role={error?'alert':'status'}>{message}</div>}<div className="timeline">{loading?<p className="muted">Dokumentumok betöltése…</p>:documents.filter(item=>item.status!=='revoked').map(item=><div className="timelineItem" key={item.documentId}><strong>{labels[item.kind]} · {item.title}</strong><span className="muted">{item.variantLabel?`${item.variantLabel} · `:'Minden változat · '}{item.visibility==='public'?'Nyilvános':'Fiókhoz kötött'} · {item.fileName} · {fmtSize(Number(item.sizeBytes))} · {item.status==='active'?'Aktív':'Feltöltés alatt'}</span>{item.status==='active'&&<button type="button" className="btn btnGhost" disabled={busy} onClick={()=>void revoke(item.documentId)}>Eltávolítás</button>}</div>)}</div>{!loading&&!documents.some(item=>item.status!=='revoked')&&<p className="muted">Ehhez a termékhez még nincs dokumentum.</p>}</div>;
}
