'use client';
import{useMemo,useState}from'react';
import{useRouter}from'next/navigation';
import styles from'@/app/admin/termekek/feltoltes/product-intake.module.css';
import v2 from'@/app/admin/termekek/feltoltes/product-intake-v2.module.css';

type ProductOption={id:string;name:string;active:boolean;variantCount:number;updatedAt:string|null};
type CopyResponse={error?:string;targetProductId?:string;draft?:boolean;mediaCount?:number};
const freshKey=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}-copy`;
export function ProductCopyPanel({products}:{products:ProductOption[]}){
 const router=useRouter(),[query,setQuery]=useState(''),[selected,setSelected]=useState(products[0]?.id??''),[includeMedia,setIncludeMedia]=useState(true),[includeSeo,setIncludeSeo]=useState(true),[includeChannels,setIncludeChannels]=useState(true),[includeStock,setIncludeStock]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[key,setKey]=useState(freshKey);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('hu-HU');return q?products.filter(product=>product.name.toLocaleLowerCase('hu-HU').includes(q)):products},[products,query]),current=products.find(product=>product.id===selected);
 async function copy(){if(!selected||busy)return;setBusy(true);setMessage('');setError(false);try{const response=await fetch('/api/admin/catalog/copy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sourceProductId:selected,idempotencyKey:key,options:{includeMedia,includeSeo,includeChannels,includeStock}})}),payload=await response.json().catch(()=>({}))as CopyResponse;if(!response.ok||!payload.targetProductId||payload.draft!==true){setError(true);setMessage(payload.error??'A termék másolása nem sikerült.');return}setMessage('A másolat piszkozatként elkészült. Megnyitom a szerkesztőt…');setKey(freshKey());router.push(`/admin/termekek/feltoltes/${payload.targetProductId}`);router.refresh()}catch{setError(true);setMessage('Hálózati hiba. Ugyanazzal a másolási kulccsal biztonságosan újrapróbálható.')}finally{setBusy(false)}}
 return <div className={v2.copyLayout}><section className={styles.editorPanel}><div className={styles.editorPanelHeader}><div><h2>⧉ Forrástermék kiválasztása</h2><p>A másolat mindig új, inaktív piszkozatként készül. Az eredeti termék nem módosul.</p></div><span className={styles.sectionState}>{products.length} termék</span></div><label className={styles.field}>Keresés<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Terméknév keresése…"/></label><div className={v2.copyProductList}>{filtered.length?filtered.slice(0,100).map(product=><button type="button" key={product.id} className={selected===product.id?v2.copyProductActive:''} onClick={()=>setSelected(product.id)}><span className={styles.productName}><i>{product.name.slice(0,1).toUpperCase()}</i><span><strong>{product.name}</strong><small>{product.variantCount} variáns · {product.active?'Aktív':'Piszkozat'}</small></span></span><b>{selected===product.id?'✓':'›'}</b></button>):<div className={styles.emptyState}>Nincs találat.</div>}</div></section><aside className={v2.copyOptions}><section className={styles.railCard}><div className={styles.railTitle}><h2>Másolási beállítások</h2><span>Biztonságos alapértékek</span></div><label className={v2.copySwitch}><input type="checkbox" checked={includeMedia} onChange={e=>setIncludeMedia(e.target.checked)}/><span><strong>Képek és variánsképek</strong><small>A termékmédia fizikailag is új objektumként kerül a másolathoz.</small></span></label><label className={v2.copySwitch}><input type="checkbox" checked={includeSeo} onChange={e=>setIncludeSeo(e.target.checked)}/><span><strong>SEO mezők</strong><small>SEO cím és meta description átvétele.</small></span></label><label className={v2.copySwitch}><input type="checkbox" checked={includeChannels} onChange={e=>setIncludeChannels(e.target.checked)}/><span><strong>B2C/B2B beállítások</strong><small>A termékszintű csatorna-láthatóság és árbeállítások átvétele.</small></span></label><label className={`${v2.copySwitch} ${v2.copyCaution}`}><input type="checkbox" checked={includeStock} onChange={e=>setIncludeStock(e.target.checked)}/><span><strong>Készlet átvétele</strong><small>Alapból kikapcsolva, hogy egy másolat ne hozzon létre véletlenül eladható készletet.</small></span></label></section><section className={styles.railCard}><h2>Új piszkozat</h2><p className={v2.copySummary}>{current?<>A <strong>{current.name}</strong> termék {current.variantCount} variánsából új piszkozat készül. Új slug és új SKU-k generálódnak.</>:'Válassz egy terméket a másoláshoz.'}</p><button className={styles.primaryButton} style={{width:'100%'}} type="button" disabled={!selected||busy} onClick={()=>void copy()}>{busy?'Másolás…':'⧉ Termék másolása'}</button>{message&&<div className={`${styles.saveMessage} ${error?styles.saveError:''}`} role={error?'alert':'status'}>{message}</div>}</section></aside></div>;
}
