'use client';

import Link from 'next/link';
import {useEffect,useState,useTransition,type DragEvent,type ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import {StorefrontRuntimeRenderer} from '@/components/builder/storefront-runtime-renderer';
import {StorefrontFidelitySettings} from '@/components/admin/storefront-fidelity-settings';
import {StorefrontOwnBlocksPanel} from '@/components/admin/storefront-own-blocks-panel';
import {StorefrontGlobalElementsPanel} from '@/components/admin/storefront-global-elements-panel';
import {StorefrontPageTemplatesPanel} from '@/components/admin/storefront-page-templates-panel';
import {StorefrontPresetLibraryPanel} from '@/components/admin/storefront-preset-library-panel';
import {createStorefrontVisualBuilderRendererRegistry} from '@/components/builder/storefront-builder-renderer-registry';
import {createStorefrontVisualBuilderComponentRegistry} from '@/lib/builder/storefront-builder-registry';
import {findStorefrontLinkedSymbolInstance} from '@/lib/builder/storefront-linked-symbols';
import {
  applyStorefrontBuilderMutation,
  createStorefrontBuilderHistory,
  listStorefrontBuilderInsertableComponents,
  pushStorefrontBuilderHistory,
  redoStorefrontBuilderHistory,
  undoStorefrontBuilderHistory,
  type StorefrontBuilderHistory,
  type StorefrontBuilderMutation,
} from '@/lib/builder/storefront-visual-builder';
import {
  applyStorefrontBindings,
  hasStorefrontRuntimeCapability,
  resolveStorefrontBinding,
  type StorefrontComponentNode,
  type StorefrontPageDocument,
  type StorefrontRuntimeCapabilityContext,
  type StorefrontResolvedComponentNode,
} from '@/lib/builder/storefront-runtime';
import {
  applyStorefrontComponentVariant,
  detectStorefrontComponentVariant,
  listStorefrontComponentVariants,
} from '@/lib/builder/storefront-component-variants';
import {inspectStorefrontFidelityBuilder,type StorefrontFidelityInspectorStatus} from '@/lib/builder/storefront-fidelity-inspector';
import type {StorefrontSavedBlockSummary} from '@/lib/builder/storefront-saved-block-persistence';
import type {StorefrontViewport} from '@/lib/builder/storefront-foundation';
import type {FeatureCode} from '@/lib/plans/catalog';
import type {StorefrontBuilderPageListItem,StorefrontBuilderRevisionListItem} from '@/lib/builder/storefront-builder-server';
import {
  createVisualBuilderPreviewAction,
  installVisualBuilderTemplateAction,
  publishVisualBuilderPageAction,
  rollbackVisualBuilderPageAction,
  saveVisualBuilderDraftAction,
} from '@/app/admin/tartalom/builder/actions';
import {VisualBuilderIcon,type VisualBuilderIconName} from './visual-builder-ui-icon';
import css from './storefront-visual-builder-95.module.css';

type TemplateEntry={templateKey:string;templateVersion:number;category:string;minPlan:'alap'|'pro';requiredFeatures:readonly string[];pageTypes:readonly string[]};
type Props={pages:StorefrontBuilderPageListItem[];document:StorefrontPageDocument|null;pageId:string|null;draftRevision:number|null;publishedRevision:number|null;revisions:StorefrontBuilderRevisionListItem[];capability:StorefrontRuntimeCapabilityContext;bindingContext:Record<string,unknown>;templates:TemplateEntry[];savedBlocks:StorefrontSavedBlockSummary[]};
type FlatNode={node:StorefrontComponentNode;parentId:string|null;index:number;depth:number};
type PanelMode='pages'|'add'|'structure'|'templates'|'presets'|'saved'|'globals';
type EditorTab='content'|'appearance'|'responsive'|'advanced';
type FieldGroup={title:string;description:string;keys:string[]};

const registry=createStorefrontVisualBuilderComponentRegistry();
const rendererRegistry=createStorefrontVisualBuilderRendererRegistry();
const VIEWPORTS:readonly {key:StorefrontViewport;label:string;width:number;icon:VisualBuilderIconName}[]=[{key:'desktop',label:'Desktop',width:1200,icon:'desktop'},{key:'tablet',label:'Tablet',width:768,icon:'tablet'},{key:'mobile',label:'Mobil',width:390,icon:'mobile'}];
const PAGE_LABELS:Record<string,string>={account:'Fiókom',blogarticle:'Blogbejegyzés',blogindex:'Blog',cart:'Kosár',catalog:'Katalógus',checkout:'Pénztár',contact:'Kapcsolat',content:'Tartalmi oldal',faq:'GYIK',home:'Főoldal',legal:'Jogi oldal',notfound:'404 oldal',search:'Keresés',product:'Termékoldal'};
const FIELD_LABELS:Record<string,string>={brandlabel:'Márkanév',brandhref:'Márka hivatkozása',brandlogosrc:'Logó képe',brandlogoalt:'Logó képleírása',showbrandtext:'Márkanév megjelenítése',sticky:'Rögzített fejléc',tagline:'Szlogen',shownavigation:'Navigáció megjelenítése',showutilities:'Egyedi gyorsműveletek',utilityitems:'Egyedi gyorsműveletek',showsearch:'Keresés megjelenítése',searchhref:'Keresés oldala',showaccount:'Fiók megjelenítése',accounthref:'Fiók oldala',showcart:'Kosár megjelenítése',carthref:'Kosár oldala',mobilemenu:'Mobil menü',items:'Menüpontok',arialabel:'Akadálymentes címke',columns:'Oszlopok',mobilecolumns:'Mobil oszlopok',layout:'Elrendezés',src:'Kép',alt:'Képleírás',level:'Címsor szintje',as:'Szövegtípus',objectposition:'Kép fókusza',title:'Cím',heading:'Címsor',eyebrow:'Felső címke',copy:'Szöveg',text:'Szöveg',description:'Leírás',label:'Felirat',href:'Hivatkozás',url:'Hivatkozás',image:'Kép',imageurl:'Kép',background:'Háttér',backgroundcolor:'Háttérszín',color:'Szín',textcolor:'Szövegszín',gap:'Elemek közötti tér',spacing:'Belső térköz',align:'Igazítás',justify:'Elosztás',width:'Szélesség',tone:'Felület',direction:'Irány',fit:'Kép illesztése',loading:'Betöltés',radius:'Lekerekítés',variant:'Változat',size:'Méret',overlay:'Fedőréteg',padding:'Belső térköz'};
const OPTION_LABELS:Record<string,string>={none:'Nincs',xs:'Nagyon szűk',s:'Kompakt',m:'Normál',l:'Tágas',xl:'Nagyon tágas','2xl':'Extra tágas',start:'Elejére',center:'Középre',end:'Végére',stretch:'Kitöltés',left:'Balra',right:'Jobbra',between:'Szétosztva',full:'Teljes szélesség',content:'Tartalmi szélesség',narrow:'Keskeny',background:'Alap háttér',surface:'Felület',muted:'Visszafogott',primary:'Elsődleges',text:'Szöveg',vertical:'Függőleges',horizontal:'Vízszintes',cover:'Kitöltés',contain:'Befoglalás',lazy:'Késleltetett',eager:'Azonnali',pill:'Kapszula',secondary:'Másodlagos',ghost:'Visszafogott'};
const TOKEN_OPTIONS:Record<string,readonly string[]>={gap:['none','xs','s','m','l','xl','2xl'],spacing:['none','xs','s','m','l','xl','2xl'],align:['start','center','end','stretch','left','right'],justify:['start','center','end','between'],width:['full','content','narrow'],tone:['background','surface','muted','primary','text'],direction:['vertical','horizontal'],fit:['cover','contain'],loading:['lazy','eager'],radius:['none','s','m','l','pill'],variant:['primary','secondary','ghost'],size:['s','m','l'],layout:['horizontal','vertical']};
const BOOLEAN_DEFAULTS:Record<string,boolean>={showbrandtext:true,shownavigation:true,showutilities:false,showsearch:false,showaccount:false,showcart:false,mobilemenu:true,sticky:false,deferoffscreen:false};
const ARRAY_TEMPLATES:Record<string,Record<string,unknown>>={utilityitems:{label:'Új művelet',href:'/',symbol:'↗'},items:{label:'Új menüpont',href:'/'}};
const APPEARANCE_KEYS=new Set(['gap','spacing','align','justify','width','tone','direction','fit','radius','variant','size','background','backgroundColor','color','textColor','overlay','padding']);
const TECHNICAL_KEYS=new Set(['presentation','styleslots','style','innerstyle','brandstyle','taglinestyle','utilitystyle','mobiletogglestyle','behavior','deferoffscreen','intrinsicsize','schema','schemakey','componentkey','componentversion','typography','accentstyle','artdirection']);
const COMPONENT_LABELS:Record<string,string>={'system.header':'Fejléc','system.navigation':'Navigáció','layout.section':'Szekció','layout.container':'Konténer','layout.grid':'Rács','layout.stack':'Elrendezési csoport','content.heading':'Címsor','content.text':'Szöveg','content.image':'Kép','content.button':'Gomb','editorial.footer':'Lábléc','editorial.split-feature':'Kiemelt osztott blokk','commerce.product-grid':'Termékrács','commerce.collection-navigation':'Kollekció navigáció','commerce.checkout-summary':'Rendelési összegzés','commerce.cart-summary':'Kosár összegzés','commerce.review-summary':'Vásárlói értékelések','commerce.recommendation-row':'Ajánlott termékek','guided.finder':'Termékkereső','guided.results':'Találatok','visual.layered-canvas':'Rétegezett vizuális blokk','visual.layer':'Vizuális réteg'};
const COMPONENT_HELP:Record<string,string>={'system.header':'A webshop fejlécének márkája, navigációja, gyorsműveletei, mobil viselkedése és megjelenése.','system.navigation':'A fejlécben megjelenő elsődleges navigáció. A központi menüadatot ugyanaz a binding authority szolgáltatja.','layout.section':'Teljes szélességű oldalszakasz, amely további elemeket fog össze.','layout.container':'Tartalomszélességet és belső térközt szabályozó konténer.','layout.grid':'Rácsalapú elrendezés oszlopokkal és reszponzív szélességekkel.','layout.stack':'Egymás mellé vagy alá rendezett elemek.','content.heading':'Szerkeszthető címsor tipográfiai és igazítási beállításokkal.','content.text':'Törzsszöveg vagy rövid szöveges elem.','content.image':'Kép, képleírás, fókusz és méretezési beállítások.','content.button':'Hivatkozás vagy CTA megjelenése és mérete.'};
const normalize=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'');
const humanize=(value:string)=>value.replace(/([a-z0-9])([A-Z])/g,'$1 $2').replace(/[._:-]+/g,' ').replace(/\b\w/g,letter=>letter.toUpperCase());
const pageLabel=(page:Pick<StorefrontBuilderPageListItem,'pageKey'|'pageType'>|Pick<StorefrontPageDocument,'pageKey'|'pageType'>)=>PAGE_LABELS[normalize(page.pageType||page.pageKey)]??humanize(page.pageType||page.pageKey);
const fieldLabel=(key:string)=>FIELD_LABELS[normalize(key)]??humanize(key);
const componentLabel=(key:string)=>COMPONENT_LABELS[key]??humanize(key.split('.').at(-1)??key);
const optionLabel=(value:string)=>OPTION_LABELS[value]??humanize(value);
const iconFor=(key:string):VisualBuilderIconName=>{const value=key.toLowerCase();if(value.includes('header'))return'header';if(value.includes('footer'))return'footer';if(value.includes('image')||value.includes('gallery')||value.includes('video'))return'image';if(value.includes('navigation')||value.includes('menu'))return'menu';if(value.includes('text')||value.includes('heading')||value.includes('copy'))return'text';if(value.includes('product')||value.includes('collection'))return'box';if(value.includes('review'))return'star';if(value.includes('hero')||value.includes('section')||value.includes('layout'))return'layout';return'component'};
const groupFor=(key:string)=>{const value=key.toLowerCase();if(value.includes('cart')||value.includes('finder')||value.includes('recipe')||value.includes('shop-the-look'))return'Interaktív kereskedelem';if(value.includes('product')||value.includes('collection')||value.includes('recommend')||value.includes('cta'))return'Kereskedelem';if(value.includes('image')||value.includes('gallery')||value.includes('video'))return'Média';if(value.includes('navigation')||value.includes('menu')||value.includes('header')||value.includes('footer'))return'Navigáció';if(value.includes('review')||value.includes('editorial')||value.includes('text')||value.includes('heading'))return'Tartalom';if(value.includes('section')||value.includes('container')||value.includes('grid')||value.includes('stack')||value.includes('button'))return'Alap elemek';return'Egyéb'};
const responsiveModeLabel=(mode:string)=>mode==='fixed'?'Fix elem':mode==='grid'?'Rugalmas rács':mode==='stack'?'Egymás alá rendeződik':'Reszponzív';
const isAppearance=(key:string)=>APPEARANCE_KEYS.has(key)||key==='style'||key.endsWith('Style');
const operationKey=(kind:string)=>`builder:final:${kind}:${crypto.randomUUID()}`;
const statusLabel=(status:StorefrontFidelityInspectorStatus)=>status==='ok'?'Rendben':status==='warning'?'Figyelmeztetés':'Javítandó';
const pageStatus=(page:StorefrontBuilderPageListItem)=>page.draftRevision?`Piszkozat · r${page.draftRevision}`:page.publishedRevision?`Közzétett · r${page.publishedRevision}`:'Nincs mentett változat';

function flatten(document:StorefrontPageDocument){const result:FlatNode[]=[];const walk=(nodes:StorefrontComponentNode[],parentId:string|null,depth:number)=>nodes.forEach((node,index)=>{result.push({node,parentId,index,depth});walk(node.children??[],node.id,depth+1)});walk(document.sections,null,0);return result}
function getNode(document:StorefrontPageDocument,id:string|null){return id?flatten(document).find(item=>item.node.id===id)?.node??null:null}
function setNested(value:unknown,path:(string|number)[],next:unknown):unknown{if(!path.length)return next;const[head,...tail]=path;if(Array.isArray(value)){const copy=[...value];copy[Number(head)]=setNested(copy[Number(head)],tail,next);return copy}const source=value&&typeof value==='object'?value as Record<string,unknown>:{};return{...source,[String(head)]:setNested(source[String(head)],tail,next)}}
function moveArrayItem(items:unknown[],from:number,to:number){const next=[...items];const[item]=next.splice(from,1);if(item!==undefined)next.splice(Math.max(0,Math.min(to,next.length)),0,item);return next}

function ScalarEditor({name,value,onChange}:{name:string;value:unknown;onChange:(value:unknown)=>void}){
  const label=fieldLabel(name);const normalized=normalize(name);
  if(Object.prototype.hasOwnProperty.call(BOOLEAN_DEFAULTS,normalized)){const checked=typeof value==='boolean'?value:BOOLEAN_DEFAULTS[normalized]??false;return <label className={css.toggle}><span>{label}</span><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/></label>}
  if(typeof value==='boolean')return <label className={css.toggle}><span>{label}</span><input type="checkbox" checked={value} onChange={event=>onChange(event.target.checked)}/></label>;
  if(typeof value==='number')return <label className={css.field}><span>{label}</span><input type="number" value={value} onChange={event=>onChange(Number(event.target.value))}/></label>;
  const options=TOKEN_OPTIONS[name];if(options)return <label className={css.field}><span>{label}</span><select value={typeof value==='string'?value:''} onChange={event=>onChange(event.target.value)}><option value="">Alapértelmezett</option>{options.map(item=><option key={item} value={item}>{optionLabel(item)}</option>)}</select></label>;
  const stringValue=typeof value==='string'?value:'';const isColor=normalized.endsWith('color')||normalized==='color'||normalized==='background';if(isColor)return <label className={css.field}><span>{label}</span><span style={{display:'grid',gridTemplateColumns:'44px 1fr',gap:6}}><input type="color" aria-label={`${label} színválasztó`} value={/^#[0-9a-f]{6}$/i.test(stringValue)?stringValue:'#ffffff'} onChange={event=>onChange(event.target.value)}/><input value={stringValue} placeholder="#ffffff" onChange={event=>onChange(event.target.value)}/></span></label>;
  const multiline=normalized.includes('text')||normalized.includes('copy')||normalized.includes('description')||stringValue.length>80;return <label className={css.field}><span>{label}</span>{multiline?<textarea rows={4} value={stringValue} onChange={event=>onChange(event.target.value)}/>:<input value={stringValue} onChange={event=>onChange(event.target.value)}/>}</label>;
}
function StructuredEditor({name,value,onChange}:{name:string;value:unknown;onChange:(value:unknown)=>void}){
  if(value===null||value===undefined||typeof value!=='object')return <ScalarEditor name={name} value={value??''} onChange={onChange}/>;
  if(Array.isArray(value)){
    const template=ARRAY_TEMPLATES[normalize(name)];
    return <div className={css.sectionCard}><div className={css.sectionTitle}><strong>{fieldLabel(name)}</strong><small>{value.length} elem</small></div>{value.map((item,index)=><div className={css.sectionCard} key={index}><div className={css.sectionTitle}><strong>{index+1}. elem</strong><span style={{display:'flex',gap:4}}><button type="button" className={css.iconButton} disabled={index===0} title="Feljebb" onClick={()=>onChange(moveArrayItem(value,index,index-1))}><VisualBuilderIcon name="chevron-up"/></button><button type="button" className={css.iconButton} disabled={index===value.length-1} title="Lejjebb" onClick={()=>onChange(moveArrayItem(value,index,index+1))}><VisualBuilderIcon name="chevron-down"/></button><button type="button" className={css.iconButton} title="Eltávolítás" onClick={()=>onChange(value.filter((_,itemIndex)=>itemIndex!==index))}><VisualBuilderIcon name="trash"/></button></span></div><StructuredEditor name={`${index+1}. elem`} value={item} onChange={next=>onChange(setNested(value,[index],next))}/></div>)}{!value.length?<p className={css.hint}>Nincs beállított elem.</p>:null}{template?<button type="button" className={css.secondary} onClick={()=>onChange([...value,structuredClone(template)])}><VisualBuilderIcon name="plus"/> Új elem hozzáadása</button>:null}</div>;
  }
  return <div className={css.sectionCard}><div className={css.sectionTitle}><strong>{fieldLabel(name)}</strong></div>{Object.entries(value as Record<string,unknown>).map(([key,child])=><StructuredEditor key={key} name={key} value={child} onChange={next=>onChange(setNested(value,[key],next))}/>)}</div>;
}
function BoundField({name,value}:{name:string;value:unknown}){const display=Array.isArray(value)?`${value.length} elem`:value&&typeof value==='object'?'Globális beállítás':value===null||value===undefined||value===''?'Nincs megadva':String(value);return <div className={css.bound}><div className={css.boundHead}><span>{fieldLabel(name)}</span><b className={css.boundBadge}>Webshop adat</b></div><div className={css.boundValue}>{display}</div><p className={css.hint}>Központi webshop-adat. Itt csak olvasható, így a vászon és a tényleges beállítás mindig ugyanazt mutatja.</p></div>}

function contentGroups(componentKey:string,keys:string[]):FieldGroup[]{
  if(componentKey!=='system.header')return[{title:'Tartalom és működés',description:`${keys.length} beállítás`,keys}];
  const groups:FieldGroup[]=[
    {title:'Márka',description:'Logó, márkanév és szlogen',keys:['brandLabel','brandHref','brandLogoSrc','brandLogoAlt','showBrandText','tagline']},
    {title:'Navigáció és gyorsműveletek',description:'Menü, keresés, fiók és kosár',keys:['showNavigation','showSearch','searchHref','showAccount','accountHref','showCart','cartHref','showUtilities','utilityItems']},
    {title:'Viselkedés',description:'Rögzítés és mobil menü',keys:['sticky','mobileMenu']},
  ];
  const used=new Set(groups.flatMap(group=>group.keys));const remaining=keys.filter(key=>!used.has(key));if(remaining.length)groups.push({title:'További beállítások',description:'Kiegészítő fejléc opciók',keys:remaining});return groups.map(group=>({...group,keys:group.keys.filter(key=>keys.includes(key))})).filter(group=>group.keys.length);
}
function appearanceGroups(componentKey:string,keys:string[]):FieldGroup[]{
  if(componentKey!=='system.header')return[{title:'Megjelenési beállítások',description:`${keys.length} kontroll`,keys}];
  const layout=['spacing','width','gap','align','justify','size'];const colors=['tone','backgroundColor','color'];const used=new Set([...layout,...colors]);const groups=[{title:'Méret és elrendezés',description:'Térköz, szélesség és igazítás',keys:layout.filter(key=>keys.includes(key))},{title:'Színek és felület',description:'Háttér és szövegszín',keys:colors.filter(key=>keys.includes(key))}];const remaining=keys.filter(key=>!used.has(key));if(remaining.length)groups.push({title:'További megjelenés',description:'Kiegészítő vizuális beállítások',keys:remaining});return groups.filter(group=>group.keys.length);
}

function Outline({document,viewport,selectedId,onSelect,onMove}:{document:StorefrontPageDocument;viewport:StorefrontViewport;selectedId:string|null;onSelect:(id:string)=>void;onMove:(nodeId:string,parentId:string|null,index:number)=>void}){
  const items=flatten(document);const[dragging,setDragging]=useState<string|null>(null);const[collapsed,setCollapsed]=useState<Set<string>>(()=>new Set());const parentOf=(id:string)=>items.find(item=>item.node.id===id)?.parentId??null;const visible=(entry:FlatNode)=>{let parent=entry.parentId;while(parent){if(collapsed.has(parent))return false;parent=parentOf(parent)}return true};const toggle=(id:string)=>setCollapsed(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next});const drop=(event:DragEvent,entry:FlatNode)=>{event.preventDefault();if(dragging&&dragging!==entry.node.id)onMove(dragging,entry.parentId,entry.index);setDragging(null)};
  return <div className={css.library}><div className={css.libraryCard}><span className={css.libraryIcon}><VisualBuilderIcon name="page"/></span><span><strong>Oldal</strong><small>{pageLabel(document)}</small></span></div>{items.filter(visible).map(entry=>{const definition=registry.get(entry.node.componentKey,entry.node.componentVersion);const linked=findStorefrontLinkedSymbolInstance(document,entry.node.id);const protectedNode=definition?.protectedSystem===true;const hidden=entry.node.responsive?.[viewport]?.hidden===true;const hasChildren=Boolean(entry.node.children?.length);return <div key={entry.node.id} className={css.libraryCard} draggable={!protectedNode} onDragStart={()=>setDragging(entry.node.id)} onDragEnd={()=>setDragging(null)} onDragOver={event=>event.preventDefault()} onDrop={event=>drop(event,entry)} style={{marginLeft:Math.min(36,entry.depth*9),borderColor:selectedId===entry.node.id?'#8fd2c2':undefined}}><span className={css.libraryIcon}>{hasChildren?<button type="button" aria-label={collapsed.has(entry.node.id)?'Kibontás':'Összecsukás'} onClick={()=>toggle(entry.node.id)}><VisualBuilderIcon name={collapsed.has(entry.node.id)?'chevron-right':'chevron-down'}/></button>:<VisualBuilderIcon name={iconFor(entry.node.componentKey)}/>}</span><button type="button" onClick={()=>onSelect(entry.node.id)} style={{border:0,background:'transparent',padding:0,textAlign:'left',color:'inherit',cursor:'pointer'}}><strong>{componentLabel(entry.node.componentKey)}</strong><small>{linked?'Kapcsolt · ':''}{protectedNode?'Védett · ':''}{hidden?'Rejtett · ':''}{entry.depth===0?'Szekció':'Komponens'}</small></button><span><button type="button" disabled={protectedNode||entry.index===0} onClick={()=>onMove(entry.node.id,entry.parentId,Math.max(0,entry.index-1))}><VisualBuilderIcon name="chevron-up"/></button><button type="button" disabled={protectedNode} onClick={()=>onMove(entry.node.id,entry.parentId,entry.index+1)}><VisualBuilderIcon name="chevron-down"/></button></span></div>})}</div>;
}

export function StorefrontVisualBuilderFinal({pages,document:initialDocument,pageId,draftRevision:initialDraftRevision,publishedRevision:initialPublishedRevision,revisions,capability,bindingContext,templates,savedBlocks}:Props){
  const router=useRouter();const[busy,startTransition]=useTransition();const[history,setHistory]=useState<StorefrontBuilderHistory|null>(()=>initialDocument?createStorefrontBuilderHistory(initialDocument):null);const[selectedId,setSelectedId]=useState<string|null>(()=>initialDocument?.sections[0]?.id??null);const[viewport,setViewport]=useState<StorefrontViewport>('desktop');const[draftRevision,setDraftRevision]=useState(initialDraftRevision);const[publishedRevision,setPublishedRevision]=useState(initialPublishedRevision);const[dirty,setDirty]=useState(false);const[notice,setNotice]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[panelMode,setPanelMode]=useState<PanelMode>('pages');const[editorTab,setEditorTab]=useState<EditorTab>('content');const[historyOpen,setHistoryOpen]=useState(false);const[publishOpen,setPublishOpen]=useState(false);const[componentQuery,setComponentQuery]=useState('');const[componentFilter,setComponentFilter]=useState('Összes');const[pageQuery,setPageQuery]=useState('');
  const document=history?.present??null;const selected=document?getNode(document,selectedId):null;const definition=selected?registry.get(selected.componentKey,selected.componentVersion):undefined;const viewportWidth=VIEWPORTS.find(item=>item.key===viewport)?.width??1200;const flat=document?flatten(document):[];const selectedFlat=selected?flat.find(item=>item.node.id===selected.id)??null:null;const fidelity=document?inspectStorefrontFidelityBuilder(document):null;const advancedMode=fidelity?.editMode!=='normal';
  const rawBrand=bindingContext.brand&&typeof bindingContext.brand==='object'&&!Array.isArray(bindingContext.brand)?bindingContext.brand as Record<string,unknown>:{};const brandName=typeof rawBrand.name==='string'?rawBrand.name:'';const editorBindingContext:Record<string,unknown>={...bindingContext,brand:{...rawBrand,homeHref:typeof rawBrand.homeHref==='string'?rawBrand.homeHref:'/',copyright:typeof rawBrand.copyright==='string'?rawBrand.copyright:(brandName?`© ${brandName}`:'')}};
  useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(null),3200);return()=>window.clearTimeout(timer)},[notice]);
  const applyMutation=(base:StorefrontPageDocument,mutation:StorefrontBuilderMutation)=>applyStorefrontBuilderMutation({document:base,mutation,registry,capability});
  const commitDocument=(next:StorefrontPageDocument)=>{setHistory(current=>current?pushStorefrontBuilderHistory(current,next):current);setDirty(true);setError(null)};
  const mutate=(mutation:StorefrontBuilderMutation)=>{if(!document)return;try{commitDocument(applyMutation(document,mutation))}catch(reason){setError(reason instanceof Error?reason.message:'A módosítás nem hajtható végre.')}};
  const setMerchantConfig=(key:string,value:unknown)=>{if(!document||!selected)return;try{let next=applyMutation(document,{type:'config',nodeId:selected.id,key,value});const binding=selected.bindings?.[key];if(binding&&Object.prototype.hasOwnProperty.call(binding,'fallback'))next=applyMutation(next,{type:'binding',nodeId:selected.id,slot:key,path:binding.path,fallback:value});commitDocument(next)}catch(reason){setError(reason instanceof Error?reason.message:'A módosítás nem hajtható végre.')}};
  const applyExternal=(next:StorefrontPageDocument,message:string,nodeId?:string)=>{commitDocument(next);setNotice(message);if(nodeId)setSelectedId(nodeId)};
  const run=(job:()=>Promise<void>)=>startTransition(()=>{setError(null);job().catch(reason=>setError(reason instanceof Error?reason.message:'A művelet sikertelen.'))});
  const move=(nodeId:string,parentId:string|null,index:number)=>mutate({type:'move',nodeId,parentId,index});
  const save=()=>{if(!document)return;run(async()=>{const result=await saveVisualBuilderDraftAction({document,expectedDraftRevision:draftRevision,operationKey:operationKey('save')});setDraftRevision(result.revisionNumber);setDirty(false);setNotice(`Mentve · r${result.revisionNumber}`);router.refresh()})};
  const preview=()=>{if(!pageId||!draftRevision)return;run(async()=>{if(dirty)throw new Error('Előnézet előtt mentsd a módosításokat.');const result=await createVisualBuilderPreviewAction({pageId,revisionNumber:draftRevision,operationKey:operationKey('preview')});window.open(`${result.href}?viewport=${viewport}`,'_blank','noopener,noreferrer');setNotice(`Előnézet létrehozva · r${result.revisionNumber}`)})};
  const publish=()=>{if(!pageId||!draftRevision)return;run(async()=>{if(dirty)throw new Error('Közzététel előtt mentsd a módosításokat.');const result=await publishVisualBuilderPageAction({pageId,expectedDraftRevision:draftRevision,operationKey:operationKey('publish')});setPublishedRevision(result.revisionNumber);setPublishOpen(false);setNotice(`Közzétéve · r${result.revisionNumber}`);router.refresh()})};
  const rollback=(target:number)=>{if(!pageId||!publishedRevision)return;run(async()=>{const result=await rollbackVisualBuilderPageAction({pageId,targetPublishedRevision:target,expectedCurrentPublishedRevision:publishedRevision,operationKey:operationKey('rollback')});setPublishedRevision(result.revisionNumber);setNotice(`Visszaállítva · r${result.revisionNumber}`);router.refresh()})};
  const install=(template:TemplateEntry)=>run(async()=>{const result=await installVisualBuilderTemplateAction({templateKey:template.templateKey,templateVersion:template.templateVersion,operationKey:operationKey('template')});setNotice(`${result.templateKey} telepítve · ${result.pageCount} oldal`);router.refresh()});
  const entitled=(template:TemplateEntry)=>hasStorefrontRuntimeCapability({minPlan:template.minPlan,features:template.requiredFeatures as readonly FeatureCode[]},capability);

  if(!document)return <div className={css.shell}><header className={css.topbar}><div className={css.brand}><span className={css.mark}>S</span><span><strong>Shoperation</strong><small>Visual Builder</small></span></div><Link className={css.back} href="/admin"><VisualBuilderIcon name="arrow-left"/> Vissza az Admin felületre</Link></header><div className={css.stage}><div className={css.panelHead}><div><strong>Indulj egy valódi sablonból</strong><small>A sablon szerkeszthető piszkozatként kerül be.</small></div></div><div className={css.library}>{templates.map(template=><article className={css.libraryCard} key={`${template.templateKey}@${template.templateVersion}`}><span className={css.libraryIcon}><VisualBuilderIcon name="templates"/></span><span><strong>{humanize(template.templateKey)}</strong><small>{template.category} · {template.pageTypes.length} oldal · {template.minPlan==='pro'?'Pro':'Alap'}</small></span><button type="button" disabled={!entitled(template)||busy} onClick={()=>install(template)}>Használat</button></article>)}</div></div></div>;

  const effectiveConfig=selected?applyStorefrontBindings(selected,editorBindingContext):{};const externallyBound=(key:string)=>{const binding=selected?.bindings?.[key];return Boolean(binding&&resolveStorefrontBinding(binding.path,editorBindingContext)!==undefined)};const configurable=(definition?.manifest.configurable??[]).filter(key=>advancedMode||!TECHNICAL_KEYS.has(normalize(key)));const contentKeys=configurable.filter(key=>!isAppearance(key));const appearanceKeys=configurable.filter(key=>isAppearance(key));const variants=selected?listStorefrontComponentVariants(registry,selected):[];const activeVariant=selected?detectStorefrontComponentVariant(registry,selected):null;const responsive=selected?.responsive?.[viewport];const responsiveOverride=Boolean(responsive&&(responsive.hidden===true||responsive.gridSpan!==undefined));const insertableSelected=selected?listStorefrontBuilderInsertableComponents({document,registry,capability,parentId:selected.id}):[];const insertableRoot=listStorefrontBuilderInsertableComponents({document,registry,capability,parentId:null});const insertable=[...insertableRoot,...insertableSelected.filter(item=>!insertableRoot.some(root=>root.componentKey===item.componentKey&&root.componentVersion===item.componentVersion))];const groups=['Összes',...Array.from(new Set(insertable.map(item=>groupFor(item.componentKey))))];const visibleInsertable=insertable.filter(item=>{const query=componentQuery.trim().toLowerCase();return(!query||`${item.componentKey} ${componentLabel(item.componentKey)}`.toLowerCase().includes(query))&&(componentFilter==='Összes'||groupFor(item.componentKey)===componentFilter)});const visiblePages=pages.filter(page=>!pageQuery.trim()||pageLabel(page).toLowerCase().includes(pageQuery.trim().toLowerCase()));
  const addComponent=(item:{componentKey:string;componentVersion:number},parentId:string|null)=>{const nodeId=`${item.componentKey.replace(/[^a-z0-9._:-]+/gi,'-')}-${crypto.randomUUID().slice(0,8)}`.toLowerCase().slice(0,127);mutate({type:'add',parentId,componentKey:item.componentKey,componentVersion:item.componentVersion,nodeId});setSelectedId(nodeId);setEditorTab('content')};
  const selectNode=(id:string)=>{setSelectedId(id);setEditorTab('content')};
  const renderField=(key:string)=>externallyBound(key)?<BoundField key={key} name={key} value={effectiveConfig[key]}/>:<StructuredEditor key={key} name={key} value={selected?.config[key]??''} onChange={value=>setMerchantConfig(key,value)}/>;
  const canvasDecorator=(node:StorefrontResolvedComponentNode,rendered:ReactNode)=>{const entry=flat.find(item=>item.node.id===node.id);const nodeDefinition=registry.get(node.componentKey,node.componentVersion);const protectedNode=nodeDefinition?.protectedSystem===true;const active=selectedId===node.id;return <div className={css.node} data-selected={active} onClick={event=>{event.stopPropagation();selectNode(node.id)}}>{active?<><span className={css.nodeLabel}>{componentLabel(node.componentKey)}{protectedNode?' · védett':''}</span><div className={css.floating} onClick={event=>event.stopPropagation()}><button type="button" aria-label="Tartalom" title="Tartalom" onClick={()=>setEditorTab('content')}><VisualBuilderIcon name="edit"/></button><button type="button" aria-label="Felfelé" title="Felfelé" disabled={!entry||entry.index===0||protectedNode} onClick={()=>entry&&move(node.id,entry.parentId,Math.max(0,entry.index-1))}><VisualBuilderIcon name="chevron-up"/></button><button type="button" aria-label="Lefelé" title="Lefelé" disabled={!entry||protectedNode} onClick={()=>entry&&move(node.id,entry.parentId,entry.index+1)}><VisualBuilderIcon name="chevron-down"/></button><button type="button" aria-label="Duplikálás" title="Duplikálás" disabled={protectedNode} onClick={()=>mutate({type:'duplicate',nodeId:node.id})}><VisualBuilderIcon name="duplicate"/></button><button type="button" aria-label="Elrendezés" title="Elrendezés" onClick={()=>setEditorTab('responsive')}><VisualBuilderIcon name="mobile"/></button><button type="button" aria-label="Megjelenés" title="Megjelenés" onClick={()=>setEditorTab('appearance')}><VisualBuilderIcon name="settings"/></button><button type="button" data-danger="true" aria-label="Törlés" title="Törlés" disabled={protectedNode} onClick={()=>{mutate({type:'remove',nodeId:node.id});setSelectedId(null)}}><VisualBuilderIcon name="trash"/></button></div></>:null}{rendered}</div>};
  const fidelityState=fidelity!;const viewportStatus=(target:StorefrontViewport):StorefrontFidelityInspectorStatus=>{const issues=fidelityState.layout.issues.filter(issue=>issue.viewport===target);return issues.some(issue=>issue.severity==='error')?'error':issues.length?'warning':'ok'};const imageIssues=fidelityState.accessibility.issues.filter(issue=>issue.code.startsWith('ACCESSIBILITY_IMAGE_'));const linkIssues=fidelityState.accessibility.issues.filter(issue=>issue.code.includes('HREF')||issue.code.includes('CONTROL_LABEL'));const contentIssues=fidelityState.accessibility.issues.filter(issue=>issue.code.includes('HEADING'));const issueStatus=(items:readonly {severity:'warning'|'error'}[]):StorefrontFidelityInspectorStatus=>items.some(item=>item.severity==='error')?'error':items.length?'warning':'ok';const readiness=[{label:'Mentett piszkozat',status:(dirty||!draftRevision?'error':'ok') as StorefrontFidelityInspectorStatus,detail:dirty?'Mentsd a módosításokat.':draftRevision?`r${draftRevision}`:'Nincs mentett piszkozat.'},...VIEWPORTS.map(item=>({label:`${item.label} nézet`,status:viewportStatus(item.key),detail:viewportStatus(item.key)==='ok'?'Nincs ismert elrendezési probléma.':'Ellenőrizd a jelzett elrendezési problémát.'})),{label:'Akadálymentesség',status:fidelityState.accessibility.status,detail:fidelityState.accessibility.issues.length?`${fidelityState.accessibility.issues.length} jelzés.`:'Rendben.'},{label:'Képek',status:issueStatus(imageIssues),detail:imageIssues.length?`${imageIssues.length} jelzés.`:'Rendben.'},{label:'Linkek',status:issueStatus(linkIssues),detail:linkIssues.length?`${linkIssues.length} jelzés.`:'Rendben.'},{label:'Kötelező tartalmak',status:issueStatus(contentIssues),detail:contentIssues.length?`${contentIssues.length} jelzés.`:'Rendben.'},{label:'Teljesítmény',status:fidelityState.performance.status,detail:fidelityState.performance.issues.length?`${fidelityState.performance.issues.length} jelzés.`:'Rendben.'},{label:'Optimalizálás',status:fidelityState.performance.status,detail:fidelityState.performance.issues.length?'Van optimalizálási teendő.':'Nincs külön optimalizálási teendő.'},{label:'Design Guard',status:(fidelityState.designGuard.mode==='off'?'warning':'ok') as StorefrontFidelityInspectorStatus,detail:fidelityState.designGuard.mode==='off'?'Kikapcsolva.':`Aktív: ${fidelityState.designGuard.mode}.`}];const readinessErrors=readiness.filter(item=>item.status==='error').length;
  const spacingKey=appearanceKeys.includes('spacing')?'spacing':appearanceKeys.includes('gap')?'gap':null;const alignKey=appearanceKeys.includes('align')?'align':null;const widthKey=appearanceKeys.includes('width')?'width':null;const sizeKey=appearanceKeys.includes('size')?'size':null;

  return <div className={css.shell}>
    <header className={css.topbar}><div className={css.brand}><span className={css.mark}>S</span><span><strong>Shoperation</strong><small>Visual Builder</small></span></div><Link className={css.back} href="/admin"><VisualBuilderIcon name="arrow-left"/> Vissza az Admin felületre</Link><select className={css.pageSelect} aria-label="Szerkesztett oldal" value={document.pageKey} onChange={event=>router.push(`/admin/tartalom/builder?page=${encodeURIComponent(event.target.value)}`)}>{pages.map(page=><option key={page.pageId} value={page.pageKey}>{pageLabel(page)}</option>)}</select><div className={css.devices} role="group" aria-label="Szerkesztési nézet">{VIEWPORTS.map(item=><button key={item.key} type="button" data-active={viewport===item.key} aria-pressed={viewport===item.key} onClick={()=>setViewport(item.key)}><VisualBuilderIcon name={item.icon}/>{item.label}</button>)}</div><div className={css.actions}><button className={css.iconButton} type="button" disabled={busy||!history?.past.length} title="Visszavonás" aria-label="Visszavonás" onClick={()=>{setHistory(current=>current?undoStorefrontBuilderHistory(current):current);setDirty(true)}}><VisualBuilderIcon name="undo"/></button><button className={css.iconButton} type="button" disabled={busy||!history?.future.length} title="Újra" aria-label="Újra" onClick={()=>{setHistory(current=>current?redoStorefrontBuilderHistory(current):current);setDirty(true)}}><VisualBuilderIcon name="redo"/></button><span className={css.saveState}>{dirty?'Nem mentett':draftRevision?`Mentve · r${draftRevision}`:'Piszkozat'}</span><button className={css.secondary} type="button" disabled={busy||!dirty} onClick={save}>Mentés</button><button className={css.secondary} type="button" onClick={()=>setHistoryOpen(true)}><VisualBuilderIcon name="history"/> Előzmények</button><button className={css.secondary} type="button" disabled={busy||dirty||!draftRevision} onClick={preview}><VisualBuilderIcon name="eye"/> Előnézet</button><button className={css.publish} type="button" disabled={busy||!draftRevision} onClick={()=>setPublishOpen(true)}><VisualBuilderIcon name="upload"/> Közzététel</button></div></header>
    {error?<div className={css.error} role="alert">{error}</div>:null}{notice?<div className={css.toast} role="status"><VisualBuilderIcon name="check"/>{notice}</div>:null}
    <div className={css.workspace}><aside className={css.left}><nav className={css.primaryNav} aria-label="Visual Builder fő navigáció">{([['pages','pages','Oldalak'],['add','plus','Hozzáadás'],['structure','layers','Rétegek'],['templates','templates','Sablonok'],['presets','presets','Presetek'],['saved','saved','Saját blokkok'],['globals','globals','Globális elemek']] as const).map(([mode,icon,label])=><button key={mode} type="button" data-active={panelMode===mode} aria-current={panelMode===mode?'page':undefined} onClick={()=>setPanelMode(mode)}><VisualBuilderIcon name={icon}/>{label}</button>)}</nav><div className={css.panel}>
      {panelMode==='pages'?<><div className={css.panelHead}><div><strong>Oldalak</strong><small>Válassz oldalt a szerkesztéshez.</small></div></div><input className={css.search} type="search" placeholder="Oldal keresése…" aria-label="Oldalak keresése" value={pageQuery} onChange={event=>setPageQuery(event.target.value)}/><div className={css.pageList}>{visiblePages.map(page=><Link key={page.pageId} data-active={page.pageKey===document.pageKey} href={`/admin/tartalom/builder?page=${encodeURIComponent(page.pageKey)}`}><span className={css.pageIcon}><VisualBuilderIcon name={page.pageKey===document.pageKey?'home':'page'}/></span><span><strong>{pageLabel(page)}</strong><small>{pageStatus(page)}</small></span></Link>)}</div>{!visiblePages.length?<p className={css.hint}>Nincs a keresésnek megfelelő oldal.</p>:null}</>:null}
      {panelMode==='add'?<><div className={css.panelHead}><div><strong>Hozzáadás</strong><small>Valódi, kompatibilis komponensek a jelenlegi oldalhoz.</small></div></div><input className={css.search} type="search" placeholder="Elem keresése…" aria-label="Komponensek keresése" value={componentQuery} onChange={event=>setComponentQuery(event.target.value)}/><div className={css.filterTabs}>{groups.map(group=><button type="button" key={group} data-active={componentFilter===group} onClick={()=>setComponentFilter(group)}>{group}</button>)}</div><div className={css.library}>{visibleInsertable.map(item=>{const canSelected=Boolean(selected&&insertableSelected.some(candidate=>candidate.componentKey===item.componentKey&&candidate.componentVersion===item.componentVersion));const canRoot=insertableRoot.some(candidate=>candidate.componentKey===item.componentKey&&candidate.componentVersion===item.componentVersion);return <article className={css.libraryCard} key={`${item.componentKey}@${item.componentVersion}`}><span className={css.libraryIcon}><VisualBuilderIcon name={iconFor(item.componentKey)}/></span><span><strong>{componentLabel(item.componentKey)}</strong><small>{groupFor(item.componentKey)} · {responsiveModeLabel(item.responsiveMode)}</small></span>{canSelected?<button type="button" onClick={()=>addComponent(item,selected?.id??null)}>Beillesztés</button>:canRoot?<button type="button" onClick={()=>addComponent(item,null)}>Hozzáadás</button>:null}</article>})}</div>{!visibleInsertable.length?<p className={css.hint}>Nincs a szűrésnek megfelelő elem.</p>:null}</>:null}
      {panelMode==='structure'?<><div className={css.panelHead}><div><strong>Rétegek</strong><small>Oldal → Szekció → Konténer → Komponens.</small></div></div><Outline document={document} viewport={viewport} selectedId={selectedId} onSelect={selectNode} onMove={move}/></>:null}
      {panelMode==='templates'?<><div className={css.panelHead}><div><strong>Sablonok</strong><small>Teljes oldal- és webshop-sablonok.</small></div><button type="button" onClick={()=>{if(dirty){setError('A sablonkönyvtár megnyitása előtt mentsd a módosításokat.');return}router.push('/admin/tartalom/builder?view=templates')}}>Könyvtár</button></div><StorefrontPageTemplatesPanel document={document} capability={capability} onApply={(next,nodeId,message)=>applyExternal(next,message,nodeId)}/></>:null}
      {panelMode==='presets'?<><div className={css.panelHead}><div><strong>Presetek</strong><small>Gyári szekció- és komponens-megjelenések.</small></div></div><StorefrontPresetLibraryPanel document={document} selectedNode={selected} capability={capability} onApply={(next,nodeId,message)=>applyExternal(next,message,nodeId)}/></>:null}
      {panelMode==='saved'?<StorefrontOwnBlocksPanel document={document} selectedNode={selected} selectedIsTopLevel={selectedFlat?.parentId===null} initialSavedBlocks={savedBlocks} capability={capability} onApply={(next,nodeId,message)=>applyExternal(next,message,nodeId)}/>:null}
      {panelMode==='globals'?<><StorefrontGlobalElementsPanel document={document} selectedNode={selected} selectedIsTopLevel={selectedFlat?.parentId===null} capability={capability} onApply={(next,nodeId,message)=>applyExternal(next,message,nodeId)}/><div style={{height:14}}/><div className={css.panelHead}><div><strong>Globális stílusok és minőség</strong><small>Színek, tipográfia, Design Guard, accessibility és performance.</small></div></div><StorefrontFidelitySettings document={document} viewport={viewport} onApply={(next,message)=>applyExternal(next,message)}/></>:null}
    </div></aside>
    <main className={css.stage} onClick={()=>setSelectedId(null)}><div className={css.viewportBadge}><VisualBuilderIcon name={viewport==='desktop'?'desktop':viewport==='tablet'?'tablet':'mobile'}/><span>{viewport==='desktop'?'Desktop':viewport==='tablet'?'Tablet':'Mobil'} · {viewportWidth}px</span><b>{selected?(responsiveOverride?'Egyedi override':'Örökölt'):'Élő nézet'}</b></div>{viewport==='mobile'?<div className={css.statusCard} style={{width:'min(100%,390px)',margin:'0 auto 12px'}}><VisualBuilderIcon name="mobile"/><div><strong>Mobil nézet</strong><small>Az aktív vászon és az Inspector ugyanazt a mobil breakpointot szerkeszti.</small></div></div>:null}<div className={css.frame} style={{width:`min(100%, ${viewportWidth}px)`}}><StorefrontRuntimeRenderer page={document} viewport={viewport} bindingContext={editorBindingContext} componentRegistry={registry} rendererRegistry={rendererRegistry} capability={capability} decorateNode={canvasDecorator}/></div></main>
    <aside className={css.inspector}>{selected&&definition?<><div className={css.inspectorHeader}><div className={css.selection}><span className={css.selectionIcon}><VisualBuilderIcon name={iconFor(selected.componentKey)}/></span><span><strong>{componentLabel(selected.componentKey)}</strong><small>{advancedMode?selected.componentKey:(definition.protectedSystem?'Védett rendszer elem':groupFor(selected.componentKey))}</small></span></div><span className={css.modeBadge}>{fidelityState.editMode==='normal'?'Normál':fidelityState.editMode==='advanced'?'Haladó':'Expert'}</span></div><div className={css.tabs} data-advanced={advancedMode} aria-label="Inspector navigáció"><button type="button" data-active={editorTab==='content'} onClick={()=>setEditorTab('content')}>Tartalom</button><button type="button" data-active={editorTab==='appearance'} onClick={()=>setEditorTab('appearance')}>Megjelenés</button><button type="button" data-active={editorTab==='responsive'} onClick={()=>setEditorTab('responsive')}>Elrendezés</button>{advancedMode?<button type="button" data-active={editorTab==='advanced'} onClick={()=>setEditorTab('advanced')}>Haladó</button>:null}</div><div className={css.inspectorBody}>
      <div className={css.statusCard}><VisualBuilderIcon name="info"/><div><strong>{componentLabel(selected.componentKey)}</strong><small>{COMPONENT_HELP[selected.componentKey]??'A kijelölt elem beállításai a közös Page Schema authorityt módosítják.'}</small></div></div>
      {editorTab==='content'?<>{contentGroups(selected.componentKey,contentKeys).map(group=><div className={css.sectionCard} key={group.title}><div className={css.sectionTitle}><strong>{group.title}</strong><small>{group.description}</small></div>{group.keys.map(renderField)}</div>)}{selected.children?.length?<div className={css.sectionCard}><div className={css.sectionTitle}><strong>Belső elemek</strong><small>{selected.children.length} elem</small></div>{selected.children.map(child=><button type="button" className={css.variantCard} key={child.id} onClick={()=>selectNode(child.id)}><strong>{componentLabel(child.componentKey)}</strong><small>Kattints a részletes szerkesztéshez.</small></button>)}</div>:null}</>:null}
      {editorTab==='appearance'?<><div className={css.sectionCard}><div className={css.sectionTitle}><strong>Gyors beállítások</strong><small>A leggyakoribb módosítások</small></div><div className={css.quickGrid}>{widthKey?<><button type="button" onClick={()=>setMerchantConfig(widthKey,'full')}>Teljes szélesség</button><button type="button" onClick={()=>setMerchantConfig(widthKey,'content')}>Tartalmi szélesség</button></>:null}{spacingKey?<><button type="button" onClick={()=>setMerchantConfig(spacingKey,'l')}>Tágasabb</button><button type="button" onClick={()=>setMerchantConfig(spacingKey,'s')}>Kompaktabb</button></>:null}{alignKey?<><button type="button" onClick={()=>setMerchantConfig(alignKey,'start')}>Elejére</button><button type="button" onClick={()=>setMerchantConfig(alignKey,'center')}>Középre</button></>:null}{sizeKey?<><button type="button" onClick={()=>setMerchantConfig(sizeKey,'s')}>Kisebb</button><button type="button" onClick={()=>setMerchantConfig(sizeKey,'l')}>Nagyobb</button></>:null}</div>{!widthKey&&!spacingKey&&!alignKey&&!sizeKey?<p className={css.hint}>Ehhez az elemhez nincs gyorsbeállítás.</p>:null}</div>{variants.length?<div className={css.sectionCard}><div className={css.sectionTitle}><strong>Megjelenési variánsok</strong><small>{activeVariant?.label??'Egyedi'}</small></div><div className={css.variants}>{variants.map(variant=><button key={variant.variantId} type="button" className={css.variantCard} data-active={activeVariant?.variantId===variant.variantId} onClick={()=>applyExternal(applyStorefrontComponentVariant(document,{nodeId:selected.id,variantId:variant.variantId},registry),`${variant.label} variáns alkalmazva.`,selected.id)}><strong>{variant.label}</strong><small>{variant.description}</small></button>)}</div></div>:null}{appearanceGroups(selected.componentKey,appearanceKeys).map(group=><div className={css.sectionCard} key={group.title}><div className={css.sectionTitle}><strong>{group.title}</strong><small>{group.description}</small></div>{group.keys.map(renderField)}</div>)}</>:null}
      {editorTab==='responsive'?<><div className={css.sectionCard}><div className={css.sectionTitle}><strong>Reszponzív öröklés</strong><small>{responsiveOverride?'Egyedi override':'Örökölt érték'}</small></div><div className={css.responsiveRail}>{VIEWPORTS.map(item=><span key={item.key} data-active={item.key===viewport}>{item.label}</span>)}</div><p className={css.hint}>{viewport==='desktop'?'Alap → Desktop':viewport==='tablet'?'Desktop → Tablet':'Desktop → Tablet → Mobil'} öröklési lánc. Az aktív nézet és a vászon mindig ugyanaz.</p></div><div className={css.sectionCard}><label className={css.toggle}><span>Elrejtés ezen a nézeten</span><input type="checkbox" checked={selected.responsive?.[viewport]?.hidden??false} onChange={event=>mutate({type:'responsive',nodeId:selected.id,viewport,hidden:event.target.checked})}/></label>{definition.manifest.responsiveMode!=='fixed'?<label className={css.field}><span>Rácsszélesség</span><select value={selected.responsive?.[viewport]?.gridSpan??''} onChange={event=>mutate({type:'responsive',nodeId:selected.id,viewport,gridSpan:event.target.value?Number(event.target.value):null})}><option value="">Örökölt</option>{Array.from({length:12},(_,index)=>index+1).map(value=><option key={value} value={value}>{value} / 12</option>)}</select></label>:null}{responsiveOverride?<button type="button" className={css.secondary} onClick={()=>mutate({type:'responsive',nodeId:selected.id,viewport,hidden:false,gridSpan:null})}><VisualBuilderIcon name="reset"/> Öröklés visszaállítása</button>:null}</div></>:null}
      {editorTab==='advanced'&&advancedMode?<div className={css.sectionCard}><div className={css.sectionTitle}><strong>Technikai részletek</strong><small>Haladó / Expert</small></div><p className={css.hint}>Elem: {selected.id}</p><p className={css.hint}>Komponens: {selected.componentKey} · v{selected.componentVersion}</p><p className={css.hint}>Responsive mód: {definition.manifest.responsiveMode}</p><div className={css.quickGrid}><button type="button" disabled={definition.protectedSystem} onClick={()=>mutate({type:'duplicate',nodeId:selected.id})}>Duplikálás</button><button type="button" disabled={definition.protectedSystem} onClick={()=>{mutate({type:'remove',nodeId:selected.id});setSelectedId(null)}}>Eltávolítás</button></div></div>:null}
    </div></>:<div className={css.emptyInspector}><VisualBuilderIcon name="pointer"/><strong>Válassz ki egy elemet</strong><p>Kattints a vásznon egy szekcióra vagy komponensre. A kereskedőbarát beállítások itt jelennek meg.</p></div>}</aside>
    </div>
    {historyOpen?<div className={css.backdrop} onClick={()=>setHistoryOpen(false)}><aside className={css.drawer} onClick={event=>event.stopPropagation()}><div className={css.drawerHeader}><div><strong>Előzmények</strong><small>Publikált verziók és visszaállítás.</small></div><button type="button" onClick={()=>setHistoryOpen(false)} aria-label="Bezárás"><VisualBuilderIcon name="close"/></button></div><div className={css.revisionList}>{revisions.filter(item=>item.kind==='published').map(item=><article key={item.revisionId}><span><strong>r{item.revisionNumber}</strong><time>{new Date(item.createdAt).toLocaleString('hu-HU')}</time></span><button type="button" disabled={busy||item.revisionNumber===publishedRevision} onClick={()=>rollback(item.revisionNumber)}>{item.revisionNumber===publishedRevision?'Aktuális':'Visszaállítás'}</button></article>)}</div></aside></div>:null}
    {publishOpen?<div className={css.backdrop} onClick={()=>setPublishOpen(false)}><aside className={css.drawer} onClick={event=>event.stopPropagation()}><div className={css.drawerHeader}><div><strong>Közzététel előtti ellenőrzés</strong><small>Valós Page Schema, accessibility, performance és Design Guard diagnosztika.</small></div><button type="button" onClick={()=>setPublishOpen(false)} aria-label="Bezárás"><VisualBuilderIcon name="close"/></button></div><div className={css.readiness}>{readiness.map(item=><article key={item.label}><span><VisualBuilderIcon name={item.status==='ok'?'check':item.status==='warning'?'warning':'error'}/></span><span><strong>{item.label}</strong><small>{item.detail}</small></span><b>{statusLabel(item.status)}</b></article>)}</div><div className={css.drawerActions}><button type="button" className={css.secondary} onClick={()=>setPublishOpen(false)}>Mégse</button><button type="button" className={css.publish} disabled={busy||dirty||!draftRevision||readinessErrors>0} onClick={publish}>Közzététel</button></div></aside></div>:null}
  </div>;
}
