'use client';
import{useMemo,useState}from'react';import{useRouter}from'next/navigation';import{CartStyleQuantityControl}from'@/components/commerce/cart-style-quantity-control';
type Variant={id:string;sku:string;label:string;name:string;minimumQuantity:number;orderMultiple:number};
type Existing={id:string;status:string;note:string|null;createdAt:string;submittedAt:string|null;items:{variantId:string;name:string;sku:string;label:string;quantity:number}[];offers:{id:string;status:string;quantity:number;totalNetHuf:number|null;netPriceAfterHuf:number|null;expiresAt:string|null;name:string;label:string}[]};
async function act(body:unknown){const r=await fetch('/api/account/b2b-quotes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error??'A művelet sikertelen.');return p}
export function B2BQuoteRequestManager({variants,requests,initialVariantId}:{variants:Variant[];requests:Existing[];initialVariantId?:string}){
 const router=useRouter(),resumable=!initialVariantId?requests.find(r=>r.status==='draft'&&r.items.length===1):undefined,initialItem=resumable?.items[0],initial=variants.find(v=>v.id===(initialVariantId??initialItem?.variantId))??variants[0], [variantId,setVariantId]=useState(initial?.id??''),[quantity,setQuantity]=useState(initialItem?.quantity??initial?.minimumQuantity??1),[note,setNote]=useState(resumable?.note??''),[draftRequestId,setDraftRequestId]=useState<string|null>(resumable?.id??null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const selected=useMemo(()=>variants.find(v=>v.id===variantId),[variants,variantId]);
 function changeVariant(id:string){setVariantId(id);const v=variants.find(x=>x.id===id);setQuantity(v?.minimumQuantity??1);setMessage('')}
 function clearSelectedVariant(){setVariantId('');setQuantity(1);setMessage('')}
 async function saveAndMaybeSubmit(submit:boolean){if(!selected)return;setBusy(true);setMessage('');try{const draft=await act({action:'save',requestId:draftRequestId,note,items:[{variantId,quantity,note:''}]});setDraftRequestId(draft.id);if(submit){await act({action:'submit',requestId:draft.id});setDraftRequestId(null);setNote('')}setMessage(submit?'Az ajánlatkérést elküldtük.':'A piszkozatot elmentettük.');router.refresh()}catch(e){setMessage(e instanceof Error?e.message:'A művelet sikertelen.')}finally{setBusy(false)}}
 async function accept(requestId:string,offerId:string){setBusy(true);setMessage('');try{await act({action:'accept',requestId,offerId});setMessage('Az ajánlatot elfogadtad.');router.refresh()}catch(e){setMessage(e instanceof Error?e.message:'Az ajánlat nem fogadható el.')}finally{setBusy(false)}}
 const statusLabel=(s:string)=>s==='draft'?'Piszkozat':s==='submitted'?'Beküldve':s==='accepted'?'Elfogadva':s==='cancelled'?'Lezárva':s;
 return <div className="accountQuoteManager">
  <section className="featurePanel"><span className="eyebrow">B2B · új ajánlatkérés</span><h2>Ajánlatot kérek</h2><p className="muted">Válassz terméket és mennyiséget. A kereskedő a meglévő értékesítési ajánlatrendszerben válaszol.</p>
   <div className="accountQuoteFormGrid">
    <label className="accountFormField accountQuoteProduct"><span>Termék</span><select value={variantId} onChange={e=>changeVariant(e.target.value)} disabled={!variants.length}><option value="">Válassz terméket</option>{variants.map(v=><option key={v.id} value={v.id}>{v.name} · {v.label} · {v.sku}</option>)}</select></label>
    <div className="accountFormField accountQuoteQuantity"><span>Mennyiség</span>{selected?<><CartStyleQuantityControl contract="rfq" quantity={quantity} minimumQuantity={selected.minimumQuantity} ariaLabel={`${selected.name} mennyiségének módosítása`} onIncrease={()=>setQuantity(quantity+selected.orderMultiple)} onDecrease={()=>setQuantity(Math.max(selected.minimumQuantity,quantity-selected.orderMultiple))} onRemove={clearSelectedVariant}/><small className="accountFieldHelp">Minimum {selected.minimumQuantity} db · rendelési egység {selected.orderMultiple} db</small></>:<small className="accountFieldHelp">Válassz terméket az ajánlatkéréshez.</small>}</div>
   </div>
   <label className="accountFormField accountQuoteNote"><span>Megjegyzés</span><textarea rows={4} maxLength={4000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Pl. kívánt szállítási idő, egyedi igény, projektinformáció"/></label>
   <div className="actions accountQuoteActions"><button className="btn" type="button" disabled={busy||!selected} onClick={()=>saveAndMaybeSubmit(false)}>Piszkozat mentése</button><button className="btn btnPrimary" type="button" disabled={busy||!selected} onClick={()=>saveAndMaybeSubmit(true)}>{busy?'Feldolgozás…':'Ajánlatkérés elküldése'}</button></div>{message&&<p className="notice" role="status">{message}</p>}
  </section>
  <section style={{marginTop:32}}><div className="sectionIntro"><div><span className="eyebrow">Előzmények</span><h2>Ajánlatkéréseim</h2></div></div>{requests.length?<div className="cards">{requests.map(r=><article className="card" key={r.id}><span className="badge">{statusLabel(r.status)}</span><h3>{new Intl.DateTimeFormat('hu-HU',{dateStyle:'medium'}).format(new Date(r.createdAt))}</h3>{r.note?<p>{r.note}</p>:null}<div>{r.items.map(x=><p key={x.variantId}><strong>{x.name}</strong> · {x.label} · {x.quantity} db</p>)}</div>{r.offers.length?<div><h4>Kereskedői ajánlat</h4>{r.offers.map(o=><div key={o.id} className="featurePanel"><strong>{o.name} · {o.label}</strong><p>{o.quantity} db{o.totalNetHuf!=null?` · Nettó összesen: ${new Intl.NumberFormat('hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(o.totalNetHuf)}`:''}</p><span className="badge">{o.status==='sent'?'Kiküldve':o.status==='accepted'?'Elfogadva':o.status}</span>{o.status==='sent'?<button type="button" className="btn btnPrimary" disabled={busy} onClick={()=>accept(r.id,o.id)}>Ajánlat elfogadása</button>:null}</div>)}</div>:r.status==='submitted'?<p className="muted">A kereskedő még dolgozik az ajánlaton.</p>:null}</article>)}</div>:<p className="muted">Még nincs korábbi ajánlatkérésed.</p>}</section>
 </div>;
}
