'use server';

import {revalidatePath} from 'next/cache';
import {getAdminRequestUser} from '@/lib/auth/admin-api';
import {requireCurrentStoreContext} from '@/lib/instances/scope';
import {createAdminClient} from '@/lib/supabase/admin';
import {validateStorefrontExistingEngineDocument,withStorefrontEngineTenant,type StorefrontComposerDocument,type StorefrontConfiguratorDocument,type StorefrontExistingEngineDocument,type StorefrontExistingEngineKind,type StorefrontGuidedFinderDocument} from '@/lib/builder/storefront-existing-engine-config';
import type {CompatibilityRule} from '@/lib/commerce/compatibility-engine';

const KEY=/^[a-z0-9]+(?:[._-][a-z0-9]+)*$/;
const cleanKey=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
async function access(){const actor=await getAdminRequestUser('catalog.manage');if(!actor)throw new Error('Nincs jogosultság a storefront commerce motorok kezeléséhez.');const scope=await requireCurrentStoreContext('catalog.manage');return{actor,scope,admin:createAdminClient()};}
function refresh(){revalidatePath('/admin/tartalom/commerce-engines');revalidatePath('/admin/tartalom/builder');revalidatePath('/');}
async function save(kind:StorefrontExistingEngineKind,document:StorefrontExistingEngineDocument){const{actor,scope,admin}=await access();const candidate=withStorefrontEngineTenant(kind,structuredClone(document),scope.instanceId);const violations=validateStorefrontExistingEngineDocument(kind,candidate);if(violations.length)throw new Error(`A konfiguráció nem menthető: ${violations[0]}`);const{data,error}=await admin.rpc('save_storefront_commerce_engine_config_v1',{p_instance_id:scope.instanceId,p_actor:actor.id,p_engine_kind:kind,p_document:candidate});if(error)throw new Error(`A konfiguráció mentése nem sikerült: ${error.message}`);const result=(data??{}) as{configId?:string;configKey?:string;engineKind?:string};if(typeof result.configId!=='string'||result.engineKind!==kind)throw new Error('A konfiguráció mentése nem igazolható.');refresh();return result;}
export async function saveGuidedFinderAction(input:{configKey:string;label:string;questionLabel:string;attributeKey:string;options:readonly {label:string;value:string}[]}){const configKey=input.configKey.trim();if(!KEY.test(configKey))throw new Error('A Finder kulcsa csak kisbetűt, számot, pontot, kötőjelet vagy aláhúzást tartalmazhat.');if(!KEY.test(input.attributeKey))throw new Error('Válassz érvényes katalógusattribútumot.');const options=input.options.map((option,index)=>{const id=cleanKey(option.label)||`option-${index+1}`;return{id,label:option.label.trim(),rules:[{id:`${configKey}-rule-${index+1}`,attributeKey:input.attributeKey,operator:'eq' as const,value:option.value.trim(),kind:'required' as const,reason:`${input.attributeKey}: ${option.value.trim()}`}]};}).filter(option=>option.label&&option.rules[0]?.value);if(options.length<2)throw new Error('Legalább két válaszlehetőség szükséges.');const document:StorefrontGuidedFinderDocument={config:{version:1,tenantId:'placeholder',finderKey:configKey,label:input.label.trim(),safetyPolicy:'standard',partialPolicy:'show-nearest',maxResults:12,steps:[{id:'step-1',title:input.label.trim(),questions:[{id:'question-1',label:input.questionLabel.trim(),mode:'single',required:true,options}]}]}};return save('guided_finder',document);}
export async function saveComposerAction(input:{configKey:string;label:string;mode:'pool'|'slots';minItems:number;maxItems:number;duplicateLimit:number;slots?:readonly {id:string;label:string;minItems:number;maxItems:number}[]}){const configKey=input.configKey.trim();if(!KEY.test(configKey))throw new Error('Érvénytelen Composer kulcs.');const slots=input.mode==='slots'?(input.slots??[]).map((slot,index)=>({id:cleanKey(slot.id||slot.label)||`slot-${index+1}`,label:slot.label.trim(),minItems:Math.max(0,Math.floor(slot.minItems)),maxItems:Math.max(1,Math.floor(slot.maxItems))})):undefined;const document:StorefrontComposerDocument={config:{version:1,tenantId:'placeholder',composerKey:configKey,label:input.label.trim(),mode:input.mode,minItems:Math.floor(input.minItems),maxItems:Math.floor(input.maxItems),duplicateLimit:Math.floor(input.duplicateLimit),...(slots?{slots}:{})}};return save('multi_product_composer',document);}
export async function saveConfiguratorAction(input:{configKey:string;label:string;slots:readonly {id:string;label:string;required:boolean}[];rules:readonly {id?:string;label:string;leftSlotId:string;rightSlotId:string;attributeKey:string}[]}){const configKey=input.configKey.trim();if(!KEY.test(configKey))throw new Error('Érvénytelen Configurator kulcs.');const slots=input.slots.map((slot,index)=>({id:cleanKey(slot.id||slot.label)||`slot-${index+1}`,label:slot.label.trim(),required:slot.required}));if(slots.length<2)throw new Error('A Configuratorhoz legalább két komponenshely szükséges.');const allowedSlots=new Set(slots.map(slot=>slot.id));const compatibilityRules:CompatibilityRule[]=input.rules.map((rule,index)=>{const left=cleanKey(rule.leftSlotId),right=cleanKey(rule.rightSlotId);if(!allowedSlots.has(left)||!allowedSlots.has(right)||left===right||!KEY.test(rule.attributeKey))throw new Error('A kompatibilitási szabály slotja vagy attribútuma érvénytelen.');return{id:cleanKey(rule.id||rule.label)||`rule-${index+1}`,label:rule.label.trim(),kind:'required',operator:'eq',left:{slotId:left,specKey:rule.attributeKey},right:{slotId:right,specKey:rule.attributeKey},compatibleReason:`${rule.label.trim()}: az értékek egyeznek.`,incompatibleReason:`${rule.label.trim()}: az értékek nem egyeznek.`,unknownReason:`${rule.label.trim()}: nincs elegendő strukturált adat.`};});if(!compatibilityRules.length)throw new Error('Legalább egy explicit kompatibilitási szabály szükséges; szabály nélkül az állapot ismeretlen marad.');const document:StorefrontConfiguratorDocument={config:{version:1,tenantId:'placeholder',configuratorKey:configKey,label:input.label.trim(),slots},compatibilityRules};return save('product_configurator',document);}
export async function deleteExistingCommerceEngineAction(configId:string){if(!/^[0-9a-f-]{36}$/i.test(configId))throw new Error('Érvénytelen konfigurációazonosító.');const{actor,scope,admin}=await access();const{data,error}=await admin.rpc('delete_storefront_commerce_engine_config_v1',{p_instance_id:scope.instanceId,p_actor:actor.id,p_config_id:configId});if(error||data!==true)throw new Error('A konfiguráció törlése nem sikerült.');refresh();return{deleted:true as const};}
