import type {FeatureCode} from '@/lib/plans/catalog';
import {STOREFRONT_BUILDER_FOUNDATION_VERSION,defineStorefrontBuilderComponent,type StorefrontBuilderPageType,type StorefrontResponsiveMode} from '@/lib/builder/storefront-foundation';
import type {StorefrontRuntimeComponentDefinition} from '@/lib/builder/storefront-runtime';
import {createStorefrontStructuredProductComponentRegistry} from '@/lib/builder/storefront-structured-product';
export const STOREFRONT_GUIDED_FINDER_COMPONENTS_VERSION='shoporation.storefront-guided-finder.v1' as const;
const def=(input:{componentKey:string;pageTypes:readonly StorefrontBuilderPageType[];configurable:readonly string[];bindingSlots:readonly string[];features?:readonly FeatureCode[];responsiveMode?:StorefrontResponsiveMode}):StorefrontRuntimeComponentDefinition=>({manifest:defineStorefrontBuilderComponent({foundationVersion:STOREFRONT_BUILDER_FOUNDATION_VERSION,componentKey:input.componentKey,componentVersion:1,schemaSlot:'children',pageTypes:input.pageTypes,configurable:input.configurable,responsiveMode:input.responsiveMode??'fixed',capability:{minPlan:'alap',features:input.features??['catalog','searchFiltering']}}),bindingSlots:input.bindingSlots});
export const STOREFRONT_GUIDED_FINDER_COMPONENT_DEFINITIONS:readonly StorefrontRuntimeComponentDefinition[]=[
 def({componentKey:'guided.finder',pageTypes:['home','catalog','search','content'],configurable:['eyebrow','title','copy','stepTitle','stepCopy','question','options','progressLabel','actionLabel','actionHref','resultStatus'],bindingSlots:['eyebrow','title','copy','stepTitle','stepCopy','question','options','progressLabel','actionLabel','actionHref','resultStatus'],responsiveMode:'grid'}),
 def({componentKey:'guided.results',pageTypes:['home','catalog','search','content'],configurable:['eyebrow','title','explanation','status','items','emptyLabel'],bindingSlots:['eyebrow','title','explanation','status','items'],responsiveMode:'grid'}),
 def({componentKey:'guided.explanation',pageTypes:['product','content'],configurable:['title','matchedTitle','mismatchedTitle','evidence'],bindingSlots:['title','evidence']}),
 def({componentKey:'guided.attribute-index',pageTypes:['home','catalog','content'],configurable:['eyebrow','title','copy','items','columns'],bindingSlots:['eyebrow','title','copy','items'],features:['catalog'],responsiveMode:'grid'}),
 def({componentKey:'guided.attribute-navigation',pageTypes:['home','catalog','search','content'],configurable:['eyebrow','title','items'],bindingSlots:['eyebrow','title','items'],features:['catalog'],responsiveMode:'grid'}),
] as const;
export function createStorefrontGuidedFinderComponentRegistry(){const registry=createStorefrontStructuredProductComponentRegistry();for(const definition of STOREFRONT_GUIDED_FINDER_COMPONENT_DEFINITIONS)registry.register(definition);return registry;}
