import type {FeatureCode} from '@/lib/plans/catalog';
import {STOREFRONT_BUILDER_FOUNDATION_VERSION,defineStorefrontBuilderComponent,type StorefrontBuilderPageType,type StorefrontResponsiveMode} from '@/lib/builder/storefront-foundation';
import type {StorefrontRuntimeComponentDefinition} from '@/lib/builder/storefront-runtime';
import {createStorefrontGuidedFinderComponentRegistry} from '@/lib/builder/storefront-guided-finder';
export const STOREFRONT_MULTI_PRODUCT_COMPOSER_COMPONENTS_VERSION='shoporation.storefront-multi-product-composer.v1' as const;
const def=(input:{componentKey:string;pageTypes:readonly StorefrontBuilderPageType[];configurable:readonly string[];bindingSlots:readonly string[];features?:readonly FeatureCode[];responsiveMode?:StorefrontResponsiveMode}):StorefrontRuntimeComponentDefinition=>({manifest:defineStorefrontBuilderComponent({foundationVersion:STOREFRONT_BUILDER_FOUNDATION_VERSION,componentKey:input.componentKey,componentVersion:1,schemaSlot:'children',pageTypes:input.pageTypes,configurable:input.configurable,responsiveMode:input.responsiveMode??'fixed',capability:{minPlan:'alap',features:input.features??['catalog','inventory','orders']}}),bindingSlots:input.bindingSlots});
export const STOREFRONT_MULTI_PRODUCT_COMPOSER_COMPONENT_DEFINITIONS:readonly StorefrontRuntimeComponentDefinition[]=[
 def({componentKey:'composer.builder',pageTypes:['home','content'],configurable:['eyebrow','title','copy','modeLabel','progressLabel','slots','items','summaryLabel','subtotalLabel','subtotal','currency','actionLabel','actionHref','revalidationLabel'],bindingSlots:['eyebrow','title','copy','modeLabel','progressLabel','slots','items','summaryLabel','subtotal','currency','actionLabel','actionHref','revalidationLabel'],responsiveMode:'grid'}),
 def({componentKey:'composer.summary',pageTypes:['cart','checkout','content'],configurable:['title','compositionId','items','subtotal','currency','editLabel','editHref','removeLabel','removeHref','revalidationLabel'],bindingSlots:['title','compositionId','items','subtotal','currency','editHref','removeHref','revalidationLabel'],responsiveMode:'grid'}),
 def({componentKey:'composer.order-group',pageTypes:['account'],configurable:['title','compositionId','items','refundLabel'],bindingSlots:['title','compositionId','items','refundLabel'],features:['orders'],responsiveMode:'grid'}),
 def({componentKey:'composer.discovery-map',pageTypes:['home','catalog','content'],configurable:['eyebrow','title','copy','items'],bindingSlots:['eyebrow','title','copy','items'],features:['catalog'],responsiveMode:'grid'}),
 def({componentKey:'composer.pairing-row',pageTypes:['home','product','content'],configurable:['eyebrow','title','copy','items'],bindingSlots:['eyebrow','title','copy','items'],features:['catalog'],responsiveMode:'grid'}),
] as const;
export function createStorefrontMultiProductComposerComponentRegistry(){const registry=createStorefrontGuidedFinderComponentRegistry();for(const definition of STOREFRONT_MULTI_PRODUCT_COMPOSER_COMPONENT_DEFINITIONS)registry.register(definition);return registry;}
