import type {FeatureCode} from '@/lib/plans/catalog';import {STOREFRONT_BUILDER_FOUNDATION_VERSION,defineStorefrontBuilderComponent,type StorefrontBuilderPageType,type StorefrontResponsiveMode} from '@/lib/builder/storefront-foundation';import type {StorefrontRuntimeComponentDefinition} from '@/lib/builder/storefront-runtime';import {createStorefrontConfiguratorComponentRegistry} from '@/lib/builder/storefront-configurator';
export const STOREFRONT_CONTEXT_RETENTION_COMPONENTS_VERSION='shoporation.storefront-context-retention.v1' as const;const def=(input:{componentKey:string;pageTypes:readonly StorefrontBuilderPageType[];configurable:readonly string[];bindingSlots:readonly string[];features?:readonly FeatureCode[];responsiveMode?:StorefrontResponsiveMode}):StorefrontRuntimeComponentDefinition=>({manifest:defineStorefrontBuilderComponent({foundationVersion:STOREFRONT_BUILDER_FOUNDATION_VERSION,componentKey:input.componentKey,componentVersion:1,schemaSlot:'children',pageTypes:input.pageTypes,configurable:input.configurable,responsiveMode:input.responsiveMode??'fixed',capability:{minPlan:'alap',features:input.features??['catalog','customers']}}),bindingSlots:input.bindingSlots});
export const STOREFRONT_CONTEXT_RETENTION_COMPONENT_DEFINITIONS:readonly StorefrontRuntimeComponentDefinition[]=[
 def({componentKey:'context.hero',pageTypes:['home'],configurable:['eyebrow','title','copy','primaryLabel','primaryHref','secondaryLabel','secondaryHref','image','imageAlt'],bindingSlots:['eyebrow','title','copy','primaryLabel','primaryHref','secondaryLabel','secondaryHref','image','imageAlt'],responsiveMode:'grid'}),
 def({componentKey:'context.profile-selector',pageTypes:['home','catalog','search','account','content'],configurable:['title','copy','profiles','activeProfileId','switchLabel','manageLabel','manageHref','guestSaveLabel','guestSaveHref','emptyLabel'],bindingSlots:['title','copy','profiles','activeProfileId','manageHref','guestSaveHref'],features:['customers'],responsiveMode:'grid'}),
 def({componentKey:'context.discovery-row',pageTypes:['home','catalog','search'],configurable:['eyebrow','title','copy','activeLabel','items','emptyLabel'],bindingSlots:['eyebrow','title','copy','activeLabel','items'],features:['catalog','productRecommendations'],responsiveMode:'grid'}),
 def({componentKey:'context.fit-evidence',pageTypes:['product','content'],configurable:['title','affinity','reasons','neutralLabel'],bindingSlots:['title','affinity','reasons'],features:['catalog']}),
 def({componentKey:'context.need-navigation',pageTypes:['home','catalog'],configurable:['eyebrow','title','items'],bindingSlots:['eyebrow','title','items'],features:['catalog'],responsiveMode:'grid'}),
 def({componentKey:'retention.running-low',pageTypes:['home','account'],configurable:['eyebrow','title','copy','items','emptyLabel'],bindingSlots:['eyebrow','title','copy','items'],features:['orders','customers'],responsiveMode:'grid'}),
 def({componentKey:'retention.reorder-row',pageTypes:['home','account','content'],configurable:['title','items','actionLabel','emptyLabel','revalidationLabel'],bindingSlots:['title','items','actionLabel','revalidationLabel'],features:['orders','customers'],responsiveMode:'grid'}),
 def({componentKey:'context.favorites',pageTypes:['home','account'],configurable:['title','items','emptyLabel'],bindingSlots:['title','items'],features:['wishlists'],responsiveMode:'grid'}),
] as const;export function createStorefrontContextRetentionComponentRegistry(){const registry=createStorefrontConfiguratorComponentRegistry();for(const definition of STOREFRONT_CONTEXT_RETENTION_COMPONENT_DEFINITIONS)registry.register(definition);return registry;}
