import 'server-only';
import {createAdminClient} from '@/lib/supabase/admin';
import {requireCurrentStoreContext} from '@/lib/instances/scope';
import {getStorefrontInteractiveSceneCatalogForInstance} from '@/lib/builder/storefront-interactive-scene-server';
import {runProductDiscovery,type ProductDiscoveryCandidate,type ProductDiscoveryResult} from '@/lib/commerce/product-discovery';
import {StructuredProductSpecificationRegistry,type StructuredSpecAssignments} from '@/lib/commerce/structured-product';
import {validateStorefrontExistingEngineDocument,type StorefrontExistingEngineDocument,type StorefrontExistingEngineKind,type StorefrontExistingEngineRecord} from '@/lib/builder/storefront-existing-engine-config';

export type StorefrontExistingCommerceAttributeOption={key:string;label:string};
export type StorefrontExistingCommerceCatalogItem={productId:string;variantId:string;label:string;href:string;slug:string;eligible:boolean;channelVisible:boolean;price:{amountMinor:number;currency:string;display:string;source:'shared-pricing-authority'};stock:{available:boolean;statusLabel:string};attributes:Readonly<Record<string,string>>;compatibility:Readonly<Record<string,{specKey:string;value:{type:'text';value:string}|null;source:'compare-spec-engine.v1'}>>;};
export type StorefrontExistingCommerceBundle={records:readonly StorefrontExistingEngineRecord[];finders:readonly StorefrontExistingEngineRecord[];composers:readonly StorefrontExistingEngineRecord[];configurators:readonly StorefrontExistingEngineRecord[];catalog:readonly StorefrontExistingCommerceCatalogItem[];attributes:readonly StorefrontExistingCommerceAttributeOption[];options:Readonly<Record<StorefrontExistingEngineKind,readonly {configKey:string;label:string}[]>>;};
type ConfigRow={id:string;engine_kind:string;config_key:string;label:string;document:unknown;active:boolean};type AttributeRow={product_id:string;name:string;value:string};
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
function hash(value:string){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(36)}
const attributeKey=(label:string)=>`attr.${normalize(label)||'field'}.${hash(label.trim().toLowerCase()).slice(0,7)}`;
const missingConfigTable=(error:{code?:string;message?:string}|null)=>Boolean(error&&(error.code==='42P01'||error.code==='PGRST205'||error.message?.includes('storefront_commerce_engine_configs')));
const kind=(value:string):value is StorefrontExistingEngineKind=>value==='guided_finder'||value==='multi_product_composer'||value==='product_configurator';
function slugFromHref(href:string){const parts=href.split('?')[0]?.split('/').filter(Boolean)??[];return decodeURIComponent(parts[parts.length-1]??'')}
function discoveryAll(registry:StructuredProductSpecificationRegistry,candidates:ProductDiscoveryCandidate[]):ProductDiscoveryResult[]{const results:ProductDiscoveryResult[]=[];for(let start=0;start<candidates.length;start+=100){const batch=runProductDiscovery({registry,query:{limit:100},candidates:candidates.slice(start,start+100)});if(batch)results.push(...batch.results);}return results;}

export async function getStorefrontExistingCommerceBundleForInstance(instanceId:string):Promise<StorefrontExistingCommerceBundle>{
  const admin=createAdminClient();const[scene,configResult,attributeResult]=await Promise.all([getStorefrontInteractiveSceneCatalogForInstance(instanceId),admin.from('storefront_commerce_engine_configs').select('id,engine_kind,config_key,label,document,active').eq('instance_id',instanceId).eq('active',true).order('engine_kind').order('label'),admin.from('product_attributes').select('product_id,name,value').eq('instance_id',instanceId).order('name')]);
  if(configResult.error&&!missingConfigTable(configResult.error))throw new Error(`STOREFRONT_EXISTING_ENGINE_CONFIGS_FAILED:${configResult.error.message}`);if(attributeResult.error)throw new Error(`STOREFRONT_EXISTING_ENGINE_ATTRIBUTES_FAILED:${attributeResult.error.message}`);
  const records:StorefrontExistingEngineRecord[]=[];for(const row of((configResult.error?[]:configResult.data??[]) as unknown as ConfigRow[])){if(!row.active||!kind(row.engine_kind))continue;if(validateStorefrontExistingEngineDocument(row.engine_kind,row.document).length)continue;records.push({id:row.id,engineKind:row.engine_kind,configKey:row.config_key,label:row.label,document:row.document as StorefrontExistingEngineDocument});}
  const attributeRows=(attributeResult.data??[]) as AttributeRow[],attributeLabels=new Map<string,string>(),valuesByProduct=new Map<string,Record<string,string>>();for(const row of attributeRows){const label=String(row.name??'').trim(),value=String(row.value??'').trim();if(!label||!value)continue;const key=attributeKey(label);if(!attributeLabels.has(key))attributeLabels.set(key,label);const values=valuesByProduct.get(row.product_id)??{};values[key]=value;valuesByProduct.set(row.product_id,values);}
  const attributes=[...attributeLabels].map(([key,label])=>({key,label})).sort((a,b)=>a.label.localeCompare(b.label,'hu')),registry=new StructuredProductSpecificationRegistry({groups:[{key:'catalog',label:'Termékadatok'}],specs:attributes.map((item,index)=>({key:item.key,label:item.label,groupKey:'catalog',valueType:'text' as const,scope:'product' as const,filterable:true,comparable:true,order:index+1}))});
  const sceneVariant=new Map<string,{productId:string;variantId:string;label:string;href:string;price:StorefrontExistingCommerceCatalogItem['price'];stock:StorefrontExistingCommerceCatalogItem['stock'];eligible:boolean;channelVisible:boolean}>(),candidates:ProductDiscoveryCandidate[]=[];
  for(const product of scene.products){const values=valuesByProduct.get(product.productId)??{},productValues:StructuredSpecAssignments=Object.fromEntries(Object.entries(values).map(([key,value])=>[key,{type:'text' as const,value}]));for(const variant of product.variants??[]){const id=`${product.productId}:${variant.variantId}`,eligible=Boolean(product.eligible&&variant.eligible&&variant.channelVisible&&variant.stock.available);sceneVariant.set(id,{productId:product.productId,variantId:variant.variantId,label:`${product.label}${variant.label?` · ${variant.label}`:''}`,href:product.href,price:variant.price,stock:variant.stock,eligible,channelVisible:variant.channelVisible});candidates.push({productId:product.productId,variantId:variant.variantId,label:`${product.label}${variant.label?` · ${variant.label}`:''}`,href:product.href,productValues,eligibility:{productActive:product.eligible,variantActive:variant.eligible,channelVisible:variant.channelVisible,sellable:variant.stock.available}});}}
  const catalog=discoveryAll(registry,candidates).flatMap(result=>{const source=sceneVariant.get(result.id);if(!source)return[];const raw=valuesByProduct.get(source.productId)??{};return[{productId:source.productId,variantId:source.variantId,label:source.label,href:source.href,slug:slugFromHref(source.href),eligible:source.eligible,channelVisible:source.channelVisible,price:source.price,stock:source.stock,attributes:Object.freeze({...raw}),compatibility:Object.freeze(Object.fromEntries(Object.entries(raw).map(([key,value])=>[key,{specKey:key,value:{type:'text' as const,value},source:'compare-spec-engine.v1' as const}]))) } satisfies StorefrontExistingCommerceCatalogItem];});
  const byKind=(engineKind:StorefrontExistingEngineKind)=>records.filter(record=>record.engineKind===engineKind),finders=byKind('guided_finder'),composers=byKind('multi_product_composer'),configurators=byKind('product_configurator');const options={guided_finder:finders.map(({configKey,label})=>({configKey,label})),multi_product_composer:composers.map(({configKey,label})=>({configKey,label})),product_configurator:configurators.map(({configKey,label})=>({configKey,label}))} satisfies StorefrontExistingCommerceBundle['options'];return{records:Object.freeze(records),finders:Object.freeze(finders),composers:Object.freeze(composers),configurators:Object.freeze(configurators),catalog:Object.freeze(catalog),attributes:Object.freeze(attributes),options};
}
export async function getCurrentStorefrontExistingCommerceBundle(){const scope=await requireCurrentStoreContext('store.read');return getStorefrontExistingCommerceBundleForInstance(scope.instanceId);}
