import Link from'next/link';
import{createAdminClient}from'@/lib/supabase/admin';
import{requirePlanFeature}from'@/lib/plans/access';
import{requireCurrentStorePageContext}from'@/lib/instances/scope';
import styles from'./product-intake.module.css';

export const dynamic='force-dynamic';
type ProductRow={id:string;name:string;active:boolean;updated_at:string|null};type VariantRow={id:string;product_id:string;label:string;sku:string;gross_price_huf:number;net_price_huf:number;stock_quantity:number;active:boolean};type MediaRow={product_id:string};type BatchRow={id:string;source_type:'manual'|'csv'|'xlsx'|'copy';state:'preview'|'applied';error_count:number;created_at:string;applied_at:string|null;result:unknown};type ChannelRow={channel_code:'b2c'|'b2b';enabled:boolean};
const fmtAgo=(iso:string|null)=>{if(!iso)return'—';const diff=Math.max(0,Date.now()-new Date(iso).getTime()),minute=60000,hour=60*minute,day=24*hour;if(diff<minute)return'most';if(diff<hour)return`${Math.floor(diff/minute)} perce`;if(diff<day)return`${Math.floor(diff/hour)} órája`;return`${Math.floor(diff/day)} napja`};
const resultCount=(value:unknown)=>Array.isArray(value)?value.length:value&&typeof value==='object'?1:0;
const sourceLabel=(source:BatchRow['source_type'])=>source==='xlsx'?'XLSX katalógus import':source==='csv'?'CSV katalógus import':source==='copy'?'Termékmásolás':'Kézi termékfelvitel';
function Mark({children,tone='mint'}:{children:React.ReactNode;tone?:'mint'|'blue'|'violet'|'sand'}){return <span className={`${styles.optionIcon} ${styles[tone]}`}>{children}</span>}
function MiniNav(){return <nav className={styles.innerNav} aria-label="Termékfeltöltő Központ"><Link className={styles.innerNavActive} href="/admin/termekek/feltoltes"><span>◇</span>Kezdőoldal</Link><Link href="/admin/termekek/feltoltes/uj"><span>＋</span>Új termék</Link><Link href="/admin/termekek/import-export#catalog-onboarding"><span>⇧</span>Tömeges feltöltés</Link><Link href="/admin/migracio"><span>⇄</span>Migráció</Link><Link href="/admin/termekek/feltoltes/masolas"><span>⧉</span>Termékmásolás</Link><Link href="/admin/termekek"><span>✓</span>Ellenőrzés</Link></nav>}

export default async function ProductIntakeCenterPage(){
  await requirePlanFeature('importExport');const scope=await requireCurrentStorePageContext('catalog.manage'),admin=createAdminClient();
  const[productsResult,variantsResult,mediaResult,batchesResult,channelsResult]=await Promise.all([
    admin.from('products').select('id,name,active,updated_at').eq('instance_id',scope.instanceId).order('updated_at',{ascending:false}).limit(500),
    admin.from('product_variants').select('id,product_id,label,sku,gross_price_huf,net_price_huf,stock_quantity,active').eq('instance_id',scope.instanceId),
    admin.from('product_media').select('product_id').eq('instance_id',scope.instanceId),
    admin.from('catalog_onboarding_batches').select('id,source_type,state,error_count,created_at,applied_at,result').eq('instance_id',scope.instanceId).order('created_at',{ascending:false}).limit(3),
    admin.from('webshop_sales_channels').select('channel_code,enabled').eq('instance_id',scope.instanceId),
  ]);
  const loadError=Boolean(productsResult.error||variantsResult.error||mediaResult.error||batchesResult.error||channelsResult.error),products=(productsResult.data??[])as ProductRow[],variants=(variantsResult.data??[])as VariantRow[],media=(mediaResult.data??[])as MediaRow[],batches=(batchesResult.data??[])as BatchRow[],channels=(channelsResult.data??[])as ChannelRow[];
  const variantsByProduct=new Map<string,VariantRow[]>();for(const variant of variants)variantsByProduct.set(variant.product_id,[...(variantsByProduct.get(variant.product_id)??[]),variant]);const mediaProducts=new Set(media.map(item=>item.product_id)),drafts=products.filter(product=>!product.active),readyDrafts=drafts.filter(product=>{const list=variantsByProduct.get(product.id)??[];return mediaProducts.has(product.id)&&list.length>0&&list.every(v=>v.sku&&v.gross_price_huf>=0&&v.net_price_huf>=0)}),incompleteCount=Math.max(0,drafts.length-readyDrafts.length),recentDrafts=drafts.slice(0,4),activeCount=products.filter(product=>product.active).length,readiness=products.length?Math.round(((activeCount+readyDrafts.length)/products.length)*100):100,channelState=new Map(channels.map(item=>[item.channel_code,item.enabled])),b2cEnabled=channelState.get('b2c')!==false,b2bEnabled=channelState.get('b2b')===true;

  return <section className={`${styles.productIntakeScreen} ${styles.hubScreen}`}><header className={styles.topBar}><label className={styles.searchBox}><span>⌕</span><input aria-label="Keresés a termékek között" placeholder="Keresés a termékek között..."/></label><div className={styles.topActions}><Link className={styles.secondaryButton} href="/admin/termekek/import-export">◷ Előzmények</Link><Link className={styles.primaryButton} href="/admin/termekek/feltoltes/uj">＋ Új termék</Link></div></header><div className={styles.pageHeading}><Link className={styles.backButton} href="/admin">←</Link><div><h1>Termékfeltöltő Központ</h1><p>Válaszd ki, hogyan szeretnéd bővíteni a katalógusodat.</p></div></div>{loadError&&<div className={styles.errorBanner}>A katalógus állapotának egy része most nem tölthető be. Módosítási műveletet csak a saját céloldalán, a meglévő fail-closed ellenőrzésekkel engedünk.</div>}
  <div className={styles.workspaceGrid}><MiniNav/><main className={styles.workspace}><div className={styles.optionGrid}><article className={`${styles.optionCard} ${styles.optionMint}`}><Mark>◇</Mark><h2>Új termék létrehozása</h2><p>Vezetett szerkesztő egyedi vagy variációs termékekhez, Product Copilot segítséggel.</p><Link className={styles.primaryButton} href="/admin/termekek/feltoltes/uj">Megnyitás <span>→</span></Link></article><article className={`${styles.optionCard} ${styles.optionBlue}`}><Mark tone="blue">⇧</Mark><h2>Tömeges feltöltés</h2><p>CSV vagy XLSX import intelligens mezőfelismeréssel, validációval és előnézettel.</p><Link className={styles.primaryButton} href="/admin/termekek/import-export#catalog-onboarding">Feltöltés indítása <span>→</span></Link></article><article className={`${styles.optionCard} ${styles.optionViolet}`}><Mark tone="violet">⇄</Mark><h2>Webshop-migráció</h2><p>Termékek áthozása más rendszerből a Migration Assistant segítségével.</p><Link className={styles.primaryButton} href="/admin/migracio">Migráció indítása <span>→</span></Link></article><article className={`${styles.optionCard} ${styles.optionSand}`}><Mark tone="sand">⧉</Mark><h2>Meglévő termék másolása</h2><p>Termék, variánsok, média, SEO és csatornák másolása új, biztonságos piszkozatba.</p><Link className={styles.primaryButton} href="/admin/termekek/feltoltes/masolas">Másolás indítása <span>→</span></Link></article></div>
  <div className={styles.contentSplit}><section className={styles.panel}><div className={styles.panelHeader}><div><h2>▣ Folyamatban lévő piszkozatok</h2><p>Itt folytathatod a korábban elkezdett termékek szerkesztését.</p></div><Link href="/admin/termekek">Összes piszkozat →</Link></div><div className={styles.compactTable}><div className={styles.tableHeader}><span>Név</span><span>Típus</span><span>Állapot</span><span>Módosítva</span><span/></div>{recentDrafts.length?recentDrafts.map(product=>{const count=(variantsByProduct.get(product.id)??[]).length,ready=readyDrafts.some(item=>item.id===product.id);return <div className={styles.tableRow} key={product.id}><span className={styles.productName}><i>{product.name.slice(0,1).toUpperCase()}</i><strong>{product.name}</strong></span><span>{count>1?`${count} variáns`:'Egyszerű termék'}</span><span><b className={`${styles.statusPill} ${ready?styles.successPill:styles.warnPill}`}>{ready?'Publikálásra kész':'Hiányos'}</b></span><span>{fmtAgo(product.updated_at)}</span><Link aria-label={`${product.name} szerkesztése`} href={`/admin/termekek/feltoltes/${product.id}`}>•••</Link></div>}):<div className={styles.emptyState}>Nincs folyamatban lévő termékpiszkozat.</div>}</div></section><section className={styles.panel}><div className={styles.panelHeader}><div><h2>◷ Legutóbbi importok</h2></div><Link href="/admin/termekek/import-export">Összes import →</Link></div><div className={styles.importList}>{batches.length?batches.map(batch=>{const count=resultCount(batch.result),done=batch.state==='applied';return <div className={styles.importRow} key={batch.id}><span className={styles.docIcon}>▤</span><div><strong>{sourceLabel(batch.source_type)}</strong><small>{count?`${count} eredmény`:done?'Alkalmazva':'Előkészítve'} · {batch.error_count} figyelmeztetés</small></div><div><b className={`${styles.statusPill} ${done?styles.successPill:styles.infoPill}`}>{done?'Sikeres':'Folyamatban'}</b><small>{fmtAgo(batch.applied_at??batch.created_at)}</small></div></div>}):<div className={styles.emptyState}>Még nincs import-előzmény.</div>}</div></section></div>
  <div className={styles.bottomSplit}><section className={styles.panel}><div className={styles.panelHeader}><div><h2>☷ Ajánlott következő lépések</h2></div></div><Link className={styles.todoRow} href="/admin/termekek"><span>□</span><div><strong>Főkép nélküli termékek ellenőrzése</strong><small>{Math.max(0,products.length-mediaProducts.size)} terméknél nincs feltöltött termékmédia.</small></div><b>›</b></Link><Link className={styles.todoRow} href="/admin/termekek"><span>□</span><div><strong>Piszkozatok befejezése</strong><small>{incompleteCount} termék vár még ellenőrzésre.</small></div><b>›</b></Link><Link className={styles.todoRow} href="/admin/termekek/import-export"><span>□</span><div><strong>Importhibák ellenőrzése</strong><small>{batches.reduce((sum,batch)=>sum+batch.error_count,0)} figyelmeztetés a legutóbbi műveletekben.</small></div><b>›</b></Link></section><section className={styles.panel}><div className={styles.panelHeader}><div><h2>▥ Katalógus áttekintés</h2></div><small>Aktuális webshop</small></div><div className={styles.metrics}><div><span>Összes termék</span><strong>{products.length}</strong></div><div><span>Piszkozat</span><strong>{drafts.length}</strong></div><div><span>Publikálásra kész</span><strong>{readyDrafts.length}</strong></div><div><span>Hiányos</span><strong className={styles.dangerText}>{incompleteCount}</strong></div></div><div className={styles.catalogProgress}><strong>Katalógus állapota</strong><div><i style={{width:`${products.length?Math.round(activeCount/products.length*100):0}%`}}/><b style={{width:`${products.length?Math.round(readyDrafts.length/products.length*100):0}%`}}/></div><small>Aktív {activeCount} · Kész piszkozat {readyDrafts.length} · Ellenőrizendő {incompleteCount}</small></div></section></div></main>
  <aside className={styles.rail}><section className={styles.railCard}><div className={styles.railTitle}><h2>▱ Gyors segítség</h2><span>További tippek ↗</span></div><Link href="/admin/termekek/import-export#catalog-onboarding">⇧ <span>CSV / XLSX tömeges feltöltés</span>›</Link><Link href="/admin/termekek/feltoltes/masolas">⧉ <span>Biztonságos termékmásolás</span>›</Link><Link href="/admin/termekek/feltoltes/uj#copilot">✦ <span>Product Copilot használata</span>›</Link></section><section className={styles.railCard}><div className={styles.railTitle}><h2>◷ Központ állapota</h2><b className={`${styles.statusPill} ${styles.successPill}`}>● Aktív</b></div><div className={styles.readiness}><div><span>Készenlét</span><strong>{readiness}%</strong></div><progress max="100" value={readiness}/></div><div className={styles.checkList}><span>✓ Kézi felvitel elérhető</span><span>✓ CSV / XLSX onboarding elérhető</span><span>✓ Migráció elérhető</span><span>✓ Termékmásolás elérhető</span><span>✓ Product Copilot jóváhagyásos</span></div></section><section className={styles.railCard}><h2>Értékesítési csatornák</h2><div className={styles.channelRow}><span>♡</span><strong>B2C</strong><b className={b2cEnabled?styles.toggleOn:styles.toggleOff}>●</b><small>{b2cEnabled?'Aktív':'Kikapcsolva'}</small></div><p>{b2cEnabled?'A B2C csatorna aktív.':'A webshop B2C csatornája jelenleg ki van kapcsolva.'}</p><div className={styles.channelRow}><span>♧</span><strong>B2B</strong><b className={b2bEnabled?styles.toggleOn:styles.toggleOff}>●</b><small>{b2bEnabled?'Aktív':'Kikapcsolva'}</small></div><p>{b2bEnabled?'A B2B csatorna aktív; termékenként külön láthatóság állítható.':'A B2B csatorna globálisan ki van kapcsolva; a termékoldali beállítás előkészíthető.'}</p></section></aside></div></section>;
}
