import './admin-shell.css';
import './launch-readiness.css';
import './workspace.css';
import Link from 'next/link';
import { requireAdmin } from '@/lib/auth/require-admin';
import { isPlatformOperator } from '@/lib/auth/platform-operator';
import { getCurrentWebshopInstance } from '@/lib/instances/access';
import { getCurrentPlan } from '@/lib/plans/access';
import { hasPlanFeature, PLANS, type FeatureCode } from '@/lib/plans/catalog';
type NavItem={href:string;label:string;feature?:FeatureCode};type NavSection={label:string;items:NavItem[]};
const MERCHANT_NAV:NavSection[]=[{label:'Kezdőlap',items:[{href:'/admin',label:'Áttekintés'},{href:'/admin/indulas',label:'Indítási központ'}]},{label:'Értékesítés',items:[{href:'/admin/rendelesek',label:'Rendelések',feature:'orders'},{href:'/admin/visszaru',label:'Visszáru',feature:'returns'},{href:'/admin/ugyfelek',label:'Ügyfelek',feature:'customers'},{href:'/admin/ertekesites',label:'CRM és értékesítés',feature:'crm'},{href:'/admin/ugyfelertek',label:'Ügyfélérték',feature:'crm'},{href:'/admin/utanakovetes',label:'Utánkövetés',feature:'crm'}]},{label:'Katalógus',items:[{href:'/admin/termekek',label:'Termékek',feature:'catalog'},{href:'/admin/termekajanlasok',label:'Termékajánlások',feature:'productRecommendations'},{href:'/admin/keszlet-elemzes',label:'Készletelemzés',feature:'advancedAnalytics'},{href:'/admin/beszerzes',label:'Beszerzés',feature:'procurement'},{href:'/admin/termekek/import-export',label:'Import / export',feature:'importExport'},{href:'/admin/termekek/tomeges',label:'Tömeges műveletek',feature:'bulkOperations'}]},{label:'Marketing és tartalom',items:[{href:'/admin/marketing',label:'Marketing alapok',feature:'marketingBasics'},{href:'/admin/kampanyok',label:'Haladó kampányok',feature:'advancedCampaigns'},{href:'/admin/tartalom',label:'Tartalom és SEO',feature:'contentMarketing'},{href:'/admin/kuponok',label:'Kuponok és akciók',feature:'coupons'},{href:'/admin/velemenyek',label:'Vásárlói vélemények',feature:'reviews'}]},{label:'Működés',items:[{href:'/admin/automatizalas',label:'Automatizálási központ',feature:'automation'},{href:'/admin/kommunikacio',label:'Digitális iroda',feature:'officeCommunication'},{href:'/admin/kommunikacio/tiltolista',label:'Kommunikációs tiltólista',feature:'officeCommunication'},{href:'/admin/ugyfelszolgalat',label:'Ügyfélszolgálat',feature:'support'},{href:'/admin/beallitasok/fizetes-szallitas',label:'Fizetés és szállítás',feature:'commerceIntegrations'},{href:'/admin/integraciok',label:'Integrációs műveletek',feature:'advancedIntegrations'}]},{label:'Elemzés és pénzügy',items:[{href:'/admin/elemzes',label:'Elemzés',feature:'advancedAnalytics'},{href:'/admin/novekedes',label:'Növekedés',feature:'advancedAnalytics'},{href:'/admin/vezetoi',label:'Vezetői analitika',feature:'executiveAnalytics'},{href:'/admin/cashflow',label:'Cash-flow',feature:'cashflow'}]},{label:'Rendszer',items:[{href:'/admin/csomag',label:'Csomagkezelés'},{href:'/admin/beallitasok',label:'Beállítások'}]}];
const OPERATOR_NAV:NavItem[]=[{href:'/admin/platform/webaruhazak',label:'Ügyfél-webshopok'},{href:'/admin/iranyitokozpont',label:'Platform irányítóközpont'},{href:'/admin/intezkedesek',label:'Intézkedési központ'},{href:'/admin/biztositekok',label:'Biztosítékok'},{href:'/admin/kiadasok',label:'Kiadási központ'},{href:'/admin/rollout',label:'Rollout központ'},{href:'/admin/utoellenorzes',label:'Utóellenőrzés'},{href:'/admin/helyreallitas',label:'Helyreállítás'},{href:'/admin/megfigyeles',label:'Megfigyelés'},{href:'/admin/muveletek',label:'Platform műveletek'},{href:'/admin/naplo',label:'Platform napló'}];
export default async function AdminLayout({children}:{children:React.ReactNode}){await requireAdmin();const[plan,operator,instance]=await Promise.all([getCurrentPlan(),isPlatformOperator(),getCurrentWebshopInstance()]);const definition=PLANS[plan],merchantName=instance?.name??'Webáruház';return <main className="adminGrid"><aside className="adminSide"><div className="adminBrand"><strong>{merchantName}</strong><span className="muted">Shoperation · {definition.name}{instance?` · ${instance.status==='pilot'?'pilot':instance.status}`:''}</span></div><nav className="adminNav" aria-label="Webshop adminisztráció">{MERCHANT_NAV.map(section=>{const items=section.items.filter(item=>!item.feature||hasPlanFeature(plan,item.feature));if(!items.length)return null;return <section className="adminNavSection" key={section.label}><span className="adminNavLabel">{section.label}</span>{items.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}</section>})}{plan==='alap'&&<Link className="adminUpgrade" href="/admin/csomag">Pro funkciók megtekintése</Link>}{operator&&<section className="adminNavSection adminOperator"><span className="adminNavLabel">Shoperation platform</span>{OPERATOR_NAV.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}</section>}</nav><Link className="adminStoreLink" href="/">← Webshop megnyitása</Link></aside>{children}</main>}
