import {STOREFRONT_BUILDER_FOUNDATION_VERSION,STOREFRONT_DEMO_CONTENT_POLICY,STOREFRONT_PAGE_SCHEMA_VERSION,STOREFRONT_TEMPLATE_MANIFEST_VERSION,STOREFRONT_TEMPLATE_MIGRATION_POLICY,defineStorefrontTemplateManifest,type StorefrontBuilderPageType} from '@/lib/builder/storefront-foundation';
import type {StorefrontComponentNode,StorefrontPageDocument} from '@/lib/builder/storefront-runtime';
import type {StorefrontInstallableTemplatePackage} from '@/lib/builder/storefront-template-installation';

export const DERMA_STUDIO_TEMPLATE_KEY='beauty.derma-studio' as const;
export const DERMA_STUDIO_TEMPLATE_VERSION=1 as const;
export const DERMA_STUDIO_VISUAL_DNA=Object.freeze({
  character:'clinically-clean-concern-first-routine-first-skincare-commerce',
  palette:{background:'warm-white',surface:'soft-mineral-grey',text:'graphite',accent:'muted-blue-green',secondary:'soft-clay'},
  typography:{display:'clean-editorial-sans',interface:'precise-sans'},
  imagery:'clean-product-macro-ingredient-glass-texture-routine',
  spacing:'precise-airy-educational',
  journey:'concern-to-routine-to-active-ingredient-to-product',
  exclusions:['medical-clinic','diagnostic-ui','treatment-or-cure-claims','black-box-score','fake-clinical-evidence','before-after-medical-claims'],
} as const);
export const DERMA_STUDIO_DESIGN_TOKENS=Object.freeze({
  '--shoporation-color-background':'#FAFAF7','--shoporation-color-surface':'#EEF1EF','--shoporation-color-surface-muted':'#E3E7E5','--shoporation-color-text':'#25292A','--shoporation-color-muted-text':'#697071','--shoporation-color-border':'#D2D8D5','--shoporation-color-primary':'#315E59','--shoporation-color-primary-contrast':'#FFFFFF','--shoporation-color-accent':'var(--merchant-accent, #6F9891)','--shoporation-color-secondary':'#C9A99D','--shoporation-heading-font':'var(--merchant-heading-font, Arial, sans-serif)','--shoporation-body-font':'var(--merchant-body-font, Arial, sans-serif)'} as const);
export const DERMA_STUDIO_ENGINE_CONTRACT=Object.freeze({requiredForFullExperience:['E1','E2','E3','E7','E13'] as const,integration:{E1:'shared-runtime',E2:'shared-product-discovery-authority',E3:'guided-finder-v1-concern-and-routine-navigation',E7:'structured-active-ingredient-and-product-attribute-data',E13:'shared-checkout-authority'},authorityRule:'routine-and-concern-guidance-is-non-diagnostic-and-read-model-only'} as const);
export const DERMA_STUDIO_HOME_SECTION_ORDER=['Clinical Clarity Hero','Shop by Concern','Routine Finder','Active Ingredient Index','Routine Steps','Targeted Formulas','Ingredient Education','Reviews','Footer'] as const;

const node=(x:StorefrontComponentNode):StorefrontComponentNode=>x;
const section=(id:string,children:StorefrontComponentNode[],tone='background',spacing='xl'):StorefrontComponentNode=>node({id,componentKey:'layout.section',componentVersion:1,config:{tone,spacing,width:'full'},children:[node({id:`${id}-container`,componentKey:'layout.container',componentVersion:1,config:{width:'content',spacing:'m'},children})]});
const header=(p:string):StorefrontComponentNode=>node({id:`${p}-header`,componentKey:'system.header',componentVersion:1,config:{brandLabel:'Derma Studio',brandHref:'/',tone:'background',sticky:true},bindings:{brandLabel:{path:'brand.name',fallback:'Derma Studio'},brandHref:{path:'brand.homeHref',fallback:'/'}},children:[node({id:`${p}-nav`,componentKey:'system.navigation',componentVersion:1,config:{ariaLabel:'Fő navigáció',items:[],layout:'horizontal'},bindings:{items:{path:'navigation.primary',fallback:[]}}})]});
const footerFallback=[{id:'shop',title:'Felfedezés',items:[{label:'Bőrcél szerint',href:'/webaruhaz'},{label:'Aktív összetevők',href:'/oldal/aktiv-osszetevok'}]},{id:'help',title:'Segítség',items:[{label:'Rutin útmutató',href:'/oldal/rutin'},{label:'Kapcsolat',href:'/kapcsolat'}]}];
const footer=(p:string):StorefrontComponentNode=>node({id:`${p}-footer`,componentKey:'editorial.footer',componentVersion:1,config:{brandLabel:'Derma Studio',columns:footerFallback,copyright:'© Derma Studio',tone:'background'},bindings:{brandLabel:{path:'brand.name',fallback:'Derma Studio'},columns:{path:'navigation.footer',fallback:footerFallback},copyright:{path:'brand.copyright',fallback:'© Derma Studio'}}});
const base=(key:string,type:StorefrontBuilderPageType,sections:StorefrontComponentNode[],metadata:Record<string,unknown>={}):StorefrontPageDocument=>({schemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,pageKey:key,pageType:type,templateKey:DERMA_STUDIO_TEMPLATE_KEY,templateVersion:DERMA_STUDIO_TEMPLATE_VERSION,metadata:{scaleOutTemplate:'Derma Studio',visualDNA:DERMA_STUDIO_VISUAL_DNA.character,...metadata},sections});
const productGrid=(id:string,title:string,path:string,columns=4):StorefrontComponentNode=>node({id,componentKey:'commerce.product-grid',componentVersion:1,config:{title,products:[],columns,presentation:'beauty',showBadges:true,showCompareAt:true,imageRatio:'4 / 5',emptyLabel:'Jelenleg nincs megjeleníthető termék.',currency:'HUF'},bindings:{title:{path:`content.${id}.title`,fallback:title},products:{path,fallback:[]}}});
const simple=(key:string,type:StorefrontBuilderPageType,title:string,copy:string)=>base(key,type,[header(key.replaceAll('.','-')),section(`${key.replaceAll('.','-')}-body`,[node({id:`${key}-title`,componentKey:'content.heading',componentVersion:1,config:{text:title,level:1,align:'left',tone:'text'},bindings:{text:{path:`content.${type}.title`,fallback:title}}}),node({id:`${key}-copy`,componentKey:'content.text',componentVersion:1,config:{text:copy,as:'p',align:'left',tone:'muted'},bindings:{text:{path:`content.${type}.copy`,fallback:copy}}})]),footer(key.replaceAll('.','-'))]);

export const DERMA_STUDIO_HOME_PAGE=base('derma-studio.home','home',[
  header('derma-home'),
  node({id:'derma-clarity-hero',componentKey:'editorial.hero',componentVersion:1,config:{eyebrow:'Derma Studio',title:'Tiszta út a következő rutinodhoz.',copy:'Indulj a bőrcélodból, nézd meg a releváns aktív összetevőket, majd építs érthető rutint strukturált termékadatokból — diagnózis és gyógyítási állítás nélkül.',image:'/storefront-demo/derma-studio/clarity.svg',imageAlt:'Derma Studio tiszta, edukációs skincare kompozíció',primaryLabel:'Rutin Finder',primaryHref:'#routine-finder',secondaryLabel:'Bőrcélok',secondaryHref:'#concerns',imagePosition:'right',height:'large'},bindings:{title:{path:'content.clarityHero.title',fallback:'Tiszta út a következő rutinodhoz.'},copy:{path:'content.clarityHero.copy',fallback:'Indulj a bőrcélodból, nézd meg a releváns aktív összetevőket, majd építs érthető rutint strukturált termékadatokból — diagnózis és gyógyítási állítás nélkül.'}}}),
  section('derma-concerns',[node({id:'concerns',componentKey:'commerce.collection-navigation',componentVersion:1,config:{title:'Válassz bőrcél szerint',items:[],columns:4,imageRatio:'1 / 1',tone:'background'},bindings:{items:{path:'collection.concerns',fallback:[]}}})]),
  section('derma-routine-finder',[node({id:'routine-finder',componentKey:'guided.finder',componentVersion:1,config:{eyebrow:'Guided Routine',title:'Építs érthető rutinútvonalat',copy:'A válaszok strukturált termékattribútumokra és magyarázható szabályokra térképeződnek; az eredmény nem diagnózis.',stepTitle:'1. lépés',stepCopy:'Kezdjük a fő bőrcéllal.',question:'Mi a fő célod?',options:[],progressLabel:'1 / 3',actionLabel:'Rutin javaslat',actionHref:'#routine-results',resultStatus:''},bindings:{stepTitle:{path:'finder.currentStep.title',fallback:'1. lépés'},stepCopy:{path:'finder.currentStep.copy',fallback:'Kezdjük a fő bőrcéllal.'},question:{path:'finder.currentQuestion.label',fallback:'Mi a fő célod?'},options:{path:'finder.currentQuestion.options',fallback:[]},progressLabel:{path:'finder.progressLabel',fallback:'1 / 3'},actionHref:{path:'finder.resultHref',fallback:'#routine-results'}}})],'surface'),
  section('derma-active-index',[node({id:'derma-active-index-block',componentKey:'guided.attribute-index',componentVersion:1,config:{eyebrow:'Active Index',title:'Aktív összetevők, érthetően',copy:'Strukturált összetevő-adatok és kapcsolódó termékek egy helyen.',items:[],columns:4},bindings:{items:{path:'catalog.activeIngredientIndex',fallback:[]}}})]),
  node({id:'derma-routine-steps',componentKey:'editorial.split-feature',componentVersion:1,config:{eyebrow:'Routine Steps',title:'Kevesebb zaj. Világosabb lépések.',copy:'A rutinlépések szerkesztett edukációs tartalomként jelennek meg; a tényleges termékillesztést az E3 Finder és a strukturált termékadatok magyarázzák.',image:'/storefront-demo/derma-studio/routine.svg',imageAlt:'Derma Studio rutinlépések vizuál',ctaLabel:'Rutin útmutató',ctaHref:'/oldal/rutin',imagePosition:'left',tone:'surface'},bindings:{title:{path:'content.routineSteps.title',fallback:'Kevesebb zaj. Világosabb lépések.'},copy:{path:'content.routineSteps.copy',fallback:'A rutinlépések szerkesztett edukációs tartalomként jelennek meg; a tényleges termékillesztést az E3 Finder és a strukturált termékadatok magyarázzák.'}}}),
  section('derma-targeted-formulas',[productGrid('dermaTargetedFormulas','Cél szerint válogatva','catalog.targeted',4)]),
  node({id:'derma-ingredient-education',componentKey:'editorial.split-feature',componentVersion:1,config:{eyebrow:'Ingredient Education',title:'Ismerd az aktív összetevőt, mielőtt választasz.',copy:'Edukációs tartalom strukturált termékkapcsolatokkal, diagnózis vagy bizonyítatlan klinikai ígéret nélkül.',image:'/storefront-demo/derma-studio/active.svg',imageAlt:'Derma Studio aktív összetevő vizuál',ctaLabel:'Aktív index',ctaHref:'/oldal/aktiv-osszetevok',imagePosition:'right',tone:'background'},bindings:{title:{path:'content.ingredientEducation.title',fallback:'Ismerd az aktív összetevőt, mielőtt választasz.'},copy:{path:'content.ingredientEducation.copy',fallback:'Edukációs tartalom strukturált termékkapcsolatokkal, diagnózis vagy bizonyítatlan klinikai ígéret nélkül.'}}}),
  section('derma-reviews',[node({id:'derma-review-summary',componentKey:'commerce.review-summary',componentVersion:1,config:{title:'Vásárlói tapasztalatok',rating:0,count:0,summary:'',href:'#reviews'},bindings:{rating:{path:'reviews.rating',fallback:0},count:{path:'reviews.count',fallback:0},summary:{path:'reviews.summary',fallback:''},href:{path:'reviews.href',fallback:'#reviews'}}})]),
  footer('derma-home')
],{sectionOrder:DERMA_STUDIO_HOME_SECTION_ORDER,visualPreset:'concern-routine-clean-home',engineBinding:'E3+E7'});

export const DERMA_STUDIO_CATALOG_PAGE=base('derma-studio.catalog','catalog',[header('derma-catalog'),section('derma-catalog-head',[node({id:'derma-catalog-title',componentKey:'content.heading',componentVersion:1,config:{text:'Skincare',level:1,align:'left',tone:'text'},bindings:{text:{path:'collection.current.title',fallback:'Skincare'}}})]),section('derma-catalog-nav',[node({id:'derma-catalog-attribute-nav',componentKey:'guided.attribute-navigation',componentVersion:1,config:{eyebrow:'Discover',title:'Bőrcél, rutinlépés és aktív összetevő szerint',items:[]},bindings:{items:{path:'catalog.attributeNavigation',fallback:[]}}})]),section('derma-catalog-products',[productGrid('dermaCatalogGrid','Termékek','catalog.products',4)]),footer('derma-catalog')],{engineBinding:'E2+E7'});

export const DERMA_STUDIO_PRODUCT_PAGE=base('derma-studio.product','product',[header('derma-product'),section('derma-product-main',[node({id:'derma-product-layout',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'start'},children:[node({id:'derma-product-gallery',componentKey:'commerce.product-gallery',componentVersion:1,config:{images:[],aspectRatio:'4 / 5',thumbnailPosition:'bottom'},bindings:{images:{path:'product.gallery',fallback:[]}},responsive:{desktop:{gridSpan:7},tablet:{gridSpan:7},mobile:{gridSpan:12}}}),node({id:'derma-product-buybox',componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap:'m',align:'stretch',justify:'start'},responsive:{desktop:{gridSpan:5},tablet:{gridSpan:5},mobile:{gridSpan:12}},children:[node({id:'derma-product-info',componentKey:'commerce.product-info',componentVersion:1,config:{eyebrow:'Derma Studio',title:'Termék',price:'',compareAtPrice:'',description:'',stockLabel:'',badges:[],currency:'HUF'},bindings:{title:{path:'product.name',fallback:'Termék'},price:{path:'pricing.displayPrice',fallback:''},compareAtPrice:{path:'pricing.compareAtPrice',fallback:''},description:{path:'product.description',fallback:''},stockLabel:{path:'inventory.stockLabel',fallback:''},badges:{path:'product.badges',fallback:[]}}}),node({id:'derma-product-snapshot',componentKey:'commerce.key-specs',componentVersion:1,config:{title:'Skin Goal Snapshot',items:[],columns:2,missingLabel:'Nincs megadva'},bindings:{items:{path:'product.keySpecs',fallback:[]}}}),node({id:'derma-product-cta',componentKey:'content.button',componentVersion:1,config:{label:'Kosárba teszem',href:'#purchase',variant:'primary',size:'l',ariaLabel:'Kosárba teszem'},bindings:{label:{path:'commerce.purchaseLabel',fallback:'Kosárba teszem'},href:{path:'commerce.purchaseHref',fallback:'#purchase'}}})]})]})]),section('derma-product-specs',[node({id:'derma-product-spec-groups',componentKey:'commerce.specification-groups',componentVersion:1,config:{title:'Aktív összetevők és tulajdonságok',groups:[],missingLabel:'Nincs megadva'},bindings:{groups:{path:'product.specGroups',fallback:[]}}})]),section('derma-product-finder-evidence',[node({id:'derma-finder-explanation',componentKey:'guided.explanation',componentVersion:1,config:{title:'Miért került ebbe az útvonalba?',matchedTitle:'Egyező szempontok',mismatchedTitle:'Eltérő szempontok',evidence:[]},bindings:{evidence:{path:'finder.productEvidence',fallback:[]}}})],'surface'),section('derma-product-recommendations',[node({id:'derma-product-recommendations-block',componentKey:'commerce.recommendation-row',componentVersion:1,config:{title:'Kapcsolódó rutinlépésekhez',products:[],columns:4,emptyLabel:'Nincs kapcsolódó ajánlat.',currency:'HUF'},bindings:{products:{path:'recommendations.products',fallback:[]}}})]),footer('derma-product')],{engineBinding:'E3+E7',productStructure:'gallery-buybox-skin-goal-snapshot-active-specs-explainability'});

export const DERMA_STUDIO_SEARCH_PAGE=base('derma-studio.search','search',[header('derma-search'),section('derma-search-nav',[node({id:'derma-search-attribute-nav',componentKey:'guided.attribute-navigation',componentVersion:1,config:{eyebrow:'Search',title:'Finomíts bőrcél vagy aktív összetevő szerint',items:[]},bindings:{items:{path:'search.attributeNavigation',fallback:[]}}})]),section('derma-search-products',[productGrid('dermaSearchGrid','Találatok','search.results',4)]),footer('derma-search')],{engineBinding:'E2+E7'});
export const DERMA_STUDIO_CART_PAGE=base('derma-studio.cart','cart',[header('derma-cart'),section('derma-cart-body',[node({id:'derma-cart-summary',componentKey:'commerce.cart-summary',componentVersion:1,config:{lines:[],subtotal:'',total:'',currency:'HUF',checkoutHref:'/penztar',checkoutLabel:'Tovább a pénztárhoz',emptyLabel:'A kosarad üres.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},total:{path:'cart.total',fallback:''}}})]),footer('derma-cart')]);
export const DERMA_STUDIO_CHECKOUT_PAGE=base('derma-studio.checkout','checkout',[header('derma-checkout'),section('derma-checkout-body',[node({id:'derma-checkout-heading',componentKey:'content.heading',componentVersion:1,config:{text:'Pénztár',level:1,align:'left',tone:'text'}}),node({id:'derma-checkout-summary',componentKey:'commerce.checkout-summary',componentVersion:1,config:{lines:[],subtotal:'',shipping:'',total:'',currency:'HUF',secureLabel:'Biztonságos, provider-neutral checkout.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},shipping:{path:'cart.shipping',fallback:''},total:{path:'cart.total',fallback:''}}})]),footer('derma-checkout')],{engineBinding:'E13'});
export const DERMA_STUDIO_ACCOUNT_PAGE=simple('derma-studio.account','account','Fiókom','Rendelések, mentett preferenciák és vásárlói adatok.');
export const DERMA_STUDIO_CONTENT_PAGE=base('derma-studio.content','content',[header('derma-content'),section('derma-content-guide',[node({id:'derma-content-title',componentKey:'content.heading',componentVersion:1,config:{text:'Rutin útmutató',level:1,align:'left',tone:'text'},bindings:{text:{path:'content.routine.title',fallback:'Rutin útmutató'}}}),node({id:'derma-content-nav',componentKey:'guided.attribute-navigation',componentVersion:1,config:{eyebrow:'Guide',title:'Bőrcél → rutinlépés → aktív összetevő',items:[]},bindings:{items:{path:'content.routine.navigation',fallback:[]}}})]),footer('derma-content')],{contentRole:'routine-guide',engineBinding:'E3+E7'});
export const DERMA_STUDIO_BLOG_INDEX_PAGE=simple('derma-studio.blog-index','blog-index','Skin Notes','Edukációs cikkek rutinról, összetevőkről és termékhasználati preferenciákról.');
export const DERMA_STUDIO_BLOG_ARTICLE_PAGE=simple('derma-studio.blog-article','blog-article','Skin Note','Edukációs tartalom orvosi diagnózis vagy kezelési ígéret nélkül.');
export const DERMA_STUDIO_FAQ_PAGE=simple('derma-studio.faq','faq','GYIK','Rutin, használat, összetevők, szállítás és visszaküldés.');
export const DERMA_STUDIO_CONTACT_PAGE=simple('derma-studio.contact','contact','Kapcsolat','Kapcsolat és ügyfélszolgálat.');
export const DERMA_STUDIO_LEGAL_PAGE=simple('derma-studio.legal','legal','Jogi információk','A kereskedő jogi és adatkezelési tartalmának helye.');
export const DERMA_STUDIO_NOT_FOUND_PAGE=simple('derma-studio.not-found','not-found','404','A keresett oldal nem található.');

export const DERMA_STUDIO_TEMPLATE_MANIFEST=defineStorefrontTemplateManifest({foundationVersion:STOREFRONT_BUILDER_FOUNDATION_VERSION,manifestVersion:STOREFRONT_TEMPLATE_MANIFEST_VERSION,templateKey:DERMA_STUDIO_TEMPLATE_KEY,templateVersion:DERMA_STUDIO_TEMPLATE_VERSION,pageSchemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,minPlan:'alap',requiredFeatures:['catalog','inventory','orders','contentMarketing','productRecommendations','searchFiltering','commerceIntegrations'],pageTypes:['home','catalog','product','search','cart','checkout','account','content','blog-index','blog-article','faq','contact','legal','not-found'],responsive:{desktop:true,tablet:true,mobile:true},migration:STOREFRONT_TEMPLATE_MIGRATION_POLICY,demoContent:{namespace:'beauty-derma-studio',policy:STOREFRONT_DEMO_CONTENT_POLICY}});
export const DERMA_STUDIO_TEMPLATE_PACKAGE:StorefrontInstallableTemplatePackage={manifest:DERMA_STUDIO_TEMPLATE_MANIFEST,pages:[DERMA_STUDIO_HOME_PAGE,DERMA_STUDIO_CATALOG_PAGE,DERMA_STUDIO_PRODUCT_PAGE,DERMA_STUDIO_SEARCH_PAGE,DERMA_STUDIO_CART_PAGE,DERMA_STUDIO_CHECKOUT_PAGE,DERMA_STUDIO_ACCOUNT_PAGE,DERMA_STUDIO_CONTENT_PAGE,DERMA_STUDIO_BLOG_INDEX_PAGE,DERMA_STUDIO_BLOG_ARTICLE_PAGE,DERMA_STUDIO_FAQ_PAGE,DERMA_STUDIO_CONTACT_PAGE,DERMA_STUDIO_LEGAL_PAGE,DERMA_STUDIO_NOT_FOUND_PAGE],demoFixtures:[{entityType:'collection',entityKey:'skin-goals',payload:{title:'Bőrcélok',handle:'skin-goals',demo:true}},{entityType:'product',entityKey:'barrier-serum',payload:{name:'Barrier Serum',slug:'barrier-serum',demo:true}},{entityType:'product',entityKey:'daily-fluid',payload:{name:'Daily Fluid',slug:'daily-fluid',demo:true}},{entityType:'content',entityKey:'active-index',payload:{title:'Active Ingredient Index',kind:'ingredient-education',demo:true}}]};
