import {STOREFRONT_BUILDER_FOUNDATION_VERSION,STOREFRONT_DEMO_CONTENT_POLICY,STOREFRONT_PAGE_SCHEMA_VERSION,STOREFRONT_TEMPLATE_MANIFEST_VERSION,STOREFRONT_TEMPLATE_MIGRATION_POLICY,defineStorefrontTemplateManifest,type StorefrontBuilderPageType} from '@/lib/builder/storefront-foundation';
import type {StorefrontComponentNode,StorefrontPageDocument} from '@/lib/builder/storefront-runtime';
import type {StorefrontInstallableTemplatePackage} from '@/lib/builder/storefront-template-installation';

export const EDITORIAL_ATELIER_TEMPLATE_KEY='fashion.editorial-atelier' as const;
export const EDITORIAL_ATELIER_TEMPLATE_VERSION=1 as const;
export const EDITORIAL_ATELIER_VISUAL_DNA=Object.freeze({character:'fashion-magazine-meets-premium-commerce',category:'fashion-apparel',position:'editorial-asymmetric-campaign-led-luxury',palette:{background:'broken-white',surface:'sand-beige',text:'ink-black',accent:'merchant-replaceable'},typography:{display:'high-contrast-editorial-serif',interface:'modern-clean-sans'},spacing:'large-editorial-negative-space',imagery:'large-campaign-fashion-photography-with-crop-led-composition',composition:'asymmetric-editorial-story-before-grid',imageRatios:{campaign:'3 / 4',product:'4 / 5',journal:'3 / 2'},exclusions:['monarche-balanced-retail-grid-clone','street-drop-culture-clone','discount-density','symmetric-hero-cards-grid-default','baked-in-campaign-text','fabricated-price-stock-rating-material-or-fit-claim']} as const);
export const EDITORIAL_ATELIER_DESIGN_TOKENS=Object.freeze({'--shoporation-color-background':'#f6f1ea','--shoporation-color-surface':'#e8ddd0','--shoporation-color-surface-muted':'#d8cabc','--shoporation-color-text':'#151412','--shoporation-color-muted-text':'#69635d','--shoporation-color-border':'#c9bcae','--shoporation-color-primary':'#151412','--shoporation-color-primary-contrast':'#fffaf4','--shoporation-color-accent':'var(--merchant-accent, #8f6d61)','--shoporation-heading-font':'var(--merchant-heading-font, Georgia, serif)','--shoporation-body-font':'var(--merchant-body-font, Arial, sans-serif)'} as const);
export const EDITORIAL_ATELIER_ENGINE_CONTRACT=Object.freeze({requiredForFullExperience:['E1','E2','E10','E13'] as const,optional:['E7'] as const,integration:{E1:'shared-page-schema-runtime',E2:'catalog-search-product-eligibility-authority',E10:'campaign-journal-lookbook-story-authority',E13:'provider-neutral-cart-checkout-authority',E7:'optional-structured-product-facts-only-when-supplied'},authorityRule:'editorial-atelier-presentation-never-invents-price-stock-rating-material-fit-sizing-product-attribute-or-order-authority'} as const);
export const EDITORIAL_ATELIER_PRO_CONTRACT=Object.freeze({feature:'shop-the-look-interactive-scene',plan:'pro',alapFallback:'editorial-split-story-plus-authoritative-product-recommendation',implementationBoundary:'future-shared-interactive-scene-or-composer-engine-required-no-template-specific-hotspot-engine',authorityBoundary:'hotspots-may-reference-authoritative-products-but-never-own-price-stock-variant-or-order-state'} as const);
export const EDITORIAL_ATELIER_HOME_SECTION_ORDER=['Magazine Cover Hero','Issue Statement','Campaign Story I','Campaign Story II','The Edit','Shop the Story','Featured Silhouettes','Journal','Newsletter','Footer'] as const;

const n=(x:StorefrontComponentNode):StorefrontComponentNode=>x;
const sec=(id:string,children:StorefrontComponentNode[],tone='background',spacing='xl'):StorefrontComponentNode=>n({id,componentKey:'layout.section',componentVersion:1,config:{tone,spacing,width:'full'},children:[n({id:`${id}-container`,componentKey:'layout.container',componentVersion:1,config:{width:'content',spacing:'m'},children})]});
const nav=[{label:'New Issue',href:'/webaruhaz?sort=new'},{label:'Women',href:'/webaruhaz?collection=women'},{label:'Men',href:'/webaruhaz?collection=men'},{label:'The Edit',href:'/webaruhaz?collection=the-edit'},{label:'Journal',href:'/blog'}];
const header=(p:string)=>n({id:`${p}-header`,componentKey:'system.header',componentVersion:1,config:{brandLabel:'Atelier Nova',brandHref:'/',tone:'background',sticky:true},bindings:{brandLabel:{path:'brand.name',fallback:'Atelier Nova'},brandHref:{path:'brand.homeHref',fallback:'/'}},children:[n({id:`${p}-nav`,componentKey:'system.navigation',componentVersion:1,config:{ariaLabel:'Fő navigáció',items:nav,layout:'horizontal'},bindings:{items:{path:'navigation.primary',fallback:nav}}})]});
const footerCols=[{id:'shop',title:'Shop',items:[{label:'New Issue',href:'/webaruhaz?sort=new'},{label:'Women',href:'/webaruhaz?collection=women'},{label:'Men',href:'/webaruhaz?collection=men'},{label:'The Edit',href:'/webaruhaz?collection=the-edit'}]},{id:'atelier',title:'Atelier',items:[{label:'Journal',href:'/blog'},{label:'Kapcsolat',href:'/kapcsolat'},{label:'GYIK',href:'/gyik'}]}];
const footer=(p:string)=>n({id:`${p}-footer`,componentKey:'editorial.footer',componentVersion:1,config:{brandLabel:'Atelier Nova',columns:footerCols,copyright:'© Atelier Nova',tone:'primary'},bindings:{brandLabel:{path:'brand.name',fallback:'Atelier Nova'},columns:{path:'navigation.footer',fallback:footerCols},copyright:{path:'brand.copyright',fallback:'© Atelier Nova'}}});
const base=(key:string,type:StorefrontBuilderPageType,sections:StorefrontComponentNode[],metadata:Record<string,unknown>={}):StorefrontPageDocument=>({schemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,pageKey:key,pageType:type,templateKey:EDITORIAL_ATELIER_TEMPLATE_KEY,templateVersion:EDITORIAL_ATELIER_TEMPLATE_VERSION,metadata:{scaleOutWave:25,templateCategory:'fashion-apparel',visualDNA:EDITORIAL_ATELIER_VISUAL_DNA.character,portfolioPosition:EDITORIAL_ATELIER_VISUAL_DNA.position,authorityRule:EDITORIAL_ATELIER_ENGINE_CONTRACT.authorityRule,...metadata},sections});
const heading=(id:string,text:string,level=2)=>n({id,componentKey:'content.heading',componentVersion:1,config:{text,level,align:'left',tone:'text'},bindings:{text:{path:`content.${id}.text`,fallback:text}}});
const text=(id:string,value:string)=>n({id,componentKey:'content.text',componentVersion:1,config:{text:value,as:'p',align:'left',tone:'muted'},bindings:{text:{path:`content.${id}.text`,fallback:value}}});
const grid=(id:string,title:string,path:string,columns=3,presentation='editorial')=>n({id,componentKey:'commerce.product-grid',componentVersion:1,config:{title,products:[],columns,presentation,showBadges:true,showCompareAt:true,imageRatio:'4 / 5',emptyLabel:'Jelenleg nincs megjeleníthető darab.',currency:'HUF'},bindings:{title:{path:`content.${id}.title`,fallback:title},products:{path,fallback:[]}}});
const rec=(id:string,title:string,path:string,columns=3)=>n({id,componentKey:'commerce.recommendation-row',componentVersion:1,config:{title,products:[],columns,emptyLabel:'Jelenleg nincs kapcsolódó ajánlat.',currency:'HUF'},bindings:{title:{path:`content.${id}.title`,fallback:title},products:{path,fallback:[]}}});
const split=(id:string,root:string,input:{eyebrow:string;title:string;copy:string;image:string;imageAlt:string;ctaLabel:string;ctaHref:string;imagePosition:'left'|'right';tone:string})=>n({id,componentKey:'editorial.split-feature',componentVersion:1,config:input,bindings:{eyebrow:{path:`content.${root}.eyebrow`,fallback:input.eyebrow},title:{path:`content.${root}.title`,fallback:input.title},copy:{path:`content.${root}.copy`,fallback:input.copy},image:{path:`content.${root}.image`,fallback:input.image},imageAlt:{path:`content.${root}.imageAlt`,fallback:input.imageAlt},ctaLabel:{path:`content.${root}.ctaLabel`,fallback:input.ctaLabel},ctaHref:{path:`content.${root}.ctaHref`,fallback:input.ctaHref}}});
const simple=(key:string,type:StorefrontBuilderPageType,title:string,copy:string,preset:string)=>{const p=key.replaceAll('.','-');return base(key,type,[header(p),sec(`${p}-content`,[heading(`${p}-title`,title,1),text(`${p}-copy`,copy)]),footer(p)],{visualPreset:preset});};

export const EDITORIAL_ATELIER_HOME_PAGE=base('editorial-atelier.home','home',[
 header('atelier-home'),
 n({id:'atelier-cover',componentKey:'editorial.hero',componentVersion:1,config:{eyebrow:'Issue 01 / New Season',title:'A wardrobe, edited like a magazine.',copy:'Nagy képek, kevés zaj és szerkesztett darabok egy kampányvezérelt divatélményben.',image:'/storefront-demo/editorial-atelier/cover.svg',imageAlt:'Atelier Nova editorial kampányfotó',primaryLabel:'Read the issue',primaryHref:'#atelier-issue',secondaryLabel:'Shop the edit',secondaryHref:'/webaruhaz?collection=the-edit',imagePosition:'left',height:'cover'},bindings:{eyebrow:{path:'content.atelierCover.eyebrow',fallback:'Issue 01 / New Season'},title:{path:'content.atelierCover.title',fallback:'A wardrobe, edited like a magazine.'},copy:{path:'content.atelierCover.copy',fallback:'Nagy képek, kevés zaj és szerkesztett darabok egy kampányvezérelt divatélményben.'},image:{path:'content.atelierCover.image',fallback:'/storefront-demo/editorial-atelier/cover.svg'},imageAlt:{path:'content.atelierCover.imageAlt',fallback:'Atelier Nova editorial kampányfotó'},primaryLabel:{path:'content.atelierCover.primaryLabel',fallback:'Read the issue'},primaryHref:{path:'content.atelierCover.primaryHref',fallback:'#atelier-issue'},secondaryLabel:{path:'content.atelierCover.secondaryLabel',fallback:'Shop the edit'},secondaryHref:{path:'content.atelierCover.secondaryHref',fallback:'/webaruhaz?collection=the-edit'}}}),
 sec('atelier-issue',[heading('atelierIssueTitle','This issue: proportion, movement, restraint.'),text('atelierIssueCopy','A szerkesztett történet vezeti a vásárlást; a termékadatokat továbbra is a commerce authority szolgáltatja.')],'background','l'),
 split('atelier-campaign-one','campaignOne',{eyebrow:'Campaign / I',title:'Volume against silence.',copy:'Egyetlen erős kép és történeti fókuszpont — nem klasszikus retail kártyasor.',image:'/storefront-demo/editorial-atelier/campaign-one.svg',imageAlt:'Atelier Nova kampány I',ctaLabel:'Explore the story',ctaHref:'/blog/campaign-one',imagePosition:'right',tone:'surface'}),
 split('atelier-campaign-two','campaignTwo',{eyebrow:'Campaign / II',title:'Structure in motion.',copy:'A második kampánykép ellenpontot ad: eltérő crop, fordított képoldal, kevesebb szöveg.',image:'/storefront-demo/editorial-atelier/campaign-two.svg',imageAlt:'Atelier Nova kampány II',ctaLabel:'See the edit',ctaHref:'/webaruhaz?collection=campaign-two',imagePosition:'left',tone:'background'}),
 sec('atelier-the-edit',[grid('atelierTheEdit','The Edit','catalog.theEdit',3)],'surface'),
 split('atelier-shop-story','shopStory',{eyebrow:'Shop the Story',title:'One look, multiple pieces.',copy:'Alapban editorial történet és kapcsolódó termékajánló; a Pro hotspot réteg közös Interactive Scene/Composer engine-re épülhet.',image:'/storefront-demo/editorial-atelier/shop-story.svg',imageAlt:'Atelier Nova összeállítás',ctaLabel:'Shop the look',ctaHref:'#atelier-shop-story-products',imagePosition:'right',tone:'primary'}),
 sec('atelier-shop-story-products',[rec('atelierShopStoryProducts','Pieces from the story','recommendations.shopStory',3)],'background','l'),
 sec('atelier-featured',[grid('atelierFeaturedSilhouettes','Featured silhouettes','catalog.featuredSilhouettes',2,'story')],'background','xl'),
 sec('atelier-journal',[n({id:'atelier-journal-preview',componentKey:'editorial.journal-preview',componentVersion:1,config:{title:'Journal / Notes from the issue',items:[],columns:3,emptyLabel:'A következő editorial történet hamarosan érkezik.'},bindings:{title:{path:'content.journal.title',fallback:'Journal / Notes from the issue'},items:{path:'content.journal.items',fallback:[]}}})]),
 n({id:'atelier-newsletter',componentKey:'marketing.newsletter-signup',componentVersion:1,config:{eyebrow:'Atelier Notes',title:'The next issue, in your inbox.',copy:'Kampányok, Journal és új szerkesztett válogatások.',actionHref:'/hirlevel',inputLabel:'E-mail-cím',buttonLabel:'Feliratkozom',consentLabel:'A feliratkozással elfogadod az adatkezelési tájékoztatót.',tone:'primary'},bindings:{eyebrow:{path:'content.newsletter.eyebrow',fallback:'Atelier Notes'},title:{path:'content.newsletter.title',fallback:'The next issue, in your inbox.'},copy:{path:'content.newsletter.copy',fallback:'Kampányok, Journal és új szerkesztett válogatások.'},actionHref:{path:'content.newsletter.actionHref',fallback:'/hirlevel'},inputLabel:{path:'content.newsletter.inputLabel',fallback:'E-mail-cím'},buttonLabel:{path:'content.newsletter.buttonLabel',fallback:'Feliratkozom'},consentLabel:{path:'content.newsletter.consentLabel',fallback:'A feliratkozással elfogadod az adatkezelési tájékoztatót.'}}}),
 footer('atelier-home')
],{sectionOrder:EDITORIAL_ATELIER_HOME_SECTION_ORDER,visualPreset:'asymmetric-fashion-magazine-home',builderLayers:{cover:['image','eyebrow','title','copy','primaryLabel','primaryHref','secondaryLabel','secondaryHref'],campaignOne:['image','eyebrow','title','copy','ctaLabel','ctaHref'],campaignTwo:['image','eyebrow','title','copy','ctaLabel','ctaHref'],shopStory:['image','eyebrow','title','copy','ctaLabel','ctaHref'],responsive:['desktop','tablet','mobile']},engineBinding:'E2+E10',proContract:EDITORIAL_ATELIER_PRO_CONTRACT});

export const EDITORIAL_ATELIER_CATALOG_PAGE=base('editorial-atelier.catalog','catalog',[header('atelier-catalog'),sec('atelier-catalog-head',[n({id:'atelier-catalog-header',componentKey:'commerce.collection-header',componentVersion:1,config:{eyebrow:'The Edit',title:'Collection',description:'Szerkesztett termékek kampány- és kollekciókontextussal.',image:'',imageAlt:'',align:'left'},bindings:{eyebrow:{path:'collection.current.eyebrow',fallback:'The Edit'},title:{path:'collection.current.title',fallback:'Collection'},description:{path:'collection.current.description',fallback:'Szerkesztett termékek kampány- és kollekciókontextussal.'},image:{path:'collection.current.image',fallback:''},imageAlt:{path:'collection.current.imageAlt',fallback:''}}})]),sec('atelier-catalog-products',[grid('atelierCatalogGrid','Collection','catalog.products',3)]),footer('atelier-catalog')],{visualPreset:'editorial-collection',engineBinding:'E2'});

export const EDITORIAL_ATELIER_PRODUCT_PAGE=base('editorial-atelier.product','product',[header('atelier-product'),sec('atelier-product-main',[n({id:'atelier-product-grid',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'start'},children:[n({id:'atelier-product-gallery',componentKey:'commerce.product-gallery',componentVersion:1,config:{images:[],aspectRatio:'4 / 5',thumbnailPosition:'bottom'},bindings:{images:{path:'product.gallery',fallback:[]}},responsive:{desktop:{gridSpan:7},tablet:{gridSpan:7},mobile:{gridSpan:12}}}),n({id:'atelier-product-buybox',componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap:'m',align:'stretch',justify:'start'},responsive:{desktop:{gridSpan:5},tablet:{gridSpan:5},mobile:{gridSpan:12}},children:[n({id:'atelier-product-info',componentKey:'commerce.product-info',componentVersion:1,config:{eyebrow:'Atelier Nova',title:'Termék',price:'',compareAtPrice:'',description:'',stockLabel:'',badges:[],currency:'HUF'},bindings:{eyebrow:{path:'product.eyebrow',fallback:'Atelier Nova'},title:{path:'product.name',fallback:'Termék'},price:{path:'pricing.displayPrice',fallback:''},compareAtPrice:{path:'pricing.compareAtPrice',fallback:''},description:{path:'product.description',fallback:''},stockLabel:{path:'inventory.stockLabel',fallback:''},badges:{path:'product.badges',fallback:[]}}}),n({id:'atelier-product-color',componentKey:'commerce.variant-swatches',componentVersion:1,config:{label:'Szín',options:[]},bindings:{label:{path:'variant.colorLabel',fallback:'Szín'},options:{path:'variant.colorOptions',fallback:[]}}}),n({id:'atelier-product-size',componentKey:'commerce.size-selector',componentVersion:1,config:{label:'Méret',options:[]},bindings:{label:{path:'variant.sizeLabel',fallback:'Méret'},options:{path:'variant.sizeOptions',fallback:[]}}}),n({id:'atelier-product-cta',componentKey:'content.button',componentVersion:1,config:{label:'Kosárba teszem',href:'#purchase',variant:'primary',size:'l',ariaLabel:'Kosárba teszem'},bindings:{label:{path:'commerce.purchaseLabel',fallback:'Kosárba teszem'},href:{path:'commerce.purchaseHref',fallback:'#purchase'}}})]})]})]),sec('atelier-product-editorial',[heading('atelierProductStoryTitle','From the issue'),text('atelierProductStoryCopy','Editorial kontextus jelenhet meg itt, de az ár, készlet, méret és termékállítások authority-ját nem írhatja felül.')],'surface'),sec('atelier-product-recommendations',[rec('atelierProductRecommendations','Complete the edit','recommendations.products',3)]),footer('atelier-product')],{visualPreset:'editorial-product-gallery-buybox',variantContract:'attribute-based-generic',soldOutVariantBehavior:'visible-disabled',engineBinding:'E2+E10',pdpGrid:{desktop:'7/12+5/12',tablet:'7/12+5/12',mobile:'12/12+12/12'},commerceClarity:['price','stock','size','purchase-cta']});

export const EDITORIAL_ATELIER_SEARCH_PAGE=base('editorial-atelier.search','search',[header('atelier-search'),sec('atelier-search-head',[heading('atelierSearchTitle','Search the issue',1),text('atelierSearchCopy','')]),sec('atelier-search-results',[grid('atelierSearchResults','Találatok','search.results',3)]),footer('atelier-search')],{engineBinding:'E2'});
export const EDITORIAL_ATELIER_CART_PAGE=base('editorial-atelier.cart','cart',[header('atelier-cart'),sec('atelier-cart-summary',[n({id:'atelier-cart-summary-block',componentKey:'commerce.cart-summary',componentVersion:1,config:{lines:[],subtotal:'',total:'',currency:'HUF',checkoutHref:'/penztar',checkoutLabel:'Tovább a pénztárhoz',emptyLabel:'A kosarad jelenleg üres.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},total:{path:'cart.total',fallback:''}}})]),sec('atelier-cart-rec',[rec('atelierCartRecommendations','From the same issue','recommendations.cart',3)],'surface'),footer('atelier-cart')],{engineBinding:'E13'});
export const EDITORIAL_ATELIER_CHECKOUT_PAGE=base('editorial-atelier.checkout','checkout',[header('atelier-checkout'),sec('atelier-checkout-body',[heading('atelierCheckoutTitle','Pénztár',1),n({id:'atelier-checkout-summary',componentKey:'commerce.checkout-summary',componentVersion:1,config:{lines:[],subtotal:'',shipping:'',total:'',currency:'HUF',secureLabel:'Biztonságos, provider-neutral checkout.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},shipping:{path:'cart.shipping',fallback:''},total:{path:'cart.total',fallback:''}}})]),footer('atelier-checkout')],{engineBinding:'E13',checkoutUxContract:'guided-accordion-owned-by-shared-e13-checkout-runtime-not-template-local'});
export const EDITORIAL_ATELIER_ACCOUNT_PAGE=simple('editorial-atelier.account','account','Fiókom','Rendelések, profiladatok és vásárlói beállítások.','quiet-account');
export const EDITORIAL_ATELIER_CONTENT_PAGE=base('editorial-atelier.content','content',[header('atelier-content'),n({id:'atelier-content-hero',componentKey:'editorial.hero',componentVersion:1,config:{eyebrow:'Atelier',title:'A campaign becomes a story.',copy:'Hosszabb editorial tartalom nagy képekkel és szerkesztett ritmussal.',image:'/storefront-demo/editorial-atelier/campaign-two.svg',imageAlt:'Atelier Nova editorial tartalom',primaryLabel:'Journal',primaryHref:'/blog',secondaryLabel:'Shop',secondaryHref:'/webaruhaz',imagePosition:'right',height:'article'},bindings:{title:{path:'content.content.title',fallback:'A campaign becomes a story.'},copy:{path:'content.content.copy',fallback:'Hosszabb editorial tartalom nagy képekkel és szerkesztett ritmussal.'},image:{path:'content.content.image',fallback:'/storefront-demo/editorial-atelier/campaign-two.svg'},imageAlt:{path:'content.content.imageAlt',fallback:'Atelier Nova editorial tartalom'}}}),footer('atelier-content')],{visualPreset:'editorial-longform',engineBinding:'E10'});
export const EDITORIAL_ATELIER_BLOG_INDEX_PAGE=base('editorial-atelier.blog-index','blog-index',[header('atelier-blog-index'),sec('atelier-blog-index-list',[n({id:'atelier-blog-journal',componentKey:'editorial.journal-preview',componentVersion:1,config:{title:'Journal',items:[],columns:3,emptyLabel:'A Journal hamarosan új történetekkel jelentkezik.'},bindings:{title:{path:'content.blog.title',fallback:'Journal'},items:{path:'content.blog.posts',fallback:[]}}})]),footer('atelier-blog-index')],{visualPreset:'magazine-journal-index',engineBinding:'E10'});
export const EDITORIAL_ATELIER_BLOG_ARTICLE_PAGE=base('editorial-atelier.blog-article','blog-article',[header('atelier-blog-article'),n({id:'atelier-article-hero',componentKey:'editorial.hero',componentVersion:1,config:{eyebrow:'Journal',title:'Editorial story',copy:'',image:'',imageAlt:'',primaryLabel:'',primaryHref:'#',secondaryLabel:'',secondaryHref:'#',imagePosition:'left',height:'article'},bindings:{eyebrow:{path:'content.article.eyebrow',fallback:'Journal'},title:{path:'content.article.title',fallback:'Editorial story'},copy:{path:'content.article.excerpt',fallback:''},image:{path:'content.article.image',fallback:''},imageAlt:{path:'content.article.imageAlt',fallback:''}}}),sec('atelier-article-body',[text('atelierArticleBody','')]),footer('atelier-blog-article')],{visualPreset:'magazine-journal-article',engineBinding:'E10'});
export const EDITORIAL_ATELIER_FAQ_PAGE=simple('editorial-atelier.faq','faq','Gyakori kérdések','Rendelés, szállítás, visszaküldés és termékinformáció.','service-editorial');
export const EDITORIAL_ATELIER_CONTACT_PAGE=simple('editorial-atelier.contact','contact','Kapcsolat','Írj nekünk, ha segítségre van szükséged.','service-editorial');
export const EDITORIAL_ATELIER_LEGAL_PAGE=simple('editorial-atelier.legal','legal','Jogi információk','A kereskedő által kezelt jogi és adatkezelési tartalom helye.','legal-editorial');
export const EDITORIAL_ATELIER_NOT_FOUND_PAGE=base('editorial-atelier.not-found','not-found',[header('atelier-not-found'),sec('atelier-not-found-body',[heading('atelierNotFoundTitle','404 / Between issues',1),text('atelierNotFoundCopy','Ez az oldal már nem található.'),n({id:'atelier-not-found-cta',componentKey:'content.button',componentVersion:1,config:{label:'Vissza a főoldalra',href:'/',variant:'secondary',size:'m',ariaLabel:'Vissza a főoldalra'}})]),footer('atelier-not-found')],{visualPreset:'magazine-not-found'});

export const EDITORIAL_ATELIER_TEMPLATE_MANIFEST=defineStorefrontTemplateManifest({foundationVersion:STOREFRONT_BUILDER_FOUNDATION_VERSION,manifestVersion:STOREFRONT_TEMPLATE_MANIFEST_VERSION,templateKey:EDITORIAL_ATELIER_TEMPLATE_KEY,templateVersion:EDITORIAL_ATELIER_TEMPLATE_VERSION,pageSchemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,minPlan:'alap',requiredFeatures:['catalog','inventory','orders','contentMarketing','marketingBasics','productRecommendations','searchFiltering','commerceIntegrations'],pageTypes:['home','catalog','product','search','cart','checkout','account','content','blog-index','blog-article','faq','contact','legal','not-found'],responsive:{desktop:true,tablet:true,mobile:true},migration:STOREFRONT_TEMPLATE_MIGRATION_POLICY,demoContent:{namespace:'fashion-editorial-atelier',policy:STOREFRONT_DEMO_CONTENT_POLICY}});
export const EDITORIAL_ATELIER_TEMPLATE_PACKAGE:StorefrontInstallableTemplatePackage={manifest:EDITORIAL_ATELIER_TEMPLATE_MANIFEST,pages:[EDITORIAL_ATELIER_HOME_PAGE,EDITORIAL_ATELIER_CATALOG_PAGE,EDITORIAL_ATELIER_PRODUCT_PAGE,EDITORIAL_ATELIER_SEARCH_PAGE,EDITORIAL_ATELIER_CART_PAGE,EDITORIAL_ATELIER_CHECKOUT_PAGE,EDITORIAL_ATELIER_ACCOUNT_PAGE,EDITORIAL_ATELIER_CONTENT_PAGE,EDITORIAL_ATELIER_BLOG_INDEX_PAGE,EDITORIAL_ATELIER_BLOG_ARTICLE_PAGE,EDITORIAL_ATELIER_FAQ_PAGE,EDITORIAL_ATELIER_CONTACT_PAGE,EDITORIAL_ATELIER_LEGAL_PAGE,EDITORIAL_ATELIER_NOT_FOUND_PAGE],demoFixtures:[{entityType:'collection',entityKey:'the-edit',payload:{title:'The Edit',handle:'the-edit',demo:true}},{entityType:'collection',entityKey:'campaign-two',payload:{title:'Campaign II',handle:'campaign-two',demo:true}},{entityType:'product',entityKey:'longline-coat',payload:{name:'Longline Coat',slug:'longline-coat',demo:true}},{entityType:'product',entityKey:'column-dress',payload:{name:'Column Dress',slug:'column-dress',demo:true}},{entityType:'product',entityKey:'wide-trouser',payload:{name:'Wide Trouser',slug:'wide-trouser',demo:true}},{entityType:'content',entityKey:'issue-01',payload:{title:'Issue 01',kind:'journal',demo:true}}]};