import {STOREFRONT_BUILDER_FOUNDATION_VERSION,STOREFRONT_DEMO_CONTENT_POLICY,STOREFRONT_PAGE_SCHEMA_VERSION,STOREFRONT_TEMPLATE_MANIFEST_VERSION,STOREFRONT_TEMPLATE_MIGRATION_POLICY,defineStorefrontTemplateManifest,type StorefrontBuilderPageType} from '@/lib/builder/storefront-foundation';
import type {StorefrontComponentNode,StorefrontPageDocument} from '@/lib/builder/storefront-runtime';
import type {StorefrontInstallableTemplatePackage} from '@/lib/builder/storefront-template-installation';

export const MODERN_LUXE_TEMPLATE_KEY='jewelry.modern-luxe' as const;
export const MODERN_LUXE_TEMPLATE_VERSION=1 as const;
export const MODERN_LUXE_VISUAL_DNA=Object.freeze({
  character:'premium-modern-jewelry-accessories-spacious-editorial-luxe',
  categories:['Ékszerek','Órák','Táskák','Napszemüvegek','Kiegészítők'],
  palette:{background:'ivory',accent:'champagne-gold',text:'black'},
  typography:{display:'elegant-editorial-serif',interface:'clean-sans',requirements:['builder-available','hungarian-characters']},
  spacing:'airy-separated',
  imagery:'large-close-up-jewelry-watch-bag-accessory',
  exclusions:['streetwear','skate','graffiti','neon','crowded-home','hero-carousel-next-prev','baked-in-marketing-copy','overloaded-gold'],
} as const);
export const MODERN_LUXE_DESIGN_TOKENS=Object.freeze({'--shoporation-color-background':'#F7F3EA','--shoporation-color-surface':'#EFE8DB','--shoporation-color-surface-muted':'#E4DBCA','--shoporation-color-text':'#111111','--shoporation-color-muted-text':'#6A6258','--shoporation-color-border':'#D8CCB9','--shoporation-color-primary':'#111111','--shoporation-color-primary-contrast':'#F7F3EA','--shoporation-color-accent':'var(--merchant-accent, #B89A62)','--shoporation-heading-font':'var(--merchant-heading-font, Georgia, serif)','--shoporation-body-font':'var(--merchant-body-font, Arial, sans-serif)'} as const);
export const MODERN_LUXE_ENGINE_CONTRACT=Object.freeze({requiredForFullExperience:['E1','E2','E13'] as const,optional:['E7','Recommendations'] as const,scaleOutIntegration:{E1:'shared-runtime',E2:'shared-product-discovery-authority',E13:'shared-checkout-authority',E7:'optional-material-size-specs',Recommendations:'shared-recommendation-surface'},marketingLayerRule:'hero-image-title-subtitle-cta-badge-overlay-decoration-separate-editable-layers'} as const);
export const MODERN_LUXE_HOME_SECTION_ORDER=['Layered Luxe Hero','Category Edit','Signature Selection','Ajándéknak választva','Brand Story','Footer'] as const;
export const MODERN_LUXE_SPACING_CONTRACT=Object.freeze({presets:['narrow','normal','airy','custom'] as const,defaultPreset:'airy',controls:['section-gap','inner-padding','column-gap'] as const,responsive:['desktop','tablet','mobile'] as const});

const node=(x:StorefrontComponentNode):StorefrontComponentNode=>x;
const section=(id:string,children:StorefrontComponentNode[],tone='background'):StorefrontComponentNode=>node({id,componentKey:'layout.section',componentVersion:1,config:{tone,spacing:'xl',width:'full'},children:[node({id:`${id}-container`,componentKey:'layout.container',componentVersion:1,config:{width:'content',spacing:'none'},children})]});
const header=(p:string):StorefrontComponentNode=>node({id:`${p}-header`,componentKey:'system.header',componentVersion:1,config:{brandLabel:'Modern Luxe',brandHref:'/',tone:'background',sticky:true},bindings:{brandLabel:{path:'brand.name',fallback:'Modern Luxe'},brandHref:{path:'brand.homeHref',fallback:'/'}},children:[node({id:`${p}-nav`,componentKey:'system.navigation',componentVersion:1,config:{ariaLabel:'Fő navigáció',items:[],layout:'horizontal'},bindings:{items:{path:'navigation.primary',fallback:[]}}})]});
const footerFallback=[{id:'shop',title:'Shop',items:[{label:'Ékszerek',href:'/webaruhaz'},{label:'Órák',href:'/webaruhaz'}]},{id:'service',title:'Szolgáltatás',items:[{label:'Kapcsolat',href:'/kapcsolat'},{label:'GYIK',href:'/gyik'}]}];
const footer=(p:string):StorefrontComponentNode=>node({id:`${p}-footer`,componentKey:'editorial.footer',componentVersion:1,config:{brandLabel:'Modern Luxe',columns:footerFallback,copyright:'© Modern Luxe',tone:'background'},bindings:{brandLabel:{path:'brand.name',fallback:'Modern Luxe'},columns:{path:'navigation.footer',fallback:footerFallback},copyright:{path:'brand.copyright',fallback:'© Modern Luxe'}}});
const base=(key:string,type:StorefrontBuilderPageType,sections:StorefrontComponentNode[],metadata:Record<string,unknown>={}):StorefrontPageDocument=>({schemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,pageKey:key,pageType:type,templateKey:MODERN_LUXE_TEMPLATE_KEY,templateVersion:MODERN_LUXE_TEMPLATE_VERSION,metadata:{scaleOutTemplate:'Modern Luxe',visualDNA:MODERN_LUXE_VISUAL_DNA.character,spacingContract:MODERN_LUXE_SPACING_CONTRACT,...metadata},sections});
const productGrid=(id:string,title:string,path:string,columns=4):StorefrontComponentNode=>node({id,componentKey:'commerce.product-grid',componentVersion:1,config:{title,products:[],columns,presentation:'luxe',showBadges:true,showCompareAt:true,imageRatio:'4 / 5',emptyLabel:'Jelenleg nincs megjeleníthető termék.',currency:'HUF'},bindings:{title:{path:`content.${id}.title`,fallback:title},products:{path,fallback:[]}}});
const simple=(key:string,type:StorefrontBuilderPageType,title:string,copy:string)=>base(key,type,[header(key.replaceAll('.','-')),section(`${key.replaceAll('.','-')}-body`,[node({id:`${key}-title`,componentKey:'content.heading',componentVersion:1,config:{text:title,level:1,align:'left',tone:'text'},bindings:{text:{path:`content.${type}.title`,fallback:title}}}),node({id:`${key}-copy`,componentKey:'content.text',componentVersion:1,config:{text:copy,as:'p',align:'left',tone:'muted'},bindings:{text:{path:`content.${type}.copy`,fallback:copy}}})]),footer(key.replaceAll('.','-'))]);

export const MODERN_LUXE_HOME_PAGE=base('modern-luxe.home','home',[
 header('modern-luxe-home'),
 section('modern-luxe-hero',[node({id:'modern-luxe-layered-hero',componentKey:'visual.layered-canvas',componentVersion:1,config:{height:'hero',tone:'background',radius:'none'},children:[
  node({id:'modern-luxe-hero-image-layer',componentKey:'visual.layer',componentVersion:1,config:{position:'full',offsetX:'none',offsetY:'none',zIndex:0,width:'full',tone:'transparent',padding:'none',opacity:1,pointerEvents:'none'},children:[node({id:'modern-luxe-hero-image',componentKey:'content.image',componentVersion:1,config:{src:'/storefront-demo/modern-luxe/hero.svg',alt:'Modern Luxe ékszerközeli hero',width:1600,height:1000,fit:'cover',loading:'eager',radius:'none'},bindings:{src:{path:'content.modernLuxeHero.image',fallback:'/storefront-demo/modern-luxe/hero.svg'},alt:{path:'content.modernLuxeHero.imageAlt',fallback:'Modern Luxe ékszerközeli hero'}}})]}),
  node({id:'modern-luxe-hero-overlay-layer',componentKey:'visual.layer',componentVersion:1,config:{position:'full',offsetX:'none',offsetY:'none',zIndex:1,width:'full',tone:'scrim-soft',padding:'none',opacity:1,pointerEvents:'none'}}),
  node({id:'modern-luxe-hero-decoration-layer',componentKey:'visual.layer',componentVersion:1,config:{position:'top-right',offsetX:'l',offsetY:'l',zIndex:2,width:'narrow',tone:'transparent',padding:'none',opacity:.9,pointerEvents:'none'},children:[node({id:'modern-luxe-hero-decoration',componentKey:'content.image',componentVersion:1,config:{src:'/storefront-demo/modern-luxe/decor.svg',alt:'',width:240,height:240,fit:'contain',loading:'eager',radius:'none'},bindings:{src:{path:'content.modernLuxeHero.decoration',fallback:'/storefront-demo/modern-luxe/decor.svg'},alt:{path:'content.modernLuxeHero.decorationAlt',fallback:''}}})]}),
  node({id:'modern-luxe-hero-badge-layer',componentKey:'visual.layer',componentVersion:1,config:{position:'top-left',offsetX:'l',offsetY:'l',zIndex:3,width:'auto',tone:'surface',padding:'s',opacity:.96,pointerEvents:'auto'},children:[node({id:'modern-luxe-hero-badge',componentKey:'content.text',componentVersion:1,config:{text:'MODERN LUXE',as:'strong',align:'left',tone:'text'},bindings:{text:{path:'content.modernLuxeHero.badge',fallback:'MODERN LUXE'}}})]}),
  node({id:'modern-luxe-hero-title-layer',componentKey:'visual.layer',componentVersion:1,config:{position:'bottom-left',offsetX:'l',offsetY:'xxl',zIndex:3,width:'wide',tone:'transparent',padding:'none',opacity:1,pointerEvents:'auto'},children:[node({id:'modern-luxe-hero-title',componentKey:'content.heading',componentVersion:1,config:{text:'Quietly iconic.',level:1,align:'left',tone:'text'},bindings:{text:{path:'content.modernLuxeHero.title',fallback:'Quietly iconic.'}}})]}),
  node({id:'modern-luxe-hero-subtitle-layer',componentKey:'visual.layer',componentVersion:1,config:{position:'bottom-left',offsetX:'l',offsetY:'xl',zIndex:3,width:'medium',tone:'transparent',padding:'none',opacity:1,pointerEvents:'auto'},children:[node({id:'modern-luxe-hero-subtitle',componentKey:'content.text',componentVersion:1,config:{text:'Ékszerek, órák és kiegészítők modern, visszafogott luxusban.',as:'p',align:'left',tone:'text'},bindings:{text:{path:'content.modernLuxeHero.subtitle',fallback:'Ékszerek, órák és kiegészítők modern, visszafogott luxusban.'}}})]}),
  node({id:'modern-luxe-hero-cta-layer',componentKey:'visual.layer',componentVersion:1,config:{position:'bottom-left',offsetX:'l',offsetY:'m',zIndex:3,width:'auto',tone:'transparent',padding:'none',opacity:1,pointerEvents:'auto'},children:[node({id:'modern-luxe-hero-cta',componentKey:'content.button',componentVersion:1,config:{label:'Kollekció megnyitása',href:'/webaruhaz',variant:'primary',size:'l',ariaLabel:'Kollekció megnyitása'},bindings:{label:{path:'content.modernLuxeHero.ctaLabel',fallback:'Kollekció megnyitása'},href:{path:'content.modernLuxeHero.ctaHref',fallback:'/webaruhaz'}}})]})
 ]})]),
 section('modern-luxe-categories',[node({id:'modern-luxe-category-nav',componentKey:'commerce.collection-navigation',componentVersion:1,config:{title:'Kategóriák',items:[{label:'Ékszerek',href:'/webaruhaz'},{label:'Órák',href:'/webaruhaz'},{label:'Táskák',href:'/webaruhaz'},{label:'Napszemüvegek',href:'/webaruhaz'},{label:'Kiegészítők',href:'/webaruhaz'}],columns:5,imageRatio:'4 / 5',tone:'background'},bindings:{title:{path:'content.modernLuxeCategories.title',fallback:'Kategóriák'},items:{path:'collection.navigation',fallback:[{label:'Ékszerek',href:'/webaruhaz'},{label:'Órák',href:'/webaruhaz'},{label:'Táskák',href:'/webaruhaz'},{label:'Napszemüvegek',href:'/webaruhaz'},{label:'Kiegészítők',href:'/webaruhaz'}]}}})]),
 section('modern-luxe-signature',[productGrid('modernLuxeSignature','Signature Selection','catalog.featured',4)]),
 section('modern-luxe-gift',[node({id:'modern-luxe-gift-feature',componentKey:'editorial.split-feature',componentVersion:1,config:{eyebrow:'Gift Edit',title:'Ajándéknak választva',copy:'Visszafogottan elegáns válogatás olyan alkalmakra, amikor számít a részlet.',image:'/storefront-demo/modern-luxe/gift.svg',imageAlt:'Modern Luxe ajándék válogatás',ctaLabel:'Ajándékötletek',ctaHref:'/webaruhaz',imagePosition:'right',tone:'surface'},bindings:{eyebrow:{path:'content.modernLuxeGift.eyebrow',fallback:'Gift Edit'},title:{path:'content.modernLuxeGift.title',fallback:'Ajándéknak választva'},copy:{path:'content.modernLuxeGift.copy',fallback:'Visszafogottan elegáns válogatás olyan alkalmakra, amikor számít a részlet.'},image:{path:'content.modernLuxeGift.image',fallback:'/storefront-demo/modern-luxe/gift.svg'},imageAlt:{path:'content.modernLuxeGift.imageAlt',fallback:'Modern Luxe ajándék válogatás'},ctaLabel:{path:'content.modernLuxeGift.ctaLabel',fallback:'Ajándékötletek'},ctaHref:{path:'content.modernLuxeGift.ctaHref',fallback:'/webaruhaz'}}})],'surface'),
 section('modern-luxe-story',[node({id:'modern-luxe-brand-story',componentKey:'editorial.split-feature',componentVersion:1,config:{eyebrow:'Our Story',title:'Modern tárgyak, időtálló részletek.',copy:'A márkatörténet levegős editorial blokkban kap helyet, külön a termékértékesítési ritmustól.',image:'/storefront-demo/modern-luxe/story.svg',imageAlt:'Modern Luxe márkatörténet',ctaLabel:'Történetünk',ctaHref:'/rolunk',imagePosition:'left',tone:'background'},bindings:{eyebrow:{path:'content.modernLuxeStory.eyebrow',fallback:'Our Story'},title:{path:'content.modernLuxeStory.title',fallback:'Modern tárgyak, időtálló részletek.'},copy:{path:'content.modernLuxeStory.copy',fallback:'A márkatörténet levegős editorial blokkban kap helyet, külön a termékértékesítési ritmustól.'},image:{path:'content.modernLuxeStory.image',fallback:'/storefront-demo/modern-luxe/story.svg'},imageAlt:{path:'content.modernLuxeStory.imageAlt',fallback:'Modern Luxe márkatörténet'},ctaLabel:{path:'content.modernLuxeStory.ctaLabel',fallback:'Történetünk'},ctaHref:{path:'content.modernLuxeStory.ctaHref',fallback:'/rolunk'}}})]),
 footer('modern-luxe-home')
],{sectionOrder:MODERN_LUXE_HOME_SECTION_ORDER,visualPreset:'airy-modern-luxe-home',heroNavigation:'none',layerContract:MODERN_LUXE_ENGINE_CONTRACT.marketingLayerRule});

export const MODERN_LUXE_CATALOG_PAGE=base('modern-luxe.catalog','catalog',[header('modern-luxe-catalog'),section('modern-luxe-catalog-head',[node({id:'modern-luxe-catalog-collection-header',componentKey:'commerce.collection-header',componentVersion:1,config:{eyebrow:'Collection',title:'Kollekció',description:'Levegős, elegáns katalógus a termékekre fókuszálva.',image:'',imageAlt:'',align:'left'},bindings:{title:{path:'collection.current.title',fallback:'Kollekció'},description:{path:'collection.current.description',fallback:'Levegős, elegáns katalógus a termékekre fókuszálva.'}}})]),section('modern-luxe-catalog-products',[productGrid('modernLuxeCatalog','Termékek','catalog.products',4)]),footer('modern-luxe-catalog')],{visualPreset:'airy-luxe-catalog',engineBinding:'E2'});
export const MODERN_LUXE_PRODUCT_PAGE=base('modern-luxe.product','product',[header('modern-luxe-product'),section('modern-luxe-product-main',[node({id:'modern-luxe-product-layout',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'start'},children:[node({id:'modern-luxe-product-gallery',componentKey:'commerce.product-gallery',componentVersion:1,config:{images:[],aspectRatio:'4 / 5',thumbnailPosition:'bottom'},bindings:{images:{path:'product.gallery',fallback:[]}},responsive:{desktop:{gridSpan:7},tablet:{gridSpan:7},mobile:{gridSpan:12}}}),node({id:'modern-luxe-product-buybox',componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap:'m',align:'stretch',justify:'start'},responsive:{desktop:{gridSpan:5},tablet:{gridSpan:5},mobile:{gridSpan:12}},children:[node({id:'modern-luxe-product-info',componentKey:'commerce.product-info',componentVersion:1,config:{eyebrow:'Modern Luxe',title:'Termék',price:'',compareAtPrice:'',description:'',stockLabel:'',badges:[],currency:'HUF'},bindings:{title:{path:'product.name',fallback:'Termék'},price:{path:'pricing.displayPrice',fallback:''},compareAtPrice:{path:'pricing.compareAtPrice',fallback:''},description:{path:'product.description',fallback:''},stockLabel:{path:'inventory.stockLabel',fallback:''},badges:{path:'product.badges',fallback:[]}}}),node({id:'modern-luxe-product-options',componentKey:'commerce.option-selector',componentVersion:1,config:{label:'Opció',options:[]},bindings:{label:{path:'variant.optionLabel',fallback:'Opció'},options:{path:'variant.optionOptions',fallback:[]}}}),node({id:'modern-luxe-product-cta',componentKey:'content.button',componentVersion:1,config:{label:'Kosárba teszem',href:'#purchase',variant:'primary',size:'l',ariaLabel:'Kosárba teszem'},bindings:{label:{path:'commerce.purchaseLabel',fallback:'Kosárba teszem'},href:{path:'commerce.purchaseHref',fallback:'#purchase'}}})]})]})]),section('modern-luxe-product-recs',[node({id:'modern-luxe-recommendations',componentKey:'commerce.recommendation-row',componentVersion:1,config:{title:'Hozzá illő darabok',products:[],columns:4,emptyLabel:'Nincs kapcsolódó ajánlat.',currency:'HUF'},bindings:{products:{path:'recommendations.products',fallback:[]}}})]),footer('modern-luxe-product')],{visualPreset:'ordered-luxe-product'});
export const MODERN_LUXE_SEARCH_PAGE=base('modern-luxe.search','search',[header('modern-luxe-search'),section('modern-luxe-search-results',[productGrid('modernLuxeSearch','Találatok','search.results',4)]),footer('modern-luxe-search')],{engineBinding:'E2'});
export const MODERN_LUXE_CART_PAGE=base('modern-luxe.cart','cart',[header('modern-luxe-cart'),section('modern-luxe-cart-body',[node({id:'modern-luxe-cart-summary',componentKey:'commerce.cart-summary',componentVersion:1,config:{lines:[],subtotal:'',total:'',currency:'HUF',checkoutHref:'/penztar',checkoutLabel:'Tovább a pénztárhoz',emptyLabel:'A kosarad üres.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},total:{path:'cart.total',fallback:''}}})]),footer('modern-luxe-cart')],{visualPreset:'restrained-luxe-cart'});
export const MODERN_LUXE_CHECKOUT_PAGE=base('modern-luxe.checkout','checkout',[header('modern-luxe-checkout'),section('modern-luxe-checkout-body',[node({id:'modern-luxe-checkout-heading',componentKey:'content.heading',componentVersion:1,config:{text:'Pénztár',level:1,align:'left',tone:'text'}}),node({id:'modern-luxe-checkout-summary',componentKey:'commerce.checkout-summary',componentVersion:1,config:{lines:[],subtotal:'',shipping:'',total:'',currency:'HUF',secureLabel:'Biztonságos, provider-neutral checkout.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},shipping:{path:'cart.shipping',fallback:''},total:{path:'cart.total',fallback:''}}})]),footer('modern-luxe-checkout')],{visualPreset:'restrained-luxe-checkout',engineBinding:'E13'});
export const MODERN_LUXE_ACCOUNT_PAGE=simple('modern-luxe.account','account','Fiókom','Rendelések, kedvencek és vásárlói adatok.');
export const MODERN_LUXE_CONTENT_PAGE=base('modern-luxe.content','content',[header('modern-luxe-content'),section('modern-luxe-content-story',[node({id:'modern-luxe-content-feature',componentKey:'editorial.split-feature',componentVersion:1,config:{eyebrow:'Story',title:'Modern Luxe',copy:'Márkatörténet és editorial tartalom levegős elrendezésben.',image:'/storefront-demo/modern-luxe/story.svg',imageAlt:'Modern Luxe story',ctaLabel:'Kollekció',ctaHref:'/webaruhaz',imagePosition:'left',tone:'background'},bindings:{title:{path:'content.story.title',fallback:'Modern Luxe'},copy:{path:'content.story.copy',fallback:'Márkatörténet és editorial tartalom levegős elrendezésben.'},image:{path:'content.story.image',fallback:'/storefront-demo/modern-luxe/story.svg'}}})]),footer('modern-luxe-content')],{contentRole:'brand-story'});
export const MODERN_LUXE_BLOG_INDEX_PAGE=simple('modern-luxe.blog-index','blog-index','Journal','Editorial történetek, ajándékötletek és stílusjegyzetek.');
export const MODERN_LUXE_BLOG_ARTICLE_PAGE=simple('modern-luxe.blog-article','blog-article','Journal','Visszafogott editorial tartalom.');
export const MODERN_LUXE_FAQ_PAGE=simple('modern-luxe.faq','faq','Gyakori kérdések','Rendelés, méretezés, szállítás és visszaküldés.');
export const MODERN_LUXE_CONTACT_PAGE=simple('modern-luxe.contact','contact','Kapcsolat','Kereskedői kapcsolat és ügyfélszolgálat.');
export const MODERN_LUXE_LEGAL_PAGE=simple('modern-luxe.legal','legal','Jogi információk','A kereskedő jogi és adatkezelési tartalmának helye.');
export const MODERN_LUXE_NOT_FOUND_PAGE=simple('modern-luxe.not-found','not-found','404','A keresett oldal nem található.');

export const MODERN_LUXE_TEMPLATE_MANIFEST=defineStorefrontTemplateManifest({foundationVersion:STOREFRONT_BUILDER_FOUNDATION_VERSION,manifestVersion:STOREFRONT_TEMPLATE_MANIFEST_VERSION,templateKey:MODERN_LUXE_TEMPLATE_KEY,templateVersion:MODERN_LUXE_TEMPLATE_VERSION,pageSchemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,minPlan:'alap',requiredFeatures:['catalog','inventory','orders','contentMarketing','productRecommendations','reviews','searchFiltering','commerceIntegrations'],pageTypes:['home','catalog','product','search','cart','checkout','account','content','blog-index','blog-article','faq','contact','legal','not-found'],responsive:{desktop:true,tablet:true,mobile:true},migration:STOREFRONT_TEMPLATE_MIGRATION_POLICY,demoContent:{namespace:'jewelry-modern-luxe',policy:STOREFRONT_DEMO_CONTENT_POLICY}});
export const MODERN_LUXE_TEMPLATE_PACKAGE:StorefrontInstallableTemplatePackage={manifest:MODERN_LUXE_TEMPLATE_MANIFEST,pages:[MODERN_LUXE_HOME_PAGE,MODERN_LUXE_CATALOG_PAGE,MODERN_LUXE_PRODUCT_PAGE,MODERN_LUXE_SEARCH_PAGE,MODERN_LUXE_CART_PAGE,MODERN_LUXE_CHECKOUT_PAGE,MODERN_LUXE_ACCOUNT_PAGE,MODERN_LUXE_CONTENT_PAGE,MODERN_LUXE_BLOG_INDEX_PAGE,MODERN_LUXE_BLOG_ARTICLE_PAGE,MODERN_LUXE_FAQ_PAGE,MODERN_LUXE_CONTACT_PAGE,MODERN_LUXE_LEGAL_PAGE,MODERN_LUXE_NOT_FOUND_PAGE],demoFixtures:[{entityType:'collection',entityKey:'jewelry',payload:{title:'Ékszerek',handle:'jewelry',demo:true}},{entityType:'collection',entityKey:'watches',payload:{title:'Órák',handle:'watches',demo:true}},{entityType:'product',entityKey:'champagne-ring',payload:{name:'Champagne Ring',slug:'champagne-ring',demo:true}},{entityType:'content',entityKey:'brand-story',payload:{title:'Modern tárgyak, időtálló részletek',kind:'brand-story',demo:true}}]};
