import type {StorefrontComponentNode,StorefrontPageDocument} from '@/lib/builder/storefront-runtime';
import type {StorefrontInstallableTemplatePackage} from '@/lib/builder/storefront-template-installation';
import {PLAYROOM_V18_TEMPLATE_PACKAGE} from '@/lib/builder/templates/playroom-v18';

export const PLAYROOM_V19_CANONICAL_TEMPLATE_VERSION=19 as const;
type GridSpan=1|2|3|4|5|6|7|8|9|10|11|12;
type JsonRecord=Record<string,unknown>;
const node=(value:StorefrontComponentNode)=>value;
const clone=<T>(value:T):T=>structuredClone(value);
const rec=(value:unknown):JsonRecord=>value&&typeof value==='object'&&!Array.isArray(value)?value as JsonRecord:{};
const responsive=(desktop:GridSpan,tablet:GridSpan=desktop,mobile:GridSpan=12):StorefrontComponentNode['responsive']=>({desktop:{gridSpan:desktop},tablet:{gridSpan:tablet},mobile:{gridSpan:mobile}});
const PAGE_BG={background:'radial-gradient(circle at 86% 8%,rgba(51,213,255,.10),transparent 25%),radial-gradient(circle at 12% 30%,rgba(255,75,190,.06),transparent 20%),#020b17'};
const SURFACE={background:'linear-gradient(155deg,#0b2947,#06172b)',border:'1px solid rgba(78,216,255,.25)',borderRadius:'.68rem',boxShadow:'0 16px 40px rgba(0,0,0,.24)'};
const PHOTO={
  setup:'https://images.pexels.com/photos/33888375/pexels-photo-33888375.jpeg?auto=compress&cs=tinysrgb&w=1600',
  controller:'https://images.pexels.com/photos/7987293/pexels-photo-7987293.jpeg?auto=compress&cs=tinysrgb&w=1500',
  editorial:'https://images.pexels.com/photos/9071471/pexels-photo-9071471.jpeg?auto=compress&cs=tinysrgb&w=1600',
  community:'https://images.pexels.com/photos/7862405/pexels-photo-7862405.jpeg?auto=compress&cs=tinysrgb&w=1600',
  audio:'https://images.pexels.com/photos/7858756/pexels-photo-7858756.jpeg?auto=compress&cs=tinysrgb&w=1400',
  gift:'https://images.pexels.com/photos/6045528/pexels-photo-6045528.jpeg?auto=compress&cs=tinysrgb&w=1400',
} as const;

const section=(id:string,children:StorefrontComponentNode[],style:JsonRecord=PAGE_BG,spacing='l')=>node({id,componentKey:'layout.section',componentVersion:1,config:{tone:'background',spacing,width:'full',style},children:[node({id:`${id}-container`,componentKey:'layout.container',componentVersion:1,config:{width:'content',spacing:'m'},children})]});
const grid=(id:string,children:StorefrontComponentNode[])=>node({id,componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'m',align:'stretch'},children});
const stack=(id:string,children:StorefrontComponentNode[],span:GridSpan=12,style:JsonRecord={})=>node({id,componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap:'m',align:'stretch',justify:'start',style},responsive:responsive(span,span===12?12:Math.min(12,span+1) as GridSpan,12),children});
const eyebrow=(id:string,text:string,color='#55e7ff')=>node({id,componentKey:'content.text',componentVersion:1,config:{text,as:'strong',align:'left',tone:'text',style:{fontSize:'.66rem',fontWeight:900,letterSpacing:'.15em',textTransform:'uppercase',color}}});
const heading=(id:string,text:string,level=2,binding?:string)=>node({id,componentKey:'content.heading',componentVersion:1,config:{text,level,align:'left',tone:'text',typography:{fontToken:'heading',fontWeight:900,lineHeight:level===1?.92:1.03,letterSpacingEm:level===1?-.045:-.025},style:{fontSize:level===1?'clamp(2.4rem,5vw,4.7rem)':undefined}},...(binding?{bindings:{text:{path:binding,fallback:text}}}:{})});
const copy=(id:string,text:string,binding?:string)=>node({id,componentKey:'content.text',componentVersion:1,config:{text,as:'p',align:'left',tone:'text',typography:{fontToken:'body',lineHeight:1.6},style:{color:'#b9cadc'}},...(binding?{bindings:{text:{path:binding,fallback:text}}}:{})});
const button=(id:string,label:string,href:string,variant:'primary'|'secondary'='primary')=>node({id,componentKey:'content.button',componentVersion:1,config:{label,href,variant,size:'m',ariaLabel:label,style:{borderRadius:'.4rem',fontWeight:900}}});
const image=(id:string,src:string,alt:string,span:GridSpan=12,bindingSrc?:string,bindingAlt?:string)=>node({id,componentKey:'content.image',componentVersion:1,config:{src,alt,width:1400,height:900,fit:'cover',loading:'lazy',radius:'none',objectPosition:'center center',artDirection:{desktop:{src,objectFit:'cover',objectPosition:'center center'},tablet:{src,objectFit:'cover',objectPosition:'center center'},mobile:{src,objectFit:'cover',objectPosition:'center center'}},style:{minHeight:'15rem',borderRadius:'.64rem',filter:'saturate(1.12) contrast(1.06) brightness(.82)'}},responsive:responsive(span,span,12),...((bindingSrc||bindingAlt)?{bindings:{...(bindingSrc?{src:{path:bindingSrc,fallback:src}}:{}),...(bindingAlt?{alt:{path:bindingAlt,fallback:alt}}:{})}}:{})});
const card=(id:string,kicker:string,title:string,text:string,span:GridSpan=4,accent='#55e7ff')=>stack(id,[eyebrow(`${id}-kicker`,kicker,accent),heading(`${id}-title`,title,3),copy(`${id}-copy`,text)],span,{...SURFACE,padding:'.95rem',minHeight:'8rem'});

const acceptedHome=PLAYROOM_V18_TEMPLATE_PACKAGE.pages.find(page=>page.pageType==='home');
if(!acceptedHome)throw new Error('PLAYROOM_V19_HOME_MISSING');
const homeHeader=acceptedHome.sections.find(item=>item.id==='playroom-home-header');
const homeFooter=acceptedHome.sections.find(item=>item.id==='playroom-home-footer');
if(!homeHeader||!homeFooter)throw new Error('PLAYROOM_V19_SHELL_MISSING');
const rekey=(source:StorefrontComponentNode,prefix:string):StorefrontComponentNode=>({...clone(source),id:source.id.replace(/^playroom-home/,prefix),...(source.children?{children:source.children.map(child=>rekey(child,prefix))}:{})});
const header=(prefix:string)=>rekey(homeHeader,prefix);
const footer=(prefix:string)=>rekey(homeFooter,prefix);

const sourcePage=(pageType:StorefrontPageDocument['pageType'])=>{
  const result=PLAYROOM_V18_TEMPLATE_PACKAGE.pages.find(page=>page.pageType===pageType);
  if(!result)throw new Error(`PLAYROOM_V19_SOURCE_PAGE_MISSING:${pageType}`);
  return result;
};
const find=(source:StorefrontPageDocument,id:string):StorefrontComponentNode|undefined=>{
  const walk=(items:readonly StorefrontComponentNode[]):StorefrontComponentNode|undefined=>{for(const item of items){if(item.id===id)return clone(item);const nested=walk(item.children??[]);if(nested)return nested;}return undefined;};
  return walk(source.sections);
};
const must=(source:StorefrontPageDocument,id:string)=>{const result=find(source,id);if(!result)throw new Error(`PLAYROOM_V19_NODE_MISSING:${id}`);return result;};
const styled=(source:StorefrontComponentNode,style:JsonRecord):StorefrontComponentNode=>({...source,config:{...source.config,style:{...rec(source.config.style),...style}}});
const page=(source:StorefrontPageDocument,sections:StorefrontComponentNode[],metadata:JsonRecord={}):StorefrontPageDocument=>({...source,templateVersion:19,metadata:{...(source.metadata??{}),canonicalUpgradeFromTemplateVersion:18,referenceFidelityRelease:'playroom-v19-full-page-family',pageFamilyVisualLanguage:'accepted-playroom-v18-home',sectionPresetSource:'canonical-top-level-page-sections',...metadata},sections});

const platformItems=[
  {id:'pc',label:'PC',href:'/webaruhaz?platform=pc',image:'/playroom/platforms/pc.svg',imageAlt:'PC platform ikon'},
  {id:'playstation',label:'PlayStation',href:'/webaruhaz?platform=playstation',image:'/playroom/platforms/playstation.svg',imageAlt:'PlayStation platform ikon'},
  {id:'xbox',label:'Xbox',href:'/webaruhaz?platform=xbox',image:'/playroom/platforms/xbox.svg',imageAlt:'Xbox platform ikon'},
  {id:'nintendo',label:'Nintendo',href:'/webaruhaz?platform=nintendo',image:'/playroom/platforms/nintendo.svg',imageAlt:'Nintendo platform ikon'},
  {id:'handheld',label:'Kézikonzol',href:'/webaruhaz?platform=handheld',image:'/playroom/platforms/handheld.svg',imageAlt:'Kézikonzol platform ikon'},
  {id:'mobile',label:'Mobil',href:'/webaruhaz?platform=mobile',image:'/playroom/platforms/mobile.svg',imageAlt:'Mobil platform ikon'},
];
const platformNav=(id:string)=>node({id,componentKey:'guided.attribute-navigation',componentVersion:1,config:{eyebrow:'PLATFORM',title:'Mivel játszol?',copy:'Ugorj a neked releváns kínálatra.',columns:3,presentation:'media-navigation',items:platformItems,styleSlots:{grid:{base:{display:'grid',gridTemplateColumns:'repeat(6,minmax(0,1fr))',gap:'.4rem'}},card:{base:{position:'relative',minHeight:'5rem',background:'linear-gradient(180deg,#0b2b49,#07182c)',border:'1px solid rgba(82,219,255,.32)',borderRadius:'.62rem',overflow:'hidden'}},mediaImage:{base:{width:'78%',height:'78%',margin:'8% 11% 14%',objectFit:'contain'}},label:{base:{fontSize:'.53rem',fontWeight:900}}}}});

const buildCatalog=()=>{const source=sourcePage('catalog');return page(source,[header('playroom-catalog'),section('playroom-catalog-hero',[grid('playroom-catalog-hero-grid',[stack('playroom-catalog-hero-copy',[eyebrow('playroom-catalog-kicker','FEDEZD FEL / JÁTSSZ / ÚJRA','#ff63bf'),heading('playroom-catalog-title','Találd meg a következő játékod.',1),copy('playroom-catalog-copy','Platform, játékstílus és valódi katalógusadatok szerint böngéssz.'),button('playroom-catalog-cta','Mutasd a kínálatot','#playroom-catalog-products')],5),image('playroom-catalog-hero-image',PHOTO.setup,'RGB gaming setup',7)])]),section('playroom-catalog-platform-presets',[platformNav('playroom-catalog-platform-navigation')]),styled({...must(source,'playroom-catalog-body'),id:'playroom-catalog-products'},PAGE_BG),section('playroom-catalog-discovery-presets',[grid('playroom-catalog-discovery-grid',[card('playroom-catalog-discovery-coop','JÁTSSZATOK EGYÜTT','Co-op és multiplayer','Közös játékra válogatott belépési pontok.',4,'#ff6fbd'),card('playroom-catalog-discovery-setup','FELSZERELÉS','Kiegészítők és setup','Kontrollerek, audio és gaming környezet.',4),card('playroom-catalog-discovery-gift','AJÁNDÉK MÓD','Ajándékötletek','Ajándékirányok valós commerce adatokkal.',4,'#b8e34a')])]),footer('playroom-catalog')],{visualPreset:'playroom-v19-catalog',engineBinding:'E2+E7'});};

const buildProduct=()=>{const source=sourcePage('product');return page(source,[header('playroom-product'),styled(must(source,'playroom-product-main'),PAGE_BG),section('playroom-product-confidence',[grid('playroom-product-confidence-grid',[card('playroom-product-confidence-platform','PLATFORM','Kompatibilitás','A kompatibilitást ellenőrzött termékadatok határozzák meg.',4),card('playroom-product-confidence-stock','ELÉRHETŐSÉG','Valós készlet','A készletet a valós kereskedelmi adatok adják.',4,'#b8e34a'),card('playroom-product-confidence-checkout','PÉNZTÁR','Biztonságos rendelés','A pénztár szerveroldalon ellenőrzi a rendelést.',4,'#ff6fbd')])]),styled(must(source,'playroom-product-facts'),PAGE_BG),section('playroom-product-story-preset',[grid('playroom-product-story-grid',[image('playroom-product-story-image',PHOTO.controller,'Gaming kontroller',6),stack('playroom-product-story-copy',[eyebrow('playroom-product-story-kicker','JÁTÉKESTRE KÉSZ','#ff6fbd'),heading('playroom-product-story-title','A termékoldal is a játékélmény része.',2),copy('playroom-product-story-copy-text','Nagy média, világos vásárlási hierarchia és kompatibilitási segítség.'),button('playroom-product-story-cta','Kapcsolódó ajánlatok','#playroom-product-recommendations','secondary')],6,SURFACE)])]),styled(must(source,'playroom-product-recommendations'),PAGE_BG),footer('playroom-product')],{visualPreset:'playroom-v19-pdp',engineBinding:'E2+E6+E7+E13',pdpGrid:'desktop-tablet-7-5-mobile-12-12'});};

const buildSearch=()=>{const source=sourcePage('search');return page(source,[header('playroom-search'),section('playroom-search-hero',[grid('playroom-search-hero-grid',[stack('playroom-search-hero-copy',[eyebrow('playroom-search-kicker','KERESÉS A PLAYROOMBAN'),heading('playroom-search-title','Mit keresel ma?',1),copy('playroom-search-copy','Játék, platform vagy kiegészítő — a keresés a valós storefront kínálatból dolgozik.'),node({id:'playroom-search-primary',componentKey:'system.search',componentVersion:1,config:{action:'/kereses',queryParam:'q',placeholder:'Játék, platform, kontroller…',buttonLabel:'Keresés',ariaLabel:'Keresés a Playroomban',presentation:'commerce'}})],7),image('playroom-search-hero-image',PHOTO.setup,'Neon gaming setup',5)])]),styled(must(source,'playroom-search-body'),PAGE_BG),section('playroom-search-shortcuts',[platformNav('playroom-search-platform-navigation')]),footer('playroom-search')],{visualPreset:'playroom-v19-search',engineBinding:'E2'});};

const buildCart=()=>{const source=sourcePage('cart');return page(source,[header('playroom-cart'),section('playroom-cart-intro',[eyebrow('playroom-cart-kicker','IRÁNY A PÉNZTÁR'),heading('playroom-cart-title','Kosár',1),copy('playroom-cart-copy','Itt a termékek, mennyiségek és a továbbhaladás kapják a fő hangsúlyt.')]),styled(must(source,'playroom-cart-body'),PAGE_BG),section('playroom-cart-recommendation-preset',[node({id:'playroom-cart-recommendations',componentKey:'commerce.recommendation-row',componentVersion:1,config:{title:'Még valami a játékesthez?',products:[],columns:4,emptyLabel:'Jelenleg nincs kapcsolódó ajánlat.',currency:'HUF',presentation:'standard',showCta:true,ctaLabel:'Megnézem',imageRatio:'4 / 5'},bindings:{products:{path:'recommendations.products',fallback:[]}}})]),section('playroom-cart-trust-preset',[grid('playroom-cart-trust-grid',[card('playroom-cart-trust-stock','KÉSZLET','Valós elérhetőség','A kosár nem talál ki készletet.',4,'#b8e34a'),card('playroom-cart-trust-price','ÁR','Valós árak','Az ár az ellenőrzött kereskedelmi adatokból érkezik.',4),card('playroom-cart-trust-order','RENDELÉS','Végső ellenőrzés','A rendelést a pénztár végén a szerver ellenőrzi.',4,'#ff6fbd')])]),footer('playroom-cart')],{visualPreset:'playroom-v19-cart',engineBinding:'E13',pageRhythm:'restrained'});};

const buildCheckout=()=>{const source=sourcePage('checkout');return page(source,[header('playroom-checkout'),section('playroom-checkout-intro',[eyebrow('playroom-checkout-kicker','BIZTONSÁGOS PÉNZTÁR','#b8e34a'),heading('playroom-checkout-title','Már csak a rendelés van hátra.',1),copy('playroom-checkout-copy','Kosár → Szállítás → Fizetés → Összesítés.')]),section('playroom-checkout-progress-preset',[grid('playroom-checkout-progress-grid',[card('playroom-checkout-step-cart','01','Kosár','Termékek és mennyiségek.',3),card('playroom-checkout-step-shipping','02','Szállítás','Szállítási adatok.',3),card('playroom-checkout-step-payment','03','Fizetés','Szolgáltatófüggetlen fizetés.',3,'#ff6fbd'),card('playroom-checkout-step-summary','04','Összesítés','Végső ellenőrzés.',3,'#b8e34a')])]),styled(must(source,'playroom-checkout-body'),PAGE_BG),footer('playroom-checkout')],{visualPreset:'playroom-v19-checkout',engineBinding:'E13',checkoutPresentation:'accordion-dropdown',checkoutFlow:['cart','shipping','payment','summary'],pageRhythm:'restrained'});};

const buildAccount=()=>{const source=sourcePage('account');return page(source,[header('playroom-account'),section('playroom-account-hero',[grid('playroom-account-hero-grid',[stack('playroom-account-copy',[eyebrow('playroom-account-kicker','JÁTÉKOS PROFIL'),heading('playroom-account-title','A te Playroomod.',1),copy('playroom-account-copy-text','Rendelések, mentett elemek és fiókadatok.')],6),image('playroom-account-image',PHOTO.community,'Gaming közösség',6)])]),section('playroom-account-navigation-presets',[grid('playroom-account-navigation-grid',[card('playroom-account-orders','RENDELÉSEK','Rendeléseim','Korábbi és folyamatban lévő rendelések.',4),card('playroom-account-favorites','MENTETT','Kedvencek','Mentett játékok és kiegészítők.',4,'#ff6fbd'),card('playroom-account-profile','PROFIL','Fiókadatok','Személyes és kapcsolati adatok.',4,'#b8e34a')])]),footer('playroom-account')],{visualPreset:'playroom-v19-account',pageRhythm:'calm'});};

const buildContent=()=>{const source=sourcePage('content');return page(source,[header('playroom-content'),section('playroom-content-feature-preset',[grid('playroom-content-feature-grid',[image('playroom-content-feature-image',PHOTO.editorial,'Gaming útmutató',7,'content.page.image','content.page.imageAlt'),stack('playroom-content-feature-copy',[eyebrow('playroom-content-kicker','PLAYROOM ÚTMUTATÓ','#b8e34a'),heading('playroom-content-title','Játssz jobban, válassz könnyebben.',1,'content.page.title'),copy('playroom-content-lead','Szerkeszthető gaming útmutató.','content.page.summary'),button('playroom-content-cta','Játékok felfedezése','/webaruhaz')],5,SURFACE)])]),section('playroom-content-body-preset',[stack('playroom-content-body',[heading('playroom-content-body-title','Útmutató',2),copy('playroom-content-body-copy','A kereskedő saját szerkesztőségi tartalma.','content.page.body')],12,SURFACE)]),footer('playroom-content')],{visualPreset:'playroom-v19-content',engineBinding:'E10'});};

const BLOG_PREVIEW_ITEMS=[
  {id:'platform-guide',eyebrow:'PLATFORM',title:'Melyik platform illik hozzád?',excerpt:'Gyors útmutató a játékstílusodhoz és a közös játékhoz.',href:'/blog/platform-guide',image:PHOTO.setup,imageAlt:'Neon gaming setup platform útmutatóhoz'},
  {id:'coop-night',eyebrow:'JÁTSSZATOK EGYÜTT',title:'Így rakj össze jobb co-op estét',excerpt:'Játék, kontroller és tér — egyszerű ötletek a közös élményhez.',href:'/blog/coop-night',image:PHOTO.editorial,imageAlt:'Barátok közös gaming esten'},
  {id:'setup-tips',eyebrow:'FELSZERELÉS',title:'Audio és kontroller tippek',excerpt:'Apró setup-döntések, amelyek tényleg javítják a játékélményt.',href:'/blog/setup-tips',image:PHOTO.audio,imageAlt:'Gaming headset és setup'},
] as const;

const buildBlogIndex=()=>{const source=sourcePage('blog-index');return page(source,[header('playroom-blog-index'),section('playroom-blog-index-feature-preset',[grid('playroom-blog-index-feature-grid',[stack('playroom-blog-index-feature-copy',[eyebrow('playroom-blog-index-kicker','PLAYROOM MAGAZIN','#ff6fbd'),heading('playroom-blog-index-title','Tippek. Útmutatók. Játékesték.',1),copy('playroom-blog-index-copy','A történetek hierarchiája kerül előtérbe.')],5),image('playroom-blog-index-feature-image',PHOTO.editorial,'Gaming magazin',7)])]),section('playroom-blog-index-body',[node({id:'playroom-blog-index-preview',componentKey:'editorial.journal-preview',componentVersion:1,config:{title:'Friss útmutatók',items:BLOG_PREVIEW_ITEMS,columns:3,emptyLabel:'Hamarosan új útmutatók érkeznek.'},bindings:{items:{path:'content.guides.items',fallback:BLOG_PREVIEW_ITEMS}}})]),section('playroom-blog-index-topic-presets',[grid('playroom-blog-index-topics',[card('playroom-blog-topic-platform','PLATFORM','Platformútmutató','Segítség a választáshoz.',4),card('playroom-blog-topic-together','EGYÜTT','Co-op esték','Ötletek közös játékhoz.',4,'#ff6fbd'),card('playroom-blog-topic-setup','FELSZERELÉS','Felszerelési tippek','Kontroller, audio és tér.',4,'#b8e34a')])]),footer('playroom-blog-index')],{visualPreset:'playroom-v19-editorial-index',engineBinding:'E10'});};

const buildBlogArticle=()=>{const source=sourcePage('blog-article');return page(source,[header('playroom-blog-article'),section('playroom-blog-article-hero',[eyebrow('playroom-blog-article-kicker','PLAYROOM MAGAZIN','#ff6fbd'),heading('playroom-blog-article-title','Playroom útmutató',1,'content.article.title'),copy('playroom-blog-article-lead','Gaming útmutató és történet.','content.article.summary'),image('playroom-blog-article-image',PHOTO.editorial,'Gaming magazin cikk',12,'content.article.image','content.article.imageAlt')]),section('playroom-blog-article-body-preset',[grid('playroom-blog-article-body-grid',[stack('playroom-blog-article-body',[heading('playroom-blog-article-body-title','A történet',2),copy('playroom-blog-article-body-copy','A tényleges szerkesztőségi tartalom.','content.article.body')],8,SURFACE),stack('playroom-blog-article-aside',[eyebrow('playroom-blog-article-aside-kicker','KÖVETKEZŐ LÉPÉS','#b8e34a'),heading('playroom-blog-article-aside-title','Folytasd a felfedezést',3),button('playroom-blog-article-aside-cta','Irány a webshop','/webaruhaz','secondary')],4,SURFACE)])]),footer('playroom-blog-article')],{visualPreset:'playroom-v19-editorial-article',engineBinding:'E10'});};

const buildFaq=()=>{const source=sourcePage('faq');const faq=(id:string,q:string,a:string)=>stack(id,[heading(`${id}-question`,q,3),copy(`${id}-answer`,a)],12,SURFACE);return page(source,[header('playroom-faq'),section('playroom-faq-hero',[eyebrow('playroom-faq-kicker','SEGÍTSÉGKÖZPONT'),heading('playroom-faq-title','Gyors válaszok, játékos zaj nélkül.',1),copy('playroom-faq-copy','Hosszabb olvasásra és gyors információkeresésre optimalizálva.')]),section('playroom-faq-questions-preset',[stack('playroom-faq-list',[faq('playroom-faq-platform','Honnan tudom, hogy kompatibilis-e?','A kompatibilitást ellenőrzött termékadatok határozzák meg.'),faq('playroom-faq-stock','A sablon mutat készletet és árat?','Igen, kizárólag valós commerce adatokból.'),faq('playroom-faq-order','Mi történik a pénztárnál?','A végső ellenőrzést a közös pénztár végzi.')])]),section('playroom-faq-help-cta-preset',[grid('playroom-faq-help-grid',[stack('playroom-faq-help-copy',[eyebrow('playroom-faq-help-kicker','TOVÁBBRA IS KÉRDÉSED VAN?','#ff6fbd'),heading('playroom-faq-help-title','Segítünk tovább.',2),button('playroom-faq-help-cta','Kapcsolat','/kapcsolat','secondary')],7,SURFACE),image('playroom-faq-help-image',PHOTO.audio,'Gaming headset',5)])]),footer('playroom-faq')],{visualPreset:'playroom-v19-faq',pageRhythm:'calm'});};

const buildContact=()=>{const source=sourcePage('contact');return page(source,[header('playroom-contact'),section('playroom-contact-hero',[grid('playroom-contact-hero-grid',[stack('playroom-contact-copy',[eyebrow('playroom-contact-kicker','ÜGYFÉLSZOLGÁLAT'),heading('playroom-contact-title','Beszéljünk.',1),copy('playroom-contact-copy-text','Ügyfélszolgálati és kapcsolatfelvételi keret.')],6),image('playroom-contact-image',PHOTO.community,'Gaming közösség',6)])]),section('playroom-contact-options-preset',[grid('playroom-contact-options-grid',[card('playroom-contact-orders','RENDELÉSI SEGÍTSÉG','Rendeléssel kapcsolatban','Rendelési kérdések.',4,'#b8e34a'),card('playroom-contact-product','TERMÉKTÁMOGATÁS','Termék és kompatibilitás','Termékinformációs segítség.',4),card('playroom-contact-general','EGYÉB','Általános kérdés','Egyéb ügyfélszolgálati kapcsolat.',4,'#ff6fbd')])]),footer('playroom-contact')],{visualPreset:'playroom-v19-contact',pageRhythm:'calm'});};

const buildLegal=()=>{const source=sourcePage('legal');return page(source,[header('playroom-legal'),section('playroom-legal-intro',[eyebrow('playroom-legal-kicker','JOGI / ADATVÉDELMI'),heading('playroom-legal-title','Jogi információk',1,'content.page.title'),copy('playroom-legal-lead','A jogi oldalon az olvashatóság az első.','content.page.summary')]),section('playroom-legal-reading-preset',[stack('playroom-legal-reading',[heading('playroom-legal-reading-title','Tájékoztató',2),copy('playroom-legal-reading-body','A kereskedő saját jogi tartalma.','content.page.body')],12,{...SURFACE,padding:'1.5rem',maxWidth:'62rem',minHeight:'10rem'})]),footer('playroom-legal')],{visualPreset:'playroom-v19-legal',pageRhythm:'reading'});};

const buildNotFound=()=>{const source=sourcePage('not-found');return page(source,[header('playroom-not-found'),section('playroom-not-found-hero-preset',[grid('playroom-not-found-grid',[stack('playroom-not-found-copy',[eyebrow('playroom-not-found-kicker','404 / VÉGE A JÁTÉKNAK?','#ff6fbd'),heading('playroom-not-found-title','Ez a pálya nem létezik.',1),copy('playroom-not-found-copy-text','Menj vissza a Playroom fő útvonalaira.'),button('playroom-not-found-home','Vissza a főoldalra','/'),button('playroom-not-found-shop','Játékok felfedezése','/webaruhaz','secondary')],5),image('playroom-not-found-image',PHOTO.gift,'Neon Playroom vizuál',7)])]),footer('playroom-not-found')],{visualPreset:'playroom-v19-404'});};

const builders:Record<StorefrontPageDocument['pageType'],()=>StorefrontPageDocument>={
  home:()=>page(acceptedHome,clone(acceptedHome.sections),{homeAcceptedFromVersion:18,visualPreset:'accepted-playroom-v18-home'}),
  catalog:buildCatalog,product:buildProduct,search:buildSearch,cart:buildCart,checkout:buildCheckout,account:buildAccount,content:buildContent,'blog-index':buildBlogIndex,'blog-article':buildBlogArticle,faq:buildFaq,contact:buildContact,legal:buildLegal,'not-found':buildNotFound,
};

export const PLAYROOM_V19_CANONICAL_TEMPLATE_PACKAGE:StorefrontInstallableTemplatePackage={...PLAYROOM_V18_TEMPLATE_PACKAGE,manifest:{...PLAYROOM_V18_TEMPLATE_PACKAGE.manifest,templateVersion:19},pages:PLAYROOM_V18_TEMPLATE_PACKAGE.manifest.pageTypes.map(pageType=>builders[pageType]())};