import type {StorefrontComponentNode,StorefrontPageDocument} from '@/lib/builder/storefront-runtime';
import type {StorefrontInstallableTemplatePackage} from '@/lib/builder/storefront-template-installation';
import {PLAYROOM_TEMPLATE_PACKAGE} from '@/lib/builder/templates/playroom';

export const PLAYROOM_REFERENCE_V2_TEMPLATE_VERSION=2 as const;
type GridSpan=1|2|3|4|5|6|7|8|9|10|11|12;

const n=(value:StorefrontComponentNode):StorefrontComponentNode=>value;
const responsive=(desktop:GridSpan,tablet:GridSpan=12,mobile:GridSpan=12):StorefrontComponentNode['responsive']=>({desktop:{gridSpan:desktop},tablet:{gridSpan:tablet},mobile:{gridSpan:mobile}});
const stack=(id:string,children:StorefrontComponentNode[],desktop:GridSpan=12,style:Record<string,unknown>={},gap='xs')=>n({id,componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap,align:'stretch',justify:'start',style},responsive:responsive(desktop),children});
const grid=(id:string,children:StorefrontComponentNode[],style:Record<string,unknown>={})=>n({id,componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'xs',align:'stretch',style},children});
const section=(id:string,children:StorefrontComponentNode[],style:Record<string,unknown>={})=>n({id,componentKey:'layout.section',componentVersion:1,config:{tone:'background',spacing:'none',width:'full',style},children:[n({id:`${id}-container`,componentKey:'layout.container',componentVersion:1,config:{width:'full',spacing:'none'},children})]});
const text=(id:string,value:string,style:Record<string,unknown>={},as:'p'|'small'|'strong'='p')=>n({id,componentKey:'content.text',componentVersion:1,config:{text:value,as,align:'left',tone:'text',style}});
const heading=(id:string,value:string,level=2,style:Record<string,unknown>={},accentText?:string)=>n({id,componentKey:'content.heading',componentVersion:1,config:{text:value,level,align:'left',tone:'text',typography:{fontToken:'heading',fontWeight:900,lineHeight:.92,letterSpacingEm:-.045},style,...(accentText?{accentText,accentStyle:{color:'#35e9ff'}}:{})}});
const button=(id:string,label:string,href:string,style:Record<string,unknown>={})=>n({id,componentKey:'content.button',componentVersion:1,config:{label,href,variant:'primary',size:'m',ariaLabel:label,style}});
const image=(id:string,src:string,alt:string,style:Record<string,unknown>={})=>n({id,componentKey:'content.image',componentVersion:1,config:{src,alt,width:1200,height:720,fit:'cover',loading:id==='playroom-hero-art'?'eager':'lazy',radius:'none',style}});
const card=(id:string,title:string,copy:string,src:string,desktop:GridSpan=3)=>stack(id,[image(`${id}-image`,src,title,{height:'4.8rem',objectFit:'cover',borderRadius:'.35rem'}),text(`${id}-title`,title,{fontSize:'.64rem',fontWeight:850},'strong'),text(`${id}-copy`,copy,{fontSize:'.53rem',color:'#9fb6cc'})],desktop,{padding:'.34rem',background:'linear-gradient(180deg,#0d2b49,#07182d)',border:'1px solid rgba(70,205,255,.20)',borderRadius:'.43rem'});

const header=n({id:'playroom-home-header',componentKey:'system.commerce-header',componentVersion:1,config:{brandLabel:'SHOPORATION',brandHref:'/',logoUrl:'/storefront/playroom/brand-mark.svg',logoAlt:'Shoperation Playroom kontroller jel',tagline:'PLAYROOM',utilityItems:[{label:'Kedvenceim',href:'/kedvencek',symbol:'♡'},{label:'Fiókom',href:'/fiokom',symbol:'♙'},{label:'Kosár',href:'/kosar',symbol:'⌑'}],tone:'background',sticky:true,presentation:'commerce-two-tier',showUtilityLabels:true,categoryTriggerSymbol:'☰',categoryTriggerHref:'/webaruhaz',navTagline:'JÁTÉK. KÖZÖSSÉG. ÉLMÉNY.',style:{background:'rgba(2,12,27,.98)',borderBottom:'1px solid rgba(54,225,255,.24)',boxShadow:'0 10px 34px rgba(0,0,0,.32)'},innerStyle:{maxWidth:'none',padding:'.5rem 2.35rem .32rem',gap:'.4rem'},brandStyle:{fontSize:'1rem',fontWeight:950},taglineStyle:{color:'#32e8df',fontSize:'.62rem',letterSpacing:'.22em',fontWeight:900},logoStyle:{width:'2.6rem',height:'2.6rem'},styleSlots:{topRow:{base:{minHeight:'2.85rem'}},searchFrame:{base:{maxWidth:'38rem',justifySelf:'center',width:'100%'}},utilityItem:{base:{border:'0',background:'transparent',padding:'.25rem'}},navigationFrame:{base:{borderTop:'1px solid rgba(69,194,255,.16)',paddingTop:'.32rem',minHeight:'2rem'}},categoryTrigger:{base:{fontSize:'1rem'}},navTagline:{base:{color:'#9db2c9'}}}},children:[n({id:'playroom-home-search',componentKey:'system.search',componentVersion:1,config:{action:'/kereses',queryParam:'q',placeholder:'Keresés játékra, konzolra, kiegészítőre…',buttonLabel:'⌕',ariaLabel:'Keresés a webshopban',presentation:'commerce',style:{height:'2.35rem',background:'#f8fbff',border:'1px solid #5adfff',borderRadius:'.35rem'},inputStyle:{color:'#16304e',fontSize:'.76rem'},buttonStyle:{background:'#06152d',color:'#fff',fontSize:'1rem',padding:'.4rem .75rem'}}}),n({id:'playroom-home-nav',componentKey:'system.navigation',componentVersion:1,config:{ariaLabel:'Fő navigáció',layout:'horizontal',items:[{label:'Játékok',href:'/webaruhaz'},{label:'Konzolok',href:'/webaruhaz?category=console'},{label:'Kiegészítők',href:'/webaruhaz?category=accessory'},{label:'Játékos felszerelés',href:'/webaruhaz?collection=setup'},{label:'Rajongói termékek',href:'/webaruhaz?category=merch'},{label:'Ajándékötletek',href:'/webaruhaz?filter=gift'},{label:'Újdonságok',href:'/webaruhaz?sort=new'},{label:'Akciók',href:'/webaruhaz?filter=sale'},{label:'Playroom Magazin',href:'/blog'}],style:{gap:'1.8rem',fontSize:'.73rem',fontWeight:750,color:'#f2f6ff'}}})]});

const trust=grid('playroom-trust-grid',[stack('playroom-trust-shipping',[text('playroom-trust-shipping-title','▱  Szállítás',{fontSize:'.61rem',fontWeight:850},'strong'),text('playroom-trust-shipping-copy','Részletek a pénztárban',{fontSize:'.52rem',color:'#9eb3c9'})],3,{padding:'.32rem .42rem'}),stack('playroom-trust-warranty',[text('playroom-trust-warranty-title','◇  Garancia',{fontSize:'.61rem',fontWeight:850},'strong'),text('playroom-trust-warranty-copy','Termékadat szerint',{fontSize:'.52rem',color:'#9eb3c9'})],3,{padding:'.32rem .42rem'}),stack('playroom-trust-return',[text('playroom-trust-return-title','⬡  Elállás',{fontSize:'.61rem',fontWeight:850},'strong'),text('playroom-trust-return-copy','Jogi feltételek szerint',{fontSize:'.52rem',color:'#9eb3c9'})],3,{padding:'.32rem .42rem'}),stack('playroom-trust-community',[text('playroom-trust-community-title','♧  Gamer közösség',{fontSize:'.61rem',fontWeight:850},'strong'),text('playroom-trust-community-copy','Tippek, hírek, események',{fontSize:'.52rem',color:'#9eb3c9'})],3,{padding:'.32rem .42rem'})],{position:'absolute',left:'.55rem',right:'.55rem',bottom:'.42rem',zIndex:4,background:'rgba(2,12,28,.84)',backdropFilter:'blur(12px)',border:'1px solid rgba(89,216,255,.18)',borderRadius:'.5rem'});
const hero=stack('playroom-hero',[image('playroom-hero-art','/storefront/playroom/hero-room-v2.svg','Neon gamer szoba három játékossal és nagy képernyővel',{position:'absolute',inset:'0',width:'100%',height:'100%',minHeight:'100%',objectFit:'cover'}),stack('playroom-hero-copy',[heading('playroom-hero-title','MIT\nJÁTSZUNK\nMA?',1,{fontSize:'clamp(3rem,4.8vw,5rem)',maxWidth:'8ch',textTransform:'uppercase',filter:'drop-shadow(0 4px 16px rgba(0,0,0,.48))'},'JÁTSZUNK'),text('playroom-hero-support','Játékok. Konzolok. Kiegészítők. Közös élmények. Egy helyen.',{maxWidth:'34ch',fontSize:'.82rem',fontWeight:650}),button('playroom-hero-primary','Fedezd fel a lehetőségeket  →','/webaruhaz',{background:'linear-gradient(90deg,#ff4cae,#ff72b8)',color:'#071021',border:'0',borderRadius:'.36rem',fontWeight:900,padding:'.68rem .95rem'})],12,{position:'relative',zIndex:3,width:'48%',minHeight:'13.8rem',padding:'1.2rem 1.25rem',justifyContent:'center',background:'linear-gradient(90deg,rgba(2,10,24,.96),rgba(2,10,24,.68) 70%,rgba(2,10,24,0))'}),trust],8,{position:'relative',minHeight:'18rem',overflow:'hidden',background:'#071328',border:'1px solid rgba(51,205,255,.22)',borderRadius:'.62rem',boxShadow:'0 18px 52px rgba(0,0,0,.36)'},'none');

const playStyleOptions=[{id:'solo',label:'Egyedül',href:'/webaruhaz?play=solo',symbol:'●',selected:true},{id:'coop',label:'Kooperatív',href:'/webaruhaz?play=coop',symbol:'∞'},{id:'party',label:'Társasági',href:'/webaruhaz?play=party',symbol:'✦'},{id:'racing',label:'Verseny',href:'/webaruhaz?genre=racing',symbol:'◈'},{id:'adventure',label:'Kaland',href:'/webaruhaz?genre=adventure',symbol:'▲'},{id:'family',label:'Családi',href:'/webaruhaz?play=family',symbol:'♧'}];
const platformItems=[{id:'playsphere',label:'▰ PlaySphere',href:'/webaruhaz?platform=playsphere'},{id:'boxone',label:'◉ BoxOne',href:'/webaruhaz?platform=boxone'},{id:'nintari',label:'▣ Nintari',href:'/webaruhaz?platform=nintari'},{id:'pc',label:'▭ PC',href:'/webaruhaz?platform=pc'},{id:'handheld',label:'▱ Kézikonzol',href:'/webaruhaz?platform=handheld'},{id:'mobile',label:'▯ Mobil',href:'/webaruhaz?platform=mobile'}];
const selectors=stack('playroom-selectors',[stack('playroom-style-card',[heading('playroom-style-heading','Válaszd ki a játékstílusod',3,{fontSize:'.98rem'}),n({id:'playroom-game-finder',componentKey:'guided.finder',componentVersion:1,config:{eyebrow:'',title:'',copy:'',options:playStyleOptions,actionLabel:'',presentation:'editorial-choice-grid',columns:6,styleSlots:{root:{base:{gridTemplateColumns:'1fr',border:'0',background:'transparent'}},content:{base:{padding:'0',gap:'0'}},eyebrow:{base:{display:'none'}},title:{base:{display:'none'}},copy:{base:{display:'none'}},action:{base:{display:'none'}},aside:{base:{display:'none'}},options:{base:{gridTemplateColumns:'repeat(6,minmax(0,1fr))',gap:'.38rem'}},option:{base:{minHeight:'4.45rem',padding:'.42rem .15rem',borderRadius:'.42rem',background:'linear-gradient(180deg,#0b2742,#07192d)',border:'1px solid rgba(76,208,255,.25)'}},optionActive:{base:{background:'linear-gradient(180deg,#122b68,#123d83)',border:'1px solid #2c8cff'}},optionMedia:{base:{fontSize:'1.3rem',color:'#4feaff'}},optionLabel:{base:{fontSize:'.59rem',fontWeight:800}}}},bindings:{stepTitle:{path:'finder.currentStep.title',fallback:''},stepCopy:{path:'finder.currentStep.copy',fallback:''},question:{path:'finder.currentQuestion.label',fallback:''},options:{path:'finder.currentQuestion.options',fallback:playStyleOptions},progressLabel:{path:'finder.progressLabel',fallback:''},actionHref:{path:'finder.resultHref',fallback:'#playroom-featured-games'},resultStatus:{path:'finder.resultStatus',fallback:''}}})],12,{padding:'.6rem .65rem',background:'linear-gradient(180deg,#08233d,#06182c)',border:'1px solid rgba(50,199,255,.25)',borderRadius:'.55rem'}),stack('playroom-platform-card',[heading('playroom-platform-heading','Válaszd ki a platformod',3,{fontSize:'.98rem'}),n({id:'playroom-platform-navigation',componentKey:'guided.attribute-navigation',componentVersion:1,config:{eyebrow:'',title:'',copy:'',columns:5,presentation:'cards',items:platformItems,styleSlots:{root:{base:{gap:'0'}},eyebrow:{base:{display:'none'}},header:{base:{display:'none'}},grid:{base:{display:'grid',gridTemplateColumns:'repeat(6,minmax(0,1fr))',gap:'.38rem'}},card:{base:{display:'grid',placeItems:'center',minHeight:'4.3rem',padding:'.35rem .12rem',borderRadius:'.42rem',background:'linear-gradient(180deg,#0a2946,#06182d)',border:'1px solid rgba(76,208,255,.24)',fontSize:'.55rem',fontWeight:800,textAlign:'center',lineHeight:1.25}}}}})],12,{padding:'.6rem .65rem',background:'linear-gradient(180deg,#08233d,#06182c)',border:'1px solid rgba(50,199,255,.25)',borderRadius:'.55rem'})],4,{gap:'.45rem'});
const heroRow=section('playroom-hero-composition',[grid('playroom-hero-composition-grid',[hero,selectors])],{padding:'.48rem 1.05rem 0',background:'#020b17'});

const setup=stack('playroom-setup',[image('playroom-setup-image','/storefront/playroom/setup-neon.svg','Játékos felszerelés konzollal, kontrollerekkel és fejhallgatóval',{position:'absolute',right:'0',bottom:'0',width:'58%',height:'100%',minHeight:'100%',objectFit:'contain',objectPosition:'right bottom'}),stack('playroom-setup-copy',[heading('playroom-setup-title','GAMER FELSZERELÉSCSOMAG',2,{fontSize:'1.22rem',color:'#ff54cf'}),text('playroom-setup-lead','Minden, amire egy legendás estéd kell.',{fontSize:'.65rem'}),text('playroom-setup-benefits','✓ Új generációs konzol\n✓ Vezeték nélküli kontroller\n✓ Térhangzású fejhallgató\n✓ RGB töltőállomás\n✓ Exkluzív gamer szőnyeg',{whiteSpace:'pre-line',fontSize:'.61rem',lineHeight:1.48}),button('playroom-setup-cta','Teljes csomag megtekintése  →','/webaruhaz?collection=setup',{background:'#f8fbff',color:'#09152a',border:'0',borderRadius:'.3rem',fontSize:'.61rem',fontWeight:850,padding:'.48rem .65rem'})],12,{position:'relative',zIndex:2,width:'52%',padding:'.75rem .85rem'})],5,{position:'relative',minHeight:'12.2rem',overflow:'hidden',background:'radial-gradient(circle at 80% 55%,rgba(36,103,255,.32),transparent 42%),linear-gradient(135deg,#091c3c,#17134b)',border:'1px solid rgba(49,199,255,.28)',borderRadius:'.52rem'},'none');
const playerTwo=stack('playroom-player-two',[heading('playroom-player-two-title','JÖHET A 2. JÁTÉKOS?',2,{fontSize:'1.2rem',color:'#35eddf'}),text('playroom-player-two-text','Közös élmények, dupla móka.',{fontSize:'.62rem'}),grid('playroom-player-two-grid',[card('playroom-player-controller','Kontrollerek','Játsszatok együtt!','/storefront/playroom/controller-neon.svg'),card('playroom-player-headset','Játékos fejhallgatók','Tiszta kommunikáció','/storefront/playroom/audio-neon.svg'),card('playroom-player-family','Családi játékok','Minden korosztálynak','/storefront/playroom/player-two.svg'),card('playroom-player-couch','Kanapés kooperatív játék','Együtt a legjobb','/storefront/playroom/gift-neon.svg')])],4,{padding:'.68rem',minHeight:'12.2rem',background:'linear-gradient(155deg,#07263b,#071b31)',border:'1px solid rgba(52,228,218,.26)',borderRadius:'.52rem'});
const upgrade=stack('playroom-upgrade',[heading('playroom-upgrade-heading','DOBD FEL A JÁTÉKESTÉT',2,{fontSize:'1.08rem',color:'#ffa04d'}),text('playroom-upgrade-copy','Több, mint játék. Teljes élmény.',{fontSize:'.59rem'}),grid('playroom-upgrade-grid',[card('playroom-upgrade-monitor','Játékmonitor','Látványban az erő','/storefront/playroom/monitor-v2.svg'),card('playroom-upgrade-audio','Audio','Hang, ami átvisz','/storefront/playroom/audio-neon.svg'),card('playroom-upgrade-light','Világítás','Hangulat a szobádban','/storefront/playroom/lighting-v2.svg'),card('playroom-upgrade-chair','Játékszék','Kényelem hosszú távon','/storefront/playroom/chair-neon.svg')])],3,{padding:'.68rem',minHeight:'12.2rem',background:'linear-gradient(150deg,#101c39,#17112f)',border:'1px solid rgba(245,86,203,.24)',borderRadius:'.52rem'});
const merchRow=section('playroom-merchandising',[grid('playroom-merchandising-grid',[setup,playerTwo,upgrade])],{padding:'.45rem 1.05rem 0',background:'#020b17'});

const featured=stack('playroom-featured-games',[heading('playroom-featured-heading','Újdonságok & Kiemelt játékok',2,{fontSize:'1.02rem'}),text('playroom-featured-subtitle','A webshop tényleges kínálatából.',{fontSize:'.55rem',color:'#9fb5ca'}),n({id:'playroomFeaturedGames',componentKey:'commerce.product-grid',componentVersion:1,config:{title:'',products:[],columns:4,presentation:'standard',showBadges:true,showCompareAt:true,showCta:true,ctaLabel:'Megnézem',imageRatio:'16 / 10',emptyLabel:'Jelenleg nincs megjeleníthető termék.',currency:'HUF',styleSlots:{root:{base:{gap:'.4rem'}},grid:{base:{gap:'.36rem'}},card:{base:{background:'linear-gradient(180deg,#0b2945,#07182c)',border:'1px solid rgba(66,202,255,.2)',borderRadius:'.4rem',padding:'.32rem'}},media:{base:{borderRadius:'.28rem'}},badge:{base:{fontSize:'.5rem'}},cta:{base:{fontSize:'.53rem',padding:'.36rem .5rem'}}}},bindings:{title:{path:'content.playroomFeaturedGames.title',fallback:''},products:{path:'catalog.existingCommerceProducts',fallback:[]}}})],7,{padding:'.62rem .68rem',minHeight:'11.2rem',background:'linear-gradient(180deg,#061a2e,#041425)',border:'1px solid rgba(61,199,255,.24)',borderRadius:'.52rem'});
const compatibility=stack('playroom-compatibility-card',[heading('playroom-compatibility-title','Platform kompatibilitás',3,{fontSize:'.96rem'}),grid('playroom-compatibility-layout',[stack('playroom-compatibility-art-wrap',[image('playroom-compatibility-art','/storefront/playroom/compatibility-neon.svg','Kontroller kompatibilitási illusztráció',{height:'5.8rem',objectFit:'contain'})],5),stack('playroom-compatibility-status-wrap',[n({id:'playroom-platform-match-status',componentKey:'compatibility.status',componentVersion:1,config:{title:'Kompatibilitási állapot',status:'unknown',compatibleLabel:'Kompatibilis',incompatibleLabel:'Nem kompatibilis',unknownLabel:'Ismeretlen',copy:'Az ismeretlen kompatibilitás nem számít kompatibilisnek.'},bindings:{status:{path:'compatibility.status',fallback:'unknown'},copy:{path:'compatibility.summary',fallback:'Az ismeretlen kompatibilitás nem számít kompatibilisnek.'}}})],7)])],7,{padding:'.58rem',background:'linear-gradient(160deg,#0a2944,#071a31)',border:'1px solid rgba(66,199,255,.22)',borderRadius:'.48rem'});
const gift=stack('playroom-gift-card',[image('playroom-gift-image','/storefront/playroom/gift-neon.svg','Neon játékos ajándékdoboz',{height:'5.6rem',objectFit:'cover',borderRadius:'.36rem'}),heading('playroom-gift-title','AJÁNDÉKOT KERESEL?',3,{fontSize:'.93rem',color:'#a88aff'}),text('playroom-gift-copy','Játékos ajándékötletek minden korosztálynak.',{fontSize:'.55rem'}),button('playroom-gift-cta','Ajándékötletek  →','/webaruhaz?filter=gift',{background:'#f6f8ff',color:'#11162d',border:'0',fontSize:'.55rem',fontWeight:850,padding:'.4rem .5rem'})],5,{padding:'.55rem',background:'linear-gradient(145deg,#171047,#23104d)',border:'1px solid rgba(174,89,255,.35)',borderRadius:'.48rem'});
const platformGift=stack('playroom-platform-match',[grid('playroom-platform-gift-grid',[compatibility,gift])],5,{},'none');
const commerceRow=section('playroom-commerce',[grid('playroom-commerce-grid',[featured,platformGift])],{padding:'.45rem 1.05rem 0',background:'#020b17'});

const community=section('playroom-play-together',[stack('playroom-community-stage',[image('playroom-community-art','/storefront/playroom/community-neon.svg','Játékos közösségi háttér',{position:'absolute',inset:'0',width:'100%',height:'100%',minHeight:'100%',objectFit:'cover',opacity:.3}),grid('playroom-community-grid',[stack('playroom-community-copy',[heading('playroom-community-title','JÁTSSZATOK EGYÜTT',2,{fontSize:'1.35rem',color:'#d86cff'}),text('playroom-community-copy-text','Játék összehoz. Fedezd fel új világokat, ossz meg élményeket.',{fontSize:'.58rem'})],3,{position:'relative',zIndex:2}),stack('playroom-community-benefits',[text('playroom-community-benefit-text','⬡ Termékek   ◇ Információk   ▱ Szállítás   ⊕ Feltételek   ♧ Közösség',{fontSize:'.59rem',fontWeight:750,whiteSpace:'nowrap'})],6,{position:'relative',zIndex:2,justifyContent:'center'}),stack('playroom-community-cta',[button('playroom-community-button','Csatlakozz a közösséghez  →','/blog',{width:'100%',background:'linear-gradient(90deg,#1687ff,#21bcff)',border:'0',fontSize:'.59rem',fontWeight:850,padding:'.52rem .65rem'})],3,{position:'relative',zIndex:2,justifyContent:'center'})])],12,{position:'relative',minHeight:'3.8rem',overflow:'hidden',padding:'.42rem .65rem',background:'linear-gradient(90deg,#0c153c,#20115b)',border:'1px solid rgba(113,93,255,.34)',borderRadius:'.48rem'},'none')],{padding:'.45rem 1.05rem 0',background:'#020b17'});

const footerLink=(id:string,label:string,href:string)=>n({id,componentKey:'content.button',componentVersion:1,config:{label,href,variant:'ghost',size:'s',ariaLabel:label,style:{padding:'0',border:'0',borderRadius:'0',fontSize:'.66rem',fontWeight:600,color:'#aec0d3'}}});
const footer=section('playroom-home-footer',[grid('playroom-footer-grid',[stack('playroom-footer-brand',[image('playroom-footer-logo','/storefront/playroom/brand-mark.svg','Shoperation Playroom jel',{width:'2.5rem',height:'2.5rem',objectFit:'contain'}),heading('playroom-footer-brand-title','SHOPORATION',3,{fontSize:'.86rem'}),text('playroom-footer-brand-subtitle','PLAYROOM',{fontSize:'.55rem',letterSpacing:'.2em',color:'#35e7df'},'strong'),text('playroom-footer-brand-copy','Játék. Közösség. Élmény.',{fontSize:'.52rem',color:'#8fa4bb'})],2),stack('playroom-footer-shop',[text('playroom-footer-shop-title','Vásárlási információk',{fontSize:'.62rem',fontWeight:850},'strong'),footerLink('playroom-footer-shipping','Szállítás','/oldal/szallitas'),footerLink('playroom-footer-payment','Fizetés','/oldal/fizetes'),footerLink('playroom-footer-return','Visszaküldés','/oldal/visszakuldes'),footerLink('playroom-footer-faq','GYIK','/gyik')],2),stack('playroom-footer-world',[text('playroom-footer-world-title','Játékvilág',{fontSize:'.62rem',fontWeight:850},'strong'),footerLink('playroom-footer-new','Újdonságok','/webaruhaz?sort=new'),footerLink('playroom-footer-mag','Playroom Magazin','/blog'),footerLink('playroom-footer-guides','Játékajánlók','/blog'),footerLink('playroom-footer-events','Események','/blog')],2),stack('playroom-footer-about',[text('playroom-footer-about-title','Rólunk',{fontSize:'.62rem',fontWeight:850},'strong'),footerLink('playroom-footer-story','Történetünk','/oldal/rolunk'),footerLink('playroom-footer-sustain','Fenntarthatóság','/oldal/fenntarthatosag'),footerLink('playroom-footer-career','Karrier','/oldal/karrier'),footerLink('playroom-footer-contact','Kapcsolat','/kapcsolat')],2),stack('playroom-footer-social',[text('playroom-footer-social-title','Kövess minket',{fontSize:'.62rem',fontWeight:850},'strong'),text('playroom-footer-social-icons','▶  ◎  ♪  f  ◉',{fontSize:'.95rem',letterSpacing:'.12em'}),text('playroom-footer-social-copy','JÁTSSZ\nFEDEZD FEL\nOSZD MEG\nTARTOZZ KÖZÉNK',{whiteSpace:'pre-line',fontSize:'.55rem',letterSpacing:'.23em',lineHeight:1.45,color:'#d36cff'},'strong')],4,{borderLeft:'1px solid rgba(89,139,191,.25)',paddingLeft:'1.1rem'})])],{padding:'.9rem 2.35rem 1rem',background:'linear-gradient(180deg,#03101e,#020914)',borderTop:'1px solid rgba(50,196,255,.18)'});

const legacyHome=PLAYROOM_TEMPLATE_PACKAGE.pages.find(page=>page.pageType==='home');
if(!legacyHome)throw new Error('PLAYROOM_HOME_PAGE_MISSING');

export const PLAYROOM_REFERENCE_V2_HOME_PAGE:StorefrontPageDocument={...legacyHome,templateVersion:PLAYROOM_REFERENCE_V2_TEMPLATE_VERSION,metadata:{...(legacyHome.metadata??{}),canonicalUpgradeFromTemplateVersion:1,visualAuthority:'Neon Gamer Webáruház Kezdőlap',referenceFidelityRelease:'playroom-v2',visualPreset:'neon-gamer-commerce-reference-v2',fidelityRecovery:true,desktopComposition:'header / 8+4 hero-selectors / 5+4+3 merchandising / 7+5 commerce / community / footer'},sections:[header,heroRow,merchRow,commerceRow,community,footer]};
export const PLAYROOM_REFERENCE_V2_TEMPLATE_PACKAGE:StorefrontInstallableTemplatePackage={...PLAYROOM_TEMPLATE_PACKAGE,manifest:{...PLAYROOM_TEMPLATE_PACKAGE.manifest,templateVersion:PLAYROOM_REFERENCE_V2_TEMPLATE_VERSION},pages:PLAYROOM_TEMPLATE_PACKAGE.pages.map(page=>page.pageType==='home'?PLAYROOM_REFERENCE_V2_HOME_PAGE:{...page,templateVersion:PLAYROOM_REFERENCE_V2_TEMPLATE_VERSION,metadata:{...(page.metadata??{}),canonicalUpgradeFromTemplateVersion:1,visualAuthority:'Neon Gamer Webáruház Kezdőlap',referenceFidelityRelease:'playroom-v2'}})};
