import {
  SPEC_LAB_BUILDER_HARDENING_CONTRACT,
  SPEC_LAB_DECISION_PATH,
  SPEC_LAB_ENGINE_CONTRACT,
  SPEC_LAB_HOME_SECTION_ORDER,
  SPEC_LAB_LEGACY_WORKING_NAME,
  SPEC_LAB_TEMPLATE_KEY,
  SPEC_LAB_TEMPLATE_VERSION,
  SPEC_LAB_VISUAL_DNA,
} from '@/lib/builder/templates/spec-lab';
import {CREATOR_STATION_VISUAL_DNA} from '@/lib/builder/templates/creator-station';

/** Wave 37 re-accepts original Wave 18 Spec Lab directly after Creator Station.
 * It hardens the inherited v1 package against the current shared Builder/runtime
 * contracts without introducing a Spec-Lab-local engine or commerce authority. */
export const SPEC_LAB_WAVE37_ACCEPTANCE=Object.freeze({
  wave:37,
  historicalWave:18,
  mode:'current-baseline-reacceptance-and-builder-hardening',
  templateKey:SPEC_LAB_TEMPLATE_KEY,
  templateVersion:SPEC_LAB_TEMPLATE_VERSION,
  legacyWorkingName:SPEC_LAB_LEGACY_WORKING_NAME,
  inheritedImplementation:true,
  historicalSequence:{previous:'tech.creator-station',current:'tech.spec-lab',relationship:'original-wave18-directly-on-creator-station'},
  portfolio:{category:'electronics-tech',specLab:SPEC_LAB_VISUAL_DNA.character,previousCreatorStation:CREATOR_STATION_VISUAL_DNA.character,decisionPath:SPEC_LAB_DECISION_PATH},
  builderContract:{
    hardening:SPEC_LAB_BUILDER_HARDENING_CONTRACT,
    stableIdentity:'stable-node-ids-and-stable-binding-paths',
    pagePresetCount:14,
    minimumPlan:'alap',
    demoNamespace:'tech-spec-lab',
    installation:'draft-only',
    homeOrder:SPEC_LAB_HOME_SECTION_ORDER,
  },
  sharedAuthority:{
    engineContract:SPEC_LAB_ENGINE_CONTRACT,
    discovery:'E2-only-for-catalog-search-and-channel-eligibility',
    guidedFinder:'E3-guidance-and-ranking-only',
    configurator:'E5-setup-intent-and-read-model-only',
    compatibility:'E6-explainable-evidence-only-unknown-is-not-compatible',
    structuredProduct:'E7-authoritative-specification-and-comparison-read-models-only',
    editorial:'E10-editorial-read-model-presentation-only',
    pricing:'shared-commerce-binding-only',
    inventory:'shared-commerce-binding-only',
    variants:'shared-commerce-binding-only',
    checkout:'shared-provider-neutral-E13',
  },
  integrationHooks:{tradeIn:'read-model-link-only-no-valuation-or-lifecycle-authority',product3dViewer:'external-viewer-launch-only-no-template-owned-3d-engine'},
  nonScope:[
    'second-spec-lab-template',
    'template-local-guided-finder-engine',
    'template-local-configurator-engine',
    'template-local-compatibility-engine',
    'template-local-structured-product-registry',
    'runtime-binding-allowlist-widening',
    'trade-in-valuation-authority',
    'trade-in-persistence',
    'template-owned-3d-engine',
    'fabricated-specification',
    'fabricated-compatibility',
    'fabricated-performance-guarantee',
    'price-or-stock-authority',
    'payment-provider-change',
    'sql-migration',
    'vercel-production-deploy',
    'supabase-mutation',
    'main-merge',
    'visual-builder-drag-drop-ui',
  ],
} as const);
