import {EDITORIAL_ATELIER_TEMPLATE_KEY,EDITORIAL_ATELIER_VISUAL_DNA} from '@/lib/builder/templates/editorial-atelier';
import {MONARCHE_VISUAL_DNA} from '@/lib/builder/templates/monarche';
import {
  STREET_DROP_ENGINE_CONTRACT,
  STREET_DROP_HOME_SECTION_ORDER,
  STREET_DROP_TEMPLATE_KEY,
  STREET_DROP_TEMPLATE_VERSION,
  STREET_DROP_VISUAL_DNA,
} from '@/lib/builder/templates/street-drop';

/**
 * Wave 45 re-accepts the repository's original Wave 26 Street Drop package
 * directly after the accepted Wave 44 Editorial Atelier baseline.
 * Historical ordering is repository-derived from PR #148 -> PR #149.
 */
export const STREET_DROP_WAVE45_ACCEPTANCE=Object.freeze({
  wave:45,
  historicalWave:26,
  mode:'current-baseline-reacceptance-and-builder-hardening',
  templateKey:STREET_DROP_TEMPLATE_KEY,
  templateVersion:STREET_DROP_TEMPLATE_VERSION,
  inheritedImplementation:true,
  historicalSequence:{
    previous:EDITORIAL_ATELIER_TEMPLATE_KEY,
    current:STREET_DROP_TEMPLATE_KEY,
    relationship:'original-wave26-stacked-directly-on-editorial-atelier-wave25',
  },
  portfolio:{
    category:'fashion-apparel',
    position:'aggressive-readable-streetwear-sneaker-drop-culture',
    character:STREET_DROP_VISUAL_DNA.character,
    monarche:MONARCHE_VISUAL_DNA.character,
    editorialAtelier:EDITORIAL_ATELIER_VISUAL_DNA.character,
    separation:[
      'not-monarche-balanced-mainstream-premium-retail',
      'not-editorial-atelier-asymmetric-luxury-magazine',
      'not-gamer-rgb-or-unreadable-graffiti',
    ] as const,
  },
  visualContract:{
    audience:['streetwear','sneaker','street-workout','skate','roller','bmx'] as const,
    foundation:'black-off-white-with-merchant-replaceable-neon-accent',
    displayTypography:'characterful-readable-display-headlines-only',
    interfaceTypography:'clean-sans-ui',
    fontRequirements:['builder-available','legally-usable','hungarian-characters'] as const,
    rhythm:'high-energy-home-ordered-commerce-pages-restrained-checkout',
  },
  experience:{
    homeOrder:STREET_DROP_HOME_SECTION_ORDER,
    heroLayers:['badge','headline','copy','primary-cta','secondary-cta','image'] as const,
    dropAlertLayers:['eyebrow','headline','copy','cta'] as const,
    pdpGrid:'desktop-tablet-7-5-mobile-12-12',
    checkoutPresentation:'shared-provider-neutral-E13',
  },
  engineContract:{
    historicalRequiredForFullExperience:['E1','E2','E13'] as const,
    historicalOptional:['E7','E3','Recommendations'] as const,
    currentRequiredForFullExperience:STREET_DROP_ENGINE_CONTRACT.requiredForFullExperience,
    currentOptional:STREET_DROP_ENGINE_CONTRACT.optional,
  },
  sharedAuthority:{
    runtime:'E1-shared-page-schema-runtime',
    discovery:'E2-only-for-catalog-search-product-eligibility-authority',
    structuredFacts:'E7-optional-source-supplied-structured-product-facts',
    guidedFinder:'E3-optional-shared-guided-fit-finder',
    recommendations:'shared-recommendation-surface-only',
    scarcity:'inventory-binding-only',
    releaseStatus:'authoritative-binding-only',
    checkout:'shared-provider-neutral-E13',
    futureReleaseEngine:'shared-release-or-drop-engine-only-never-template-local',
  },
  safety:{
    fabricatedPrice:false,
    fabricatedStock:false,
    fabricatedStockCount:false,
    fabricatedCountdown:false,
    fabricatedReleaseStatus:false,
    fabricatedRating:false,
    templateProductEligibilityAuthority:false,
    templateInventoryAuthority:false,
    templateDropScheduler:false,
    templateCheckoutAuthority:false,
    templatePaymentAuthority:false,
  },
  builderContract:{
    hierarchy:'template-page-presets-section-presets-components',
    stableIdentity:'stable-node-ids-and-stable-binding-paths',
    responsiveGrid:'shared-desktop-tablet-mobile-grid',
    pagePresetCount:14,
    minimumPlan:'alap',
    protectedHomeSequence:true,
    protectedPdpGrid:'desktop-tablet-7-5-mobile-12-12',
    imageRule:'business-copy-price-promo-and-cta-never-baked-into-image-assets',
    runtimeAllowlistWidened:false,
    componentRegistryWidened:false,
    bindingNamespaceWidened:false,
    visualBuilder:'future-compatible-no-template-local-builder-engine',
  },
  nonScope:[
    'duplicate-street-drop-template',
    'template-specific-drop-scheduler',
    'template-specific-release-engine',
    'template-specific-scarcity-engine',
    'template-specific-inventory-engine',
    'fabricated-commerce-or-product-authority',
    'visual-builder-drag-drop-ui',
    'live-canvas',
    'inline-editing',
    'payment-provider-change',
    'sql-migration',
    'vercel-production-deploy',
    'supabase-mutation',
    'tenant-status-change',
    'tenant-plan-change',
    'main-merge',
    'wave46-implementation',
  ] as const,
});
