import {STOREFRONT_BUILDER_FOUNDATION_VERSION,STOREFRONT_DEMO_CONTENT_POLICY,STOREFRONT_PAGE_SCHEMA_VERSION,STOREFRONT_TEMPLATE_MANIFEST_VERSION,STOREFRONT_TEMPLATE_MIGRATION_POLICY,defineStorefrontTemplateManifest,type StorefrontBuilderPageType} from '@/lib/builder/storefront-foundation';
import type {StorefrontComponentNode,StorefrontPageDocument} from '@/lib/builder/storefront-runtime';
import type {StorefrontInstallableTemplatePackage} from '@/lib/builder/storefront-template-installation';

export const STREET_DROP_TEMPLATE_KEY='fashion.street-drop' as const;
export const STREET_DROP_TEMPLATE_VERSION=1 as const;
export const STREET_DROP_VISUAL_DNA=Object.freeze({
  character:'aggressive-urban-drop-commerce',
  audience:['streetwear','sneaker','skate','bmx','roller'],
  palette:{background:'black-off-white',accent:'merchant-replaceable-neon'},
  typography:{display:'readable-urban-display',interface:'clean-sans',requirements:['builder-available','hungarian-characters']},
  focus:['drop','release','limited-stock','community'],
  pageRhythm:{home:'high-energy',catalog:'ordered',product:'ordered',cart:'restrained',checkout:'restrained-accordion'},
  exclusions:['baked-in-marketing-copy','unreadable-graffiti-font','gamer-rgb','luxury-editorial-clone','fake-stock-scarcity'],
} as const);
export const STREET_DROP_DESIGN_TOKENS=Object.freeze({
  '--shoporation-color-background':'#f7f4ed','--shoporation-color-surface':'#111111','--shoporation-color-surface-muted':'#e8e4dc','--shoporation-color-text':'#111111','--shoporation-color-muted-text':'#68645d','--shoporation-color-border':'#c9c4ba','--shoporation-color-primary':'#111111','--shoporation-color-primary-contrast':'#f7f4ed','--shoporation-color-accent':'var(--merchant-accent, #c8ff00)','--shoporation-heading-font':'var(--merchant-heading-font, Impact, Arial Black, Arial, sans-serif)','--shoporation-body-font':'var(--merchant-body-font, Arial, sans-serif)',
} as const);
export const STREET_DROP_ENGINE_CONTRACT=Object.freeze({
  requiredForFullExperience:['E1','E2','E13'] as const,
  optional:['E7','E3','Recommendations'] as const,
  scaleOutIntegration:{E1:'shared-runtime',E2:'shared-product-discovery-authority',E13:'shared-checkout-authority',E7:'optional-size-material-specs',E3:'optional-guided-fit-finder',Recommendations:'shared-recommendation-surface'},
  stockScarcityAuthority:'inventory-binding-only',
  marketingLayerRule:'every-visible-hero-banner-element-editable-separately',
} as const);
export const STREET_DROP_HOME_SECTION_ORDER=['Drop Hero','Release Bar','Shop the Drop','Categories','Limited Stock','Street Story','New Arrivals','Community Journal','Drop Alert','Footer'] as const;

const node=(x:StorefrontComponentNode):StorefrontComponentNode=>x;
const section=(id:string,children:StorefrontComponentNode[],tone='background'):StorefrontComponentNode=>node({id,componentKey:'layout.section',componentVersion:1,config:{tone,spacing:'xl',width:'full'},children:[node({id:`${id}-container`,componentKey:'layout.container',componentVersion:1,config:{width:'content',spacing:'m'},children})]});
const header=(p:string):StorefrontComponentNode=>node({id:`${p}-header`,componentKey:'system.header',componentVersion:1,config:{brandLabel:'Street Drop',brandHref:'/',tone:'background',sticky:true},bindings:{brandLabel:{path:'brand.name',fallback:'Street Drop'},brandHref:{path:'brand.homeHref',fallback:'/'}},children:[node({id:`${p}-nav`,componentKey:'system.navigation',componentVersion:1,config:{ariaLabel:'Fő navigáció',items:[],layout:'horizontal'},bindings:{items:{path:'navigation.primary',fallback:[]}}})]});
const footerFallback=[{id:'drop',title:'Drop',items:[{label:'Újdonságok',href:'/webaruhaz'},{label:'Sneaker',href:'/webaruhaz'}]},{id:'crew',title:'Crew',items:[{label:'Journal',href:'/blog'},{label:'Kapcsolat',href:'/kapcsolat'}]}];
const footer=(p:string):StorefrontComponentNode=>node({id:`${p}-footer`,componentKey:'editorial.footer',componentVersion:1,config:{brandLabel:'Street Drop',columns:footerFallback,copyright:'© Street Drop',tone:'primary'},bindings:{brandLabel:{path:'brand.name',fallback:'Street Drop'},columns:{path:'navigation.footer',fallback:footerFallback},copyright:{path:'brand.copyright',fallback:'© Street Drop'}}});
const base=(key:string,type:StorefrontBuilderPageType,sections:StorefrontComponentNode[],metadata:Record<string,unknown>={}):StorefrontPageDocument=>({schemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,pageKey:key,pageType:type,templateKey:STREET_DROP_TEMPLATE_KEY,templateVersion:STREET_DROP_TEMPLATE_VERSION,metadata:{scaleOutTemplate:'Wave 2 / Street Drop',visualDNA:STREET_DROP_VISUAL_DNA.character,...metadata},sections});
const productGrid=(id:string,title:string,path:string,columns=4):StorefrontComponentNode=>node({id,componentKey:'commerce.product-grid',componentVersion:1,config:{title,products:[],columns,presentation:'street',showBadges:true,showCompareAt:true,imageRatio:'4 / 5',emptyLabel:'Jelenleg nincs megjeleníthető termék.',currency:'HUF'},bindings:{title:{path:`content.${id}.title`,fallback:title},products:{path,fallback:[]}}});
const simple=(key:string,type:StorefrontBuilderPageType,title:string,copy:string,metadata:Record<string,unknown>={})=>base(key,type,[header(key.replaceAll('.','-')),section(`${key.replaceAll('.','-')}-body`,[node({id:`${key}-title`,componentKey:'content.heading',componentVersion:1,config:{text:title,level:1,align:'left',tone:'text'},bindings:{text:{path:`content.${type}.title`,fallback:title}}}),node({id:`${key}-copy`,componentKey:'content.text',componentVersion:1,config:{text:copy,as:'p',align:'left',tone:'text'},bindings:{text:{path:`content.${type}.copy`,fallback:copy}}})]),footer(key.replaceAll('.','-'))],metadata);

export const STREET_DROP_HOME_PAGE=base('street-drop.home','home',[
 header('street-drop-home'),
 section('street-drop-hero',[node({id:'street-drop-hero-grid',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'center'},children:[node({id:'street-drop-hero-copy-stack',componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap:'m',align:'start',justify:'center'},responsive:{desktop:{gridSpan:5},tablet:{gridSpan:5},mobile:{gridSpan:12}},children:[node({id:'street-drop-hero-badge',componentKey:'content.text',componentVersion:1,config:{text:'DROP 01',as:'strong',align:'left',tone:'text'},bindings:{text:{path:'content.streetDropHero.badge',fallback:'DROP 01'}}}),node({id:'street-drop-hero-title',componentKey:'content.heading',componentVersion:1,config:{text:'NEW DROP. NO REPLAY.',level:1,align:'left',tone:'text'},bindings:{text:{path:'content.streetDropHero.title',fallback:'NEW DROP. NO REPLAY.'}}}),node({id:'street-drop-hero-copy',componentKey:'content.text',componentVersion:1,config:{text:'Streetwear, sneaker és ride culture egy gyors, limitált dropban.',as:'p',align:'left',tone:'text'},bindings:{text:{path:'content.streetDropHero.copy',fallback:'Streetwear, sneaker és ride culture egy gyors, limitált dropban.'}}}),node({id:'street-drop-hero-primary',componentKey:'content.button',componentVersion:1,config:{label:'Shop the Drop',href:'/webaruhaz',variant:'primary',size:'l',ariaLabel:'Shop the Drop'},bindings:{label:{path:'content.streetDropHero.primaryLabel',fallback:'Shop the Drop'},href:{path:'content.streetDropHero.primaryHref',fallback:'/webaruhaz'}}}),node({id:'street-drop-hero-secondary',componentKey:'content.button',componentVersion:1,config:{label:'Release info',href:'#release',variant:'secondary',size:'m',ariaLabel:'Release info'},bindings:{label:{path:'content.streetDropHero.secondaryLabel',fallback:'Release info'},href:{path:'content.streetDropHero.secondaryHref',fallback:'#release'}}})]}),node({id:'street-drop-hero-image',componentKey:'content.image',componentVersion:1,config:{src:'/storefront-demo/street-drop/hero.svg',alt:'Street Drop városi kampány',width:1200,height:900,fit:'cover',loading:'eager',radius:'none'},bindings:{src:{path:'content.streetDropHero.image',fallback:'/storefront-demo/street-drop/hero.svg'},alt:{path:'content.streetDropHero.imageAlt',fallback:'Street Drop városi kampány'}},responsive:{desktop:{gridSpan:7},tablet:{gridSpan:7},mobile:{gridSpan:12}}})]})],'background'),
 section('street-drop-release',[node({id:'street-drop-release-label',componentKey:'content.text',componentVersion:1,config:{text:'RELEASE STATUS',as:'strong',align:'left',tone:'text'},bindings:{text:{path:'content.releaseBar.label',fallback:'RELEASE STATUS'}}}),node({id:'street-drop-release-title',componentKey:'content.heading',componentVersion:1,config:{text:'A következő drop státusza',level:2,align:'left',tone:'text'},bindings:{text:{path:'content.releaseBar.title',fallback:'A következő drop státusza'}}}),node({id:'street-drop-release-copy',componentKey:'content.text',componentVersion:1,config:{text:'A dátum, státusz és készletjelzés mindig valódi merchant/inventory bindingból érkezik.',as:'p',align:'left',tone:'muted'},bindings:{text:{path:'drop.releaseStatus',fallback:'Nincs aktív release státusz.'}}})],'surface'),
 section('street-drop-shop',[productGrid('streetDropProducts','Shop the Drop','catalog.drop',4)]),
 section('street-drop-categories',[node({id:'street-drop-category-navigation',componentKey:'commerce.collection-navigation',componentVersion:1,config:{title:'Pick your lane',items:[],columns:4,imageRatio:'4 / 5',tone:'background'},bindings:{title:{path:'content.streetCategories.title',fallback:'Pick your lane'},items:{path:'collection.navigation',fallback:[]}}})]),
 section('street-drop-limited',[productGrid('limitedStock','Limited Stock','catalog.limited',4)],'surface'),
 section('street-drop-story',[node({id:'street-drop-story-grid',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'center'},children:[node({id:'street-drop-story-image',componentKey:'content.image',componentVersion:1,config:{src:'/storefront-demo/street-drop/story.svg',alt:'Street Drop skate és BMX közösségi jelenet',width:1200,height:900,fit:'cover',loading:'lazy',radius:'none'},bindings:{src:{path:'content.streetStory.image',fallback:'/storefront-demo/street-drop/story.svg'},alt:{path:'content.streetStory.imageAlt',fallback:'Street Drop skate és BMX közösségi jelenet'}},responsive:{desktop:{gridSpan:6},tablet:{gridSpan:6},mobile:{gridSpan:12}}}),node({id:'street-drop-story-stack',componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap:'m',align:'start',justify:'center'},responsive:{desktop:{gridSpan:6},tablet:{gridSpan:6},mobile:{gridSpan:12}},children:[node({id:'street-drop-story-eyebrow',componentKey:'content.text',componentVersion:1,config:{text:'STREET STORY',as:'strong',align:'left',tone:'text'},bindings:{text:{path:'content.streetStory.eyebrow',fallback:'STREET STORY'}}}),node({id:'street-drop-story-title',componentKey:'content.heading',componentVersion:1,config:{text:'Built outside the showroom.',level:2,align:'left',tone:'text'},bindings:{text:{path:'content.streetStory.title',fallback:'Built outside the showroom.'}}}),node({id:'street-drop-story-copy',componentKey:'content.text',componentVersion:1,config:{text:'Közösségi történet külön szerkeszthető képpel, szöveggel és CTA-val.',as:'p',align:'left',tone:'text'},bindings:{text:{path:'content.streetStory.copy',fallback:'Közösségi történet külön szerkeszthető képpel, szöveggel és CTA-val.'}}}),node({id:'street-drop-story-cta',componentKey:'content.button',componentVersion:1,config:{label:'Read the story',href:'/blog',variant:'secondary',size:'m',ariaLabel:'Read the story'},bindings:{label:{path:'content.streetStory.ctaLabel',fallback:'Read the story'},href:{path:'content.streetStory.ctaHref',fallback:'/blog'}}})]})]})]),
 section('street-drop-new',[productGrid('streetNewArrivals','New Arrivals','catalog.newArrivals',4)]),
 section('street-drop-community',[node({id:'street-drop-community-journal',componentKey:'editorial.journal-preview',componentVersion:1,config:{title:'Community / Journal',items:[],columns:3,emptyLabel:'Nincs még publikált közösségi történet.'},bindings:{title:{path:'content.communityJournal.title',fallback:'Community / Journal'},items:{path:'content.communityJournal.items',fallback:[]}}})]),
 section('street-drop-alert',[node({id:'street-drop-alert-eyebrow',componentKey:'content.text',componentVersion:1,config:{text:'DROP ALERT',as:'strong',align:'center',tone:'text'},bindings:{text:{path:'content.dropAlert.eyebrow',fallback:'DROP ALERT'}}}),node({id:'street-drop-alert-title',componentKey:'content.heading',componentVersion:1,config:{text:'Ne maradj le a következő release-ről.',level:2,align:'center',tone:'text'},bindings:{text:{path:'content.dropAlert.title',fallback:'Ne maradj le a következő release-ről.'}}}),node({id:'street-drop-alert-copy',componentKey:'content.text',componentVersion:1,config:{text:'A feliratkozás a közös marketing authorityn keresztül működik.',as:'p',align:'center',tone:'muted'},bindings:{text:{path:'content.dropAlert.copy',fallback:'A feliratkozás a közös marketing authorityn keresztül működik.'}}}),node({id:'street-drop-alert-cta',componentKey:'content.button',componentVersion:1,config:{label:'Drop Alert',href:'/hirlevel',variant:'primary',size:'m',ariaLabel:'Drop Alert'},bindings:{label:{path:'content.dropAlert.ctaLabel',fallback:'Drop Alert'},href:{path:'content.dropAlert.ctaHref',fallback:'/hirlevel'}}})],'surface'),
 footer('street-drop-home')
],{sectionOrder:STREET_DROP_HOME_SECTION_ORDER,visualPreset:'urban-drop-home',marketingLayerRule:'separate-editable-layers',stockScarcityAuthority:'inventory-only'});

export const STREET_DROP_CATALOG_PAGE=base('street-drop.catalog','catalog',[header('street-drop-catalog'),section('street-drop-catalog-head',[node({id:'street-drop-catalog-header',componentKey:'commerce.collection-header',componentVersion:1,config:{eyebrow:'Catalog',title:'Street Drop',description:'Rendezett kategóriaoldal a gyors drop-főoldal után.',image:'',imageAlt:'',align:'left'},bindings:{title:{path:'collection.current.title',fallback:'Street Drop'},description:{path:'collection.current.description',fallback:'Rendezett kategóriaoldal a gyors drop-főoldal után.'}}})]),section('street-drop-catalog-products',[productGrid('streetCatalog','Összes termék','catalog.products',4)]),footer('street-drop-catalog')],{visualPreset:'ordered-street-catalog',engineBinding:'E2'});
export const STREET_DROP_PRODUCT_PAGE=base('street-drop.product','product',[header('street-drop-product'),section('street-drop-product-main',[node({id:'street-drop-product-grid',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'start'},children:[node({id:'street-drop-product-gallery',componentKey:'commerce.product-gallery',componentVersion:1,config:{images:[],aspectRatio:'4 / 5',thumbnailPosition:'bottom'},bindings:{images:{path:'product.gallery',fallback:[]}},responsive:{desktop:{gridSpan:7},tablet:{gridSpan:7},mobile:{gridSpan:12}}}),node({id:'street-drop-product-buybox',componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap:'m',align:'stretch',justify:'start'},responsive:{desktop:{gridSpan:5},tablet:{gridSpan:5},mobile:{gridSpan:12}},children:[node({id:'street-drop-product-info',componentKey:'commerce.product-info',componentVersion:1,config:{eyebrow:'Drop',title:'Termék',price:'',compareAtPrice:'',description:'',stockLabel:'',badges:[],currency:'HUF'},bindings:{eyebrow:{path:'product.eyebrow',fallback:'Drop'},title:{path:'product.name',fallback:'Termék'},price:{path:'pricing.displayPrice',fallback:''},compareAtPrice:{path:'pricing.compareAtPrice',fallback:''},description:{path:'product.description',fallback:''},stockLabel:{path:'inventory.stockLabel',fallback:''},badges:{path:'product.badges',fallback:[]}}}),node({id:'street-drop-color',componentKey:'commerce.variant-swatches',componentVersion:1,config:{label:'Szín',options:[],emptyLabel:'Nincs választható szín.'},bindings:{label:{path:'variant.colorLabel',fallback:'Szín'},options:{path:'variant.colorOptions',fallback:[]}}}),node({id:'street-drop-size',componentKey:'commerce.size-selector',componentVersion:1,config:{label:'Méret',options:[],emptyLabel:'Nincs választható méret.'},bindings:{label:{path:'variant.sizeLabel',fallback:'Méret'},options:{path:'variant.sizeOptions',fallback:[]}}}),node({id:'street-drop-cta',componentKey:'content.button',componentVersion:1,config:{label:'Kosárba teszem',href:'#purchase',variant:'primary',size:'l',ariaLabel:'Kosárba teszem'},bindings:{label:{path:'commerce.purchaseLabel',fallback:'Kosárba teszem'},href:{path:'commerce.purchaseHref',fallback:'#purchase'}}})]})]})]),section('street-drop-product-recs',[node({id:'street-drop-recommendations',componentKey:'commerce.recommendation-row',componentVersion:1,config:{title:'Complete the fit',products:[],columns:4,emptyLabel:'Nincs kapcsolódó ajánlat.',currency:'HUF'},bindings:{products:{path:'recommendations.products',fallback:[]}}})]),footer('street-drop-product')],{visualPreset:'ordered-street-pdp',engineBinding:'E2',limitedStockAuthority:'inventory-binding-only'});
export const STREET_DROP_SEARCH_PAGE=base('street-drop.search','search',[header('street-drop-search'),section('street-drop-search-results',[productGrid('streetSearch','Találatok','search.results',4)]),footer('street-drop-search')],{engineBinding:'E2'});
export const STREET_DROP_CART_PAGE=base('street-drop.cart','cart',[header('street-drop-cart'),section('street-drop-cart-body',[node({id:'street-drop-cart-summary',componentKey:'commerce.cart-summary',componentVersion:1,config:{lines:[],subtotal:'',total:'',currency:'HUF',checkoutHref:'/penztar',checkoutLabel:'Tovább a pénztárhoz',emptyLabel:'A kosarad üres.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},total:{path:'cart.total',fallback:''}}})]),footer('street-drop-cart')],{visualPreset:'restrained-street-cart'});
export const STREET_DROP_CHECKOUT_PAGE=base('street-drop.checkout','checkout',[header('street-drop-checkout'),section('street-drop-checkout-body',[node({id:'street-drop-checkout-heading',componentKey:'content.heading',componentVersion:1,config:{text:'Checkout',level:1,align:'left',tone:'text'}}),node({id:'street-drop-checkout-summary',componentKey:'commerce.checkout-summary',componentVersion:1,config:{lines:[],subtotal:'',shipping:'',total:'',currency:'HUF',secureLabel:'Biztonságos, provider-neutral checkout.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},shipping:{path:'cart.shipping',fallback:''},total:{path:'cart.total',fallback:''}}})]),footer('street-drop-checkout')],{visualPreset:'restrained-street-checkout',checkoutPresentation:'accordion-dropdown',engineBinding:'E13'});
export const STREET_DROP_ACCOUNT_PAGE=simple('street-drop.account','account','Fiókom','Rendelések, kedvencek és mentett vásárlói adatok a közös account authorityból.');
export const STREET_DROP_CONTENT_PAGE=base('street-drop.content','content',[header('street-drop-content'),section('street-drop-content-body',[node({id:'street-drop-content-grid',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'center'},children:[node({id:'street-drop-content-image',componentKey:'content.image',componentVersion:1,config:{src:'/storefront-demo/street-drop/story.svg',alt:'Street Drop story',width:1200,height:900,fit:'cover',loading:'lazy',radius:'none'},bindings:{src:{path:'content.story.image',fallback:'/storefront-demo/street-drop/story.svg'},alt:{path:'content.story.imageAlt',fallback:'Street Drop story'}},responsive:{desktop:{gridSpan:6},tablet:{gridSpan:6},mobile:{gridSpan:12}}}),node({id:'street-drop-content-stack',componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap:'m',align:'start',justify:'center'},responsive:{desktop:{gridSpan:6},tablet:{gridSpan:6},mobile:{gridSpan:12}},children:[node({id:'street-drop-content-title',componentKey:'content.heading',componentVersion:1,config:{text:'Street Story',level:1,align:'left',tone:'text'},bindings:{text:{path:'content.story.title',fallback:'Street Story'}}}),node({id:'street-drop-content-copy',componentKey:'content.text',componentVersion:1,config:{text:'Közösségi és kampánytörténet külön szerkeszthető layerekkel.',as:'p',align:'left',tone:'text'},bindings:{text:{path:'content.story.copy',fallback:'Közösségi és kampánytörténet külön szerkeszthető layerekkel.'}}})]})]})]),footer('street-drop-content')],{contentRole:'street-story'});
export const STREET_DROP_BLOG_INDEX_PAGE=base('street-drop.blog-index','blog-index',[header('street-drop-blog-index'),section('street-drop-blog-index-body',[node({id:'street-drop-journal-index',componentKey:'editorial.journal-preview',componentVersion:1,config:{title:'Community Journal',items:[],columns:3,emptyLabel:'Nincs még publikált történet.'},bindings:{items:{path:'content.journal.items',fallback:[]}}})]),footer('street-drop-blog-index')]);
export const STREET_DROP_BLOG_ARTICLE_PAGE=base('street-drop.blog-article','blog-article',[header('street-drop-blog-article'),node({id:'street-drop-article-hero',componentKey:'editorial.hero',componentVersion:1,config:{eyebrow:'Journal',title:'Street Story',copy:'Közösségi történet.',image:'/storefront-demo/street-drop/story.svg',imageAlt:'Street Drop journal',primaryLabel:'Shop',primaryHref:'/webaruhaz',secondaryLabel:'',secondaryHref:'#',imagePosition:'right',height:'editorial'},bindings:{title:{path:'content.article.title',fallback:'Street Story'},copy:{path:'content.article.excerpt',fallback:'Közösségi történet.'},image:{path:'content.article.image',fallback:'/storefront-demo/street-drop/story.svg'}}}),footer('street-drop-blog-article')]);
export const STREET_DROP_FAQ_PAGE=simple('street-drop.faq','faq','GYIK','Dropok, méretezés, készlet, szállítás és visszaküldés.');
export const STREET_DROP_CONTACT_PAGE=simple('street-drop.contact','contact','Kapcsolat','Kereskedői kapcsolat és ügyfélszolgálat.');
export const STREET_DROP_LEGAL_PAGE=simple('street-drop.legal','legal','Jogi információk','A kereskedő jogi és adatkezelési tartalmának helye.');
export const STREET_DROP_NOT_FOUND_PAGE=simple('street-drop.not-found','not-found','404','Ez az oldal már nincs ebben a dropban.');

export const STREET_DROP_TEMPLATE_MANIFEST=defineStorefrontTemplateManifest({foundationVersion:STOREFRONT_BUILDER_FOUNDATION_VERSION,manifestVersion:STOREFRONT_TEMPLATE_MANIFEST_VERSION,templateKey:STREET_DROP_TEMPLATE_KEY,templateVersion:STREET_DROP_TEMPLATE_VERSION,pageSchemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,minPlan:'alap',requiredFeatures:['catalog','inventory','orders','contentMarketing','marketingBasics','productRecommendations','reviews','searchFiltering','commerceIntegrations'],pageTypes:['home','catalog','product','search','cart','checkout','account','content','blog-index','blog-article','faq','contact','legal','not-found'],responsive:{desktop:true,tablet:true,mobile:true},migration:STOREFRONT_TEMPLATE_MIGRATION_POLICY,demoContent:{namespace:'fashion-street-drop',policy:STOREFRONT_DEMO_CONTENT_POLICY}});
export const STREET_DROP_TEMPLATE_PACKAGE:StorefrontInstallableTemplatePackage={manifest:STREET_DROP_TEMPLATE_MANIFEST,pages:[STREET_DROP_HOME_PAGE,STREET_DROP_CATALOG_PAGE,STREET_DROP_PRODUCT_PAGE,STREET_DROP_SEARCH_PAGE,STREET_DROP_CART_PAGE,STREET_DROP_CHECKOUT_PAGE,STREET_DROP_ACCOUNT_PAGE,STREET_DROP_CONTENT_PAGE,STREET_DROP_BLOG_INDEX_PAGE,STREET_DROP_BLOG_ARTICLE_PAGE,STREET_DROP_FAQ_PAGE,STREET_DROP_CONTACT_PAGE,STREET_DROP_LEGAL_PAGE,STREET_DROP_NOT_FOUND_PAGE],demoFixtures:[{entityType:'collection',entityKey:'drop-01',payload:{title:'Drop 01',handle:'drop-01',demo:true}},{entityType:'collection',entityKey:'sneaker',payload:{title:'Sneaker',handle:'sneaker',demo:true}},{entityType:'product',entityKey:'street-shell',payload:{name:'Street Shell',slug:'street-shell',demo:true}},{entityType:'content',entityKey:'street-story',payload:{title:'Built Outside',kind:'journal',demo:true}}]};
