import {
  STOREFRONT_BUILDER_FOUNDATION_VERSION,
  STOREFRONT_DEMO_CONTENT_POLICY,
  STOREFRONT_PAGE_SCHEMA_VERSION,
  STOREFRONT_TEMPLATE_MANIFEST_VERSION,
  STOREFRONT_TEMPLATE_MIGRATION_POLICY,
  defineStorefrontTemplateManifest,
  type StorefrontBuilderPageType,
} from '@/lib/builder/storefront-foundation';
import type {StorefrontComponentNode,StorefrontPageDocument} from '@/lib/builder/storefront-runtime';
import type {StorefrontInstallableTemplatePackage} from '@/lib/builder/storefront-template-installation';

export const TECH_DECK_TEMPLATE_KEY='tech.tech-deck' as const;
export const TECH_DECK_TEMPLATE_VERSION=1 as const;

export const TECH_DECK_VISUAL_DNA=Object.freeze({
  character:'clean-consumer-electronics-decision-commerce',
  palette:{background:'bright-white',surface:'cool-soft-gray',text:'graphite-black',accent:'restrained-cool-blue'},
  typography:{display:'clean-sans-display',interface:'clean-sans'},
  spacing:'generous-precise-whitespace',
  imagery:'product-first-consumer-technology',
  chrome:'minimal-rounded-quiet-tech',
  exclusions:['gamer-rgb','industrial-dashboard','dark-spec-lab'],
} as const);

export const TECH_DECK_DESIGN_TOKENS=Object.freeze({
  '--shoporation-color-background':'#ffffff',
  '--shoporation-color-surface':'#f4f6f8',
  '--shoporation-color-surface-muted':'#e9edf2',
  '--shoporation-color-text':'#111418',
  '--shoporation-color-muted-text':'#5f6670',
  '--shoporation-color-border':'#d9dee5',
  '--shoporation-color-primary':'#111418',
  '--shoporation-color-primary-contrast':'#ffffff',
  '--shoporation-color-accent':'var(--merchant-accent, #146ef5)',
  '--shoporation-color-accent-soft':'var(--merchant-accent-soft, #e8f1ff)',
  '--shoporation-heading-font':'var(--merchant-heading-font, Arial, sans-serif)',
  '--shoporation-body-font':'var(--merchant-body-font, Arial, sans-serif)',
} as const);

export const TECH_DECK_ENGINE_CONTRACT=Object.freeze({
  requiredForFullExperience:['E1','E2','E7','E13'] as const,
  wave2Integration:{E1:'runtime-implemented',E2:'product-discovery-binding-contract',E7:'compare-spec-engine-v1-implemented',E13:'checkout-binding-contract'},
} as const);

export const TECH_DECK_HOME_SECTION_ORDER=[
  'Product Launch Hero','Shop by Category','Featured Technology','Best Sellers','Compare Spotlight','Use Case Navigation','Feature Story','Recommendations','Buying Guides','Footer',
] as const;

const node=(input:StorefrontComponentNode):StorefrontComponentNode=>input;
const section=(id:string,children:StorefrontComponentNode[],input:{tone?:string;spacing?:string;width?:string}={}):StorefrontComponentNode=>node({id,componentKey:'layout.section',componentVersion:1,config:{tone:input.tone??'background',spacing:input.spacing??'xl',width:input.width??'full'},children:[node({id:`${id}-container`,componentKey:'layout.container',componentVersion:1,config:{width:'content',spacing:'m'},children})]});
const stack=(id:string,children:StorefrontComponentNode[],responsive?:StorefrontComponentNode['responsive']):StorefrontComponentNode=>node({id,componentKey:'layout.stack',componentVersion:1,config:{direction:'vertical',gap:'m',align:'stretch',justify:'start'},responsive,children});
const header=(prefix:string):StorefrontComponentNode=>node({id:`${prefix}-header`,componentKey:'system.header',componentVersion:1,config:{brandLabel:'Tech Deck',brandHref:'/',tone:'background',sticky:true},bindings:{brandLabel:{path:'brand.name',fallback:'Tech Deck'},brandHref:{path:'brand.homeHref',fallback:'/'}},children:[node({id:`${prefix}-navigation`,componentKey:'system.navigation',componentVersion:1,config:{ariaLabel:'Fő navigáció',items:[],layout:'horizontal'},bindings:{items:{path:'navigation.primary',fallback:[]}}})]});
const footerFallback=[{id:'shop',title:'Vásárlás',items:[{label:'Újdonságok',href:'/webaruhaz'},{label:'Kategóriák',href:'/webaruhaz'}]},{id:'help',title:'Segítség',items:[{label:'Kapcsolat',href:'/kapcsolat'},{label:'GYIK',href:'/gyik'}]}];
const footer=(prefix:string):StorefrontComponentNode=>node({id:`${prefix}-footer`,componentKey:'editorial.footer',componentVersion:1,config:{brandLabel:'Tech Deck',columns:footerFallback,copyright:'© Tech Deck',tone:'background'},bindings:{brandLabel:{path:'brand.name',fallback:'Tech Deck'},columns:{path:'navigation.footer',fallback:footerFallback},copyright:{path:'brand.copyright',fallback:'© Tech Deck'}}});
const basePage=(pageKey:string,pageType:StorefrontBuilderPageType,sections:StorefrontComponentNode[],metadata:Record<string,unknown>={}):StorefrontPageDocument=>({schemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,pageKey,pageType,templateKey:TECH_DECK_TEMPLATE_KEY,templateVersion:TECH_DECK_TEMPLATE_VERSION,metadata:{goldenTemplate:'Golden #2',visualDNA:TECH_DECK_VISUAL_DNA.character,...metadata},sections});
const productGrid=(id:string,title:string,bindingPath:string,columns=4):StorefrontComponentNode=>node({id,componentKey:'commerce.product-grid',componentVersion:1,config:{title,products:[],columns,presentation:'tech',showBadges:true,showCompareAt:true,imageRatio:'1 / 1',emptyLabel:'Jelenleg nincs megjeleníthető termék.',currency:'HUF'},bindings:{title:{path:`content.${id}.title`,fallback:title},products:{path:bindingPath,fallback:[]}}});
const recommendationRow=(id:string,title:string,bindingPath:string):StorefrontComponentNode=>node({id,componentKey:'commerce.recommendation-row',componentVersion:1,config:{title,products:[],columns:4,emptyLabel:'Jelenleg nincs kapcsolódó ajánlat.',currency:'HUF'},bindings:{title:{path:`content.${id}.title`,fallback:title},products:{path:bindingPath,fallback:[]}}});

export const TECH_DECK_HOME_PAGE=basePage('tech-deck.home','home',[
  header('tech-home'),
  node({id:'tech-launch-hero',componentKey:'commerce.product-launch-hero',componentVersion:1,config:{eyebrow:'Újdonság',title:'Technológia, amit könnyű választani.',copy:'Tiszta összehasonlítás, érthető specifikációk és a lényegre fókuszáló termékélmény.',image:'/storefront-demo/tech-deck/launch.svg',imageAlt:'Tech Deck termékbevezető vizuál',price:'',compareAtPrice:'',badge:'New',primaryLabel:'Megnézem',primaryHref:'/webaruhaz',secondaryLabel:'Összehasonlítás',secondaryHref:'/osszehasonlitas',tone:'background'},bindings:{eyebrow:{path:'content.launchHero.eyebrow',fallback:'Újdonság'},title:{path:'content.launchHero.title',fallback:'Technológia, amit könnyű választani.'},copy:{path:'content.launchHero.copy',fallback:'Tiszta összehasonlítás, érthető specifikációk és a lényegre fókuszáló termékélmény.'},image:{path:'content.launchHero.image',fallback:'/storefront-demo/tech-deck/launch.svg'},imageAlt:{path:'content.launchHero.imageAlt',fallback:'Tech Deck termékbevezető vizuál'},price:{path:'content.launchHero.price',fallback:''},compareAtPrice:{path:'content.launchHero.compareAtPrice',fallback:''},badge:{path:'content.launchHero.badge',fallback:'New'},primaryLabel:{path:'content.launchHero.primaryLabel',fallback:'Megnézem'},primaryHref:{path:'content.launchHero.primaryHref',fallback:'/webaruhaz'},secondaryLabel:{path:'content.launchHero.secondaryLabel',fallback:'Összehasonlítás'},secondaryHref:{path:'content.launchHero.secondaryHref',fallback:'/osszehasonlitas'}}}),
  section('tech-shop-by-category',[node({id:'tech-category-navigation',componentKey:'commerce.collection-navigation',componentVersion:1,config:{title:'Vásárlás kategória szerint',items:[],columns:4,imageRatio:'1 / 1',tone:'background'},bindings:{title:{path:'content.categoryNavigation.title',fallback:'Vásárlás kategória szerint'},items:{path:'collection.navigation',fallback:[]}}})],{spacing:'l'}),
  section('tech-featured-technology',[productGrid('featuredTechnology','Kiemelt technológia','catalog.featuredTechnology',4)]),
  section('tech-best-sellers',[productGrid('bestSellers','Legnépszerűbbek','catalog.bestSellers',4)],{tone:'surface'}),
  section('tech-compare-spotlight',[node({id:'tech-compare-spotlight-block',componentKey:'commerce.compare-spotlight',componentVersion:1,config:{title:'Mi a különbség?',copy:'A legfontosabb eltérések egy helyen.',products:[],rows:[],ctaLabel:'Teljes összehasonlítás',ctaHref:'/osszehasonlitas'},bindings:{title:{path:'content.compareSpotlight.title',fallback:'Mi a különbség?'},copy:{path:'content.compareSpotlight.copy',fallback:'A legfontosabb eltérések egy helyen.'},products:{path:'commerce.compareSpotlight.products',fallback:[]},rows:{path:'commerce.compareSpotlight.rows',fallback:[]},ctaLabel:{path:'content.compareSpotlight.ctaLabel',fallback:'Teljes összehasonlítás'},ctaHref:{path:'content.compareSpotlight.ctaHref',fallback:'/osszehasonlitas'}}})]),
  section('tech-use-case-navigation',[node({id:'tech-use-case-navigation-block',componentKey:'commerce.collection-navigation',componentVersion:1,config:{title:'Mire használod?',items:[],columns:4,imageRatio:'4 / 3',tone:'background'},bindings:{title:{path:'content.useCases.title',fallback:'Mire használod?'},items:{path:'collection.useCases',fallback:[]}}})],{spacing:'l'}),
  node({id:'tech-feature-story',componentKey:'editorial.split-feature',componentVersion:1,config:{eyebrow:'Feature story',title:'A specifikáció mögött az élmény számít.',copy:'Mutasd meg egyszerűen, mit jelent a technológia a mindennapi használatban.',image:'/storefront-demo/tech-deck/feature.svg',imageAlt:'Tech Deck feature story vizuál',ctaLabel:'További részletek',ctaHref:'/journal',imagePosition:'right',tone:'surface'},bindings:{eyebrow:{path:'content.techFeature.eyebrow',fallback:'Feature story'},title:{path:'content.techFeature.title',fallback:'A specifikáció mögött az élmény számít.'},copy:{path:'content.techFeature.copy',fallback:'Mutasd meg egyszerűen, mit jelent a technológia a mindennapi használatban.'},image:{path:'content.techFeature.image',fallback:'/storefront-demo/tech-deck/feature.svg'},imageAlt:{path:'content.techFeature.imageAlt',fallback:'Tech Deck feature story vizuál'},ctaLabel:{path:'content.techFeature.ctaLabel',fallback:'További részletek'},ctaHref:{path:'content.techFeature.ctaHref',fallback:'/journal'}}}),
  section('tech-recommendations',[recommendationRow('homeRecommendations','Neked ajánljuk','recommendations.home')]),
  section('tech-buying-guides',[node({id:'tech-buying-guides-block',componentKey:'editorial.journal-preview',componentVersion:1,config:{title:'Vásárlási útmutatók',items:[],columns:3,emptyLabel:'Hamarosan új útmutatók érkeznek.'},bindings:{title:{path:'content.buyingGuides.title',fallback:'Vásárlási útmutatók'},items:{path:'content.buyingGuides.items',fallback:[]}}})]),
  footer('tech-home'),
],{sectionOrder:TECH_DECK_HOME_SECTION_ORDER,visualPreset:'clean-consumer-tech-home'});

export const TECH_DECK_CATALOG_PAGE=basePage('tech-deck.catalog','catalog',[
  header('tech-catalog'),
  section('tech-catalog-hero',[node({id:'tech-catalog-collection-header',componentKey:'commerce.collection-header',componentVersion:1,config:{eyebrow:'Shop',title:'Összes termék',description:'Szűrj a számodra fontos műszaki adatok szerint.',image:'',imageAlt:'',align:'left'},bindings:{eyebrow:{path:'collection.current.eyebrow',fallback:'Shop'},title:{path:'collection.current.title',fallback:'Összes termék'},description:{path:'collection.current.description',fallback:'Szűrj a számodra fontos műszaki adatok szerint.'},image:{path:'collection.current.image',fallback:''},imageAlt:{path:'collection.current.imageAlt',fallback:''}}})],{spacing:'l'}),
  section('tech-catalog-body',[node({id:'tech-catalog-grid',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'start'},children:[node({id:'tech-catalog-facets',componentKey:'commerce.catalog-facets',componentVersion:1,config:{title:'Szűrés',facets:[],clearHref:'/webaruhaz',clearLabel:'Törlés'},bindings:{facets:{path:'catalog.facets',fallback:[]},clearHref:{path:'catalog.clearHref',fallback:'/webaruhaz'},clearLabel:{path:'catalog.clearLabel',fallback:'Törlés'}},responsive:{desktop:{gridSpan:3},tablet:{gridSpan:4},mobile:{gridSpan:12}}}),node({...productGrid('catalogGrid','Termékek','catalog.products',3),responsive:{desktop:{gridSpan:9},tablet:{gridSpan:8},mobile:{gridSpan:12}}})]})]),
  footer('tech-catalog'),
],{visualPreset:'structured-tech-catalog',engineBinding:'E7'});

export const TECH_DECK_PRODUCT_PAGE=basePage('tech-deck.product','product',[
  header('tech-product'),
  section('tech-product-main',[node({id:'tech-product-grid',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'start'},children:[node({id:'tech-product-gallery',componentKey:'commerce.product-gallery',componentVersion:1,config:{images:[],aspectRatio:'1 / 1',thumbnailPosition:'bottom'},bindings:{images:{path:'product.gallery',fallback:[]}},responsive:{desktop:{gridSpan:7},tablet:{gridSpan:7},mobile:{gridSpan:12}}}),stack('tech-product-buybox',[node({id:'tech-product-info',componentKey:'commerce.product-info',componentVersion:1,config:{eyebrow:'Tech Deck',title:'Termék',price:'',compareAtPrice:'',description:'',stockLabel:'',badges:[],currency:'HUF'},bindings:{eyebrow:{path:'product.eyebrow',fallback:'Tech Deck'},title:{path:'product.name',fallback:'Termék'},price:{path:'pricing.displayPrice',fallback:''},compareAtPrice:{path:'pricing.compareAtPrice',fallback:''},description:{path:'product.description',fallback:''},stockLabel:{path:'inventory.stockLabel',fallback:''},badges:{path:'product.badges',fallback:[]}}}),node({id:'tech-product-color',componentKey:'commerce.variant-swatches',componentVersion:1,config:{label:'Szín',options:[]},bindings:{label:{path:'variant.colorLabel',fallback:'Szín'},options:{path:'variant.colorOptions',fallback:[]}}}),node({id:'tech-product-option',componentKey:'commerce.option-selector',componentVersion:1,config:{label:'Tárhely',options:[]},bindings:{label:{path:'variant.optionLabel',fallback:'Tárhely'},options:{path:'variant.optionOptions',fallback:[]}}}),node({id:'tech-product-key-specs',componentKey:'commerce.key-specs',componentVersion:1,config:{title:'A legfontosabb adatok',items:[],columns:2,missingLabel:'Nincs megadva'},bindings:{items:{path:'product.keySpecs',fallback:[]}}}),node({id:'tech-product-compare',componentKey:'commerce.compare-button',componentVersion:1,config:{label:'Összehasonlítás',href:'#compare',count:0,disabled:false},bindings:{label:{path:'commerce.compareLabel',fallback:'Összehasonlítás'},href:{path:'commerce.compareHref',fallback:'#compare'},count:{path:'commerce.compareCount',fallback:0}}}),node({id:'tech-product-cta',componentKey:'content.button',componentVersion:1,config:{label:'Kosárba teszem',href:'#purchase',variant:'primary',size:'l',ariaLabel:'Kosárba teszem'},bindings:{label:{path:'commerce.purchaseLabel',fallback:'Kosárba teszem'},href:{path:'commerce.purchaseHref',fallback:'#purchase'}}})],{desktop:{gridSpan:5},tablet:{gridSpan:5},mobile:{gridSpan:12}})]})]),
  section('tech-product-specifications',[node({id:'tech-product-specification-groups',componentKey:'commerce.specification-groups',componentVersion:1,config:{title:'Műszaki adatok',groups:[],missingLabel:'Nincs megadva'},bindings:{groups:{path:'product.specGroups',fallback:[]}}})]),
  section('tech-product-documents',[node({id:'tech-product-documents-block',componentKey:'commerce.technical-documents',componentVersion:1,config:{title:'Dokumentumok',documents:[],emptyLabel:'Ehhez a termékhez nincs letölthető dokumentum.'},bindings:{documents:{path:'product.documents',fallback:[]}}})],{tone:'surface',spacing:'l'}),
  section('tech-product-recommendations',[recommendationRow('productRecommendations','Ezek is érdekelhetnek','recommendations.products')]),
  footer('tech-product'),
],{visualPreset:'7-5-tech-product',engineBinding:'E7',variantContract:'attribute-based-generic',soldOutVariantBehavior:'visible-disabled'});

export const TECH_DECK_SEARCH_PAGE=basePage('tech-deck.search','search',[
  header('tech-search'),
  section('tech-search-heading',[node({id:'tech-search-title',componentKey:'content.heading',componentVersion:1,config:{text:'Keresési eredmények',level:1,align:'left',tone:'text'},bindings:{text:{path:'search.title',fallback:'Keresési eredmények'}}}),node({id:'tech-search-copy',componentKey:'content.text',componentVersion:1,config:{text:'',as:'p',align:'left',tone:'muted'},bindings:{text:{path:'search.summary',fallback:''}}})],{spacing:'l'}),
  section('tech-search-body',[node({id:'tech-search-grid',componentKey:'layout.grid',componentVersion:1,config:{columns:12,gap:'l',align:'start'},children:[node({id:'tech-search-facets',componentKey:'commerce.catalog-facets',componentVersion:1,config:{title:'Szűrés',facets:[],clearHref:'/kereses',clearLabel:'Törlés'},bindings:{facets:{path:'search.facets',fallback:[]},clearHref:{path:'search.clearHref',fallback:'/kereses'},clearLabel:{path:'search.clearLabel',fallback:'Törlés'}},responsive:{desktop:{gridSpan:3},tablet:{gridSpan:4},mobile:{gridSpan:12}}}),node({...productGrid('searchResults','Találatok','search.results',3),responsive:{desktop:{gridSpan:9},tablet:{gridSpan:8},mobile:{gridSpan:12}}})]})]),
  footer('tech-search'),
],{visualPreset:'structured-tech-search',engineBinding:'E2+E7'});

export const TECH_DECK_COMPARE_PAGE=basePage('tech-deck.content','content',[
  header('tech-compare'),
  section('tech-compare-content',[node({id:'tech-compare-table',componentKey:'commerce.compare-table',componentVersion:1,config:{title:'Termékek összehasonlítása',products:[],groups:[],differencesOnly:false,missingLabel:'Nincs megadva'},bindings:{products:{path:'commerce.compare.products',fallback:[]},groups:{path:'commerce.compare.groups',fallback:[]},title:{path:'content.compare.title',fallback:'Termékek összehasonlítása'}}})]),
  footer('tech-compare'),
],{visualPreset:'structured-compare-table',engineBinding:'E7',contentRole:'product-compare'});

export const TECH_DECK_CART_PAGE=basePage('tech-deck.cart','cart',[header('tech-cart'),section('tech-cart-summary',[node({id:'tech-cart-summary-block',componentKey:'commerce.cart-summary',componentVersion:1,config:{lines:[],subtotal:'',total:'',currency:'HUF',checkoutHref:'/penztar',checkoutLabel:'Tovább a pénztárhoz',emptyLabel:'A kosarad jelenleg üres.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},total:{path:'cart.total',fallback:''}}})]),section('tech-cart-recommendations',[recommendationRow('cartRecommendations','Még hozzáadhatod','recommendations.cart')],{tone:'surface'}),footer('tech-cart')],{visualPreset:'clean-tech-cart'});
export const TECH_DECK_CHECKOUT_PAGE=basePage('tech-deck.checkout','checkout',[header('tech-checkout'),section('tech-checkout-intro',[node({id:'tech-checkout-title',componentKey:'content.heading',componentVersion:1,config:{text:'Pénztár',level:1,align:'left',tone:'text'}}),node({id:'tech-checkout-summary-block',componentKey:'commerce.checkout-summary',componentVersion:1,config:{lines:[],subtotal:'',shipping:'',total:'',currency:'HUF',secureLabel:'Biztonságos rendelés · a fizetési és szállítási folyamat a közös checkout engine feladata.'},bindings:{lines:{path:'cart.lines',fallback:[]},subtotal:{path:'cart.subtotal',fallback:''},shipping:{path:'cart.shipping',fallback:''},total:{path:'cart.total',fallback:''}}})]),footer('tech-checkout')],{visualPreset:'clean-tech-checkout',engineBinding:'E13'});

const simpleContentPage=(input:{pageKey:string;pageType:StorefrontBuilderPageType;title:string;titleBinding:string;copy:string;copyBinding:string;visualPreset:string})=>basePage(input.pageKey,input.pageType,[header(input.pageKey.replace('.','-')),section(`${input.pageKey.replace('.','-')}-content`,[node({id:`${input.pageKey}-title`,componentKey:'content.heading',componentVersion:1,config:{text:input.title,level:1,align:'left',tone:'text'},bindings:{text:{path:input.titleBinding,fallback:input.title}}}),node({id:`${input.pageKey}-copy`,componentKey:'content.text',componentVersion:1,config:{text:input.copy,as:'p',align:'left',tone:'text'},bindings:{text:{path:input.copyBinding,fallback:input.copy}}})]),footer(input.pageKey.replace('.','-'))],{visualPreset:input.visualPreset});
export const TECH_DECK_ACCOUNT_PAGE=simpleContentPage({pageKey:'tech-deck.account',pageType:'account',title:'Fiókom',titleBinding:'content.account.title',copy:'Rendelések, profiladatok és vásárlói beállítások.',copyBinding:'content.account.copy',visualPreset:'clean-tech-account'});
export const TECH_DECK_BLOG_INDEX_PAGE=basePage('tech-deck.blog-index','blog-index',[header('tech-blog-index'),section('tech-blog-index-content',[node({id:'tech-blog-index-guides',componentKey:'editorial.journal-preview',componentVersion:1,config:{title:'Vásárlási útmutatók',items:[],columns:3,emptyLabel:'Hamarosan új útmutatók érkeznek.'},bindings:{title:{path:'content.blog.title',fallback:'Vásárlási útmutatók'},items:{path:'content.blog.posts',fallback:[]}}})]),footer('tech-blog-index')],{visualPreset:'tech-buying-guide-index'});
export const TECH_DECK_BLOG_ARTICLE_PAGE=basePage('tech-deck.blog-article','blog-article',[header('tech-blog-article'),node({id:'tech-article-hero',componentKey:'editorial.hero',componentVersion:1,config:{eyebrow:'Buying guide',title:'Útmutató',copy:'',image:'',imageAlt:'',primaryLabel:'',primaryHref:'#',secondaryLabel:'',secondaryHref:'#',imagePosition:'right',height:'article'},bindings:{eyebrow:{path:'content.article.eyebrow',fallback:'Buying guide'},title:{path:'content.article.title',fallback:'Útmutató'},copy:{path:'content.article.excerpt',fallback:''},image:{path:'content.article.image',fallback:''},imageAlt:{path:'content.article.imageAlt',fallback:''}}}),section('tech-article-body',[node({id:'tech-article-body-copy',componentKey:'content.text',componentVersion:1,config:{text:'',as:'p',align:'left',tone:'text'},bindings:{text:{path:'content.article.bodyExcerpt',fallback:''}}})]),footer('tech-blog-article')],{visualPreset:'tech-buying-guide-article'});
export const TECH_DECK_FAQ_PAGE=simpleContentPage({pageKey:'tech-deck.faq',pageType:'faq',title:'Gyakori kérdések',titleBinding:'content.faq.title',copy:'Válaszok rendelésről, szállításról, garanciáról és termékekről.',copyBinding:'content.faq.intro',visualPreset:'service-content'});
export const TECH_DECK_CONTACT_PAGE=simpleContentPage({pageKey:'tech-deck.contact',pageType:'contact',title:'Kapcsolat',titleBinding:'content.contact.title',copy:'Segítünk a választásban és a rendelésben.',copyBinding:'content.contact.intro',visualPreset:'service-content'});
export const TECH_DECK_LEGAL_PAGE=simpleContentPage({pageKey:'tech-deck.legal',pageType:'legal',title:'Jogi információk',titleBinding:'content.legal.title',copy:'A kereskedő által kezelt jogi és adatkezelési tartalom helye.',copyBinding:'content.legal.intro',visualPreset:'legal-content'});
export const TECH_DECK_NOT_FOUND_PAGE=basePage('tech-deck.not-found','not-found',[header('tech-not-found'),section('tech-not-found-content',[node({id:'tech-not-found-title',componentKey:'content.heading',componentVersion:1,config:{text:'404',level:1,align:'center',tone:'text'}}),node({id:'tech-not-found-copy',componentKey:'content.text',componentVersion:1,config:{text:'Ez az oldal nem található.',as:'p',align:'center',tone:'muted'}}),node({id:'tech-not-found-cta',componentKey:'content.button',componentVersion:1,config:{label:'Vissza a főoldalra',href:'/',variant:'secondary',size:'m',ariaLabel:'Vissza a főoldalra'}})]),footer('tech-not-found')],{visualPreset:'minimal-not-found'});

export const TECH_DECK_TEMPLATE_MANIFEST=defineStorefrontTemplateManifest({foundationVersion:STOREFRONT_BUILDER_FOUNDATION_VERSION,manifestVersion:STOREFRONT_TEMPLATE_MANIFEST_VERSION,templateKey:TECH_DECK_TEMPLATE_KEY,templateVersion:TECH_DECK_TEMPLATE_VERSION,pageSchemaVersion:STOREFRONT_PAGE_SCHEMA_VERSION,minPlan:'alap',requiredFeatures:['catalog','inventory','orders','contentMarketing','productRecommendations','searchFiltering','commerceIntegrations'],pageTypes:['home','catalog','product','search','cart','checkout','account','content','blog-index','blog-article','faq','contact','legal','not-found'],responsive:{desktop:true,tablet:true,mobile:true},migration:STOREFRONT_TEMPLATE_MIGRATION_POLICY,demoContent:{namespace:'tech-tech-deck',policy:STOREFRONT_DEMO_CONTENT_POLICY}});

export const TECH_DECK_TEMPLATE_PACKAGE:StorefrontInstallableTemplatePackage={manifest:TECH_DECK_TEMPLATE_MANIFEST,pages:[TECH_DECK_HOME_PAGE,TECH_DECK_CATALOG_PAGE,TECH_DECK_PRODUCT_PAGE,TECH_DECK_SEARCH_PAGE,TECH_DECK_CART_PAGE,TECH_DECK_CHECKOUT_PAGE,TECH_DECK_ACCOUNT_PAGE,TECH_DECK_COMPARE_PAGE,TECH_DECK_BLOG_INDEX_PAGE,TECH_DECK_BLOG_ARTICLE_PAGE,TECH_DECK_FAQ_PAGE,TECH_DECK_CONTACT_PAGE,TECH_DECK_LEGAL_PAGE,TECH_DECK_NOT_FOUND_PAGE],demoFixtures:[{entityType:'collection',entityKey:'phones',payload:{title:'Telefonok',handle:'phones',demo:true}},{entityType:'collection',entityKey:'audio',payload:{title:'Audio',handle:'audio',demo:true}},{entityType:'product',entityKey:'nova-phone',payload:{name:'Nova Phone',slug:'nova-phone',priceLabel:'349 900 Ft',demo:true}},{entityType:'product',entityKey:'air-buds',payload:{name:'Air Buds',slug:'air-buds',priceLabel:'69 900 Ft',demo:true}},{entityType:'content',entityKey:'phone-guide',payload:{title:'Melyik telefon való neked?',kind:'buying-guide',demo:true}}]};
