import {
  TRAIL_EXPEDITION_DESIGN_TOKENS,
  TRAIL_EXPEDITION_ENGINE_CONTRACT,
  TRAIL_EXPEDITION_HOME_SECTION_ORDER,
  TRAIL_EXPEDITION_SELECTOR_CONTRACT,
  TRAIL_EXPEDITION_TEMPLATE_KEY,
  TRAIL_EXPEDITION_TEMPLATE_VERSION,
  TRAIL_EXPEDITION_VISUAL_DNA,
} from '@/lib/builder/templates/trail-expedition';
import {TRAIL_EXPEDITION_WAVE41_ACCEPTANCE} from '@/lib/builder/templates/trail-expedition-wave41-acceptance';
import {SPORT_HUB_TEMPLATE_KEY,SPORT_HUB_VISUAL_DNA} from '@/lib/builder/templates/sport-hub';
import {SPORT_HUB_WAVE59_ACCEPTANCE} from '@/lib/builder/templates/sport-hub-wave59-acceptance';
import {PERFORMANCE_LAB_TEMPLATE_KEY,PERFORMANCE_LAB_VISUAL_DNA} from '@/lib/builder/templates/performance-lab';

/**
 * Wave 60 replays repository-proven historical Wave 41 / PR #217 directly
 * after current Wave 59 Sport Hub. Trail & Expedition v1 is inherited
 * byte-for-byte from the accepted Wave 41 implementation, including its
 * current-contract hardening. This contract re-accepts that package on the
 * current Storefront/Page Schema/Builder baseline without inventing a new
 * template, runtime authority, registry, binding namespace or checkpoint.
 */
export const TRAIL_EXPEDITION_WAVE60_ACCEPTANCE=Object.freeze({
  wave:60,
  historicalCounterpartWave:41,
  historicalPullRequest:217,
  originalTemplateWave:22,
  originalTemplatePullRequest:145,
  predecessorAcceptance:SPORT_HUB_WAVE59_ACCEPTANCE.mode,
  historicalAcceptance:TRAIL_EXPEDITION_WAVE41_ACCEPTANCE.mode,
  mode:'current-baseline-reacceptance-and-builder-hardening',
  templateKey:TRAIL_EXPEDITION_TEMPLATE_KEY,
  templateVersion:TRAIL_EXPEDITION_TEMPLATE_VERSION,
  inheritedImplementation:true,
  sequence:{
    previous:'wave59-sport.sport-hub',
    current:TRAIL_EXPEDITION_TEMPLATE_KEY,
    historicalPrevious:'wave40-sport.sport-hub',
    historicalCurrent:'wave41-sport.trail-expedition',
    originalPrevious:'wave21-sport.sport-hub',
    originalCurrent:'wave22-sport.trail-expedition',
    next:PERFORMANCE_LAB_TEMPLATE_KEY,
    relationship:'historical-wave41-successor-replayed-on-current-stacked-baseline',
    releaseCheckpointBeforeCurrent:false,
  },
  portfolio:{
    category:'sport-outdoor',
    categoryPositionWithinSportOutdoor:2,
    position:'route-adventure-first-trail-trekking-and-camping-commerce',
    trailExpedition:TRAIL_EXPEDITION_VISUAL_DNA.character,
    previousSportHub:SPORT_HUB_VISUAL_DNA.character,
    previousTemplateKey:SPORT_HUB_TEMPLATE_KEY,
    nextPerformanceLab:PERFORMANCE_LAB_VISUAL_DNA.character,
  },
  experience:{
    shoppingEntryQuestion:TRAIL_EXPEDITION_SELECTOR_CONTRACT.question,
    adventureRoutes:TRAIL_EXPEDITION_SELECTOR_CONTRACT.routes,
    selectorGeometry:TRAIL_EXPEDITION_SELECTOR_CONTRACT.geometry,
    selectorDefaultState:TRAIL_EXPEDITION_SELECTOR_CONTRACT.defaultState,
    selectorActiveState:TRAIL_EXPEDITION_SELECTOR_CONTRACT.activeState,
    desktopInteraction:TRAIL_EXPEDITION_SELECTOR_CONTRACT.desktopInteraction,
    mobileInteraction:TRAIL_EXPEDITION_SELECTOR_CONTRACT.mobileInteraction,
    homeOrder:TRAIL_EXPEDITION_HOME_SECTION_ORDER,
  },
  visualContract:{
    character:TRAIL_EXPEDITION_VISUAL_DNA.character,
    palette:['forest-charcoal','stone-graphite','mist-white','pine-green','trail-amber','slate'],
    typography:['cinematic-editorial-grotesk','clean-sans'],
    imagery:'trail-ridge-camp-winter-forest-family-expedition-field-notes',
    exclusions:TRAIL_EXPEDITION_VISUAL_DNA.exclusions,
    merchantEditableTokens:TRAIL_EXPEDITION_DESIGN_TOKENS,
  },
  builderContract:{
    hierarchy:'template-page-presets-section-presets-components',
    responsiveModes:['desktop','tablet','mobile'],
    pagePresetCount:14,
    minimumPlan:'alap',
    stableIdentity:'unique-node-ids-and-stable-binding-paths',
    merchantEditableDesignTokens:true,
    marketingCopyOrCommerceTruthBakedIntoImages:false,
    runtimeAllowlistWidened:false,
    componentRegistryWidened:false,
    bindingNamespaceWidened:false,
    visualBuilder:'current-shared-builder-compatible-no-template-local-builder-engine',
    homeOrder:TRAIL_EXPEDITION_HOME_SECTION_ORDER,
    inheritedHistoricalCorrections:TRAIL_EXPEDITION_WAVE41_ACCEPTANCE.builderContract.hardeningCorrections,
  },
  historicalHardening:{
    catalogNodeIdentity:'collection-header-renamed-to-trail-catalog-collection-header-to-remove-system-header-collision',
    contentComponent:'content-story-index-replaced-with-content-allowed-story-body',
    contentBindings:'content-body-mapped-to-existing-content-guideBody-blocks-and-relations-paths',
    currentBlobExpectedToContainCorrections:true,
    noAutomaticReplayOfHistoricalPatch:true,
  },
  bindingContract:{
    currentSharedNamespacesOnly:true,
    forbiddenTemplateLocalNamespaces:['trail','routeSafety','weather','difficulty','fitness'],
    runtimeAllowlistWidened:false,
    componentRegistryWidened:false,
    bindingNamespaceWidened:false,
  },
  commerceAuthority:{
    engineContract:TRAIL_EXPEDITION_ENGINE_CONTRACT,
    discovery:'E2-only-for-catalog-search-channel-and-product-eligibility',
    structuredOutdoorFacts:'E7-only-when-authoritative-product-data-supplies-them',
    editorial:'E10-for-checklists-field-notes-guides-and-route-editorial-presentation',
    routeSelector:'shared-collection-navigation-presentation-only',
    guidedFinder:'no-template-local-state-machine-compose-with-shared-engine-when-integrated',
    routeMap:'editorial-context-only-not-live-navigation-weather-safety-or-difficulty-authority',
    pricing:'shared-commerce-binding-only',
    inventory:'shared-commerce-binding-only',
    variants:'shared-commerce-binding-only',
    reviews:'shared-review-binding-only-no-fabricated-score',
    checkout:'shared-provider-neutral-E13',
    noTemplateProductAuthority:true,
    noTemplatePricingAuthority:true,
    noTemplateInventoryAuthority:true,
    noTemplateVariantAuthority:true,
    noTemplateOutdoorSuitabilityAuthority:true,
    noTemplateRouteSafetyAuthority:true,
    noTemplateCheckoutAuthority:true,
    noTemplatePaymentAuthority:true,
  },
  distinctness:{
    sportHub:'not-broad-mainstream-multisport-hub-commerce',
    performanceLab:'not-specialist-goal-spec-data-lab-commerce',
    genericStorefront:'not-generic-hero-cards-repeated-grid-clone',
    ownPosition:'route-adventure-first-outdoor-commerce-over-shared-truth',
    separationIncludes:['layout','section-order','dark-cinematic-palette','typography','route-imagery','diamond-slant-selector','field-note-editorial-rhythm'],
  },
  safety:{
    fabricatedRouteSafety:false,
    fabricatedWeatherSuitability:false,
    fabricatedDifficulty:false,
    fabricatedFitnessSuitability:false,
    fabricatedSurvivalClaims:false,
    fabricatedPerformanceClaims:false,
    templateLocalGuidedFinderEngine:false,
    liveNavigationEngine:false,
    liveWeatherEngine:false,
  },
  installationContract:{
    draftOnly:true,
    demoNamespace:'sport-trail-expedition',
    mutableAuthority:['storefrontPageDrafts'],
    immutableAuthority:['products','variants','pricing','inventory','customers','orders','b2b'],
  },
  nonScope:[
    'second-trail-expedition-template','template-local-stateful-guided-finder','template-local-layout-engine','template-local-commerce-engine','template-local-checkout-engine',
    'live-route-navigation-or-gps','live-weather-or-safety-authority','template-local-difficulty-fitness-or-survival-authority',
    'shared-runtime-allowlist-widening','shared-component-registry-widening','shared-binding-namespace-widening',
    'fabricated-route-safety-weather-difficulty-fitness-survival-or-performance-claims','sport-hub-duplication','performance-lab-duplication',
    'price-or-stock-authority','payment-provider-change','visual-builder-roadmap-expansion','ai-builder-roadmap-expansion',
    'sql-migration','customer-baseline-change','vercel-production-deploy','supabase-mutation','fresh-install-project-state-change','tenant-status-change','tenant-plan-change','main-merge','wave61-implementation',
  ],
} as const);
