import Link from 'next/link';
import { formatHuf } from '@/lib/catalog';
import { createAdminClient } from '@/lib/supabase/admin';
import { CommunicationQueueButton } from '@/components/admin/communication-queue-button';

export const dynamic='force-dynamic';
type Order={id:string;order_number:string;customer_id:string|null;customer_email:string;billing_name:string;status:string;total_gross_huf:number;created_at:string};
type Profile={id:string;email:string|null;full_name:string|null;company_name:string|null;role:string;reseller_approved:boolean};
type Consent={email:string;status:'granted'|'withdrawn';occurred_at:string};
const paidStatuses=['paid','processing','shipped','completed'];
const daysSince=(date:string)=>Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/86400000));

export default async function FollowUpPage(){
 const admin=createAdminClient();
 const [{data:ordersData,error:ordersError},{data:profilesData,error:profilesError},{data:consentData,error:consentError}]=await Promise.all([
  admin.from('orders').select('id,order_number,customer_id,customer_email,billing_name,status,total_gross_huf,created_at').order('created_at',{ascending:false}).limit(5000),
  admin.from('profiles').select('id,email,full_name,company_name,role,reseller_approved').limit(5000),
  admin.from('marketing_consents').select('email,status,occurred_at').eq('channel','email').order('occurred_at',{ascending:false}).limit(10000)
 ]);
 const orders=(ordersData??[]) as Order[];const profiles=(profilesData??[]) as Profile[];const now=Date.now();const loadError=Boolean(ordersError||profilesError||consentError);
 const latestConsent=new Map<string,Consent>();for(const row of (consentData??[]) as Consent[]){const key=row.email.trim().toLowerCase();if(!latestConsent.has(key))latestConsent.set(key,row);}const hasConsent=(email:string)=>latestConsent.get(email.trim().toLowerCase())?.status==='granted';
 const paymentFollowups=orders.filter(o=>o.status==='pending'&&now-new Date(o.created_at).getTime()>=24*3600000&&now-new Date(o.created_at).getTime()<7*86400000).sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime());
 const stats=new Map<string,{name:string;email:string;orders:number;revenue:number;last:string}>();
 for(const o of orders.filter(o=>paidStatuses.includes(o.status))){const key=o.customer_id??o.customer_email.toLowerCase();const cur=stats.get(key)??{name:o.billing_name,email:o.customer_email,orders:0,revenue:0,last:o.created_at};cur.orders++;cur.revenue+=o.total_gross_huf;if(new Date(o.created_at)>new Date(cur.last))cur.last=o.created_at;stats.set(key,cur);}
 const winbackAll=[...stats.entries()].filter(([,s])=>daysSince(s.last)>=90).map(([key,s])=>({key,...s,days:daysSince(s.last)})).sort((a,b)=>b.revenue-a.revenue);
 const repeatAll=[...stats.entries()].filter(([,s])=>s.orders>=2&&daysSince(s.last)>=30&&daysSince(s.last)<90).map(([key,s])=>({key,...s,days:daysSince(s.last)})).sort((a,b)=>b.revenue-a.revenue);
 const winback=winbackAll.filter(c=>hasConsent(c.email));const repeat=repeatAll.filter(c=>hasConsent(c.email));const blockedMarketing=winbackAll.length+repeatAll.length-winback.length-repeat.length;const partnerLeads=profiles.filter(p=>p.role==='reseller'&&!p.reseller_approved);const opportunityValue=paymentFollowups.reduce((s,o)=>s+o.total_gross_huf,0)+winback.reduce((s,c)=>s+c.revenue,0);
 return <section className="adminMain"><span className="eyebrow">Admin · Utánkövetés</span><h1 className="sectionTitle">Kereskedelmi utánkövetési központ</h1><p className="lead">Az operatív és marketing utánkövetés innen már biztonságosan sorba tehető. A provider aktiválásáig minden előkészített kommunikáció várakozó állapotban marad.</p>
 {loadError&&<div className="errorNotice" role="alert"><strong>Az utánkövetési adatok egy része nem tölthető be.</strong> Marketingkommunikációt ilyen állapotban ne készíts elő.</div>}
 <div className="cards adminMetricCards"><div className="card"><span className="badge">Fizetésmentés</span><div className="price">{paymentFollowups.length}</div><p className="muted">operatív, 24 óra–7 nap közötti függő rendelés</p></div><div className="card"><span className="badge">Marketingre engedélyezett</span><div className="price">{winback.length+repeat.length}</div><p className="muted">aktuális kifejezett hozzájárulással</p></div><div className="card"><span className="badge">Marketingből kizárva</span><div className="price">{blockedMarketing}</div><p className="muted">nincs engedély vagy visszavonták</p></div><div className="card"><span className="badge">Jelzett érték</span><div className="price">{formatHuf(opportunityValue)}</div><p className="muted">nyitott fizetés + engedélyezett visszanyerési érték</p></div></div>
 <section className="card"><div className="adminToolbar"><div><span className="eyebrow">1. prioritás · operatív</span><h2>Fizetésre váró rendelések</h2><p className="muted">Rendelés teljesítéséhez kapcsolódó kapcsolatfelvétel; nem marketinglista.</p></div><Link className="btn" href="/admin/rendelesek?status=pending">Összes függő rendelés</Link></div><div className="integrationList">{paymentFollowups.slice(0,20).map(o=><div key={o.id}><span><Link className="textLink" href={`/admin/rendelesek/${o.id}`}><strong>{o.order_number}</strong></Link> · {o.billing_name} · {daysSince(o.created_at)} napja<br/><span className="muted">{formatHuf(o.total_gross_huf)}</span></span><CommunicationQueueButton kind="payment_followup" reference={o.id} label="Fizetési utánkövetés sorba"/></div>)}</div>{paymentFollowups.length===0&&<p className="muted">Nincs releváns fizetési utánkövetés.</p>}</section>
 <div className="splitFeature"><section className="featurePanel"><span className="eyebrow">Marketing engedélyezve</span><h2>30–89 napja inaktív visszatérők</h2><div className="integrationList">{repeat.slice(0,15).map(c=><div key={c.key}><span><strong>{c.name}</strong><br/><span className="muted">{c.orders} rendelés · {c.days} napja · {formatHuf(c.revenue)}</span></span><CommunicationQueueButton kind="repeat_30d" reference={c.email} label="Újravásárlás sorba"/></div>)}</div>{repeat.length===0&&<p className="muted">Nincs engedélyezett ügyfél ebben a szegmensben.</p>}</section><section className="featurePanel darkPanel"><span className="eyebrow">Marketing engedélyezve</span><h2>90+ napja inaktív ügyfelek</h2><div className="integrationList">{winback.slice(0,15).map(c=><div key={c.key}><span><strong>{c.name}</strong><br/><span>{c.orders} rendelés · {c.days} napja · {formatHuf(c.revenue)}</span></span><CommunicationQueueButton kind="winback_90d" reference={c.email} label="Visszanyerés sorba"/></div>)}</div>{winback.length===0&&<p>Nincs engedélyezett ügyfél ebben a szegmensben.</p>}</section></div>
 <section className="card"><span className="eyebrow">Partner pipeline</span><h2>{partnerLeads.length} viszonteladó vár döntésre</h2><div className="integrationList">{partnerLeads.slice(0,20).map(p=><div key={p.id}><span><strong>{p.company_name||p.full_name||'Névtelen partner'}</strong><br/><span className="muted">{p.email||'Nincs e-mail'}</span></span><Link className="textLink" href="/admin/ugyfelek">Partnerkezelés →</Link></div>)}</div></section>
 <p className="muted">A sorba állítás szerveroldalon újraellenőrzi a jogosultságot és a marketing-hozzájárulást. A napi és havi idempotencia-kulcsok megakadályozzák az ugyanazon utánkövetés véletlen duplikálását.</p></section>;
}
