import { getCommunicationIdentity } from '@/lib/communication/identity';

export type EmailTemplate='order_confirmation'|'payment_confirmed'|'order_shipped'|'order_completed';
type EmailInput={to:string;template:EmailTemplate;orderNumber:string;customerName:string;totalGrossHuf:number;trackingNumber?:string|null;invoiceUrl?:string|null;siteUrl?:string;idempotencyKey?:string};
function escapeHtml(value:string){return value.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]??ch));}
function money(value:number){return new Intl.NumberFormat('hu-HU',{style:'currency',currency:'HUF',maximumFractionDigits:0}).format(value)}
function content(input:EmailInput,brandName:string){const name=escapeHtml(input.customerName),order=escapeHtml(input.orderNumber);if(input.template==='payment_confirmed')return{subject:`${brandName} · Fizetés beérkezett – ${order}`,title:'A fizetésed beérkezett',body:`Kedves ${name}! A(z) ${order} rendelés fizetését rögzítettük. Fizetett összeg: ${money(input.totalGrossHuf)}.`};if(input.template==='order_shipped')return{subject:`${brandName} · Csomagod úton van – ${order}`,title:'Átadtuk a csomagot a futárnak',body:`Kedves ${name}! A(z) ${order} rendelésed úton van.${input.trackingNumber?` Csomagkövetési azonosító: ${escapeHtml(input.trackingNumber)}.`:''}`};if(input.template==='order_completed')return{subject:`${brandName} · Rendelés teljesítve – ${order}`,title:'Köszönjük a vásárlást',body:`Kedves ${name}! A(z) ${order} rendelést teljesítettük. Köszönjük, hogy nálunk vásároltál.`};return{subject:`${brandName} · Rendelés visszaigazolása – ${order}`,title:'Köszönjük a rendelésed',body:`Kedves ${name}! A(z) ${order} rendelést rögzítettük. Végösszeg: ${money(input.totalGrossHuf)}.`}}
function namedFrom(rawFrom:string,fromName:string){return /<[^>]+>/.test(rawFrom)?rawFrom:`${fromName} <${rawFrom}>`;}
export async function sendTransactionalEmail(input:EmailInput){const provider=process.env.EMAIL_PROVIDER??'resend';if(provider!=='resend')throw new Error(`Unsupported email provider: ${provider}`);const apiKey=process.env.RESEND_API_KEY,rawFrom=process.env.EMAIL_FROM;if(!apiKey||!rawFrom)throw new Error('RESEND_API_KEY and EMAIL_FROM required');const identity=await getCommunicationIdentity(),siteUrl=(input.siteUrl||identity.siteUrl).replace(/\/$/,''),c=content(input,identity.brandName),html=`<!doctype html><html><body style="font-family:Arial,sans-serif;color:#17312b"><div style="max-width:620px;margin:auto;padding:24px"><h2>${escapeHtml(identity.brandName)}</h2><h1>${c.title}</h1><p>${c.body}</p>${input.invoiceUrl?`<p><a href="${escapeHtml(input.invoiceUrl)}">Számla megnyitása</a></p>`:''}<p><a href="${siteUrl}/fiokom">Rendeléseim megnyitása</a></p><hr style="border:0;border-top:1px solid #ddd;margin:28px 0"><p style="font-size:12px;color:#68726c">${escapeHtml(identity.brandName)} · tranzakciós értesítés</p></div></body></html>`,headers:Record<string,string>={authorization:`Bearer ${apiKey}`,'content-type':'application/json'};if(input.idempotencyKey)headers['Idempotency-Key']=input.idempotencyKey.slice(0,256);let response:Response;try{response=await fetch('https://api.resend.com/emails',{method:'POST',headers,body:JSON.stringify({from:namedFrom(rawFrom,identity.fromName),to:[input.to],subject:c.subject,html,reply_to:identity.supportEmail||undefined}),cache:'no-store'})}catch(error){throw new Error(`Email provider outcome unknown: ${error instanceof Error?error.message:'network error'}`)}const payload=await response.json() as{id?:string;message?:string};if(!response.ok||!payload.id)throw new Error(payload.message||`Email provider error: ${response.status}`);return{provider:'resend',messageId:payload.id,detailsUrl:`${siteUrl}/fiokom`}}
