import 'server-only';
import type { InvoiceLine,InvoiceProvider } from './types';

const ENDPOINT='https://www.szamlazz.hu/szamla/';
function esc(value:unknown){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;')}
function round2(value:number){return Math.round((value+Number.EPSILON)*100)/100}
function isoDate(value?:string){const d=value?new Date(value):new Date();return d.toISOString().slice(0,10)}
function addDays(date:string,days:number){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function paymentLabel(method:string){if(method==='bank_transfer')return'Átutalás';if(method==='cash_on_delivery')return'Utánvét';return'Bankkártya'}
function vatText(rate:number){const rounded=Math.round(rate*1000)/1000;return Number.isInteger(rounded)?String(rounded):String(rounded)}
function xmlLine(line:{name:string;sku:string;quantity:number;unitNet:number;vat:number;net:number;gross:number}){const vatAmount=round2(line.gross-line.net);return `<tetel><megnevezes>${esc(line.name)}</megnevezes><azonosito>${esc(line.sku)}</azonosito><mennyiseg>${line.quantity}</mennyiseg><mennyisegiEgyseg>db</mennyisegiEgyseg><nettoEgysegar>${line.unitNet}</nettoEgysegar><afakulcs>${vatText(line.vat)}</afakulcs><nettoErtek>${line.net}</nettoErtek><afaErtek>${vatAmount}</afaErtek><bruttoErtek>${line.gross}</bruttoErtek><megjegyzes></megjegyzes></tetel>`}
function normalizedLines(input:Parameters<InvoiceProvider['createInvoice']>[0]){const lines=input.items.map((item:InvoiceLine)=>({name:item.name,sku:item.sku,quantity:item.quantity,unitNet:item.unitNetHuf,vat:item.vatRatePercent,net:item.lineNetHuf,gross:item.lineGrossHuf}));if(lines.some(line=>!Number.isFinite(line.unitNet)||line.unitNet<=0||!Number.isFinite(line.vat)))throw new Error('Invoice tax snapshot missing');if(input.shippingGrossHuf>0){const raw=process.env.INVOICE_SHIPPING_VAT_RATE_PERCENT;if(!raw)throw new Error('INVOICE_SHIPPING_VAT_RATE_PERCENT required');const vat=Number(raw);if(!Number.isFinite(vat)||vat<0)throw new Error('Invalid shipping VAT rate');const net=round2(input.shippingGrossHuf/(1+vat/100));lines.push({name:'Szállítás',sku:'SHIPPING',quantity:1,unitNet:net,vat,net,gross:input.shippingGrossHuf})}if(input.discountGrossHuf>0){const rates=[...new Set(lines.filter(line=>line.sku!=='SHIPPING').map(line=>Math.round(line.vat*1000)/1000))];if(rates.length!==1)throw new Error('Mixed VAT discount allocation requires manual invoicing');const vat=rates[0],gross=-input.discountGrossHuf,net=round2(gross/(1+vat/100));lines.push({name:'Kedvezmény',sku:'DISCOUNT',quantity:1,unitNet:net,vat,net,gross})}const grossTotal=round2(lines.reduce((sum,line)=>sum+line.gross,0));if(Math.abs(grossTotal-input.totalGrossHuf)>0.01)throw new Error(`Invoice total mismatch: ${grossTotal} != ${input.totalGrossHuf}`);return lines}

export class SzamlazzHuInvoiceProvider implements InvoiceProvider{
 async healthCheck(){const configured=Boolean(process.env.SZAMLAZZ_AGENT_KEY&&process.env.SZAMLAZZ_CONNECTION_VERIFIED==='true');return{ok:configured,message:configured?'Számlázz.hu konfiguráció engedélyezve.':'Számlázz.hu Agent kulcs vagy ellenőrzött kapcsolat hiányzik.'}}
 async createInvoice(input:Parameters<InvoiceProvider['createInvoice']>[0]){const agentKey=process.env.SZAMLAZZ_AGENT_KEY;if(!agentKey||process.env.SZAMLAZZ_CONNECTION_VERIFIED!=='true')throw new Error('Szamlazz.hu credentials and verified connection required');const lines=normalizedLines(input),issueDate=isoDate(),fulfillmentDate=isoDate(input.createdAt),dueDays=Math.max(0,Math.min(365,Number(process.env.SZAMLAZZ_DUE_DAYS??8)||0)),dueDate=input.paid?issueDate:addDays(issueDate,dueDays),electronic=process.env.SZAMLAZZ_EINVOICE==='true',prefix=process.env.SZAMLAZZ_INVOICE_PREFIX??'',customerName=input.customer.companyName||input.customer.name;
 const xml=`<?xml version="1.0" encoding="UTF-8"?><xmlszamla xmlns="http://www.szamlazz.hu/xmlszamla" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.szamlazz.hu/xmlszamla https://www.szamlazz.hu/szamla/docs/xsds/agent/xmlszamla.xsd"><beallitasok><szamlaagentkulcs>${esc(agentKey)}</szamlaagentkulcs><eszamla>${electronic}</eszamla><szamlaLetoltes>false</szamlaLetoltes><valaszVerzio>1</valaszVerzio><aggregator></aggregator><szamlaKulsoAzon>${esc(input.orderId)}</szamlaKulsoAzon></beallitasok><fejlec><keltDatum>${issueDate}</keltDatum><teljesitesDatum>${fulfillmentDate}</teljesitesDatum><fizetesiHataridoDatum>${dueDate}</fizetesiHataridoDatum><fizmod>${esc(paymentLabel(input.paymentMethod))}</fizmod><penznem>HUF</penznem><szamlaNyelve>hu</szamlaNyelve><megjegyzes>${esc(`Shoperation rendelés: ${input.orderId}`)}</megjegyzes><arfolyamBank></arfolyamBank><arfolyam>0</arfolyam><rendelesSzam>${esc(input.orderId)}</rendelesSzam><dijbekeroSzamlaszam></dijbekeroSzamlaszam><elolegszamla>false</elolegszamla><vegszamla>false</vegszamla><helyesbitoszamla>false</helyesbitoszamla><helyesbitettSzamlaszam></helyesbitettSzamlaszam><dijbekero>false</dijbekero><szamlaszamElotag>${esc(prefix)}</szamlaszamElotag><fizetve>${input.paid}</fizetve></fejlec><elado><bank>${esc(process.env.SZAMLAZZ_BANK_NAME??'')}</bank><bankszamlaszam>${esc(process.env.SZAMLAZZ_BANK_ACCOUNT??'')}</bankszamlaszam><emailReplyto>${esc(process.env.SZAMLAZZ_REPLY_TO??'')}</emailReplyto><emailTargy></emailTargy><emailSzoveg></emailSzoveg></elado><vevo><nev>${esc(customerName)}</nev><orszag>Magyarország</orszag><irsz>${esc(input.billingAddress.postalCode)}</irsz><telepules>${esc(input.billingAddress.city)}</telepules><cim>${esc(input.billingAddress.line1)}</cim><email>${esc(input.customer.email)}</email><sendEmail>false</sendEmail><adoalany>${input.customer.taxNumber?1:-1}</adoalany><adoszam>${esc(input.customer.taxNumber??'')}</adoszam><telefonszam>${esc(input.customer.phone??'')}</telefonszam><megjegyzes></megjegyzes></vevo><tetelek>${lines.map(xmlLine).join('')}</tetelek></xmlszamla>`;
 const form=new FormData();form.append('action-xmlagentxmlfile',new Blob([xml],{type:'text/xml'}),'invoice.xml');const response=await fetch(ENDPOINT,{method:'POST',body:form,cache:'no-store'}),errorCode=response.headers.get('szlahu_error_code'),errorHeader=response.headers.get('szlahu_error'),invoiceHeader=response.headers.get('szlahu_szamlaszam'),body=await response.text();if(!response.ok||errorCode||!invoiceHeader){const message=errorHeader?decodeURIComponent(errorHeader):body.slice(0,240)||`HTTP ${response.status}`;throw new Error(`Szamlazz.hu invoice failed${errorCode?` (${errorCode})`:''}: ${message}`)}const invoiceNumber=decodeURIComponent(invoiceHeader),customerUrl=response.headers.get('szlahu_vevoifiokurl');return{invoiceNumber,documentUrl:customerUrl?decodeURIComponent(customerUrl):undefined,providerReference:invoiceNumber}}
}

export class UnconfiguredInvoiceProvider implements InvoiceProvider{async healthCheck(){return{ok:false,message:'Számlázó szolgáltató nincs konfigurálva.'}}async createInvoice(_input:Parameters<InvoiceProvider['createInvoice']>[0]):ReturnType<InvoiceProvider['createInvoice']>{throw new Error('Invoice provider credentials and API contract required')}}
export function getConfiguredInvoiceProviderCode(){return process.env.INVOICE_PROVIDER==='szamlazz'&&process.env.SZAMLAZZ_AGENT_KEY&&process.env.SZAMLAZZ_CONNECTION_VERIFIED==='true'?'szamlazz':null}
export function getInvoiceProvider(code=process.env.INVOICE_PROVIDER):InvoiceProvider{if(code==='szamlazz')return new SzamlazzHuInvoiceProvider();return new UnconfiguredInvoiceProvider()}
