import 'server-only';
import type { Money,PickupPoint,ShippingProvider,ShipmentInput } from './types';
function requireEnv(name:string){const value=process.env[name];if(!value)throw new Error(`${name} required`);return value}
function xmlEscape(value:string){return value.replace(/[<>&'\"]/g,char=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[char]??char))}
function tag(name:string,value:string|number|undefined){return value===undefined?'':`<${name}>${xmlEscape(String(value))}</${name}>`}
function extract(xml:string,name:string){return xml.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]?.trim()??''}
function splitName(name:string){const parts=name.trim().split(/\s+/);return{surname:parts.pop()??name,name:parts.join(' ')||name}}
function splitStreet(line:string){const normalized=line.trim().replace(/\s+/g,' '),match=normalized.match(/^(.*?)[,\s]+(\d+[A-Za-zÁÉÍÓÖŐÚÜŰáéíóöőúüű]?(?:[\/-]\d*[A-Za-zÁÉÍÓÖŐÚÜŰáéíóöőúüű]?)?\.?)$/);if(!match||!match[1]?.trim()||!match[2]?.trim())throw new Error('Packeta home delivery street and house number required');return{street:match[1].trim(),houseNumber:match[2].trim()}}
type FeedRow={id?:string|number;name?:string;place?:string;street?:string;city?:string;zip?:string;country?:string;displayFrontend?:number|string;gps?:{latitude?:number|string;longitude?:number|string};latitude?:number|string;longitude?:number|string};
function rows(payload:unknown):FeedRow[]{if(Array.isArray(payload))return payload as FeedRow[];if(payload&&typeof payload==='object'){for(const key of ['data','branches','items','result']){const value=(payload as Record<string,unknown>)[key];if(Array.isArray(value))return value as FeedRow[]}}return[]}
export class PacketaShipping implements ShippingProvider{
 async healthCheck(){requireEnv('PACKETA_API_PASSWORD');requireEnv('PACKETA_WIDGET_API_KEY');requireEnv('PACKETA_SENDER');const verified=process.env.PACKETA_CONNECTION_VERIFIED==='true';return{ok:verified,message:verified?'Packeta partnerkonfiguráció használatra kész.':'A Packeta API-adatok jelen vannak, de a partneri tesztelés még nincs jóváhagyva.'}}
 async quote():Promise<Money>{throw new Error('Packeta díjszámítás a webshop szerződéses díjtáblájából történik')}
 async pickupPoints(input:{query?:string;country?:string;limit?:number}):Promise<PickupPoint[]>{const apiKey=requireEnv('PACKETA_WIDGET_API_KEY'),country=(input.country??'hu').toLowerCase(),query=(input.query??'').trim().toLocaleLowerCase('hu-HU'),limit=Math.min(Math.max(input.limit??40,1),80);const url=`https://pickup-point.api.packeta.com/v5/${encodeURIComponent(apiKey)}/branch/json?lang=hu`;const response=await fetch(url,{next:{revalidate:3600}});if(!response.ok)throw new Error(`Packeta pickup feed error (${response.status})`);const payload=await response.json() as unknown;return rows(payload).filter(row=>String(row.displayFrontend??1)==='1'&&(!row.country||String(row.country).toLowerCase()===country)).map(row=>{const lat=Number(row.gps?.latitude??row.latitude),lng=Number(row.gps?.longitude??row.longitude),name=String(row.name??row.place??`Packeta ${row.id??''}`).trim(),address=[row.zip,row.city,row.street].filter(Boolean).join(' ');return{id:String(row.id??''),name,address,postalCode:row.zip?String(row.zip):undefined,city:row.city?String(row.city):undefined,lat:Number.isFinite(lat)?lat:undefined,lng:Number.isFinite(lng)?lng:undefined,type:'pickup_point'}}).filter(point=>point.id&&(!query||`${point.name} ${point.address}`.toLocaleLowerCase('hu-HU').includes(query))).slice(0,limit)}
 async validatePickupPoint(id:string){const apiKey=requireEnv('PACKETA_WIDGET_API_KEY');const response=await fetch('https://widget.packeta.com/v6/pps/api/widget/v1/validate',{method:'POST',headers:{'content-type':'application/json','x-language':'hu'},body:JSON.stringify({apiKey,point:{id},options:{country:'hu'}}),cache:'no-store'});return response.ok}
 async createShipment(input:ShipmentInput){const password=requireEnv('PACKETA_API_PASSWORD'),sender=requireEnv('PACKETA_SENDER');if(input.kind==='parcel_point'&&!input.parcelPointId)throw new Error('Packeta parcel point required');if(input.kind==='parcel_point'&&input.parcelPointId&&!await this.validatePickupPoint(input.parcelPointId))throw new Error('Packeta parcel point validation failed');const person=splitName(input.customer.name),addressId=input.parcelPointId??process.env.PACKETA_HOME_DELIVERY_ID;if(!addressId)throw new Error('Packeta delivery service/addressId required');const home=input.kind==='home_delivery'?splitStreet(input.address.line1):null,cod=Math.max(0,Math.round(input.codAmountHuf??0)),body=`<createPacket><apiPassword>${xmlEscape(password)}</apiPassword><packetAttributes>${tag('number',input.orderId)}${tag('name',person.name)}${tag('surname',person.surname)}${tag('email',input.customer.email)}${tag('phone',input.customer.phone)}${tag('addressId',addressId)}${tag('cod',cod)}${tag('value',input.declaredValueHuf)}${tag('currency','HUF')}${tag('weight',Math.max(input.weightGrams/1000,0.01).toFixed(3))}${tag('eshop',sender)}${home?`${tag('street',home.street)}${tag('houseNumber',home.houseNumber)}${tag('city',input.address.city)}${tag('zip',input.address.postalCode)}`:''}</packetAttributes></createPacket>`;let response:Response;try{response=await fetch('https://www.zasilkovna.cz/api/rest',{method:'POST',headers:{'content-type':'application/xml; charset=utf-8'},body,cache:'no-store'})}catch(error){throw new Error(`Shipment reconciliation required: Packeta createPacket network result unknown (${error instanceof Error?error.message:'network error'})`)}const raw=await response.text();if(response.status>=500)throw new Error(`Shipment reconciliation required: Packeta createPacket result unknown (HTTP ${response.status})`);if(!response.ok)throw new Error(`Packeta API error (${response.status})`);const status=extract(raw,'status');if(status&&status.toLowerCase()!=='ok')throw new Error(`Packeta createPacket failed: ${extract(raw,'fault')||extract(raw,'string')||status}`);const packetId=extract(raw,'result')||extract(raw,'id');if(!packetId)throw new Error('Shipment reconciliation required: Packeta packet id missing after createPacket');return{trackingNumber:`Z${packetId.replace(/^Z/i,'')}`,providerReference:packetId}}
}
