export type Money={amount:number;currency:'HUF'};
export type Address={country:string;postalCode:string;city:string;line1:string;line2?:string};
export type CheckoutCustomer={email:string;phone?:string;name:string;companyName?:string;taxNumber?:string};
export type InvoiceLine={name:string;sku:string;quantity:number;unitGrossHuf:number;lineGrossHuf:number};
export type PaymentCallbackResult={paid:boolean;providerReference:string;eventId?:string;status?:'pending'|'paid'|'failed'|'cancelled'|'refunded'|'unknown';eventType?:string;acknowledgement?:{body:string;headers?:Record<string,string>;status?:number}};
export interface PaymentGateway{createPayment(input:{orderId:string;total:Money;returnUrl:string;cancelUrl?:string;callbackUrl?:string;idempotencyKey?:string;customerEmail?:string}):Promise<{redirectUrl:string;providerReference:string}>;verifyCallback(payload:unknown):Promise<PaymentCallbackResult>;healthCheck?():Promise<{ok:boolean;message:string}>}
export type ShipmentKind='parcel_point'|'home_delivery'|'pickup';
export type PickupPoint={id:string;name:string;address:string;postalCode?:string;city?:string;lat?:number;lng?:number;type?:string};
export type ShipmentInput={orderId:string;customer:CheckoutCustomer;address:Address;weightGrams:number;kind?:ShipmentKind;parcelPointId?:string;declaredValueHuf?:number};
export type ShipmentResult={trackingNumber:string;labelUrl?:string;providerReference?:string};
export interface ShippingProvider{quote(input:{postalCode:string;weightGrams:number;kind?:ShipmentKind}):Promise<Money>;createShipment(input:ShipmentInput):Promise<ShipmentResult>;healthCheck?():Promise<{ok:boolean;message:string}>;pickupPoints?(input:{query?:string;country?:string;limit?:number}):Promise<PickupPoint[]>;validatePickupPoint?(id:string):Promise<boolean>}
export interface InvoiceProvider{createInvoice(input:{orderId:string;customer:CheckoutCustomer;billingAddress:Address;items:InvoiceLine[];shippingGrossHuf:number;totalGrossHuf:number}):Promise<{invoiceNumber:string;documentUrl?:string;providerReference?:string}>}
