alter table public.products add column if not exists stock_quantity integer not null default 0;
alter table public.products add column if not exists active boolean not null default true;
alter table public.orders add column if not exists customer_email text;
alter table public.orders add column if not exists customer_type text not null default 'retail' check (customer_type in ('retail','company','reseller'));
alter table public.orders add column if not exists shipping_method text;
alter table public.orders add column if not exists payment_method text;
alter table public.orders add column if not exists external_payment_id text;
alter table public.orders add column if not exists tracking_number text;
create table if not exists public.customer_profiles (user_id uuid primary key references auth.users(id) on delete cascade, customer_type text not null default 'retail' check (customer_type in ('retail','company','reseller')), full_name text, company_name text, tax_number text, phone text, approved_reseller boolean not null default false, created_at timestamptz not null default now());
alter table public.customer_profiles enable row level security;
create policy "profile owner can read" on public.customer_profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy "profile owner can update" on public.customer_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
