-- V8 historical inventory snapshots for true average-inventory analytics.
-- One row per product variant and business date. Safe to re-run the capture function.

create table if not exists public.inventory_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null default current_date,
  variant_id uuid not null references public.product_variants(id) on delete cascade,
  stock_quantity integer not null check (stock_quantity >= 0),
  unit_cost_net_huf numeric(12,2),
  inventory_cost_net_huf numeric(14,2),
  retail_net_price_huf numeric(12,2) not null,
  inventory_retail_net_huf numeric(14,2) not null,
  captured_at timestamptz not null default now(),
  unique(snapshot_date, variant_id)
);

create index if not exists inventory_snapshots_variant_date_idx
  on public.inventory_snapshots(variant_id, snapshot_date desc);
create index if not exists inventory_snapshots_date_idx
  on public.inventory_snapshots(snapshot_date desc);

alter table public.inventory_snapshots enable row level security;

-- Snapshot history is an internal commercial/financial dataset. Service-role/admin
-- server code reads it; no public/client policy is intentionally granted here.

create or replace function public.capture_inventory_snapshot(p_snapshot_date date default current_date)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  insert into public.inventory_snapshots(
    snapshot_date,
    variant_id,
    stock_quantity,
    unit_cost_net_huf,
    inventory_cost_net_huf,
    retail_net_price_huf,
    inventory_retail_net_huf,
    captured_at
  )
  select
    p_snapshot_date,
    pv.id,
    greatest(coalesce(pv.stock, 0), 0),
    pv.unit_cost_net_huf,
    case when pv.unit_cost_net_huf is null then null else greatest(coalesce(pv.stock,0),0) * pv.unit_cost_net_huf end,
    pv.net_price_huf,
    greatest(coalesce(pv.stock,0),0) * pv.net_price_huf,
    now()
  from public.product_variants pv
  on conflict (snapshot_date, variant_id) do update set
    stock_quantity = excluded.stock_quantity,
    unit_cost_net_huf = excluded.unit_cost_net_huf,
    inventory_cost_net_huf = excluded.inventory_cost_net_huf,
    retail_net_price_huf = excluded.retail_net_price_huf,
    inventory_retail_net_huf = excluded.inventory_retail_net_huf,
    captured_at = now();

  get diagnostics affected = row_count;
  return affected;
end;
$$;

revoke all on function public.capture_inventory_snapshot(date) from public;
revoke all on function public.capture_inventory_snapshot(date) from anon;
revoke all on function public.capture_inventory_snapshot(date) from authenticated;
grant execute on function public.capture_inventory_snapshot(date) to service_role;

comment on table public.inventory_snapshots is 'Daily product-variant inventory snapshots used for average inventory, stock turn and GMROI history.';
comment on function public.capture_inventory_snapshot(date) is 'Idempotently captures all current product variant stock and valuation fields for one business date.';
