-- V14: strict idempotency ownership for simulation, decision and execution keys.
create or replace function public.simulate_action_proposal(p_proposal_id uuid,p_actor_id uuid,p_event_key text)
returns public.action_proposals language plpgsql security definer set search_path=''
as $$declare p public.action_proposals;a public.control_alerts;ev record;v_hash text;v_snapshot jsonb;v_from text;begin
 if nullif(trim(p_event_key),'') is null then raise exception 'event_key_required';end if;perform pg_advisory_xact_lock(hashtextextended('action-proposal:'||p_proposal_id::text,0));
 select proposal_id into ev from public.action_proposal_events where event_key=p_event_key;if found then if ev.proposal_id<>p_proposal_id then raise exception 'event_key_conflict';end if;select * into p from public.action_proposals where id=p_proposal_id;return p;end if;
 select * into p from public.action_proposals where id=p_proposal_id for update;if not found then raise exception 'proposal_not_found';end if;if p.status not in ('proposed','simulated') then raise exception 'proposal_not_simulatable';end if;if p.expires_at<=now() then raise exception 'proposal_expired';end if;
 select * into a from public.control_alerts where id=p.alert_id;if a.status in ('resolved','dismissed') then raise exception 'source_alert_closed';end if;v_from:=p.status;
 v_snapshot:=jsonb_build_object('alert_id',a.id,'alert_key',a.alert_key,'status',a.status,'severity',a.severity,'priority_score',a.priority_score,'last_detected_at',a.last_detected_at,'evidence',a.evidence,'proposal_payload',p.proposed_payload,'simulated_at',now());v_hash:=md5(v_snapshot::text);
 update public.action_proposals set status='simulated',simulation_snapshot=v_snapshot,simulation_hash=v_hash,simulated_at=now(),updated_at=now() where id=p.id returning * into p;
 insert into public.action_proposal_events(event_key,proposal_id,event_type,from_status,to_status,actor_id,metadata) values(p_event_key,p.id,'simulated',v_from,'simulated',p_actor_id,jsonb_build_object('simulation_hash',v_hash));return p;end;$$;
revoke all on function public.simulate_action_proposal(uuid,uuid,text) from public,anon,authenticated;grant execute on function public.simulate_action_proposal(uuid,uuid,text) to service_role;

create or replace function public.execute_action_proposal(p_proposal_id uuid,p_actor_id uuid,p_execution_key text)
returns public.action_executions language plpgsql security definer set search_path=''
as $$declare p public.action_proposals;e public.action_executions;v_result jsonb;begin
 if nullif(trim(p_execution_key),'') is null then raise exception 'execution_key_required';end if;perform pg_advisory_xact_lock(hashtextextended('action-proposal:'||p_proposal_id::text,0));select * into e from public.action_executions where execution_key=p_execution_key;if found then if e.proposal_id<>p_proposal_id then raise exception 'execution_key_conflict';end if;return e;end if;
 select * into p from public.action_proposals where id=p_proposal_id for update;if not found then raise exception 'proposal_not_found';end if;if p.status<>'approved' then raise exception 'proposal_not_approved';end if;if public.action_proposal_is_stale(p.id) then raise exception 'simulation_stale';end if;if p.expires_at<=now() then raise exception 'proposal_expired';end if;if p.action_kind not in ('human_task','notify_admin','record_decision') then raise exception 'adapter_not_allowlisted';end if;
 v_result:=case p.action_kind when 'human_task' then jsonb_build_object('adapter','human_task','recorded',true,'note','V14 execution authorizes human follow-up only') when 'notify_admin' then jsonb_build_object('adapter','notify_admin','queued',false,'note','No external notification transport is executed by V14') else jsonb_build_object('adapter','record_decision','recorded',true) end;
 insert into public.action_executions(execution_key,proposal_id,adapter,status,input_snapshot,result,executed_by) values(p_execution_key,p.id,p.action_kind,'succeeded',coalesce(p.simulation_snapshot,'{}'::jsonb),v_result,p_actor_id) returning * into e;update public.action_proposals set status='executed',executed_at=now(),updated_at=now() where id=p.id;insert into public.action_proposal_events(event_key,proposal_id,event_type,from_status,to_status,actor_id,metadata) values('execute:'||p_execution_key,p.id,'executed','approved','executed',p_actor_id,jsonb_build_object('execution_id',e.id,'adapter',e.adapter));return e;end;$$;
revoke all on function public.execute_action_proposal(uuid,uuid,text) from public,anon,authenticated;grant execute on function public.execute_action_proposal(uuid,uuid,text) to service_role;
