-- V15 audit hardening: activation idempotency, global-control audit and terminal state guards.
create table if not exists public.automation_control_events(
 id bigint generated by default as identity primary key,event_key text not null unique,paused boolean not null,actor_id uuid references auth.users(id) on delete set null,reason text,occurred_at timestamptz not null default now()
);
alter table public.automation_control_events enable row level security;revoke all on public.automation_control_events from public,anon,authenticated;grant select,insert on public.automation_control_events to service_role;
drop trigger if exists guard_automation_control_event_update_trigger on public.automation_control_events;create trigger guard_automation_control_event_update_trigger before update or delete on public.automation_control_events for each row execute function public.guard_automation_event_immutable();

create or replace function public.activate_automation_runbook(p_instance_id uuid,p_actor_id uuid,p_event_key text)
returns public.automation_runbook_instances language plpgsql security definer set search_path=''
as $$
declare i public.automation_runbook_instances;r public.automation_runbooks;a public.control_alerts;p public.action_proposals;c public.automation_control;e public.automation_events;begin
 if nullif(trim(p_event_key),'') is null then raise exception 'event_key_required';end if;perform pg_advisory_xact_lock(hashtextextended('automation-instance:'||p_instance_id::text,0));
 select * into e from public.automation_events where event_key=p_event_key;if found then if e.instance_id<>p_instance_id or e.event_type<>'activated' then raise exception 'event_key_conflict';end if;select * into i from public.automation_runbook_instances where id=p_instance_id;return i;end if;
 select * into i from public.automation_runbook_instances where id=p_instance_id for update;if not found then raise exception 'instance_not_found';end if;if i.status<>'planned' then raise exception 'instance_not_activatable';end if;
 select * into c from public.automation_control where singleton=true;if c.global_paused or(c.circuit_open_until is not null and c.circuit_open_until>now()) then raise exception 'automation_circuit_open';end if;
 select * into r from public.automation_runbooks where id=i.runbook_id;if not r.enabled then raise exception 'runbook_disabled';end if;select * into a from public.control_alerts where id=i.alert_id;if a.status not in ('open','acknowledged') then raise exception 'source_alert_not_active';end if;
 if r.requires_action_approval then if i.proposal_id is null then raise exception 'approved_action_required';end if;select * into p from public.action_proposals where id=i.proposal_id;if p.status not in ('approved','executed') or public.action_proposal_is_stale(p.id) then raise exception 'approved_action_stale_or_missing';end if;end if;
 update public.automation_runbook_instances set status='active',started_at=coalesce(started_at,now()),paused_at=null,updated_at=now() where id=i.id returning * into i;
 insert into public.automation_events(event_key,instance_id,event_type,actor_id,metadata) values(p_event_key,i.id,'activated',p_actor_id,jsonb_build_object('runbook_id',i.runbook_id));return i;
end;$$;
revoke all on function public.activate_automation_runbook(uuid,uuid,text) from public,anon,authenticated;grant execute on function public.activate_automation_runbook(uuid,uuid,text) to service_role;

create or replace function public.set_automation_global_pause(p_actor_id uuid,p_paused boolean,p_reason text,p_event_key text)
returns public.automation_control language plpgsql security definer set search_path=''
as $$declare c public.automation_control;e public.automation_control_events;begin
 if nullif(trim(p_event_key),'') is null then raise exception 'event_key_required';end if;perform pg_advisory_xact_lock(hashtextextended('automation-global-control',0));
 select * into e from public.automation_control_events where event_key=p_event_key;if found then if e.paused<>p_paused then raise exception 'event_key_conflict';end if;select * into c from public.automation_control where singleton=true;return c;end if;
 update public.automation_control set global_paused=p_paused,pause_reason=case when p_paused then coalesce(nullif(trim(p_reason),''),'Kézi szüneteltetés') else null end,updated_at=now() where singleton=true returning * into c;
 insert into public.automation_control_events(event_key,paused,actor_id,reason) values(p_event_key,p_paused,p_actor_id,p_reason);return c;end;$$;
revoke all on function public.set_automation_global_pause(uuid,boolean,text,text) from public,anon,authenticated;grant execute on function public.set_automation_global_pause(uuid,boolean,text,text) to service_role;

create or replace function public.guard_automation_instance_terminal()
returns trigger language plpgsql set search_path=''
as $$begin if old.status in ('completed','failed','cancelled') and new.status is distinct from old.status then raise exception 'terminal_automation_instance_immutable';end if;return new;end;$$;
drop trigger if exists guard_automation_instance_terminal_trigger on public.automation_runbook_instances;create trigger guard_automation_instance_terminal_trigger before update on public.automation_runbook_instances for each row execute function public.guard_automation_instance_terminal();

create or replace function public.guard_automation_step_integrity()
returns trigger language plpgsql set search_path=''
as $$begin
 if new.instance_id is distinct from old.instance_id or new.step_id is distinct from old.step_id then raise exception 'automation_step_identity_immutable';end if;
 if old.status in ('succeeded','skipped','cancelled') and new.status is distinct from old.status then raise exception 'terminal_automation_step_immutable';end if;
 if old.status='pending' and new.status not in ('pending','ready','cancelled') then raise exception 'invalid_step_transition';end if;
 if old.status='ready' and new.status not in ('ready','running','cancelled') then raise exception 'invalid_step_transition';end if;
 if old.status='running' and new.status not in ('running','succeeded','failed') then raise exception 'invalid_step_transition';end if;
 if old.status='failed' and new.status not in ('failed','ready','running','cancelled') then raise exception 'invalid_step_transition';end if;
 return new;end;$$;
drop trigger if exists guard_automation_step_integrity_trigger on public.automation_step_runs;create trigger guard_automation_step_integrity_trigger before update on public.automation_step_runs for each row execute function public.guard_automation_step_integrity();
