-- V17 audit hardening: approvals belong to one gate hash and CI must be trusted evidence.
alter table public.release_approvals add column if not exists gate_hash text;
update public.release_approvals a set gate_hash=c.gate_hash from public.release_candidates c where c.id=a.candidate_id and a.gate_hash is null;
alter table public.release_approvals alter column gate_hash set not null;
alter table public.release_approvals drop constraint if exists release_approvals_candidate_id_slot_key;
alter table public.release_approvals drop constraint if exists release_approvals_candidate_id_approver_id_key;
create unique index if not exists release_approvals_gate_slot_uq on public.release_approvals(candidate_id,gate_hash,slot);
create unique index if not exists release_approvals_gate_approver_uq on public.release_approvals(candidate_id,gate_hash,approver_id);

create or replace function public.release_ci_is_trusted(p_candidate_id uuid)
returns boolean language sql security definer set search_path=''
as $$select coalesce(c.ci_status='success' and c.ci_observed_at is not null and c.ci_evidence->>'source' in('github_actions','vercel') and c.ci_evidence->>'verification'='trusted',false) from public.release_candidates c where c.id=p_candidate_id$$;
revoke all on function public.release_ci_is_trusted(uuid) from public,anon,authenticated;grant execute on function public.release_ci_is_trusted(uuid) to service_role;

create or replace function public.evaluate_release_candidate(p_candidate_id uuid,p_actor_id uuid,p_event_key text)
returns public.release_candidates language plpgsql security definer set search_path=''
as $$declare c public.release_candidates;pol public.release_policies;r public.assurance_readiness;ar record;ev public.release_events;v_ci_ok boolean;v_rb_ok boolean;v_assurance_ok boolean;v_snapshot jsonb;v_hash text;begin
 perform pg_advisory_xact_lock(hashtextextended('release:'||p_candidate_id::text,0));select * into ev from public.release_events where event_key=p_event_key;if found then if ev.candidate_id<>p_candidate_id then raise exception 'event_key_conflict';end if;select * into c from public.release_candidates where id=p_candidate_id;return c;end if;
 select * into c from public.release_candidates where id=p_candidate_id for update;if not found then raise exception 'candidate_not_found';end if;if c.status in('approved','rejected','expired','cancelled') then raise exception 'candidate_terminal';end if;select * into pol from public.release_policies where id=c.policy_id;if not pol.enabled then raise exception 'release_policy_disabled';end if;select * into r from public.assurance_readiness;select * into ar from public.assurance_recent_runs where status='completed' order by completed_at desc nulls last limit 1;
 v_ci_ok:=not pol.require_ci_green or(public.release_ci_is_trusted(c.id) and c.ci_observed_at>=now()-make_interval(mins=>pol.ci_freshness_minutes));v_rb_ok:=not pol.require_rollback_plan or nullif(trim(c.rollback_plan),'') is not null;v_assurance_ok:=r.assurance_score>=pol.min_assurance_score and r.stale_controls<=pol.max_stale_controls and r.critical_open=0 and r.high_open<=pol.max_high_findings and r.accepted_risks<=pol.max_accepted_risks and r.readiness_status='ready' and ar.id is not null;
 v_snapshot:=jsonb_build_object('policy_id',pol.id,'policy_version',pol.version,'assurance_score',r.assurance_score,'readiness_status',r.readiness_status,'stale_controls',r.stale_controls,'critical_open',r.critical_open,'high_open',r.high_open,'accepted_risks',r.accepted_risks,'assurance_run_id',ar.id,'assurance_bundle_hash',ar.evidence_bundle_hash,'ci_status',c.ci_status,'ci_observed_at',c.ci_observed_at,'ci_source',c.ci_evidence->>'source','ci_trusted',public.release_ci_is_trusted(c.id),'ci_ok',v_ci_ok,'rollback_plan_ok',v_rb_ok,'assurance_ok',v_assurance_ok,'evaluated_at',now());v_hash:=md5(v_snapshot::text);
 insert into public.release_gate_results(gate_key,candidate_id,gate_name,status,evidence,evidence_hash) values('candidate:'||c.id||':evaluation:'||v_hash,c.id,'release_readiness',case when v_ci_ok and v_rb_ok and v_assurance_ok then 'pass' else 'fail' end,v_snapshot,v_hash);
 update public.release_candidates set status=case when v_ci_ok and v_rb_ok and v_assurance_ok then 'ready' else 'evaluated' end,assurance_run_id=ar.id,assurance_bundle_hash=ar.evidence_bundle_hash,assurance_score=r.assurance_score,gate_snapshot=v_snapshot,gate_hash=v_hash,evaluated_at=now(),expires_at=now()+make_interval(mins=>pol.evaluation_valid_minutes),updated_at=now() where id=c.id returning * into c;
 insert into public.release_events(event_key,candidate_id,event_type,actor_id,metadata) values(p_event_key,c.id,'evaluated',p_actor_id,jsonb_build_object('gate_hash',v_hash,'status',c.status));return c;end;$$;
revoke all on function public.evaluate_release_candidate(uuid,uuid,text) from public,anon,authenticated;grant execute on function public.evaluate_release_candidate(uuid,uuid,text) to service_role;

create or replace function public.decide_release_candidate(p_candidate_id uuid,p_actor_id uuid,p_decision text,p_note text,p_event_key text)
returns public.release_candidates language plpgsql security definer set search_path=''
as $$declare c public.release_candidates;pol public.release_policies;ev public.release_events;v_slot integer;v_count integer;v_window jsonb;begin
 if p_decision not in('approved','rejected') then raise exception 'invalid_decision';end if;perform pg_advisory_xact_lock(hashtextextended('release:'||p_candidate_id::text,0));select * into ev from public.release_events where event_key=p_event_key;if found then if ev.candidate_id<>p_candidate_id then raise exception 'event_key_conflict';end if;select * into c from public.release_candidates where id=p_candidate_id;return c;end if;
 select * into c from public.release_candidates where id=p_candidate_id for update;if not found then raise exception 'candidate_not_found';end if;select * into pol from public.release_policies where id=c.policy_id;if c.status<>'ready' or c.gate_hash is null then raise exception 'candidate_not_ready';end if;if public.release_candidate_is_stale(c.id) then raise exception 'release_evidence_stale';end if;
 select case when exists(select 1 from public.release_approvals where candidate_id=c.id and gate_hash=c.gate_hash) then 2 else 1 end into v_slot;if pol.approval_mode='single' then v_slot:=1;end if;
 insert into public.release_approvals(candidate_id,gate_hash,slot,approver_id,decision,note) values(c.id,c.gate_hash,v_slot,p_actor_id,p_decision,p_note);
 if p_decision='rejected' then update public.release_candidates set status='rejected',rejected_at=now(),updated_at=now() where id=c.id returning * into c;insert into public.release_events(event_key,candidate_id,event_type,actor_id,metadata) values(p_event_key,c.id,'rejected',p_actor_id,jsonb_build_object('slot',v_slot,'gate_hash',c.gate_hash,'note',p_note));return c;end if;
 select count(*) into v_count from public.release_approvals where candidate_id=c.id and gate_hash=c.gate_hash and decision='approved';if pol.approval_mode='single' or v_count>=2 then v_window:=public.release_window_status(c.id);if coalesce((v_window->>'allowed')::boolean,false)=false then raise exception 'release_window_closed';end if;update public.release_candidates set status='approved',approved_at=now(),updated_at=now() where id=c.id returning * into c;end if;
 insert into public.release_events(event_key,candidate_id,event_type,actor_id,metadata) values(p_event_key,c.id,case when c.status='approved' then 'approved' else 'approval_added' end,p_actor_id,jsonb_build_object('slot',v_slot,'gate_hash',c.gate_hash,'approval_mode',pol.approval_mode,'note',p_note));return c;end;$$;
revoke all on function public.decide_release_candidate(uuid,uuid,text,text,text) from public,anon,authenticated;grant execute on function public.decide_release_candidate(uuid,uuid,text,text,text) to service_role;

create or replace view public.release_candidate_queue with(security_invoker=true) as
select c.id as candidate_id,c.candidate_key,c.version_label,c.source_ref,c.source_sha,c.risk_class,c.change_summary,c.status,c.ci_status,c.ci_observed_at,c.assurance_score,c.assurance_bundle_hash,c.evaluated_at,c.expires_at,c.approved_at,c.created_at,p.policy_key,p.version as policy_version,p.name as policy_name,p.approval_mode,p.min_assurance_score,
 (select count(*) from public.release_approvals a where a.candidate_id=c.id and a.gate_hash=c.gate_hash and a.decision='approved')::integer as approval_count,public.release_candidate_is_stale(c.id) as stale,(public.release_window_status(c.id)->>'allowed')::boolean as window_allowed,(select count(*) from public.release_changes ch where ch.candidate_id=c.id)::integer as change_count,(select count(*) from public.release_changes ch where ch.candidate_id=c.id and ch.risk_level='high')::integer as high_risk_changes
from public.release_candidates c join public.release_policies p on p.id=c.policy_id;
revoke all on public.release_candidate_queue from public,anon,authenticated;grant select on public.release_candidate_queue to service_role;
