-- V17: bind evaluations to the complete change-set.
alter table public.release_candidates add column if not exists change_set_hash text;
create or replace function public.release_change_set_hash(p_candidate_id uuid)
returns text language sql security definer set search_path=''
as $$select md5(coalesce(string_agg(ch.change_key||'|'||ch.category||'|'||ch.risk_level||'|'||ch.title||'|'||ch.description,'||' order by ch.change_key),'')) from public.release_changes ch where ch.candidate_id=p_candidate_id$$;
revoke all on function public.release_change_set_hash(uuid) from public,anon,authenticated;grant execute on function public.release_change_set_hash(uuid) to service_role;

create or replace function public.create_release_candidate(p_candidate_key text,p_version_label text,p_source_ref text,p_source_sha text,p_risk_class text,p_change_summary text,p_rollback_plan text,p_created_by uuid,p_event_key text)
returns public.release_candidates language plpgsql security definer set search_path=''
as $$declare c public.release_candidates;pol public.release_policies;ev public.release_events;begin
 if nullif(trim(p_candidate_key),'') is null or nullif(trim(p_source_sha),'') is null then raise exception 'candidate_identity_required';end if;select * into ev from public.release_events where event_key=p_event_key;if found then select * into c from public.release_candidates where id=ev.candidate_id;return c;end if;select distinct on(policy_key) * into pol from public.release_policies where enabled and risk_class=p_risk_class order by policy_key,version desc limit 1;if not found then raise exception 'release_policy_not_found';end if;
 insert into public.release_candidates(candidate_key,version_label,source_ref,source_sha,risk_class,change_summary,rollback_plan,policy_id,created_by,expires_at) values(p_candidate_key,p_version_label,p_source_ref,p_source_sha,p_risk_class,p_change_summary,p_rollback_plan,pol.id,p_created_by,now()+make_interval(mins=>pol.evaluation_valid_minutes)) returning * into c;
 insert into public.release_changes(candidate_id,change_key,category,title,description,risk_level) values(c.id,'initial','code','Kiadási változás',p_change_summary,case when p_risk_class='high_impact' then 'high' else 'medium' end);
 update public.release_candidates set change_set_hash=public.release_change_set_hash(c.id) where id=c.id returning * into c;insert into public.release_events(event_key,candidate_id,event_type,actor_id,metadata) values(p_event_key,c.id,'created',p_created_by,jsonb_build_object('source_ref',p_source_ref,'source_sha',p_source_sha,'policy_id',pol.id,'change_set_hash',c.change_set_hash));return c;end;$$;
revoke all on function public.create_release_candidate(text,text,text,text,text,text,text,uuid,text) from public,anon,authenticated;grant execute on function public.create_release_candidate(text,text,text,text,text,text,text,uuid,text) to service_role;

create or replace function public.add_release_change(p_candidate_id uuid,p_actor_id uuid,p_change_key text,p_category text,p_title text,p_description text,p_risk_level text,p_event_key text)
returns public.release_candidates language plpgsql security definer set search_path=''
as $$declare c public.release_candidates;ev public.release_events;begin perform pg_advisory_xact_lock(hashtextextended('release:'||p_candidate_id::text,0));select * into ev from public.release_events where event_key=p_event_key;if found then if ev.candidate_id<>p_candidate_id then raise exception 'event_key_conflict';end if;select * into c from public.release_candidates where id=p_candidate_id;return c;end if;select * into c from public.release_candidates where id=p_candidate_id for update;if not found then raise exception 'candidate_not_found';end if;if c.status in('approved','rejected','expired','cancelled') then raise exception 'candidate_terminal';end if;
 insert into public.release_changes(candidate_id,change_key,category,title,description,risk_level) values(c.id,p_change_key,p_category,p_title,p_description,p_risk_level);update public.release_candidates set status='draft',gate_snapshot=null,gate_hash=null,evaluated_at=null,change_set_hash=public.release_change_set_hash(c.id),updated_at=now() where id=c.id returning * into c;insert into public.release_events(event_key,candidate_id,event_type,actor_id,metadata) values(p_event_key,c.id,'evaluation_invalidated',p_actor_id,jsonb_build_object('reason','change_set_updated','change_key',p_change_key,'change_set_hash',c.change_set_hash));return c;end;$$;
revoke all on function public.add_release_change(uuid,uuid,text,text,text,text,text,text) from public,anon,authenticated;grant execute on function public.add_release_change(uuid,uuid,text,text,text,text,text,text) to service_role;

create or replace function public.evaluate_release_candidate(p_candidate_id uuid,p_actor_id uuid,p_event_key text)
returns public.release_candidates language plpgsql security definer set search_path=''
as $$declare c public.release_candidates;pol public.release_policies;r public.assurance_readiness;ar record;ev public.release_events;v_ci_ok boolean;v_rb_ok boolean;v_assurance_ok boolean;v_change_ok boolean;v_change_hash text;v_snapshot jsonb;v_hash text;begin perform pg_advisory_xact_lock(hashtextextended('release:'||p_candidate_id::text,0));select * into ev from public.release_events where event_key=p_event_key;if found then if ev.candidate_id<>p_candidate_id then raise exception 'event_key_conflict';end if;select * into c from public.release_candidates where id=p_candidate_id;return c;end if;select * into c from public.release_candidates where id=p_candidate_id for update;if not found then raise exception 'candidate_not_found';end if;if c.status in('approved','rejected','expired','cancelled') then raise exception 'candidate_terminal';end if;select * into pol from public.release_policies where id=c.policy_id;if not pol.enabled then raise exception 'release_policy_disabled';end if;select * into r from public.assurance_readiness;select * into ar from public.assurance_recent_runs where status='completed' order by completed_at desc nulls last limit 1;v_change_hash:=public.release_change_set_hash(c.id);
 v_ci_ok:=not pol.require_ci_green or(public.release_ci_is_trusted(c.id) and c.ci_observed_at>=now()-make_interval(mins=>pol.ci_freshness_minutes));v_rb_ok:=not pol.require_rollback_plan or nullif(trim(c.rollback_plan),'') is not null;v_assurance_ok:=r.assurance_score>=pol.min_assurance_score and r.stale_controls<=pol.max_stale_controls and r.critical_open=0 and r.high_open<=pol.max_high_findings and r.accepted_risks<=pol.max_accepted_risks and r.readiness_status='ready' and ar.id is not null;v_change_ok:=not(c.risk_class='standard' and exists(select 1 from public.release_changes where candidate_id=c.id and risk_level='high'));
 v_snapshot:=jsonb_build_object('policy_id',pol.id,'policy_version',pol.version,'assurance_score',r.assurance_score,'readiness_status',r.readiness_status,'stale_controls',r.stale_controls,'critical_open',r.critical_open,'high_open',r.high_open,'accepted_risks',r.accepted_risks,'assurance_run_id',ar.id,'assurance_bundle_hash',ar.evidence_bundle_hash,'change_set_hash',v_change_hash,'change_set_ok',v_change_ok,'ci_status',c.ci_status,'ci_observed_at',c.ci_observed_at,'ci_source',c.ci_evidence->>'source','ci_trusted',public.release_ci_is_trusted(c.id),'ci_ok',v_ci_ok,'rollback_plan_ok',v_rb_ok,'assurance_ok',v_assurance_ok,'evaluated_at',now());v_hash:=md5(v_snapshot::text);
 insert into public.release_gate_results(gate_key,candidate_id,gate_name,status,evidence,evidence_hash) values('candidate:'||c.id||':evaluation:'||v_hash,c.id,'release_readiness',case when v_ci_ok and v_rb_ok and v_assurance_ok and v_change_ok then 'pass' else 'fail' end,v_snapshot,v_hash);update public.release_candidates set status=case when v_ci_ok and v_rb_ok and v_assurance_ok and v_change_ok then 'ready' else 'evaluated' end,assurance_run_id=ar.id,assurance_bundle_hash=ar.evidence_bundle_hash,assurance_score=r.assurance_score,change_set_hash=v_change_hash,gate_snapshot=v_snapshot,gate_hash=v_hash,evaluated_at=now(),expires_at=now()+make_interval(mins=>pol.evaluation_valid_minutes),updated_at=now() where id=c.id returning * into c;insert into public.release_events(event_key,candidate_id,event_type,actor_id,metadata) values(p_event_key,c.id,'evaluated',p_actor_id,jsonb_build_object('gate_hash',v_hash,'status',c.status,'change_set_hash',v_change_hash));return c;end;$$;
revoke all on function public.evaluate_release_candidate(uuid,uuid,text) from public,anon,authenticated;grant execute on function public.evaluate_release_candidate(uuid,uuid,text) to service_role;

create or replace function public.release_candidate_is_stale(p_candidate_id uuid)
returns boolean language sql security definer set search_path=''
as $$with c as(select * from public.release_candidates where id=p_candidate_id),pol as(select p.* from public.release_policies p join c on c.policy_id=p.id),latest as(select * from public.assurance_recent_runs where status='completed' order by completed_at desc nulls last limit 1),r as(select * from public.assurance_readiness),w as(select public.release_window_status(p_candidate_id) s)
select case when c.evaluated_at is null then true when c.expires_at<=now() then true when not pol.enabled then true when latest.id is null then true when c.assurance_bundle_hash is distinct from latest.evidence_bundle_hash then true when c.change_set_hash is distinct from public.release_change_set_hash(c.id) then true when r.readiness_status<>'ready' or r.assurance_score<pol.min_assurance_score or r.stale_controls>pol.max_stale_controls or r.critical_open>0 or r.high_open>pol.max_high_findings or r.accepted_risks>pol.max_accepted_risks then true when pol.require_ci_green and(not public.release_ci_is_trusted(c.id) or c.ci_observed_at is null or c.ci_observed_at<now()-make_interval(mins=>pol.ci_freshness_minutes)) then true when coalesce((w.s->>'allowed')::boolean,false)=false then true else false end from c join pol on true left join latest on true cross join r cross join w$$;
revoke all on function public.release_candidate_is_stale(uuid) from public,anon,authenticated;grant execute on function public.release_candidate_is_stale(uuid) to service_role;
