-- V21: structured observability with PII-safe metadata and bounded retention.
create table if not exists public.observability_events(
 id bigint generated by default as identity primary key,
 event_key text not null unique,
 correlation_id text not null,
 category text not null check(category in('http','commerce','integration','payment','database','security','system')),
 severity text not null check(severity in('debug','info','warning','error','critical')),
 event_name text not null,
 duration_ms integer check(duration_ms is null or duration_ms>=0),
 status_code integer,
 source text not null,
 metadata jsonb not null default '{}'::jsonb,
 occurred_at timestamptz not null default now()
);
alter table public.observability_events enable row level security;
revoke all on public.observability_events from public,anon,authenticated;
grant select on public.observability_events to service_role;

create or replace function public.record_observability_event(p_event_key text,p_correlation_id text,p_category text,p_severity text,p_event_name text,p_duration_ms integer,p_status_code integer,p_source text,p_metadata jsonb default '{}'::jsonb)
returns bigint language plpgsql security definer set search_path=''
as $$declare v_id bigint;v_existing public.observability_events;v_meta jsonb;begin
 if nullif(trim(p_event_key),'') is null or nullif(trim(p_correlation_id),'') is null then raise exception 'observability_key_required';end if;
 if p_category not in('http','commerce','integration','payment','database','security','system') then raise exception 'invalid_category';end if;
 if p_severity not in('debug','info','warning','error','critical') then raise exception 'invalid_severity';end if;
 select * into v_existing from public.observability_events where event_key=p_event_key;
 if found then
  if v_existing.correlation_id<>p_correlation_id or v_existing.event_name<>p_event_name or v_existing.category<>p_category then raise exception 'event_key_conflict';end if;
  return v_existing.id;
 end if;
 -- defensive redaction: known PII/secret keys are stripped before persistence.
 v_meta:=coalesce(p_metadata,'{}'::jsonb)-array['email','phone','password','token','authorization','cookie','address','name','full_name'];
 insert into public.observability_events(event_key,correlation_id,category,severity,event_name,duration_ms,status_code,source,metadata)
 values(p_event_key,p_correlation_id,p_category,p_severity,p_event_name,p_duration_ms,p_status_code,p_source,v_meta) returning id into v_id;
 return v_id;
end;$$;
revoke all on function public.record_observability_event(text,text,text,text,text,integer,integer,text,jsonb) from public,anon,authenticated;
grant execute on function public.record_observability_event(text,text,text,text,text,integer,integer,text,jsonb) to service_role;

create or replace view public.observability_kpis with(security_invoker=true) as
select
 count(*) filter(where occurred_at>=now()-interval '24 hours')::integer as events_24h,
 count(*) filter(where severity in('error','critical') and occurred_at>=now()-interval '24 hours')::integer as errors_24h,
 count(*) filter(where severity='critical' and occurred_at>=now()-interval '24 hours')::integer as critical_24h,
 coalesce(round(avg(duration_ms) filter(where duration_ms is not null and occurred_at>=now()-interval '24 hours')),0)::integer as avg_duration_ms_24h,
 coalesce(percentile_cont(0.95) within group(order by duration_ms) filter(where duration_ms is not null and occurred_at>=now()-interval '24 hours'),0)::integer as p95_duration_ms_24h,
 max(occurred_at) as last_event_at
from public.observability_events;
revoke all on public.observability_kpis from public,anon,authenticated;grant select on public.observability_kpis to service_role;

create or replace view public.observability_issue_queue with(security_invoker=true) as
select id,correlation_id,category,severity,event_name,duration_ms,status_code,source,metadata,occurred_at
from public.observability_events
where severity in('warning','error','critical') and occurred_at>=now()-interval '7 days'
order by case severity when 'critical' then 1 when 'error' then 2 else 3 end,occurred_at desc;
revoke all on public.observability_issue_queue from public,anon,authenticated;grant select on public.observability_issue_queue to service_role;

create or replace function public.purge_observability_events(p_retention_days integer default 30)
returns integer language plpgsql security definer set search_path=''
as $$declare n integer;begin
 if p_retention_days<7 or p_retention_days>365 then raise exception 'invalid_retention';end if;
 delete from public.observability_events where occurred_at<now()-make_interval(days=>p_retention_days);
 get diagnostics n=row_count;return n;
end;$$;
revoke all on function public.purge_observability_events(integer) from public,anon,authenticated;grant execute on function public.purge_observability_events(integer) to service_role;
