-- Tenant ownership and RBAC for merchant CRM tables.
alter table public.commercial_opportunities add column if not exists instance_id uuid references public.webshop_instances(id) on delete cascade;
alter table public.commercial_offers add column if not exists instance_id uuid references public.webshop_instances(id) on delete cascade;
alter table public.sales_tasks add column if not exists instance_id uuid references public.webshop_instances(id) on delete cascade;
update public.commercial_opportunities set instance_id=public.single_runtime_instance_id() where instance_id is null and public.single_runtime_instance_id() is not null;
update public.commercial_offers o set instance_id=x.instance_id from public.commercial_opportunities x where o.opportunity_id=x.id and o.instance_id is null;
update public.sales_tasks t set instance_id=x.instance_id from public.commercial_opportunities x where t.opportunity_id=x.id and t.instance_id is null;
do $$ begin if exists(select 1 from public.commercial_opportunities where instance_id is null) or exists(select 1 from public.commercial_offers where instance_id is null) or exists(select 1 from public.sales_tasks where instance_id is null) then raise exception 'CRM tenant hardening blocked by unassigned rows';end if;end $$;
alter table public.commercial_opportunities alter column instance_id set not null;
alter table public.commercial_offers alter column instance_id set not null;
alter table public.sales_tasks alter column instance_id set not null;
alter table public.commercial_opportunities drop constraint if exists commercial_opportunities_opportunity_key_key;
drop index if exists public.commercial_opportunities_opportunity_key_key;
drop index if exists public.commercial_opportunities_one_active_b2b_reorder_idx;
drop index if exists public.commercial_opportunities_one_active_b2c_auto_idx;
drop index if exists public.commercial_opportunities_one_active_b2c_guest_auto_idx;
drop index if exists public.sales_tasks_task_key_key;
create unique index if not exists commercial_opportunities_instance_key_uidx on public.commercial_opportunities(instance_id,opportunity_key);
create unique index if not exists commercial_opportunities_active_b2b_uidx on public.commercial_opportunities(instance_id,reseller_id) where channel='b2b' and kind='reorder' and status in('open','in_progress') and reseller_id is not null;
create unique index if not exists commercial_opportunities_active_b2c_uidx on public.commercial_opportunities(instance_id,customer_id) where channel='b2c' and kind in('retention','winback') and status in('open','in_progress') and customer_id is not null;
create unique index if not exists commercial_opportunities_active_guest_uidx on public.commercial_opportunities(instance_id,lower(customer_email)) where channel='b2c' and kind in('retention','winback') and status in('open','in_progress') and customer_id is null and customer_email is not null;
create unique index if not exists sales_tasks_instance_key_uidx on public.sales_tasks(instance_id,task_key);
create index if not exists commercial_opportunities_instance_queue_idx on public.commercial_opportunities(instance_id,status,priority_score desc,due_at);
create index if not exists commercial_offers_instance_status_idx on public.commercial_offers(instance_id,status,created_at desc);
create index if not exists sales_tasks_instance_queue_idx on public.sales_tasks(instance_id,status,priority desc,due_at);
create or replace function public.can_manage_sales(p_instance_id uuid,p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$select public.is_platform_operator(p_user_id) or public.has_store_role(p_instance_id,array['owner','admin','marketing_manager'],p_user_id);$$;
do $$ declare p record;t text;begin foreach t in array array['commercial_opportunities','commercial_offers','sales_tasks'] loop execute format('alter table public.%I enable row level security',t);for p in select policyname from pg_policies where schemaname='public' and tablename=t loop execute format('drop policy if exists %I on public.%I',p.policyname,t);end loop;end loop;end $$;
create policy commercial_opportunities_store_all on public.commercial_opportunities for all to authenticated using(public.can_manage_sales(instance_id)) with check(public.can_manage_sales(instance_id));
create policy commercial_offers_store_all on public.commercial_offers for all to authenticated using(public.can_manage_sales(instance_id)) with check(public.can_manage_sales(instance_id));
create policy sales_tasks_store_all on public.sales_tasks for all to authenticated using(public.can_manage_sales(instance_id)) with check(public.can_manage_sales(instance_id));
