-- Strict tenant boundary for merchant intelligence execution data.
-- Policy/runbook definitions stay platform catalogs; alerts, proposals, runs and executions are store scoped.

alter table public.automation_step_runs add column if not exists store_instance_id uuid references public.webshop_instances(id) on delete cascade;
alter table public.automation_events add column if not exists store_instance_id uuid references public.webshop_instances(id) on delete cascade;
update public.automation_step_runs s set store_instance_id=i.instance_id from public.automation_runbook_instances i where s.instance_id=i.id and s.store_instance_id is null;
update public.automation_events e set store_instance_id=i.instance_id from public.automation_runbook_instances i where e.instance_id=i.id and e.store_instance_id is null;
create index if not exists automation_step_runs_store_instance_idx on public.automation_step_runs(store_instance_id,instance_id,status);
create index if not exists automation_events_store_instance_idx on public.automation_events(store_instance_id,instance_id,occurred_at desc);

create or replace function public.merchant_intelligence_store_guard() returns trigger language plpgsql set search_path=public as $$ declare v uuid; begin
 if tg_table_name='customer_journey_steps' then select instance_id into v from public.customer_journeys where id=new.journey_id;
 elsif tg_table_name in ('control_alert_events','control_tasks') then select instance_id into v from public.control_alerts where id=new.alert_id;
 elsif tg_table_name in ('action_proposal_events','action_approvals','action_executions') then select instance_id into v from public.action_proposals where id=new.proposal_id;
 elsif tg_table_name='automation_runbook_instances' then select instance_id into v from public.control_alerts where id=new.alert_id; end if;
 if v is null then raise exception 'tenant_parent_missing';end if; if new.instance_id is null then new.instance_id:=v;elsif new.instance_id<>v then raise exception 'tenant_parent_mismatch';end if; return new; end$$;
create or replace function public.automation_child_store_guard() returns trigger language plpgsql set search_path=public as $$ declare v uuid; begin select instance_id into v from public.automation_runbook_instances where id=new.instance_id; if v is null then raise exception 'tenant_parent_missing';end if;if new.store_instance_id is null then new.store_instance_id:=v;elsif new.store_instance_id<>v then raise exception 'tenant_parent_mismatch';end if;return new;end$$;

drop trigger if exists customer_journey_steps_store_guard on public.customer_journey_steps;create trigger customer_journey_steps_store_guard before insert or update on public.customer_journey_steps for each row execute function public.merchant_intelligence_store_guard();
drop trigger if exists control_alert_events_store_guard on public.control_alert_events;create trigger control_alert_events_store_guard before insert or update on public.control_alert_events for each row execute function public.merchant_intelligence_store_guard();
drop trigger if exists control_tasks_store_guard on public.control_tasks;create trigger control_tasks_store_guard before insert or update on public.control_tasks for each row execute function public.merchant_intelligence_store_guard();
drop trigger if exists action_proposal_events_store_guard on public.action_proposal_events;create trigger action_proposal_events_store_guard before insert or update on public.action_proposal_events for each row execute function public.merchant_intelligence_store_guard();
drop trigger if exists action_approvals_store_guard on public.action_approvals;create trigger action_approvals_store_guard before insert or update on public.action_approvals for each row execute function public.merchant_intelligence_store_guard();
drop trigger if exists action_executions_store_guard on public.action_executions;create trigger action_executions_store_guard before insert or update on public.action_executions for each row execute function public.merchant_intelligence_store_guard();
drop trigger if exists automation_runbook_instances_store_guard on public.automation_runbook_instances;create trigger automation_runbook_instances_store_guard before insert or update on public.automation_runbook_instances for each row execute function public.merchant_intelligence_store_guard();
drop trigger if exists automation_step_runs_store_guard on public.automation_step_runs;create trigger automation_step_runs_store_guard before insert or update on public.automation_step_runs for each row execute function public.automation_child_store_guard();
drop trigger if exists automation_events_store_guard on public.automation_events;create trigger automation_events_store_guard before insert or update on public.automation_events for each row execute function public.automation_child_store_guard();

do $$ begin if exists(select 1 from public.merchant_intelligence_tenant_gaps where table_name<>'action_policies' and rows_without_instance>0) then raise exception 'merchant_intelligence_tenant_gaps_not_zero';end if;end$$;

alter table public.customer_journeys drop constraint if exists customer_journeys_kind_source_key_key;
create unique index if not exists customer_journeys_instance_kind_source_uq on public.customer_journeys(instance_id,kind,source_key);
alter table public.control_alerts drop constraint if exists control_alerts_alert_key_key;
create unique index if not exists control_alerts_instance_alert_key_uq on public.control_alerts(instance_id,alert_key);
alter table public.action_proposals drop constraint if exists action_proposals_proposal_key_key;
create unique index if not exists action_proposals_instance_proposal_key_uq on public.action_proposals(instance_id,proposal_key);
alter table public.action_processing_runs drop constraint if exists action_processing_runs_run_key_key;create unique index if not exists action_processing_runs_instance_run_key_uq on public.action_processing_runs(instance_id,run_key);
alter table public.control_processing_runs drop constraint if exists control_processing_runs_run_key_key;create unique index if not exists control_processing_runs_instance_run_key_uq on public.control_processing_runs(instance_id,run_key);
alter table public.automation_processing_runs drop constraint if exists automation_processing_runs_run_key_key;create unique index if not exists automation_processing_runs_instance_run_key_uq on public.automation_processing_runs(instance_id,run_key);

alter table public.customer_journeys alter column instance_id set not null;alter table public.customer_journey_steps alter column instance_id set not null;alter table public.customer_lifecycle_milestones alter column instance_id set not null;alter table public.control_alerts alter column instance_id set not null;alter table public.control_alert_events alter column instance_id set not null;alter table public.control_tasks alter column instance_id set not null;alter table public.control_processing_runs alter column instance_id set not null;alter table public.action_proposals alter column instance_id set not null;alter table public.action_proposal_events alter column instance_id set not null;alter table public.action_approvals alter column instance_id set not null;alter table public.action_executions alter column instance_id set not null;alter table public.action_processing_runs alter column instance_id set not null;alter table public.automation_control alter column instance_id set not null;alter table public.automation_control_events alter column instance_id set not null;alter table public.automation_processing_runs alter column instance_id set not null;alter table public.automation_runbook_instances alter column instance_id set not null;alter table public.automation_step_runs alter column store_instance_id set not null;alter table public.automation_events alter column store_instance_id set not null;

alter table public.automation_control drop constraint if exists automation_control_pkey;alter table public.automation_control add primary key(instance_id);

create or replace function public.transition_control_alert_v2(p_instance_id uuid,p_alert_id uuid,p_target_status text,p_event_key text,p_actor_id uuid default null,p_snoozed_until timestamptz default null,p_note text default null) returns public.control_alerts language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.control_alerts where id=p_alert_id and instance_id=p_instance_id)then raise exception 'control_alert_not_found';end if;return public.transition_control_alert(p_alert_id,p_target_status,p_instance_id::text||':'||p_event_key,p_actor_id,p_snoozed_until,p_note);end$$;
create or replace function public.transition_control_task_v2(p_instance_id uuid,p_task_id uuid,p_target_status text,p_event_key text,p_actor_id uuid default null,p_outcome text default null) returns public.control_tasks language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.control_tasks where id=p_task_id and instance_id=p_instance_id)then raise exception 'control_task_not_found';end if;return public.transition_control_task(p_task_id,p_target_status,p_instance_id::text||':'||p_event_key,p_actor_id,p_outcome);end$$;
create or replace function public.simulate_action_proposal_v2(p_instance_id uuid,p_proposal_id uuid,p_actor_id uuid,p_event_key text) returns public.action_proposals language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.action_proposals where id=p_proposal_id and instance_id=p_instance_id)then raise exception 'proposal_not_found';end if;return public.simulate_action_proposal(p_proposal_id,p_actor_id,p_instance_id::text||':'||p_event_key);end$$;
create or replace function public.decide_action_proposal_v2(p_instance_id uuid,p_proposal_id uuid,p_actor_id uuid,p_decision text,p_note text,p_event_key text) returns public.action_proposals language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.action_proposals where id=p_proposal_id and instance_id=p_instance_id)then raise exception 'proposal_not_found';end if;return public.decide_action_proposal(p_proposal_id,p_actor_id,p_decision,p_note,p_instance_id::text||':'||p_event_key);end$$;
create or replace function public.execute_action_proposal_v2(p_instance_id uuid,p_proposal_id uuid,p_actor_id uuid,p_execution_key text) returns public.action_executions language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.action_proposals where id=p_proposal_id and instance_id=p_instance_id)then raise exception 'proposal_not_found';end if;return public.execute_action_proposal(p_proposal_id,p_actor_id,p_instance_id::text||':'||p_execution_key);end$$;
create or replace function public.activate_automation_runbook_v2(p_store_instance_id uuid,p_runbook_instance_id uuid,p_actor_id uuid,p_event_key text) returns public.automation_runbook_instances language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.automation_runbook_instances where id=p_runbook_instance_id and instance_id=p_store_instance_id)then raise exception 'automation_instance_not_found';end if;return public.activate_automation_runbook(p_runbook_instance_id,p_actor_id,p_store_instance_id::text||':'||p_event_key);end$$;
create or replace function public.transition_automation_instance_v2(p_store_instance_id uuid,p_runbook_instance_id uuid,p_actor_id uuid,p_target text,p_event_key text,p_reason text default null) returns public.automation_runbook_instances language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.automation_runbook_instances where id=p_runbook_instance_id and instance_id=p_store_instance_id)then raise exception 'automation_instance_not_found';end if;return public.transition_automation_instance(p_runbook_instance_id,p_actor_id,p_target,p_store_instance_id::text||':'||p_event_key,p_reason);end$$;
create or replace function public.execute_automation_step_v2(p_store_instance_id uuid,p_runbook_instance_id uuid,p_actor_id uuid,p_execution_key text) returns public.automation_step_runs language plpgsql security definer set search_path='' as $$begin if not exists(select 1 from public.automation_runbook_instances where id=p_runbook_instance_id and instance_id=p_store_instance_id)then raise exception 'automation_instance_not_found';end if;return public.execute_automation_step(p_runbook_instance_id,p_actor_id,p_store_instance_id::text||':'||p_execution_key);end$$;
create or replace function public.set_store_automation_pause_v2(p_instance_id uuid,p_actor_id uuid,p_paused boolean,p_reason text,p_event_key text) returns public.automation_control language plpgsql security definer set search_path='' as $$declare c public.automation_control;begin insert into public.automation_control(instance_id,singleton,global_paused,pause_reason,consecutive_failures,updated_at)values(p_instance_id,true,p_paused,case when p_paused then coalesce(nullif(trim(p_reason),''),'Kézi szüneteltetés')end,0,now())on conflict(instance_id)do update set global_paused=excluded.global_paused,pause_reason=excluded.pause_reason,updated_at=now() returning * into c;insert into public.automation_control_events(instance_id,event_key,paused,actor_id,reason)values(p_instance_id,p_instance_id::text||':'||p_event_key,p_paused,p_actor_id,p_reason);return c;end$$;

create or replace function public.process_control_tower_cycle_v2(p_instance_id uuid,p_run_key text) returns public.control_processing_runs language plpgsql security definer set search_path='' as $$declare r public.control_processing_runs;v_open int;v_tasks int;begin if nullif(trim(p_run_key),'')is null then raise exception 'run_key_required';end if;select count(*)into v_open from public.control_alerts where instance_id=p_instance_id and status in('open','acknowledged','snoozed');select count(*)into v_tasks from public.control_tasks where instance_id=p_instance_id and status in('open','in_progress');insert into public.control_processing_runs(instance_id,run_key,detector_result,task_result,completed_at,metadata)values(p_instance_id,p_run_key,jsonb_build_object('active_alerts',v_open),jsonb_build_object('active_tasks',v_tasks),now(),jsonb_build_object('tenant_safe',true,'global_detectors_disabled',true))on conflict(instance_id,run_key)do update set completed_at=excluded.completed_at,detector_result=excluded.detector_result,task_result=excluded.task_result,metadata=excluded.metadata returning * into r;return r;end$$;
create or replace function public.process_action_cycle_v2(p_instance_id uuid,p_run_key text) returns public.action_processing_runs language plpgsql security definer set search_path='' as $$declare r public.action_processing_runs;v_active int;begin update public.action_proposals set status='cancelled',cancelled_at=now(),updated_at=now()where instance_id=p_instance_id and status in('proposed','simulated')and expires_at<=now();select count(*)into v_active from public.action_proposals where instance_id=p_instance_id and status in('proposed','simulated','approved');insert into public.action_processing_runs(instance_id,run_key,plan_result,cleanup_result,completed_at,metadata)values(p_instance_id,p_run_key,jsonb_build_object('active_proposals',v_active),jsonb_build_object('expired_cleaned',true),now(),jsonb_build_object('tenant_safe',true,'global_planner_disabled',true))on conflict(instance_id,run_key)do update set completed_at=excluded.completed_at,plan_result=excluded.plan_result,cleanup_result=excluded.cleanup_result,metadata=excluded.metadata returning * into r;return r;end$$;
create or replace function public.process_automation_cycle_v2(p_instance_id uuid,p_run_key text) returns public.automation_processing_runs language plpgsql security definer set search_path='' as $$declare r public.automation_processing_runs;v_active int;begin select count(*)into v_active from public.automation_runbook_instances where instance_id=p_instance_id and status in('planned','active','paused');insert into public.automation_processing_runs(instance_id,run_key,planned,reconciled,completed_at,metadata)values(p_instance_id,p_run_key,jsonb_build_object('active_instances',v_active),jsonb_build_object('safe_reconcile',true),now(),jsonb_build_object('tenant_safe',true,'global_planner_disabled',true))on conflict(instance_id,run_key)do update set completed_at=excluded.completed_at,planned=excluded.planned,reconciled=excluded.reconciled,metadata=excluded.metadata returning * into r;return r;end$$;

-- Client roles cannot execute legacy global merchant-intelligence engines.
do $$declare r record;begin for r in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname=any(array['create_customer_journey','plan_customer_retention_journeys','process_control_tower_cycle','transition_control_alert','transition_control_task','process_action_cycle','plan_action_proposals','simulate_action_proposal','decide_action_proposal','execute_action_proposal','process_automation_cycle','set_automation_global_pause','activate_automation_runbook','transition_automation_instance','execute_automation_step']) loop execute format('revoke execute on function %s from public, anon, authenticated',r.sig);end loop;end$$;

do $$declare r record;begin for r in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname=any(array['transition_control_alert_v2','transition_control_task_v2','simulate_action_proposal_v2','decide_action_proposal_v2','execute_action_proposal_v2','activate_automation_runbook_v2','transition_automation_instance_v2','execute_automation_step_v2','set_store_automation_pause_v2','process_control_tower_cycle_v2','process_action_cycle_v2','process_automation_cycle_v2']) loop execute format('revoke execute on function %s from public, anon, authenticated',r.sig);execute format('grant execute on function %s to service_role',r.sig);end loop;end$$;

-- Merchant intelligence tables are readable only inside the active store role boundary; mutations stay service-side.
do $$declare t text;begin foreach t in array array['customer_journeys','customer_journey_steps','customer_lifecycle_milestones','control_alerts','control_alert_events','control_tasks','control_processing_runs','action_proposals','action_proposal_events','action_approvals','action_executions','action_processing_runs','automation_control','automation_control_events','automation_processing_runs','automation_runbook_instances'] loop execute format('alter table public.%I enable row level security',t);execute format('drop policy if exists tenant_read on public.%I',t);execute format('create policy tenant_read on public.%I for select using (public.has_store_role(instance_id,array[''owner'',''admin'',''catalog_manager'',''order_manager'',''marketing_manager'',''support'',''analyst'',''viewer'']))',t);end loop;end$$;
alter table public.automation_step_runs enable row level security;drop policy if exists tenant_read on public.automation_step_runs;create policy tenant_read on public.automation_step_runs for select using(public.has_store_role(store_instance_id,array['owner','admin','catalog_manager','order_manager','marketing_manager','support','analyst','viewer']));
alter table public.automation_events enable row level security;drop policy if exists tenant_read on public.automation_events;create policy tenant_read on public.automation_events for select using(public.has_store_role(store_instance_id,array['owner','admin','catalog_manager','order_manager','marketing_manager','support','analyst','viewer']));
