-- Tenant-aware merchant intelligence views. Platform system-health view remains global by design.
create or replace view public.action_center_queue with(security_invoker=true) as
select p.id proposal_id,p.proposal_key,p.status,p.action_kind,p.impact_class,p.risk_score,p.rationale,p.expires_at,p.simulated_at,p.approved_at,p.executed_at,a.id alert_id,a.alert_key,a.category,a.alert_type,a.severity,a.priority_score alert_priority,a.title alert_title,a.status alert_status,pol.policy_key,pol.version policy_version,pol.name policy_name,pol.approval_mode,((select count(*) from public.action_approvals x where x.instance_id=p.instance_id and x.proposal_id=p.id and x.decision='approved'))::int approval_count,public.action_proposal_is_stale(p.id) simulation_stale,p.instance_id
from public.action_proposals p join public.control_alerts a on a.id=p.alert_id and a.instance_id=p.instance_id join public.action_policies pol on pol.id=p.policy_id where p.status in('proposed','simulated','approved');

create or replace view public.action_center_kpis with(security_invoker=true) as
select count(*)::int active_proposals,count(*) filter(where status='proposed')::int proposed_count,count(*) filter(where status='simulated')::int simulated_count,count(*) filter(where status='approved')::int approved_count,count(*) filter(where impact_class='high_impact')::int high_impact_count,count(*) filter(where expires_at<now()+interval '4 hours')::int expiring_soon_count,count(*) filter(where public.action_proposal_is_stale(id))::int stale_count,instance_id
from public.action_proposals where status in('proposed','simulated','approved') group by instance_id;

create or replace view public.automation_runbook_queue with(security_invoker=true) as
select i.id instance_id,i.instance_key,i.status,i.escalation_level,i.failure_count,i.deadline_at,i.started_at,i.created_at,r.runbook_key,r.version runbook_version,r.name runbook_name,r.category,r.risk_class,r.requires_action_approval,r.max_failures,a.id alert_id,a.title alert_title,a.severity,a.priority_score,a.status alert_status,i.proposal_id,p.status proposal_status,count(sr.id) total_steps,count(sr.id) filter(where sr.status='succeeded') succeeded_steps,count(sr.id) filter(where sr.status='failed') failed_steps,count(sr.id) filter(where sr.status in('ready','running')) executable_steps,round(extract(epoch from now()-coalesce(i.started_at,i.created_at))/3600::numeric,1) age_hours,case when i.deadline_at<now() and i.status in('planned','active','paused') then true else false end overdue,i.instance_id store_instance_id
from public.automation_runbook_instances i join public.automation_runbooks r on r.id=i.runbook_id join public.control_alerts a on a.id=i.alert_id and a.instance_id=i.instance_id left join public.action_proposals p on p.id=i.proposal_id and p.instance_id=i.instance_id left join public.automation_step_runs sr on sr.instance_id=i.id and sr.store_instance_id=i.instance_id group by i.id,r.id,a.id,p.id;

create or replace view public.automation_kpis with(security_invoker=true) as
select count(*) filter(where status='planned')::int planned,count(*) filter(where status='active')::int active,count(*) filter(where status='paused')::int paused,count(*) filter(where status='failed')::int failed,count(*) filter(where overdue)::int overdue,count(*) filter(where escalation_level>0)::int escalated,coalesce(sum(failed_steps),0)::int failed_steps,coalesce(avg(age_hours) filter(where status in('planned','active','paused')),0) avg_open_age_hours,store_instance_id
from public.automation_runbook_queue group by store_instance_id;

create or replace view public.control_tower_queue with(security_invoker=true) as
select a.id alert_id,a.alert_key,a.category,a.alert_type,a.severity,a.priority_score,a.status,a.title,a.description,a.recommended_action,a.order_id,a.customer_id,a.reseller_id,a.variant_id,a.opportunity_id,a.evidence,a.occurrence_count,a.detected_at,a.last_detected_at,a.snoozed_until,round(extract(epoch from now()-a.incident_started_at)/3600::numeric,1) age_hours,t.id task_id,t.status task_status,t.owner_user_id,t.due_at task_due_at,t.outcome task_outcome,case when t.status in('open','in_progress') and t.due_at<now() then true else false end task_overdue,a.incident_started_at,a.instance_id
from public.control_alerts a left join public.control_tasks t on t.alert_id=a.id and t.instance_id=a.instance_id and t.task_key=(a.instance_id::text||':alert:'||a.id::text||':primary') where a.status in('open','acknowledged','snoozed');

create or replace view public.control_tower_category_summary with(security_invoker=true) as
select category,severity,count(*)::int alert_count,max(priority_score) max_priority,round(avg(extract(epoch from now()-incident_started_at)/3600::numeric),1) avg_age_hours,instance_id from public.control_alerts where status in('open','acknowledged','snoozed') group by instance_id,category,severity;

create or replace view public.control_tower_kpis with(security_invoker=true) as
with q as(select * from public.control_tower_queue),x as(select instance_id,count(*)::int open_alerts,count(*) filter(where severity='critical')::int critical_alerts,count(*) filter(where severity='high')::int high_alerts,count(*) filter(where age_hours>=24)::int over_24h_alerts,count(*) filter(where task_overdue)::int overdue_tasks,count(*) filter(where category='operations')::int operations_alerts,count(*) filter(where category='inventory')::int inventory_alerts,count(*) filter(where category='commercial')::int commercial_alerts,count(*) filter(where category='service')::int service_alerts,coalesce(sum((evidence->>'expected_value_net_huf')::numeric) filter(where category='commercial' and evidence?'expected_value_net_huf'),0) commercial_value_at_risk_net_huf,coalesce(avg(age_hours),0) avg_alert_age_hours from q group by instance_id)
select open_alerts,critical_alerts,high_alerts,over_24h_alerts,overdue_tasks,operations_alerts,inventory_alerts,commercial_alerts,service_alerts,commercial_value_at_risk_net_huf,avg_alert_age_hours,greatest(0,least(100,100-critical_alerts*15-high_alerts*7-overdue_tasks*5-over_24h_alerts*2)) control_health_score,instance_id from x;
