-- Tenant-safe planners and cycle orchestration for merchant intelligence.

create or replace function public.create_customer_journey_v2(p_instance_id uuid,p_kind public.customer_journey_kind,p_user_id uuid,p_email text,p_source_key text,p_metadata jsonb default '{}'::jsonb)
returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;begin
 if p_instance_id is null or length(trim(p_email))<5 or length(trim(p_source_key))<3 then raise exception 'invalid_journey_identity';end if;
 insert into public.customer_journeys(instance_id,kind,user_id,email,source_key,metadata)
 values(p_instance_id,p_kind,p_user_id,lower(trim(p_email)),trim(p_source_key),coalesce(p_metadata,'{}'::jsonb))
 on conflict(instance_id,kind,source_key) do update set updated_at=now() returning id into v_id;return v_id;
end$$;

create or replace function public.plan_customer_retention_journeys_v2(p_instance_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$declare m record;r record;v_journey uuid;v_created int:=0;v_steps int:=0;begin
 for m in select * from public.customer_commercial_metrics where instance_id=p_instance_id and segment in('at_risk','winback','dormant') loop
  select public.create_customer_journey_v2(p_instance_id,case when m.segment='at_risk' then 'replenishment'::public.customer_journey_kind else 'winback'::public.customer_journey_kind end,m.customer_id,m.email_key,concat(m.customer_key,':',m.segment),jsonb_build_object('segment',m.segment,'paidOrders',m.paid_orders,'revenueGrossHuf',m.revenue_gross_huf,'lastOrderAt',m.last_order_at)) into v_journey;
  v_created:=v_created+1;
  insert into public.customer_journey_steps(instance_id,journey_id,step_key,purpose,template_key,scheduled_at)
  values(p_instance_id,v_journey,case when m.segment='at_risk' then 'replenishment-reminder' else 'winback-reminder' end,'marketing',case when m.segment='at_risk' then 'repeat_30d' else 'winback_90d' end,now()) on conflict(journey_id,step_key) do nothing;if found then v_steps:=v_steps+1;end if;
 end loop;
 for r in select id,user_id,email,recovery_token,last_seen_at,expires_at from public.checkout_recovery_intents where instance_id=p_instance_id and status='open' and expires_at>now() and last_seen_at<=now()-interval '2 hours' loop
  select public.create_customer_journey_v2(p_instance_id,'abandoned_checkout'::public.customer_journey_kind,r.user_id,r.email,r.id::text,jsonb_build_object('checkoutRecoveryId',r.id,'recoveryToken',r.recovery_token,'lastSeenAt',r.last_seen_at,'expiresAt',r.expires_at)) into v_journey;
  v_created:=v_created+1;insert into public.customer_journey_steps(instance_id,journey_id,step_key,purpose,template_key,scheduled_at) values(p_instance_id,v_journey,'checkout-recovery','marketing','abandoned_checkout',now()) on conflict(journey_id,step_key) do nothing;if found then v_steps:=v_steps+1;end if;
 end loop;
 update public.checkout_recovery_intents set status='expired',updated_at=now() where instance_id=p_instance_id and status='open' and expires_at<=now();
 return jsonb_build_object('journeysSeen',v_created,'stepsCreated',v_steps);
end$$;

create or replace function public.expire_or_cancel_action_proposals_v2(p_instance_id uuid,p_run_key text)
returns jsonb language plpgsql security definer set search_path=public as $$declare r record;v_exp int:=0;v_cancel int:=0;begin
 for r in select p.*,a.status alert_status from public.action_proposals p join public.control_alerts a on a.id=p.alert_id and a.instance_id=p.instance_id where p.instance_id=p_instance_id and p.status in('proposed','simulated','approved') loop
  if r.expires_at<=now() then update public.action_proposals set status='expired',updated_at=now() where id=r.id and instance_id=p_instance_id and status in('proposed','simulated','approved');if found then insert into public.action_proposal_events(instance_id,event_key,proposal_id,event_type,from_status,to_status,metadata) values(p_instance_id,'expire:'||p_instance_id||':'||p_run_key||':'||r.id,r.id,'expired',r.status,'expired','{}') on conflict do nothing;v_exp:=v_exp+1;end if;
  elsif r.alert_status in('resolved','dismissed') then update public.action_proposals set status='cancelled',cancelled_at=now(),updated_at=now() where id=r.id and instance_id=p_instance_id and status in('proposed','simulated','approved');if found then insert into public.action_proposal_events(instance_id,event_key,proposal_id,event_type,from_status,to_status,metadata) values(p_instance_id,'cancel:'||p_instance_id||':'||p_run_key||':'||r.id,r.id,'cancelled',r.status,'cancelled',jsonb_build_object('reason','source_alert_closed')) on conflict do nothing;v_cancel:=v_cancel+1;end if;end if;
 end loop;return jsonb_build_object('expired',v_exp,'cancelled',v_cancel);
end$$;

create or replace function public.plan_action_proposals_v2(p_instance_id uuid,p_run_key text)
returns jsonb language plpgsql security definer set search_path=public as $$declare a record;p record;v_count int:=0;v_rank int;v_min int;v_min_priority int;v_incident text;v_key text;begin
 if p_instance_id is null or nullif(trim(p_run_key),'') is null then raise exception 'tenant_and_run_key_required';end if;
 for a in select * from public.control_alerts where instance_id=p_instance_id and status in('open','acknowledged','snoozed') loop
  v_rank:=case a.severity when 'critical' then 4 when 'high' then 3 when 'warning' then 2 else 1 end;v_incident:=to_char(a.incident_started_at at time zone 'UTC','YYYYMMDDHH24MISSUS');
  for p in select distinct on(policy_key) * from public.action_policies where enabled and category=a.category and(alert_type is null or alert_type=a.alert_type) order by policy_key,version desc loop
   v_min:=case p.min_severity when 'critical' then 4 when 'high' then 3 when 'warning' then 2 else 1 end;v_min_priority:=coalesce((p.conditions->>'min_priority_score')::int,0);if v_rank<v_min or a.priority_score<v_min_priority then continue;end if;
   v_key:=p_instance_id::text||':alert:'||a.id::text||':incident:'||v_incident||':policy:'||p.policy_key||':v'||p.version;
   insert into public.action_proposals(instance_id,proposal_key,alert_id,policy_id,action_kind,impact_class,risk_score,rationale,proposed_payload,source_snapshot,expires_at)
   values(p_instance_id,v_key,a.id,p.id,p.action_kind,p.impact_class,least(100,greatest(a.priority_score,case p.impact_class when 'high_impact' then 85 when 'reversible' then 60 else 30 end)),'Tenant-aware policy '||p.policy_key||' matched active alert '||a.alert_key,p.action_template,jsonb_build_object('alert_key',a.alert_key,'alert_status',a.status,'severity',a.severity,'priority_score',a.priority_score,'last_detected_at',a.last_detected_at,'incident_started_at',a.incident_started_at,'evidence',a.evidence),now()+(p.expires_after_hours||' hours')::interval)
   on conflict(instance_id,proposal_key) do update set risk_score=excluded.risk_score,rationale=excluded.rationale,source_snapshot=excluded.source_snapshot,updated_at=now() where public.action_proposals.status in('proposed','simulated');if found then v_count:=v_count+1;end if;
  end loop;
 end loop;return jsonb_build_object('proposals_upserted',v_count,'tenant_safe',true);
end$$;

create or replace function public.process_action_cycle_v2(p_instance_id uuid,p_run_key text)
returns public.action_processing_runs language plpgsql security definer set search_path=public as $$declare r public.action_processing_runs;v_plan jsonb;v_clean jsonb;v_key text;begin
 if p_instance_id is null or nullif(trim(p_run_key),'') is null then raise exception 'tenant_and_run_key_required';end if;v_key:=p_instance_id::text||':'||trim(p_run_key);perform pg_advisory_xact_lock(hashtextextended('action-cycle:'||v_key,0));
 select * into r from public.action_processing_runs where instance_id=p_instance_id and run_key=v_key;if found and r.completed_at is not null then return r;end if;if not found then insert into public.action_processing_runs(instance_id,run_key) values(p_instance_id,v_key) returning * into r;end if;
 select public.expire_or_cancel_action_proposals_v2(p_instance_id,v_key) into v_clean;select public.plan_action_proposals_v2(p_instance_id,v_key) into v_plan;
 update public.action_processing_runs set cleanup_result=v_clean,plan_result=v_plan,completed_at=now(),metadata=jsonb_build_object('sequence',jsonb_build_array('expire_cancel','plan'),'tenant_safe',true) where id=r.id and instance_id=p_instance_id returning * into r;return r;
end$$;

create or replace function public.plan_automation_runbooks_v2(p_instance_id uuid,p_run_key text)
returns jsonb language plpgsql security definer set search_path=public as $$declare a record;r public.automation_runbooks;v_proposal uuid;v_instance uuid;v_created int:=0;v_existing int:=0;v_waiting int:=0;v_key text;v_incident text;begin
 for a in select * from public.control_alerts where instance_id=p_instance_id and status in('open','acknowledged') and severity in('warning','high','critical') loop
  select rb.* into r from public.automation_runbooks rb where rb.enabled=true and rb.category=a.category and(case rb.min_severity when 'critical' then 4 when 'high' then 3 when 'warning' then 2 else 1 end)<=(case a.severity when 'critical' then 4 when 'high' then 3 when 'warning' then 2 else 1 end) order by rb.version desc limit 1;if not found then continue;end if;
  v_proposal:=null;select ap.id into v_proposal from public.action_proposals ap where ap.instance_id=p_instance_id and ap.alert_id=a.id and ap.created_at>=a.incident_started_at and ap.status in('simulated','approved','executed') order by ap.created_at desc limit 1;
  if r.requires_action_approval and v_proposal is null then v_waiting:=v_waiting+1;continue;end if;
  v_incident:=to_char(a.incident_started_at at time zone 'UTC','YYYYMMDDHH24MISSUS');v_key:=p_instance_id::text||':alert:'||a.id||':incident:'||v_incident||':runbook:'||r.runbook_key||':v'||r.version;
  if exists(select 1 from public.automation_runbook_instances where instance_id=p_instance_id and instance_key=v_key) then v_existing:=v_existing+1;continue;end if;
  insert into public.automation_runbook_instances(instance_id,instance_key,runbook_id,alert_id,proposal_id,status,source_snapshot,deadline_at) values(p_instance_id,v_key,r.id,a.id,v_proposal,'planned',jsonb_build_object('alert_status',a.status,'severity',a.severity,'priority_score',a.priority_score,'last_detected_at',a.last_detected_at,'incident_started_at',a.incident_started_at,'proposal_id',v_proposal),now()+make_interval(hours=>r.max_duration_hours)) returning id into v_instance;
  insert into public.automation_step_runs(store_instance_id,instance_id,step_id,status) select p_instance_id,v_instance,s.id,case when s.step_order=1 then 'ready' else 'pending' end from public.automation_runbook_steps s where s.runbook_id=r.id order by s.step_order;
  insert into public.automation_events(store_instance_id,event_key,instance_id,event_type,metadata) values(p_instance_id,'planned:'||p_instance_id||':'||p_run_key||':'||v_instance,v_instance,'planned',jsonb_build_object('runbook_key',r.runbook_key,'runbook_version',r.version,'source_alert_id',a.id,'incident_started_at',a.incident_started_at));v_created:=v_created+1;
 end loop;return jsonb_build_object('created',v_created,'existing',v_existing,'waiting_for_proposal',v_waiting,'tenant_safe',true);
end$$;

create or replace function public.cancel_stale_automation_incidents_v2(p_instance_id uuid,p_run_key text) returns integer language plpgsql security definer set search_path=public as $$declare i record;v_count int:=0;begin
 for i in select ai.id,ai.alert_id,ai.source_snapshot,ca.incident_started_at from public.automation_runbook_instances ai join public.control_alerts ca on ca.id=ai.alert_id and ca.instance_id=ai.instance_id where ai.instance_id=p_instance_id and ai.status in('planned','active','paused') loop
  if not(i.source_snapshot?'incident_started_at') or(i.source_snapshot->>'incident_started_at')::timestamptz is distinct from i.incident_started_at then update public.automation_runbook_instances set status='cancelled',cancelled_at=now(),updated_at=now() where id=i.id and instance_id=p_instance_id;update public.automation_step_runs set status='cancelled',finished_at=coalesce(finished_at,now()),updated_at=now() where instance_id=i.id and store_instance_id=p_instance_id and status in('pending','ready','failed');insert into public.automation_events(store_instance_id,event_key,instance_id,event_type,metadata) values(p_instance_id,'incident-stale:'||p_instance_id||':'||p_run_key||':'||i.id,i.id,'cancelled',jsonb_build_object('reason','source_incident_changed')) on conflict(event_key) do nothing;v_count:=v_count+1;end if;
 end loop;return v_count;end$$;

create or replace function public.refresh_automation_ready_steps_v2(p_instance_id uuid,p_run_key text) returns jsonb language plpgsql security definer set search_path=public as $$declare x record;v_completed int:=0;v_cancelled int:=0;v_ready int:=0;v_instances int:=0;begin
 for x in select sr.id,sr.instance_id,sr.result,ct.status task_status from public.automation_step_runs sr left join public.control_tasks ct on ct.id=(sr.result->>'control_task_id')::uuid and ct.instance_id=p_instance_id where sr.store_instance_id=p_instance_id and sr.status='waiting' loop
  if x.task_status='completed' then update public.automation_step_runs set status='succeeded',finished_at=now(),updated_at=now(),result=result||jsonb_build_object('human_task_completed',true) where id=x.id and store_instance_id=p_instance_id;insert into public.automation_events(store_instance_id,event_key,instance_id,step_run_id,event_type,metadata) values(p_instance_id,'human-complete:'||p_instance_id||':'||p_run_key||':'||x.id,x.instance_id,x.id,'step_succeeded',jsonb_build_object('reason','control_task_completed')) on conflict(event_key) do nothing;v_completed:=v_completed+1;
  elsif x.task_status='cancelled' then update public.automation_step_runs set status='failed',finished_at=now(),last_error='control_task_cancelled',next_attempt_at=null,updated_at=now() where id=x.id and store_instance_id=p_instance_id;update public.automation_runbook_instances set failure_count=failure_count+1,updated_at=now() where id=x.instance_id and instance_id=p_instance_id;insert into public.automation_events(store_instance_id,event_key,instance_id,step_run_id,event_type,metadata) values(p_instance_id,'human-cancel:'||p_instance_id||':'||p_run_key||':'||x.id,x.instance_id,x.id,'step_failed',jsonb_build_object('reason','control_task_cancelled')) on conflict(event_key) do nothing;v_cancelled:=v_cancelled+1;end if;
 end loop;
 update public.automation_step_runs sr set status='ready',ready_at=coalesce(ready_at,now()),updated_at=now() from public.automation_runbook_steps st,public.automation_runbook_instances i where sr.step_id=st.id and sr.instance_id=i.id and sr.store_instance_id=p_instance_id and i.instance_id=p_instance_id and i.status='active' and sr.status='pending' and(st.requires_previous_success=false or not exists(select 1 from public.automation_step_runs prev join public.automation_runbook_steps ps on ps.id=prev.step_id where prev.instance_id=sr.instance_id and prev.store_instance_id=p_instance_id and ps.step_order<st.step_order and prev.status not in('succeeded','skipped')));get diagnostics v_ready=row_count;
 for x in select i.id from public.automation_runbook_instances i where i.instance_id=p_instance_id and i.status='active' and not exists(select 1 from public.automation_step_runs sr where sr.instance_id=i.id and sr.store_instance_id=p_instance_id and sr.status not in('succeeded','skipped')) loop update public.automation_runbook_instances set status='completed',completed_at=now(),updated_at=now() where id=x.id and instance_id=p_instance_id;insert into public.automation_events(store_instance_id,event_key,instance_id,event_type,metadata) values(p_instance_id,'auto-complete:'||p_instance_id||':'||p_run_key||':'||x.id,x.id,'completed',jsonb_build_object('reason','all_steps_succeeded')) on conflict(event_key) do nothing;v_instances:=v_instances+1;end loop;
 return jsonb_build_object('human_tasks_completed',v_completed,'human_tasks_cancelled',v_cancelled,'steps_ready',v_ready,'instances_completed',v_instances);
end$$;

create or replace function public.reconcile_automation_runbooks_v2(p_instance_id uuid,p_run_key text) returns jsonb language plpgsql security definer set search_path=public as $$declare rec record;r public.automation_runbooks;v_cancelled int:=0;v_failed int:=0;v_escalated int:=0;v_ready int:=0;v_task uuid;begin
 for rec in select ai.*,ca.status alert_status,ca.priority_score,ca.title alert_title,ap.status proposal_status from public.automation_runbook_instances ai join public.control_alerts ca on ca.id=ai.alert_id and ca.instance_id=ai.instance_id left join public.action_proposals ap on ap.id=ai.proposal_id and ap.instance_id=ai.instance_id where ai.instance_id=p_instance_id and ai.status in('planned','active','paused') loop
  select * into r from public.automation_runbooks where id=rec.runbook_id;
  if rec.alert_status not in('open','acknowledged') or(r.requires_action_approval and coalesce(rec.proposal_status,'') in('rejected','expired','cancelled')) then update public.automation_runbook_instances set status='cancelled',cancelled_at=now(),updated_at=now() where id=rec.id and instance_id=p_instance_id;update public.automation_step_runs set status='cancelled',finished_at=coalesce(finished_at,now()),updated_at=now() where instance_id=rec.id and store_instance_id=p_instance_id and status in('pending','ready','failed');insert into public.automation_events(store_instance_id,event_key,instance_id,event_type,metadata) values(p_instance_id,'reconcile-cancel:'||p_instance_id||':'||p_run_key||':'||rec.id,rec.id,'cancelled',jsonb_build_object('reason','source_condition_closed_or_proposal_invalid')) on conflict(event_key) do nothing;v_cancelled:=v_cancelled+1;continue;end if;
  if rec.failure_count>=r.max_failures then update public.automation_runbook_instances set status='failed',updated_at=now() where id=rec.id and instance_id=p_instance_id;insert into public.control_tasks(instance_id,task_key,alert_id,status,priority_score,title,recommended_action,due_at,metadata) values(p_instance_id,p_instance_id||':automation-failed:'||rec.id,rec.alert_id,'open',greatest(90,rec.priority_score),'Automatizálási hiba · '||rec.alert_title,'Vizsgáld meg a runbook ismétlődő hibáit.',now()+interval '2 hours',jsonb_build_object('source','tenant_runbook_failure','runbook_instance_id',rec.id)) on conflict(instance_id,task_key) do update set priority_score=greatest(public.control_tasks.priority_score,excluded.priority_score),updated_at=now() returning id into v_task;v_failed:=v_failed+1;continue;end if;
  if rec.deadline_at<=now() and rec.escalation_level<5 then update public.automation_runbook_instances set escalation_level=least(5,escalation_level+1),updated_at=now() where id=rec.id and instance_id=p_instance_id;insert into public.control_tasks(instance_id,task_key,alert_id,status,priority_score,title,recommended_action,due_at,metadata) values(p_instance_id,p_instance_id||':automation-overdue:'||rec.id,rec.alert_id,'open',least(100,greatest(80,rec.priority_score)+rec.escalation_level*3),'Lejárt automatizálási SLA · '||rec.alert_title,'Ellenőrizd a lejárt runbookot.',now()+interval '2 hours',jsonb_build_object('source','tenant_runbook_escalation','runbook_instance_id',rec.id,'escalation_level',rec.escalation_level+1)) on conflict(instance_id,task_key) do update set priority_score=greatest(public.control_tasks.priority_score,excluded.priority_score),due_at=least(public.control_tasks.due_at,excluded.due_at),updated_at=now() returning id into v_task;v_escalated:=v_escalated+1;end if;
 end loop;
 update public.automation_step_runs sr set status='ready',ready_at=coalesce(ready_at,now()),updated_at=now() where sr.store_instance_id=p_instance_id and sr.status='failed' and sr.next_attempt_at<=now() and sr.attempt_count<(select s.max_attempts from public.automation_runbook_steps s where s.id=sr.step_id) and exists(select 1 from public.automation_runbook_instances inst where inst.id=sr.instance_id and inst.instance_id=p_instance_id and inst.status='active');get diagnostics v_ready=row_count;
 return jsonb_build_object('cancelled',v_cancelled,'failed',v_failed,'escalated',v_escalated,'retries_ready',v_ready);
end$$;

create or replace function public.process_automation_cycle_v2(p_instance_id uuid,p_run_key text) returns public.automation_processing_runs language plpgsql security definer set search_path=public as $$declare x public.automation_processing_runs;v_stale int;v_sync jsonb;v_plan jsonb;v_rec jsonb;v_key text;begin
 if p_instance_id is null or nullif(trim(p_run_key),'') is null then raise exception 'tenant_and_run_key_required';end if;v_key:=p_instance_id||':'||trim(p_run_key);perform pg_advisory_xact_lock(hashtextextended('automation-cycle:'||v_key,0));select * into x from public.automation_processing_runs where instance_id=p_instance_id and run_key=v_key;if found and x.completed_at is not null then return x;end if;if not found then insert into public.automation_processing_runs(instance_id,run_key) values(p_instance_id,v_key) returning * into x;end if;
 select public.cancel_stale_automation_incidents_v2(p_instance_id,v_key) into v_stale;select public.refresh_automation_ready_steps_v2(p_instance_id,v_key) into v_sync;select public.plan_automation_runbooks_v2(p_instance_id,v_key) into v_plan;select public.reconcile_automation_runbooks_v2(p_instance_id,v_key) into v_rec;v_rec:=v_rec||jsonb_build_object('stale_incidents_cancelled',v_stale,'step_sync',v_sync);
 update public.automation_processing_runs set planned=v_plan,reconciled=v_rec,completed_at=now(),metadata=jsonb_build_object('sequence',jsonb_build_array('cancel_stale_incidents','sync_human_steps','plan','reconcile'),'tenant_safe',true) where id=x.id and instance_id=p_instance_id returning * into x;return x;
end$$;

-- Server-only execution surface.
do $$declare n text;a text;begin
 for n,a in select * from(values
 ('create_customer_journey_v2','uuid,public.customer_journey_kind,uuid,text,text,jsonb'),('plan_customer_retention_journeys_v2','uuid'),('expire_or_cancel_action_proposals_v2','uuid,text'),('plan_action_proposals_v2','uuid,text'),('process_action_cycle_v2','uuid,text'),('plan_automation_runbooks_v2','uuid,text'),('cancel_stale_automation_incidents_v2','uuid,text'),('refresh_automation_ready_steps_v2','uuid,text'),('reconcile_automation_runbooks_v2','uuid,text'),('process_automation_cycle_v2','uuid,text')) v(n,a) loop execute format('revoke all on function public.%I(%s) from public,anon,authenticated',n,a);execute format('grant execute on function public.%I(%s) to service_role',n,a);end loop;
end$$;
revoke execute on function public.create_customer_journey(public.customer_journey_kind,uuid,text,text,jsonb) from public,anon,authenticated;
revoke execute on function public.plan_customer_retention_journeys() from public,anon,authenticated;
revoke execute on function public.plan_action_proposals(text),public.process_action_cycle(text),public.expire_or_cancel_action_proposals(text) from public,anon,authenticated;
revoke execute on function public.plan_automation_runbooks(text),public.process_automation_cycle(text),public.cancel_stale_automation_incidents(text),public.refresh_automation_ready_steps(text),public.reconcile_automation_runbooks(text) from public,anon,authenticated;
